### ISSUE TITLE
Internal Loadbalancer not being created on GKE 

### ISSUE THREAD

**Issue by ghost** [istio/istio#11365]
**Describe the bug**
When creating an istio-ingressgateway in gcp and adding "internal" annotation load balancer is stuck in pending 

**Expected behavior**
Loadbalancer is created 

**Steps to reproduce the bug**
add 
    serviceAnnotations:
      cloud.google.com/load-balancer-type: "internal"
to the "istio-ingressgateway:" in the values file

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
not using istioctl 
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.3", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-10T00:39:15Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
helm chart downloaded from 
https://istio.io/docs/setup/kubernetes/download-release/

**Environment**
cloud provider: gcp
nodes: n1-standard-4 (4 vCPUs, 15 GB memory)

I am aware of the issue with gcp internal load balancer limit (something that was not written in documentation when we moved to google cloud)
"A maximum of 5 ports in a forwarding rule, unless you configure the forwarding rule to match all ports."

there are 8 port configured on "istio-ingressgateway"
Port 80
Port 443
Port 31400
Port 15011 - tcp-pilot-grpc-tls
Port 8060 - tcp-citadel-grpc-tls
Port 853 - tcp-dns-tls
Port 15030 - http2-prometheus
Port 15031 - http2-grafana

I would like to work with everything offered in the ingressgateway
is there any way around this and still use internal load balancer?
I tried splitting the LB and putting 80/443/31400/853 on one LB
and 15011/8060/15030/15031 on the second LB
But when i started with the bookstore app example everything did not work properly.
When going back to regular LB (external) with all ports on one LB everything worked great.
Due to limitations in our company we need to work with internal LB's.
is there any way around this?

Thanks

**Comment by MrBlaise** [comment]
We have the same problem

**Comment by tewner** [comment]
Same here.

**Comment by sdake** [comment]
@howardjohn this smells like a platform problem.  Can you pleae advise or get this issue into the hand of someone that can?

Cheers
-steve

**Comment by natealcedo** [comment]
Hey this is something I need as well. Will GKE support this anytime soon? I know aws and azure support this currently

**Comment by cr-amatziab** [comment]
From what i know google are working on creating an lb without the 5 port limit.
No ETA on when this is going to happen

**Comment by devilmind81** [comment]
Hi guys,
any news on this?
I have the same problem here.

thanks in advance.

**Comment by cr-amatziab** [comment]
google still have a 5 port limit on internal load balancer.|
you can try the managed istio they offer as part of gke maybe it can solve the issue.
another solution is to create multiple gateways (service + istio gateway) this will also require adjustments with the helm chart if you are installing it via helm

**Comment by nesl247** [comment]
FYI their managed istio addon does not include an internal load balancer. You actually have to create it yourself, and it will have the same limitations.

**Comment by costinm** [comment]
In 1.5, we only need:
- 15012 - for 'flat network' multicluster and mesh expansion
- 853 - if using DNS-over TLS, we can replace it in 1.6 once we intercept DNS
- 15443 - for multi-network support

In addition, 443 and 80 if the 'internal gateway' is running behind a L7 LB - so we can preserve
X-Forwarde/client ip/etc.

So we now fit perfectly. 

I would strongly recommend leaving the configuration of the internal load blancer and services outside of the installer options - it's too confusing and hard to review, and it's something a net admin 
may need to adjust and fine tune frequently, without having to run cluster-admin operations. 
It's also easier to provide multiple examples - the installer has an API duplicating most of K8S Service API in a very confusing way.

**Comment by mark-church** [comment]
Hi I'm from the GKE team. It is correct that the L4 ILB in GCP currently supports a [max of 5 ports](https://cloud.google.com/load-balancing/docs/quotas) per forwarding rule. We are currently working increasing this limit which is scheduled to go public Beta some time in early Q2 of this year. It is currently in Alpha and so if you would like to get access to this functionality contact your account team to do so. Until then 1 Service type internal LB can map to only 5 ports and so multiple Services will have to be used to expose more than 5 ports.

**Comment by pankaj-akhade** [comment]
@mark-church ,

Could you please tell us the exact date of beta release.

Thank in advance!!

**Comment by Sabyasachi2k** [comment]
> **Describe the bug**
> When creating an istio-ingressgateway in gcp and adding "internal" annotation load balancer is stuck in pending
> 
> **Expected behavior**
> Loadbalancer is created
> 
> **Steps to reproduce the bug**
> add
> serviceAnnotations:
> cloud.google.com/load-balancer-type: "internal"
> to the "istio-ingressgateway:" in the values file
> 
> **Version**
> {{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
> not using istioctl
> Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.3", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-10T00:39:15Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
> 
> **Installation**
> helm chart downloaded from
> https://istio.io/docs/setup/kubernetes/download-release/
> 
> **Environment**
> cloud provider: gcp
> nodes: n1-standard-4 (4 vCPUs, 15 GB memory)
> 
> I am aware of the issue with gcp internal load balancer limit (something that was not written in documentation when we moved to google cloud)
> "A maximum of 5 ports in a forwarding rule, unless you configure the forwarding rule to match all ports."
> 
> there are 8 port configured on "istio-ingressgateway"
> Port 80
> Port 443
> Port 31400
> Port 15011 - tcp-pilot-grpc-tls
> Port 8060 - tcp-citadel-grpc-tls
> Port 853 - tcp-dns-tls
> Port 15030 - http2-prometheus
> Port 15031 - http2-grafana
> 
> I would like to work with everything offered in the ingressgateway
> is there any way around this and still use internal load balancer?
> I tried splitting the LB and putting 80/443/31400/853 on one LB
> and 15011/8060/15030/15031 on the second LB
> But when i started with the bookstore app example everything did not work properly.
> When going back to regular LB (external) with all ports on one LB everything worked great.
> Due to limitations in our company we need to work with internal LB's.
> is there any way around this?
> 
> Thanks

I do not think this is an issue. This is the expected behavior.  What you are trying to do in create an ingress gateway which has an internal IP. This means that it is not exposed outside your cluster. You cannot be hitting this from outside your cluster. And since there is no external IP the external IP is hence shown as <pending>. We use the same configuration and its working as expected. If you have to hit it from say postman from your local it is a bit convoluted but is doable and lets you hit your services hosted in the kubernetes cluster. The other problem is it seems you are trying to hit the Grafana and Kiali from outside, which again is not possible since the "internal" nature of your Istio LB.

**Comment by howardjohn** [comment]
This is fixed in istio 1.6 as we only expose 3 ports. If you have custom configuration please ensure you do not have > 5 ports until support for this is added

**Comment by mark-church** [comment]
Hi everybody, up to 50 ports are now supported for L4 ILBs deployed through GKE Services. Multiple Services can be deployed against the same internal VIP for up to 10 Services per VIP. This does not require whitelisting and is now publicly available: https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing#shared_VIP

**Comment by amankhare94** [comment]
@mark-church I was trying to use the create istio-ingressgateway service. 
Istio version=1.4.10

For that I am still getting the error:

  `Warning  CreatingLoadBalancerFailed  8s (x3 over 37s)   service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service istio-system/istio-ingressgateway: googleapi: Error 400: Invalid value for field 'resource.ports[5]': '15030'. Too many ports specified. Maximum is 5., invalid`

What could be the reason for this?

**Comment by smakam** [comment]
hi @amankhare94 did u use the purpose as mentioned here(https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing#shared_VIP)
