### ISSUE TITLE
VirtualService "Only unique values for domains are permitted" error when bound to gateway

### ISSUE THREAD

**Issue by fbcbarbosa** [istio/istio#11510]
**Describe the bug**

I've configured two different virtualservices (let's call them svcC and svcA) with the same host. Although this should be supported [since 1.01](https://istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host) if the services are bound to a gateway, Pilot immediately started to log _thousands_ of errors, like this one:

```
2019-02-04T16:36:55.695262Zu0009warnu0009adsu0009ADS:RDS: ACK ERROR 127.0.0.1:53914 sidecar~[redacted].svc.cluster.local-1 (u0026{ sidecar [redacted].svc.cluster.local map[POD_NAME:[redacted] istio:sidecar INTERCEPTION_MODE:REDIRECT ISTIO_PROXY_VERSION:1.0.2 ISTIO_PROXY_SHA:istio-proxy:99cfc3f74c414dd4fa4aa784a0f8b13e22b81893 ISTIO_VERSION:1.0.2]}) node:u003cid:"sidecar~[redacted].svc.cluster.local" cluster:"[redacted]" metadata:u003cfields:u003ckey:"INTERCEPTION_MODE" value:u003cstring_value:"REDIRECT" u003e u003e fields:u003ckey:"ISTIO_PROXY_SHA" value:u003cstring_value:"istio-proxy:99cfc3f74c414dd4fa4aa784a0f8b13e22b81893" u003e u003e fields:u003ckey:"ISTIO_PROXY_VERSION" value:u003cstring_value:"1.0.2" u003e u003e fields:u003ckey:"ISTIO_VERSION" value:u003cstring_value:"1.0.2" u003e u003e fields:u003ckey:"POD_NAME" value:u003cstring_value:"planner-77bd79b5f6-9fzgd" u003e u003e fields:u003ckey:"istio" value:u003cstring_value:"sidecar" u003e u003e u003e build_version:"0/1.8.0-dev//RELEASE" u003e resource_names:"15030" resource_names:"8000" resource_names:"9091" resource_names:"9093" resource_names:"9200" resource_names:"3000" resource_names:"8085" resource_names:"8060" resource_names:"15004" resource_names:"20001" resource_names:"9090" resource_names:"15031" resource_names:"9411" resource_names:"5000" resource_names:"15010" resource_names:"8080" resource_names:"80" type_url:"type.googleapis.com/envoy.api.v2.RouteConfiguration" response_nonce:"2019-02-04 16:36:55.454848283 +0000 UTC m=+598.910418388" error_detail:u003ccode:13 message:"Only unique values for domains are permitted. Duplicate entry of domain svcC.mydomain.com.br" u003e
```

I only saw error messages with "Duplicate entry of domain **svcC.mydomain.com.br**", no "Duplicate entry of domain **svcC**". Not sure if relevant. Also note that my services were both bound to a ingress gateway **and** to the internal Mesh gateway, but the documentation does not state this is not supported.

I missed the error logs and let the cluster run like this for a few hours. I first noticed the problem when the communication between two applications unrelated to either svcA and svcC stopped working.

The virtualservice configurations were more or less likes this:

```
---
#service C
spec:
  gateways:
  - gateway
  - mesh
  hosts:
  - svcC.mydomain.com.br
  - svcC
  - svcA.mydomain.com.br
  - svcA
  http:
---
#service A
spec:
  gateways:
  - gateway
  - mesh
  hosts:
  - svcA.mydomain.com.br
  - svcA
  http:
  ...
```

The usecase is that svcA was going to be deprecated for the new API at svc C, but I wanted svcC to resolve requests for both the new and the old hostnames (some clients might have cached the old hostname).

Supposedly it should work [since 1.0.1](https://istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host).

Note that I experienced the same issue on _October_ of last year when running 1.0.1, but didn't report because one of the services had no gateway, so I thought that explained the problem.

**Expected behavior**

I expected no errors. I understand the cross-service order is undefined but this configuration shouldn't break the virtual services involved and specially not unrelated services. If what caused the error is the "Mesh" gateway, then the documentation needs to be updated.

**Steps to reproduce the bug**

Configuring two services like this is what caused the issue:

```
---
#service C
spec:
  gateways:
  - gateway
  - mesh
  hosts:
  - svcC.mydomain.com.br
  - svcC
  - svcA.mydomain.com.br
  - svcA
  http:
---
#service A
spec:
  gateways:
  - gateway
  - mesh
  hosts:
  - svcA.mydomain.com.br
  - svcA
  http:
  ...
```

I will try to run it on Minikube later and see if I can get a working example.

**Version**
Kubernetes version 1.10.11
Istio version 1.0.2

**Installation**
Helm chart.

**Environment**
AWS, managed by Kops.

**Comment by tzilist** [comment]
Getting the same issue here, using istio version 1.1-rc1 and k8s version 1.11.7

**Comment by alaqelsplk** [comment]
Also getting this issue after our upgrade to 1.1

**Comment by cosoriog** [comment]
I'm seeing this in 1.1.0.
Fixed it by splitting virtual service in two, one for public requests and one for internal

```
---
#service C
metadata:
  name: svc-c-public
spec:
  gateways:
  - gateway
  hosts:
  - svcC.mydomain.com.br
  - svcA.mydomain.com.br
  http:
---
#service A
metadata:
  name: svc-a-public
spec:
  gateways:
  - gateway
  hosts:
  - svcA.mydomain.com.br
  http:
---
#service C
metadata:
  name: svc-c-internal
spec:
  gateways:
  - mesh
  hosts:
  - svcC.namespace..svc.cluster.local
  - svcA.namespace..svc.cluster.local
  http:
---
#service A
metadata:
  name: svc-a-internal
spec:
  gateways:
  - mesh
  hosts:
  - svcA.namespace..svc.cluster.local
  http:
  ...
```

In my case, match section for service A and service C are different (different URLs) so this solution might not work in this case.

**Comment by rmichela** [comment]
This issue still affects Istio 1.2.0. You cannot have two `VirtualServices` bound to the same host with the `mesh` gateway enabled on both.

**Comment by howardjohn** [comment]
Running from master this seems to work:
```
cat <<EOF|kaf -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
  namespace: default
spec:
  gateways:
  - mesh
  hosts:
  - 'foo'
  http:
  - match:
    - uri:
        exact: /productpage
    route:
    - destination:
        host: productpage
        port:
          number: 9080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo-2
  namespace: default
spec:
  gateways:
  - mesh
  hosts:
  - 'foo'
  http:
  - match:
    - uri:
        exact: /productpage2
    route:
    - destination:
        host: productpage
        port:
          number: 9080
EOF
```

Is my config not representative of the issue you all are running into, or this may have been fixed?
