### ISSUE TITLE
istio-pilot-multicluster-e2e flakey

### ISSUE THREAD

**Issue by esnible** [istio/istio#11526]
After pushing a PR that is just new samples (no code, just docs) the prow/istio-pilot-multicluster-e2e.sh job failed.

https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11508/istio-pilot-multicluster-e2e/8184

The error is "istio.io/istio/tests/e2e/tests/pilot Failure 0.00s" presumably caused by

```
meshpolicy.authentication.istio.io "default" created
...
error: unable to recognize "/logs/artifacts/pilot-test-60a8d0acfeef49a5b4249154e7/yaml/istio-remote.yaml": no matches for kind "MeshPolicy" in version "authentication.istio.io/v1alpha1"
...
2019-02-05T15:51:02.705863Z	error	Failed to complete Init. Error command failed: "configmap \"istio\" created\nconfigmap \"istio-sidecar-injector\" created\nserviceaccount \"istio-cleanup-secrets-service-account\" created\nclusterrole.rbac.authorization.k8s.io \"istio-cleanup-secrets-istio-system\" created\nclusterrolebinding.rbac.authorization.k8s.io \"istio-cleanup-secrets-istio-system\" created\njob.batch \"istio-cleanup-secrets-43e935545430b718658e04bac1004d45\" created\nserviceaccount \"istio-citadel-service-account\" created\nserviceaccount \"istio-multi\" created\nclusterrole.rbac.authorization.k8s.io \"istio-citadel-istio-system\" created\nclusterrole.rbac.authorization.k8s.io \"istio-reader\" created\nclusterrolebinding.rbac.authorization.k8s.io \"istio-citadel-istio-system\" created\nclusterrolebinding.rbac.authorization.k8s.io \"istio-multi\" created\nservice \"istio-citadel\" created\ndeployment.extensions \"istio-citadel\" created\nservice \"istio-ingressgateway\" created\nendpoints \"istio-ingressgateway\" created\nerror: unable to recognize \"/logs/artifacts/pilot-test-60a8d0acfeef49a5b4249154e7/yaml/istio-remote.yaml\": no matches for kind \"MeshPolicy\" in version \"authentication.istio.io/v1alpha1\"\n" exit status 1

```

All pods were up and running.

**Comment by ymesika** [comment]
@esnible I have a fix for this in #11492 but hitting further failed tests after overcoming the above issue (the two tests I temporarily skipped).

**Comment by ozevren** [comment]
@ymesika, assigning this issue to you, since you're working on it.

**Comment by esnible** [comment]
Test failed today with same PR.  https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11570/istio-pilot-multicluster-e2e/8257

4 failed / 630 succeeded in 31m39s

Failures were of the form "try again" from _tests/e2e/tests/pilot/pilot_test.go_

```
--- FAIL: TestTLSMultiplexing (126.67s)
    --- FAIL: TestTLSMultiplexing/request (105.40s)
        --- PASS: TestTLSMultiplexing/request/a->d_80 (0.77s)
        --- PASS: TestTLSMultiplexing/request/a->d.istio-system_80 (0.54s)
        --- FAIL: TestTLSMultiplexing/request/a->d_7070 (49.32s)
        	pilot_test.go:213: try again
        --- FAIL: TestTLSMultiplexing/request/a->d.istio-system_7070 (47.92s)
        	pilot_test.go:213: try again
```

**The error "try again" is useless!  Dozens of tests throw it!  What does it mean?!?**  We are never going to find the flake if we don't have more data on what went wrong.

**Comment by esnible** [comment]
Test failed today with a documentation-only PR: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11508/istio-pilot-multicluster-e2e/8397

3 failed / 631 succeeded in 30m58s

Failures were of the form "expected 10 requests to reach v2 => Got map[]" from _tests/e2e/tests/pilot/pilot_test.go_

```
--- FAIL: TestVirtualServiceMergingAtGateway (46.95s)
    --- FAIL: TestVirtualServiceMergingAtGateway/VirtualServiceMergingAtGateway-route1 (12.14s)
    	pilot_test.go:213: expected 10 requests to reach v1 => Got map[]
    --- FAIL: TestVirtualServiceMergingAtGateway/VirtualServiceMergingAtGateway-route2 (11.99s)
    	pilot_test.go:213: expected 10 requests to reach v2 => Got map[]
    --- PASS: TestVirtualServiceMergingAtGateway/VirtualServiceMergingAtGateway-route1#01 (0.76s)
    --- PASS: TestVirtualServiceMergingAtGateway/VirtualServiceMergingAtGateway-route2#01 (0.80s)
```

**The error "expected 10 requests to reach v2 => Got map[]" is confusing.  What does it mean? **

That error is thrown by _tests/e2e/tests/pilot/ingressgateway_test.go_ line 312.  TestVirtualServiceMergingAtGateway().  I suspect the message means that of the 10 requests 0 succeeded reaching either version.  Earlier in the log I see ```
error	client request error command failed: "2019-02-10T14:08:44.632511Z\tinfo\tError Get http://istio-ingressgateway.istio-system/route2: dial tcp 10.11.242.94:80: connect: connection refused\ncommand terminated with exit code 1\n" exit status 1 for http://istio-ingressgateway.istio-system/route2 in t from primary cluster
``` which I means the IngressGateway isn't listening.  From the logs I am unsure why it is not listening.

**Comment by esnible** [comment]
Another failure on TestTLSMultiplexing today.

**Comment by esnible** [comment]
Test today failed with same PR.  https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11592/istio-pilot-multicluster-e2e/8434

```
...
2019-02-11T18:59:38.392311Z	info	All deployments are ready
...
        --- PASS: TestSidecarScope/v1alpha3/ns1:_bookinfo.com:9999_reachable_via_egress_TCP_listener_7.7.7.7:23145_from_remote_cluster (0.94s)
=== RUN   TestTcpNonHeadlessPorts
=== RUN   TestTcpNonHeadlessPorts/request
=== RUN   TestTcpNonHeadlessPorts/request/a_from_primary_cluster->a_90
SIGQUIT: quit
...
*** Test killed with quit: ran too long (36m0s).
```

**Comment by esnible** [comment]
Failed with same PR: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11592/istio-pilot-multicluster-e2e/8495

```
2019-02-12T19:38:58.783562Z	info	Running command /home/prow/go/out/linux_amd64/release/istioctl --kubeconfig= -n istio-system proxy-config endpoint c-v2-66f4f568bd-pwjk4
2019-02-12T19:38:59.938277Z	error	endpoints for app 'c' in proxy config in pod c-v2-66f4f568bd-pwjk4 are not correct: [10.24.0.8 10.24.3.10 10.8.0.17 10.8.3.10] vs [10.8.0.17 10.8.3.10]
```
etc.

**Comment by duderino** [comment]
Here are three recent examples:


https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11702/istio-pilot-multicluster-e2e/8490
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11602/istio-pilot-multicluster-e2e/8470
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11707/istio-pilot-multicluster-e2e/8497/

**Comment by duderino** [comment]
@wenchenglu can you assign someone to fix the TestTLSMultiplexing errors.

**Comment by duderino** [comment]
This is affecting lots of 1.1 PRs so P0.

**Comment by duderino** [comment]
I think there are at least 2 issues here.  The TestTLSMultiplexing errors may have resulted from a recent Envoy import, but @wenchenglu will ask someone to look into that.

There also seems to be a much older general environment instability.  Commentary from @ozevren:

```
I think this is the culprit:
error: unable to recognize "/logs/artifacts/pilot-test-3e602856e64d400e9289d7726d/yaml/istio-remote.yaml": no matches for kind "MeshPolicy" in version "authentication.istio.io/v1alpha1" 2019-02-12T19:58:54.247714Z	info Command error: exit status 1 2019-02-12T19:58:54.247814Z error	Remote Istio /logs/artifacts/pilot-test-3e602856e64d400e9289d7726d/yaml/istio-remote.yaml deployment failed 2019-02-12T19:58:54.247824Z	error Failed to deploy Istio.
It looks like we might be missing a CRD maybe?
I am assuming this is relase-1.1 branch? This also looks suspicious:

..Successfully got an update from the "stable" chart repository Update Complete. ⎈Happy Helming!⎈ Saving 4 charts Downloading istio-cni from repo https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts Deleting outdated charts configmap "istio" created configmap "istio-sidecar-injector" created
(Notice the master-latest-daily in the URL).I think Steven Dake was saying something about this
```

@utka can you check out the latter?

**Comment by wenchenglu** [comment]
@JimmyCYJ will look into it

**Comment by JimmyCYJ** [comment]
I am looking at the test log of TestTLSMultiplexing/request/a->d_7070.
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11570/istio-pilot-multicluster-e2e/8257?log#log

From the following error logs, it is very likely that proxy crashes.
=== RUN   TestTLSMultiplexing/request/t->d_7070
2019-02-06T21:19:16.668162Z	error	client request error command failed: "2019-02-06T21:19:16.611142Z\tinfo\tError Get http://d:7070/t: read tcp 10.52.0.15:58504->10.55.250.142:7070: read: connection reset by peer\ncommand terminated with exit code 1\n" exit status 1 for http://d:7070/t in t from primary cluster
=== RUN   TestTLSMultiplexing/request/t->d.istio-system_7070
2019-02-06T21:19:17.168787Z	error	client request error command failed: "2019-02-06T21:19:17.138379Z\tinfo\tError Get http://d.istio-system:7070/t: read tcp 10.52.0.15:58544->10.55.250.142:7070: read: connection reset by peer\ncommand terminated with exit code 1\n" exit status 1 for http://d.istio-system:7070/t in t from primary cluster

**Comment by incfly** [comment]
Trying to narrow down the root of cause. Questions

- TLSMultiplexing only fails/flakey in multicluster-e2e? I looked at the test grid and seems it's passing stable in pilot e2e test, https://testgrid.k8s.io/istio-presubmits#pilot-e2e-envoyv2-v1alpha3
- If it's only failing in multicluster setup, I really doubt this has something to do with our SNI based gateway(tls inspector) used in multi cluster + Permissive mode implemented by ALPN (tls_inspector). Not sure after requests are routed using SNI, will the server side car can still get ALPN bytes?

@rshriram @PiotrSikora thoughts?

**Comment by rshriram** [comment]
are the requests crossing two clusters, where service in one cluster is accessing a serivce in another cluster over plain text?
I am not sure what is the state of the current multicluster, single control plane setup. Not sure if we use the ingress gateway by default to forward requests. If we do that, then the TLS multiplexing wont work as the ingress gateway will only do SNI passthrough and nothing else.

**Comment by incfly** [comment]
I don't know that either... @esnible could you comment on current multi cluster setup and what are app deployments in the test?

@rshriram We don't need ingress gateway to do more fancy stuff other than replay the requests. My concern is: gateway sni is based on `envoy.listener_filter.tls_inspector`, the targeted server side service sidecar also rely on `listener_filter.tls_inspector`, and PERMISSIVE only works if the ALPN is detected by the sidecar's tls_inspector. I doubt after sni passthrough happen, that ALPN bytes are lost at server side sidecar, thus permissive won't work.

**Comment by rshriram** [comment]
that was my point. if you are not using a gateway and directly talking from source sidecar to destination server sidecar in another cluster, then things should work. If you are talking via any intermediary, then it will break immediately.

**Comment by utka** [comment]
This is additional setup which happens for multicluster test comparing to single one 
https://github.com/istio/istio/blob/c3973fd36b55c8a38999e1fa0feecea3040c6226/prow/cluster_lib.sh#L65 and https://github.com/istio/istio/blob/c3973fd36b55c8a38999e1fa0feecea3040c6226/prow/cluster_lib.sh#L123

**Comment by incfly** [comment]
So if I understand correctly, with current Envoy expected behavior, inspected bytes can only be consumed once, then permissive mode doesn't really work for gateway based multi cluster? And only works for VPC based multi cluster. Does that sound right?

**Comment by PiotrSikora** [comment]
That's not necessarily true, if intermediary is acting as a TCP proxy and not terminating TLS, then it shouldn't affect anything and service-to-service `PERMISSIVE` mode should still work.

Having said that, I have no idea how the multi-cluster is supposed to work. Could someone draw a diagram with network paths and transport protocols involved? Thank you.

**Comment by incfly** [comment]
Assigned to @esnible and @ymesika per https://github.com/istio/istio/issues/11526#issuecomment-462970163

**Comment by JimmyCYJ** [comment]
Is there a way to run istio-pilot-multicluster-e2e from local machine? I am trying to run this test in my own cluster. $ ./prow/istio-pilot-multicluster-e2e.sh E2E_ARGS="--skip_cleanup" does not work. It keeps printing out these messages.

```
+ mason_client --type=gke-e2e-test --boskos-url=http://boskos.boskos.svc.cluster.local --owner=istio-pilot-multicluster-e2e --info-save /tmp/jIVDI.boskos.info --kubeconfig-save /usr/local/google/home/yinjie/.kube/config
+ ready=false
+ [[ false == true ]]
+ kill -s 0 161749
+ exited=false
+ [[ false == true ]]
+ sleep 10
+ for _ in {1..60}
+ grep -q READY /tmp/rmrsS.boskos.log
+ ready=false
...
```

**Comment by ymesika** [comment]
This test is an old one for what we called in v1.0 "VPN Connectivity" where a flat network is assumed. 
In that Multicluster setup the calls between clusters were direct and not through a gateway like we have in _Gateway connectivity_ or _Split Horizon EDS_. Therefore you need a shared and routable network between the local/remote clusters in order to run it.

Not sure who added this test but I believe the intentions were to run the same single cluster test on both local and remote clusters. So if you run a test, for instance, that `a` calls `d` from either local's `a` or remote's `a`, it will hit `d` but you don't know if it's the local or remote endpoint of that `d` service.
You don't care as long as you don't have auth enabled. When auth is enabled and strict (like in the TestTLSMultiplexing) the calls will fail when calling `d` on the other cluster. Reason is that both clusters are not using the same root CA.

This isn't the only problem in the test though. Other problems is that it takes ~40 mins to execute and usually fails on the timeout or incorrect values file taken for the setup. See my PR referenced above for changes I had to make to make the test pass.

**Comment by incfly** [comment]
Thanks for the explanation and deep dive! @ymesika 

So if the issue is due to the root cert is not the same, and TLS failed at STRICT mode, then we definitely should fix the test infra setup to make multi cluster use the same root, which is what we recommend to our users.

FYI @utka 

Remove this from release-1.1 milestone give the issue is about align test setup with our release.

**Comment by esnible** [comment]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11734/istio_auth_sds_e2e/1933

15 failed / 286 succeeded in 20m46s.  Failures are pilot TestGrpc, pilot TestHttp, and pilot TestRouteMirroring.

**Comment by howardjohn** [comment]
Tests are still failing continuously https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12844/istio-pilot-multicluster-e2e/10293

**Comment by incfly** [comment]
Unassign myself since `TestTLSMultiplexing` is no longer in the failing test.

**Comment by vadimeisenbergibm** [comment]
Seems to be related to https://github.com/istio/istio/issues/12446, the health-check of all the remote tests fail.

**Comment by howardjohn** [comment]
New type of failures @john-a-joyce https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/13344/istio-pilot-multicluster-e2e/11064

**Comment by howardjohn** [comment]
This test is now passing. If it doesn't you may need to pick up recent changes. If it still fails open a new issue
