### ISSUE TITLE
Istio breaks MongoDb from helm

### ISSUE THREAD

**Issue by kamilgregorczyk** [istio/istio#11675]
I'd like to run stable/mongodb chart from helm repo but I'm not able to connect to it once istio is enabled in cluster. It works perfectly when there is no istio. I tried connecting to mongo with other deployment, I also tried their client from their helm notes and I'm getting connection refused errros. What's more, kubernetes can't perform any readiness checks as it's also failing. Here's what I did:

1. Ran minikube
1. Installed helm with tiller account 
1. Installed istio with this command:
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set prometheus.service.nodePort.enabled=true --set tracing.enabled=true --set tracing.service.type=NodePort --set kiali.enabled=true --set grafana.enabled=true --set grafana.service.type=NodePort
```
1. Enabled sidecar injection for default & micronaut-blog namespace
1. Installed mongo with this command 
```
helm install stable/mongodb --namespace=micronaut-blog --name mongo --set securityContext.fsGroup=0,securityContext.runAsUser=0
```
1. Tried to connect to it by running:
```
export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace micronaut-blog mongo-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)

 kubectl run --namespace micronaut-blog mongo-mongodb-client --rm --tty -i --restart='Never' --image bitnami/mongodb --command -- mongo admin --host mongo-mongodb --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
```

And I got:
```
➜  blog git:(master) ✗ kubectl -n micronaut-blog logs  mongo-mongodb-client mongo-mongodb-client
MongoDB shell version v4.0.6
connecting to: mongodb://mongo-mongodb:27017/admin?authSource=admin&gssapiServiceName=mongodb
2019-02-11T18:19:24.256+0000 E QUERY    [js] Error: couldn't connect to server mongo-mongodb:27017, connection attempt failed: SocketException: Error connecting to mongo-mongodb:27017 (10.107.86.91:27017) :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:343:13
@(connect):1:6
exception: connect failed
```
Password that got exported is correct, I also tried with other deployment and I got the same result.

Here are logs from  mongo pod:
```
 kubectl -n micronaut-blog describe pod mongo-mongodb-5b5dcd74b4-tqt7m
...
...
  Warning  Unhealthy  52m  kubelet, minikube  Liveness probe failed: MongoDB shell version v4.0.6
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
2019-02-11T17:38:38.431+0000 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:343:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  52m  kubelet, minikube  Readiness probe failed: MongoDB shell version v4.0.6
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
2019-02-11T17:38:42.994+0000 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:343:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  52m (x2 over 52m)  kubelet, minikube  (combined from similar events): Readiness probe failed: MongoDB shell version v4.0.6
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
2019-02-11T17:38:52.514+0000 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:343:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  10m  kubelet, minikube  Readiness probe failed: OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "process_linux.go:95: adding pid 17055 to cgroups caused \"failed to write 17055 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod8fbb7f7f-2e23-11e9-9138-080027b7e471/7530730b25330511b523079e0eac0fd5fa5ea7d09db2c9b2234acc2de9615dc3/cgroup.procs: invalid argument\"": unknown

```

NOTE:
I'm running mongo with some args because of #8443 

**Version**
```
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
helm

**Environment**
MacOS, Minikube

**Comment by kamilgregorczyk** [comment]
I just created a new namespace without istio injection and it works flawlessly

**Comment by Bessonov** [comment]
Dup of https://github.com/istio/istio/issues/8443

Should be fixed by https://github.com/istio/istio/pull/10507

**Comment by FengyunPan2** [comment]
meet it too.

**Comment by howardjohn** [comment]
I am pretty sure this is fixed in 1.1, just need to confirm. More discussion on it here, so I'll close this to consolidate since they are the same problem. https://github.com/istio/istio/issues/8443

If you do see this issue on 1.1.3+ please let us know

**Comment by sukruthakittur** [comment]
I still have the exact same issue on 1.2.2. Is there a known resolution for it?

**Comment by n-moser** [comment]
Our problem was that the MongoDB only creates the user configuration in the very first run. However, the initial connection to the database can only be established later due to Istio, so the MongoDB is restarted and the configuration becomes corrupt. Our workaround was to deactivate the sidecar injection, then install the Mongodb and reactivate the injection afterwards.

**Comment by ktarplee** [comment]
@howardjohn This is still an issue with ISTIO 1.3.3.  It seems to be what @n-moser claims above.

Log from the first time start...

```text
10:18:26.35 
 10:18:26.35 Welcome to the Bitnami mongodb container
 10:18:26.35 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
 10:18:26.36 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 10:18:26.36 Send us your feedback at containers@bitnami.com
 10:18:26.36 
 10:18:26.36 INFO  ==> ** Starting MongoDB setup **
 10:18:26.37 INFO  ==> Validating settings in MONGODB_* env vars...
 10:18:26.37 INFO  ==> Initializing MongoDB...
 10:18:26.37 INFO  ==> Deploying MongoDB from scratch...
 10:18:26.37 INFO  ==> No injected configuration files found. Creating default config files...
 10:18:27.01 INFO  ==> Creating users...
 10:18:27.01 INFO  ==> Creating root user...
exception: connect failed
 10:18:27.06 INFO  ==> Stopping MongoDB...
```

Log after the pod restart...

```text
10:18:29.49 
 10:18:29.49 Welcome to the Bitnami mongodb container
 10:18:29.50 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
 10:18:29.50 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 10:18:29.50 Send us your feedback at containers@bitnami.com
 10:18:29.50 
 10:18:29.50 INFO  ==> ** Starting MongoDB setup **
 10:18:29.51 INFO  ==> Validating settings in MONGODB_* env vars...
 10:18:29.51 INFO  ==> Initializing MongoDB...
 10:18:29.51 INFO  ==> Deploying MongoDB with persisted data...
 10:18:29.51 INFO  ==> No injected configuration files found. Creating default config files...
 10:18:29.57 INFO  ==> 
 10:18:29.57 INFO  ==> ########################################################################
 10:18:29.58 INFO  ==>  Installation parameters for MongoDB:
 10:18:29.58 INFO  ==>    Persisted data and properties have been restored.
 10:18:29.58 INFO  ==>    Any input specified will not take effect.
 10:18:29.58 INFO  ==> (Passwords are not shown for security reasons)
 10:18:29.58 INFO  ==> ########################################################################
 10:18:29.58 INFO  ==> 
 10:18:29.58 INFO  ==> Loading custom scripts...
find: '/docker-entrypoint-initdb.d/': No such file or directory
 10:18:29.58 INFO  ==> ** MongoDB setup finished! **

 10:18:29.59 INFO  ==> ** Starting MongoDB **
2019-11-22T10:18:29.612+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
2019-11-22T10:18:29.614+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2019-11-22T10:18:29.616+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/bitnami/mongodb/data/db 64-bit host=pai-mongodb-74fd866c79-md5tv
2019-11-22T10:18:29.616+0000 I CONTROL  [initandlisten] db version v4.0.13
2019-11-22T10:18:29.616+0000 I CONTROL  [initandlisten] git version: bda366f0b0e432ca143bc41da54d8732bd8d03c0
2019-11-22T10:18:29.616+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
2019-11-22T10:18:29.616+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2019-11-22T10:18:29.616+0000 I CONTROL  [initandlisten] modules: none
2019-11-22T10:18:29.616+0000 I CONTROL  [initandlisten] build environment:
2019-11-22T10:18:29.617+0000 I CONTROL  [initandlisten]     distmod: debian92
2019-11-22T10:18:29.617+0000 I CONTROL  [initandlisten]     distarch: x86_64
2019-11-22T10:18:29.617+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2019-11-22T10:18:29.617+0000 I CONTROL  [initandlisten] options: { config: "/opt/bitnami/mongodb/conf/mongodb.conf", net: { bindIpAll: true, ipv6: false, port: 27017, unixDomainSocket: { enabled: true, pathPrefix: "/opt/bitnami/mongodb/tmp" } }, processManagement: { fork: false, pidFilePath: "/opt/bitnami/mongodb/tmp/mongodb.pid" }, security: { authorization: "disabled" }, setParameter: { enableLocalhostAuthBypass: "true" }, storage: { dbPath: "/bitnami/mongodb/data/db", directoryPerDB: false, journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, logRotate: "reopen", path: "/opt/bitnami/mongodb/logs/mongodb.log", quiet: false, verbosity: 0 } }
```

With sidecar.istio.io/inject: "false" the log is...

```text
10:44:50.74 
 10:44:50.74 Welcome to the Bitnami mongodb container
 10:44:50.74 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
 10:44:50.74 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 10:44:50.74 Send us your feedback at containers@bitnami.com
 10:44:50.74 
 10:44:50.75 INFO  ==> ** Starting MongoDB setup **
 10:44:50.75 INFO  ==> Validating settings in MONGODB_* env vars...
 10:44:50.76 INFO  ==> Initializing MongoDB...
 10:44:50.76 INFO  ==> Deploying MongoDB from scratch...
 10:44:50.76 INFO  ==> No injected configuration files found. Creating default config files...
 10:44:51.40 INFO  ==> Creating users...
 10:44:51.40 INFO  ==> Creating root user...
 10:44:51.56 INFO  ==> Enabling authentication...
 10:44:51.57 INFO  ==> Users created
 10:44:51.57 INFO  ==> Stopping MongoDB...
 10:44:53.05 INFO  ==> 
 10:44:53.05 INFO  ==> ########################################################################
 10:44:53.05 INFO  ==>  Installation parameters for MongoDB:
 10:44:53.05 INFO  ==> (Passwords are not shown for security reasons)
 10:44:53.05 INFO  ==> ########################################################################
 10:44:53.05 INFO  ==> 
 10:44:53.06 INFO  ==> Loading custom scripts...
find: '/docker-entrypoint-initdb.d/': No such file or directory
 10:44:53.06 INFO  ==> ** MongoDB setup finished! **

 10:44:53.07 INFO  ==> ** Starting MongoDB **
2019-11-22T10:44:53.093+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
2019-11-22T10:44:53.095+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2019-11-22T10:44:53.097+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/bitnami/mongodb/data/db 64-bit host=pai-mongodb-98b777b7b-j64rb
2019-11-22T10:44:53.097+0000 I CONTROL  [initandlisten] db version v4.0.13
2019-11-22T10:44:53.097+0000 I CONTROL  [initandlisten] git version: bda366f0b0e432ca143bc41da54d8732bd8d03c0
2019-11-22T10:44:53.097+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
2019-11-22T10:44:53.097+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2019-11-22T10:44:53.097+0000 I CONTROL  [initandlisten] modules: none
2019-11-22T10:44:53.097+0000 I CONTROL  [initandlisten] build environment:
2019-11-22T10:44:53.097+0000 I CONTROL  [initandlisten]     distmod: debian92
2019-11-22T10:44:53.097+0000 I CONTROL  [initandlisten]     distarch: x86_64
2019-11-22T10:44:53.097+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2019-11-22T10:44:53.097+0000 I CONTROL  [initandlisten] options: { config: "/opt/bitnami/mongodb/conf/mongodb.conf", net: { bindIpAll: true, ipv6: false, port: 27017, unixDomainSocket: { enabled: true, pathPrefix: "/opt/bitnami/mongodb/tmp" } }, processManagement: { fork: false, pidFilePath: "/opt/bitnami/mongodb/tmp/mongodb.pid" }, security: { authorization: "enabled" }, setParameter: { enableLocalhostAuthBypass: "false" }, storage: { dbPath: "/bitnami/mongodb/data/db", directoryPerDB: false, journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, logRotate: "reopen", path: "/opt/bitnami/mongodb/logs/mongodb.log", quiet: false, verbosity: 0 } }
```

I ran into this problem because I noticed the following:
* Without ISTIO the root password authentication was enabled and set properly and no mongodb restarts.
* With ISTIO the root password authentication was disabled (because the generated config file changed) and the pod failed to launch the first time.

I suspect this is a bitnami/mongodb issue but I am not sure.  It seems to fail on startup because ISTIO causes the "connect failed".

**Comment by akrausesap** [comment]
I still have the same issue with istio 1.3.5. please see referenced issue for further details
