### ISSUE TITLE
TLS modes PASSTHROUGH and SIMPLE do not work in same cluster

### ISSUE THREAD

**Issue by adenis-sv** [istio/istio#11786]
**Describe the bug**
I am trying to implement TLS termination on Gateway for one application and on backend side for another.
Following tasks from the documentation.

    https://istio.io/docs/tasks/traffic-management/secure-ingress/ 1
    For TLS mode SIMPLE
    https://preliminary.istio.io/docs/examples/advanced-gateways/ingress-sni-passthrough/ 1
    For TLS mode PASSTHROUGH

Each of them separately works fine.

But if I an trying to deploy them both the second one reports error on attempt to connect.
The first one looks the winner.
Tried to use the unique port names in Gateway and Server but it did not help as well.

Error for the second application looks like

curl -vvv https://myapp.mydomain.com
*   Trying 34.123.123.123…
* TCP_NODELAY set
* Connected to myapp.mydomain.com (34.123.123.123) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to myapp.mydomain.com:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to myapp.mydomain.com

**Expected behavior**
Applications with TLS mode SIMPLE and PASSTHROUGH should work in the same cluster

**Steps to reproduce the bug**
    Install application with TLS mode SIMPLE
    https://istio.io/docs/tasks/traffic-management/secure-ingress/ 1
    and with PASSTHROUGH
    https://preliminary.istio.io/docs/examples/advanced-gateways/ingress-sni-passthrough/ 1
    
Tried to adjust Gateways to make port name unique like the following

Gateway for tls mode SIMPLE

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
  namespace: httpbin
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http-httpbin
      protocol: HTTP
#    tls:
#      httpsRedirect: true
    hosts:
    - "httpbin.mydomain.com"
  - port:
      number: 443
      name: https-httpbin
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "httpbin.mydomain.com"
```

And for PASSTROUGH

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: nginx-passthrough
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http-nginx
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - nginx.mydomain.com
  - port:
      number: 443
      name: https-nginx
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - nginx.mydomain.com
```
Tried to discuss it on https://discuss.istio.io/t/tls-modes-passthrough-and-simple/852
Any advises how to address the issue would be appreciated

**Version**
Kubernetes 1.11(AWS EKS), Istio 1.0.5

**Installation**
istio:
	helm install --wait \
	--name istio \
	--namespace istio-system \
	--set global.mtls.enabled=true \
	install/kubernetes/helm/istio

**Environment**
Kubernetes 1.11(AWS EKS)

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by rshriram** [comment]
If you mark the passthrough port's protocol as TLS, it should work as intended.. HTTPS implies you are doing TLS termination of HTTP requests. TLS implies (in istio), you are either terminating TLS connection or forwarding it based on SNI.

**Comment by adenis-sv** [comment]
Tried these changes, still same error
```    port:
      name: https-nginx
      number: 443
      protocol: TLS
    tls:
      mode: PASSTHROUGH
```
and just in case tried with 'tls-" port name as well
```    port:
      name: tls-nginx
      number: 443
      protocol: TLS
    tls:
      mode: PASSTHROUGH
```

**Comment by kbruner** [comment]
I hate a similar issue, this time with both gateway ports being intended for TLS passthrough.  (Istio 1.0.5)

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: https-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: tls-mysvc
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "mysvc.example.com"
  - port:
      number: 443
      name: tls-nginx
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "nginx.example.com"
```

The API accepts the policy, but the `istio-ingressgateway` pod log has the following: `[2019-02-26 00:31:37.514][27][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 0.0.0.0_443: error adding listener '0.0.0.0:443': multiple filter chains with the same matching rules are defined`

Same issue if I replace TLS/tls with HTTPS/https.

(This may be a different issue because of the port re-use.  If so, let me know and I'll file a separate issue.)

**Comment by rshriram** [comment]
ack

**Comment by hzxuzhonghu** [comment]
using istio-1.1.0-rc.0, i found 
```
2019-02-26T05:31:48.839826Z	warn	ads	ADS:LDS: ACK ERROR 127.0.0.1:39148 istio-ingressgateway-6c8bf9f58d-trj9m.istio-system version_info:"2019-02-26T05:31:00Z/33" node:<id:"router~172.17.0.4~istio-ingressgateway-6c8bf9f58d-trj9m.istio-system~istio-system.svc.cluster.local" cluster:"istio-ingressgateway" metadata:<fields:<key:"CONFIG_NAMESPACE" value:<string_value:"istio-system" > > fields:<key:"ISTIO_META_INSTANCE_IPS" value:<string_value:"172.17.0.4,172.17.0.4" > > fields:<key:"ISTIO_PROXY_SHA" value:<string_value:"istio-proxy:fc273e117a6ed875c7cb9b3c3251c8d982bc7196" > > fields:<key:"ISTIO_PROXY_VERSION" value:<string_value:"1.1.0" > > fields:<key:"ISTIO_VERSION" value:<string_value:"1.1.0-rc.0" > > fields:<key:"POD_NAME" value:<string_value:"istio-ingressgateway-6c8bf9f58d-trj9m" > > fields:<key:"ROUTER_MODE" value:<string_value:"sni-dnat" > > fields:<key:"istio" value:<string_value:"sidecar" > > > locality:<> build_version:"fc273e117a6ed875c7cb9b3c3251c8d982bc7196/1.10.0-dev/Clean/RELEASE/BoringSSL" > type_url:"type.googleapis.com/envoy.api.v2.Listener" response_nonce:"68c11f3d-25f6-48dd-b5d9-442b6efdf7c4" error_detail:<code:13 message:"Error adding/updating listener 0.0.0.0_443: Proto constraint validation failed (field: \"route_specifier\", reason: is required): stat_prefix: \"0.0.0.0_443\"\nhttp_filters {\n  name: \"mixer\"\n  typed_config {\n    [type.googleapis.com/istio.mixer.v1.config.client.HttpClientConfig] {\n      transport {\n        network_fail_policy {\n          policy: FAIL_CLOSE\n        }\n        check_cluster: \"outbound|15004||istio-policy.istio-system.svc.cluster.local\"\n        report_cluster: \"outbound|15004||istio-telemetry.istio-system.svc.cluster.local\"\n      }\n      service_configs {\n        key: \"default\"\n        value {\n        }\n      }\n      default_destination_service: \"default\"\n      mixer_attributes {\n        attributes {\n          key: \"context.reporter.kind\"\n          value {\n            string_value: \"outbound\"\n          }\n        }\n        attributes {\n          key: \"context.reporter.uid\"\n          value {\n            string_value: \"kubernetes://istio-ingressgateway-6c8bf9f58d-trj9m.istio-system\"\n          }\n        }\n        attributes {\n          key: \"source.namespace\"\n          value {\n            string_value: \"istio-system\"\n          }\n        }\n        attributes {\n          key: \"source.uid\"\n          value {\n            string_value: \"kubernetes://istio-ingressgateway-6c8bf9f58d-trj9m.istio-system\"\n          }\n        }\n      }\n      forward_attributes {\n        attributes {\n          key: \"source.uid\"\n          value {\n            string_value: \"kubernetes://istio-ingressgateway-6c8bf9f58d-trj9m.istio-system\"\n          }\n        }\n      }\n    }\n  }\n}\nhttp_filters {\n  name: \"envoy.cors\"\n}\nhttp_filters {\n  name: \"envoy.fault\"\n}\nhttp_filters {\n  name: \"envoy.router\"\n}\ntracing {\n  operation_name: EGRESS\n  client_sampling {\n    value: 100\n  }\n  random_sampling {\n    value: 100\n  }\n  overall_sampling {\n    value: 100\n  }\n}\nserver_name: \"istio-envoy\"\naccess_log {\n  name: \"envoy.file_access_log\"\n  typed_config {\n    [type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog] {\n      path: \"/dev/stdout\"\n      format: \"[%START_TIME%] \\\"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\\\" %RESPONSE_CODE% %RESPONSE_FLAGS% \\\"%DYNAMIC_METADATA(istio.mixer:status)%\\\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \\\"%REQ(X-FORWARDED-FOR)%\\\" \\\"%REQ(USER-AGENT)%\\\" \\\"%REQ(X-REQUEST-ID)%\\\" \\\"%REQ(:AUTHORITY)%\\\" \\\"%UPSTREAM_HOST%\\\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME%\\n\"\n    }\n  }\n}\nuse_remote_address {\n  value: true\n}\ngenerate_request_id {\n  value: true\n}\nforward_client_cert_details: SANITIZE_SET\nset_current_client_cert_details {\n  subject {\n    value: true\n  }\n  dns: true\n  uri: true\n}\nupgrade_configs {\n  upgrade_type: \"websocket\"\n}\nstream_idle_timeout {\n}\n" > 

```

**Comment by rshriram** [comment]
@adenis-sv what is your virtual service configuration for the gateway ? [remember that gateways need virtual services to complete the routing]. 

Same goes for @kbruner . Since you are using TLS passthrough, I am assuming that your virtual service is using TLS blocks for routing?

**Comment by GregHanson** [comment]
resolved by #12071

**Comment by nirvanagit** [comment]
@adenis-sv - did you SNI and SIMPLE work on the same port?

**Comment by gauti038** [comment]
I am using version 1.4.2. Still facing the same issue. Did anyone solve this? If so, Please explain

**Comment by mchendil82** [comment]
I do face the same issue..  I believe the actual issue is that "PASSTHROUGH mode itself not working".. People might have combined 2 ISTIO gateways and assuming that it is not working with 2 different gateways with, "SIMPLE" and "PASSTHROUGH" mode  (it could be an older issue on port context i.e. was with same port, 2 gateways were not working in past and I believe @rshriram fixed it already)..

But now, the fact is that "PASSTHROUGH" mode is not working at all even just with a single gateway.. We do have application that need to be up with HTTPS behind envoy proxy  via ingress but simple "PASSTHROUGH" is not working... Ingress nodeport times out as soon as,  I change it to "PASSHTROUGH" but when I switch the "tlsmode" to: "SIMPLE" or "AUTO_PASSTHROUGH", "MUTUAL" mode, gateway is up and I able to telnet it via Node port... 

Only for "PASSTHROUGH" mode gateway is NOT coming up and it times out.

**Comment by houshym** [comment]
I have same issue. any solution for that. I just read this blog http://linjing.io/post/istio-ingressgateay-port-relationship/ but the solution does not work. 
my scenario is:
1- in one of my microservice, I have a apache server ( ssl enabled) expose on container port 8443. 
2- in second one (seperate app), I have nginx ssl enabled( port 443)
I have a GW for each service (PASSTHROUGH). each of them work solely but if I apply both GW, one of them randomly generate  curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to nginx.skylinenet.net:443
