### ISSUE TITLE
Helm repo for 1.1.1 uses wrong hub

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12884]
`hub: gcr.io/istio-release` should be `hub: docker.io/istio`.

1.1.0 is correct, 1.1.1 is wrong.

 https://storage.googleapis.com/istio-release/releases/1.1.1/charts/istio-1.1.1.tgz

@mandarjog @utka

**Comment by utka** [comment]
Fixed manually.

**Comment by jnsvd** [comment]
I'm still getting errors when applying the `istio-init` chart:

```
Back-off pulling image "gcr.io/istio-release/kubectl:1.1.1
Error: ImagePullBackOff
pulling image "gcr.io/istio-release/kubectl:1.1.1"
Failed to pull image "gcr.io/istio-release/kubectl:1.1.1": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/istio-release/kubectl:1.1.1 not found
Error: ErrImagePull
```

**Comment by eperdeme** [comment]
Same error here;

https://gcsweb.istio.io/gcs/istio-release/releases/1.1.1/charts/
```yaml
  istio-init:
    namespace: istio-system
    enabled: true
    wait: true
    chart: istio/istio-init
    version: 1.1.0
  istio:
    namespace: istio-system
    enabled: true
    chart: istio/istio
    version: 1.1.0
```
```bash
Failed to pull image "gcr.io/istio-release/kubectl:1.1.1": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/istio-release/kubectl:1.1.1 not found
```

**Comment by jnsvd** [comment]
@utka Can this issue be reopened?

**Comment by utka** [comment]
Updated istio-init as well

**Comment by jnsvd** [comment]
@utka I can confirm the issue is resolved now, so this ticket can be closed.
Thanks.
