### ISSUE TITLE
Chart version and appVersion are not updated release.

### ISSUE THREAD

**Issue by morvencao** [istio/istio#14290]
Download Istio release 1.1.1 and beyond from release page: https://github.com/istio/istio/releases

And extract the release tarball, then check the version in `Chart.yaml`, you will see that the chart version and `appVersion` are not updated:

```
root@mcdev:~/ibm-istio# grep -i version  istio-1.1.4/install/kubernetes/helm/istio-init/Chart.yaml
apiVersion: v1
version: 1.1.0
appVersion: 1.1.0
tillerVersion: ">=2.7.2-0"
root@mcdev:~/ibm-istio# grep -i version  istio-1.1.4/install/kubernetes/helm/istio/Chart.yaml
apiVersion: v1
version: 1.1.0
appVersion: 1.1.0
tillerVersion: ">=2.7.2-0"
```

I can see we have [release script](https://github.com/istio/istio/blob/master/release/gcb/helm_values.sh#L36-L42) to replace the version, looks like it doesn't work for release 1.1.x

/cc @linsun

**Comment by ibm-jason** [comment]
@howardjohn is this something that we can manually update?

**Comment by howardjohn** [comment]
@ibm-jason I don't think it is feasible to update for every release. We have a script that does it https://github.com/istio/istio/pull/13993 that was just merged

**Comment by ibm-jason** [comment]
@howardjohn Right, I'm aware of the script that was just merged. I guess my question is more about the anomaly- @morvencao is saying that helm charts `1.1.1` don't have the correct chart and appVersion values. Do we manually fix this as a 1-off, or will the script eventually fix it?

**Comment by howardjohn** [comment]
Ah got it. In theory we could manually change all of 1.1.0 -> 1.1.7. We already did this for *some* version spots (there are ~20 places that have a version apparently). Maybe we just do it for 1.1.7 though. I am not sure how easy it is to modify the release though, maybe we can just make sure 1.1.8 and 1.2 are right?

**Comment by morvencao** [comment]
`master` and `release1.2` should have this fix, see: https://github.com/istio/istio/blob/master/release/gcb/helm_values.sh#L36-L42 
https://github.com/istio/istio/blob/release-1.2/release/gcb/helm_values.sh#L36-L42

**Comment by sdake** [comment]
imo we should just cut a new z stream of the 1.1 series where this problem is fixed.  Although T&R is not my responsibility, I am very wary of re-releasing 7 artifacts of Istio.  Then we would have the "good" artifacts, and the "bad" artifacts.  How would operators/sre's know the difference?

Note, when we had a monthly release cadence of the z streams, I manually (via sed) pushed PRs after every new release to rev the tip of 1.0.z to the next new version.  This is the pattern we should be following.  Helm is annoying in the regard that this cannot be templated, but this is the best community practice workaround in place.

Cheers
-steve

**Comment by linsun** [comment]
@morvencao @ibm-jason is this an issue fixed in newer 1.1.x like 1.1.7?  If not, I agree, we should fix it in the next 1.1.x release.

should we backport  https://github.com/istio/istio/blob/master/release/gcb/helm_values.sh#L36-L42
https://github.com/istio/istio/blob/release-1.2/release/gcb/helm_values.sh#L36-L42 to 1.1 to fix this?

cc @utka

**Comment by ibm-jason** [comment]
@linsun I've downloaded 1.1.7 and the issue still exists:

```
$ grep -i version istio-1.1.7/install/kubernetes/helm/istio-init/Chart.yaml
apiVersion: v1
version: 1.1.0
appVersion: 1.1.0
tillerVersion: ">=2.7.2-0"
```
/cc @utka

**Comment by morvencao** [comment]
@ibm-jason The fix: https://github.com/istio/istio/pull/14291 was merged three days ago, it should be in next 1.1.x release.

**Comment by ibm-jason** [comment]
Thanks @morvencao! I think this closes out the issue. 🎉
