### ISSUE TITLE
Stale endpoints on scale to zero

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14336]
Scale deployment to 5 replicas, see all 5 in `/clusters`

```
outbound|80||identity.envoylite.svc.cluster.local::10.60.22.51:8080::region::us-central1
outbound|80||identity.envoylite.svc.cluster.local::10.60.22.52:8080::region::us-central1
outbound|80||identity.envoylite.svc.cluster.local::10.60.25.75:8080::region::us-central1
outbound|80||identity.envoylite.svc.cluster.local::10.60.25.76:8080::region::us-central1
outbound|80||identity.envoylite.svc.cluster.local::10.60.25.77:8080::region::us-central1
```

Scale deployment to 0 replicas, endpoints still remain in `/clusters`

```
outbound|80||identity.envoylite.svc.cluster.local::10.60.22.51:8080::region::us-central1
outbound|80||identity.envoylite.svc.cluster.local::10.60.22.52:8080::region::us-central1
outbound|80||identity.envoylite.svc.cluster.local::10.60.25.75:8080::region::us-central1
outbound|80||identity.envoylite.svc.cluster.local::10.60.25.76:8080::region::us-central1
outbound|80||identity.envoylite.svc.cluster.local::10.60.25.77:8080::region::us-central1
```

Running 1.2 dailies from 5/22

Adding `s.ConfigUpdate(true)` to https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/eds.go#L503 fixes this, but I am not sure it is the best option

Scaling back up triggers a push which resolves this

This is not very critical, because if you have 0 endpoints you aren't going to have any successful requests anyways

**Comment by mbanikazemi** [comment]
Hmmm, I see them removed in my cluster.

**Comment by howardjohn** [comment]
@mbanikazemi if there are any other config changes, etc pilot will trigger a push which will remove them I think, could be what happened?

**Comment by mbanikazemi** [comment]
@howardjohn Testsed it on a small cluster with no load but one cannot be sure there were no other triggers. Will check again tomorrow.

**Comment by XanderStrike** [comment]
Repro'd on GKE with 1.2.5, I'll see if I can get a fix going.

**Comment by howardjohn** [comment]
@p4ali that is the same case as above, which is fixed since 1.2.5

**Comment by robertpanzer** [comment]
I just tested that with 1.2.7 I still see the last endpoint in /clusters and requests are still routed.
Only current master that has #16967 seems to show the updated behavior.

**Comment by howardjohn** [comment]
>@p4ali that is the same case as above, which is fixed since 1.2.5

To clarify, by "since 1.2.5" I mean in 1.4, not in 1.2.6
