### ISSUE TITLE
Increase in 504 timeouts from source envoy since 1.3.x upgrade

### ISSUE THREAD

**Issue by Stono** [istio/istio#17533]
**Bug description**
Following on from what I raised on the test and release call today, we're approximately 3 days into 1.3.x. and we've noticed an increased in upstream timeouts from the perspective of the source envoy, with a `504` response_code and a `UT` response_flag. 

This graph shows from the source:

<img width="1673" alt="Screenshot 2019-10-01 at 18 31 10" src="https://user-images.githubusercontent.com/1486729/65985485-d22f4600-e479-11e9-9fdd-71382c76aac8.png">

However there are no timeouts reported at the destination:

<img width="1680" alt="Screenshot 2019-10-01 at 18 31 18" src="https://user-images.githubusercontent.com/1486729/65985506-dc514480-e479-11e9-9e01-06a43ba5113a.png">

We aren't seeing any issues in the destination application logs, only the source application logs which show connection timeouts.

I'm still investigating and trying to gather more information, but felt this is now more than a coincidence so I'm raising the issue here to track.  We alert on such failures so it isn't that I'm now just seeing them as I'm looking more closely, they are firing alerts that weren't firing before so the issue wasn't there.  

I've decided to roll back to a `1.2.6` proxy on some of the higher throughput (and higher 504 rate) applications, and will monitor them over the next 12-24 hours and report back here.  
 
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
No 504s when the upstream isn't timing out

**Steps to reproduce the bug**
Unsure as of yet, only seeing so far on 1.3.1

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.1

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by duderino** [comment]
@yxue can you take a look?

**Comment by Stono** [comment]
Just to confirm we're seeing similar issues across multiple isolated clusters within the same GCP region, and in some occasions spikes are at identical times. 

This is now leading me more towards there being some underlying network issue that's happened to start at the same time as our istio upgrade, and I'm trying to get Google to investigate further (albeit not having much joy).

It's proving extremely difficult to pin point at the point in time but will update as and when I have more information.

**Comment by Stono** [comment]
Google have finally accepted they've got small amounts of packet loss between VM's in europe-west4, this started at the same time we pushed istio 1.3.0 through those environments.  At this point in time I'm relatively confident this is NOT actually an istio problem, but will confirm (and close) as I find out more in the coming days.

**Comment by duderino** [comment]
Ummm, yay?

Thanks @Stono for finding the needle in the haystack.

**Comment by nrjpoddar** [comment]
> Ummm, yay?
> 

@duderino conflicted feelings? ;)

**Comment by duderino** [comment]
Exactly ;)

**Comment by Stocco** [comment]
Hey @Stono  we've just deployed  1.3.1 from 1.1.7 two days ago and we saw an increase in our 5xx errors - especially the  random 'DC' ones.. The percentage is still low, but is happening too much frequently and its making us want  to go back to  1.2.x versions.
Are you back on 1.3.x versions again?

**Comment by Stono** [comment]
Stocco I rolled one cluster back to `1.2.6` and saw the same issues, hence why I believe it to be the GCP packet loss.

**Comment by Stono** [comment]
OK so Google are still having this issue and I'm confident that it's the source of my issues however, I've noticed that despite retry policies being in place, istio is not retrying the timeouts despite being configured to do so, as a result our apps aren't as tolerant as they should be.

https://github.com/istio/istio/issues/17613#issuecomment-538457757

**Comment by howardjohn** [comment]
Thanks for verifying this isn't an Istio issue. Looks like we are tracking the timeout issue in https://github.com/istio/istio/issues/17613 so I'll close this
