### ISSUE TITLE
SSL handshake in initial egress request fails consistently but subsequent requests work

### ISSUE THREAD

**Issue by nixgadget** [istio/istio#17549]
Istio: `1.3.1`
Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T14:00:14Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
mTLS: *Enabled*

After deploying *1.3.1*, I am seeing a strange behaviour with each of my Java applications (microservices) which tries to establish a connection with an external API (Egress). After deployment of the services, SSL handshake in the initial Egress request always fails but every other request following that works.

For demo purposes I created a simple Java service that tries to consume an external weather API (api.openweathermap.org). In terms of the initial SSL handshake I see,

```
init keymanager of type SunX509
trigger seeding of SecureRandom
done seeding SecureRandom
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
main, setSoTimeout(0) called
main, the previous server name in SNI (type=host_name (0), value=api.openweathermap.org) was replaced with (type=host_name (0), value=api.openweathermap.org)
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1.1
%% No cached client session
update handshake state: client_hello[1]
upcoming handshake states: server_hello[2]
*** ClientHello, TLSv1.2
RandomCookie:  GMT: 1553132478 bytes = { 211, 149, 7, 123, 5, 214, 187, 177, 43, 241, 45, 110, 173, 37, 227, 179, 33, 148, 90, 163, 142, 3, 18, 136, 179, 98, 164, 46 }
Session ID:  {}
Cipher Suites: [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC
_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WIT
H_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_1
28_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECD
SA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_A
ES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
Compression Methods:  { 0 }
Extension elliptic_curves, curve names: {secp256r1, secp384r1, secp521r1, sect283k1, sect283r1, sect409k1, sect409r1, sect571k1, sect571r1, secp256k1}
Extension ec_point_formats, formats: [uncompressed]
Extension signature_algorithms, signature_algorithms: SHA512withECDSA, SHA512withRSA, SHA384withECDSA, SHA384withRSA, SHA256withECDSA, SHA256withRSA, SHA256withDSA, SHA224withECDSA, SHA224withRSA, SHA224withDSA, SHA1withECDSA, SHA1withRSA, SHA1withDSA
Extension extended_master_secret
Extension server_name, server_name: [type=host_name (0), value=api.openweathermap.org]
***
[write] MD5 and SHA1 hashes:  len = 230
0000: 01 00 00 E2 03 03 5D 93   EC BE D3 95 07 7B 05 D6  ......].........
0010: BB B1 2B F1 2D 6E AD 25   E3 B3 21 94 5A A3 8E 03  ..+.-n.%..!.Z...
0020: 12 88 B3 62 A4 2E 00 00   56 C0 24 C0 28 00 3D C0  ...b....V.$.(.=.
0030: 26 C0 2A 00 6B 00 6A C0   0A C0 14 00 35 C0 05 C0  &.*.k.j.....5...
0040: 0F 00 39 00 38 C0 23 C0   27 00 3C C0 25 C0 29 00  ..9.8.#.'.<.%.).
0050: 67 00 40 C0 09 C0 13 00   2F C0 04 C0 0E 00 33 00  g.@...../.....3.
0060: 32 C0 2C C0 2B C0 30 00   9D C0 2E C0 32 00 9F 00  2.,.+.0.....2...
0070: A3 C0 2F 00 9C C0 2D C0   31 00 9E 00 A2 00 FF 01  ../...-.1.......
0080: 00 00 63 00 0A 00 16 00   14 00 17 00 18 00 19 00  ..c.............
0090: 09 00 0A 00 0B 00 0C 00   0D 00 0E 00 16 00 0B 00  ................
00A0: 02 01 00 00 0D 00 1C 00   1A 06 03 06 01 05 03 05  ................
00B0: 01 04 03 04 01 04 02 03   03 03 01 03 02 02 03 02  ................
00C0: 01 02 02 00 17 00 00 00   00 00 1B 00 19 00 00 16  ................
00D0: 61 70 69 2E 6F 70 65 6E   77 65 61 74 68 65 72 6D  api.openweatherm
00E0: 61 70 2E 6F 72 67                                  ap.org
main, WRITE: TLSv1.2 Handshake, length = 230
[Raw write]: length = 235
0000: 16 03 03 00 E6 01 00 00   E2 03 03 5D 93 EC BE D3  ...........]....
0010: 95 07 7B 05 D6 BB B1 2B   F1 2D 6E AD 25 E3 B3 21  .......+.-n.%..!
0020: 94 5A A3 8E 03 12 88 B3   62 A4 2E 00 00 56 C0 24  .Z......b....V.$
0030: C0 28 00 3D C0 26 C0 2A   00 6B 00 6A C0 0A C0 14  .(.=.&.*.k.j....
0040: 00 35 C0 05 C0 0F 00 39   00 38 C0 23 C0 27 00 3C  .5.....9.8.#.'.<
0050: C0 25 C0 29 00 67 00 40   C0 09 C0 13 00 2F C0 04  .%.).g.@...../..
0060: C0 0E 00 33 00 32 C0 2C   C0 2B C0 30 00 9D C0 2E  ...3.2.,.+.0....
0070: C0 32 00 9F 00 A3 C0 2F   00 9C C0 2D C0 31 00 9E  .2...../...-.1..
0080: 00 A2 00 FF 01 00 00 63   00 0A 00 16 00 14 00 17  .......c........
0090: 00 18 00 19 00 09 00 0A   00 0B 00 0C 00 0D 00 0E  ................
00A0: 00 16 00 0B 00 02 01 00   00 0D 00 1C 00 1A 06 03  ................
00B0: 06 01 05 03 05 01 04 03   04 01 04 02 03 03 03 01  ................
00C0: 03 02 02 03 02 01 02 02   00 17 00 00 00 00 00 1B  ................
00D0: 00 19 00 00 16 61 70 69   2E 6F 70 65 6E 77 65 61  .....api.openwea
00E0: 74 68 65 72 6D 61 70 2E   6F 72 67                 thermap.org
main, received EOFException: error
main, handling exception: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
main, SEND TLSv1.2 ALERT:  fatal, description = handshake_failure
main, WRITE: TLSv1.2 Alert, length = 2
main, Exception sending alert: java.net.SocketException: Broken pipe (Write failed)
main, called closeSocket()
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.openweathermap.org/data/2.5/weather": Remote host closed connection during handshake; nested exception is javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:674)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:636)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:598)
        at co.riro.demoweatherapp.service.WeatherService.invoke(WeatherService.java:35)
        at co.riro.demoweatherapp.service.WeatherService.getWeather(WeatherService.java:28)
        at co.riro.demoweatherapp.DemoApplication.lambda$run$0(DemoApplication.java:33)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
        at co.riro.demoweatherapp.DemoApplication.main(DemoApplication.java:20)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:994)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:78)
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:660)
        ... 20 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:505)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        ... 30 more
```

Subsequent handshakes,
```
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
main, setSoTimeout(0) called
main, the previous server name in SNI (type=host_name (0), value=api.openweathermap.org) was replaced with (type=host_name (0), value=api.openweathermap.org)
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1.1
%% No cached client session
update handshake state: client_hello[1]
upcoming handshake states: server_hello[2]
*** ClientHello, TLSv1.2
RandomCookie:  GMT: 1553132478 bytes = { 154, 196, 29, 189, 239, 129, 130, 251, 174, 97, 30, 44, 103, 173, 210, 2, 214, 231, 132, 203, 28, 33, 220, 66, 165, 127, 222, 118 }
Session ID:  {}
Cipher Suites: [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
Compression Methods:  { 0 }
Extension elliptic_curves, curve names: {secp256r1, secp384r1, secp521r1, sect283k1, sect283r1, sect409k1, sect409r1, sect571k1, sect571r1, secp256k1}
Extension ec_point_formats, formats: [uncompressed]
Extension signature_algorithms, signature_algorithms: SHA512withECDSA, SHA512withRSA, SHA384withECDSA, SHA384withRSA, SHA256withECDSA, SHA256withRSA, SHA256withDSA, SHA224withECDSA, SHA224withRSA, SHA224withDSA, SHA1withECDSA, SHA1withRSA, SHA1withDSA
Extension extended_master_secret
Extension server_name, server_name: [type=host_name (0), value=api.openweathermap.org]
***
[write] MD5 and SHA1 hashes:  len = 230
0000: 01 00 00 E2 03 03 5D 93   EC BE 9A C4 1D BD EF 81  ......].........
0010: 82 FB AE 61 1E 2C 67 AD   D2 02 D6 E7 84 CB 1C 21  ...a.,g........!
0020: DC 42 A5 7F DE 76 00 00   56 C0 24 C0 28 00 3D C0  .B...v..V.$.(.=.
0030: 26 C0 2A 00 6B 00 6A C0   0A C0 14 00 35 C0 05 C0  &.*.k.j.....5...
0040: 0F 00 39 00 38 C0 23 C0   27 00 3C C0 25 C0 29 00  ..9.8.#.'.<.%.).
0050: 67 00 40 C0 09 C0 13 00   2F C0 04 C0 0E 00 33 00  g.@...../.....3.
0060: 32 C0 2C C0 2B C0 30 00   9D C0 2E C0 32 00 9F 00  2.,.+.0.....2...
0070: A3 C0 2F 00 9C C0 2D C0   31 00 9E 00 A2 00 FF 01  ../...-.1.......
0080: 00 00 63 00 0A 00 16 00   14 00 17 00 18 00 19 00  ..c.............
0090: 09 00 0A 00 0B 00 0C 00   0D 00 0E 00 16 00 0B 00  ................
00A0: 02 01 00 00 0D 00 1C 00   1A 06 03 06 01 05 03 05  ................
00B0: 01 04 03 04 01 04 02 03   03 03 01 03 02 02 03 02  ................
00C0: 01 02 02 00 17 00 00 00   00 00 1B 00 19 00 00 16  ................
00D0: 61 70 69 2E 6F 70 65 6E   77 65 61 74 68 65 72 6D  api.openweatherm
00E0: 61 70 2E 6F 72 67                                  ap.org
main, WRITE: TLSv1.2 Handshake, length = 230
[Raw write]: length = 235
0000: 16 03 03 00 E6 01 00 00   E2 03 03 5D 93 EC BE 9A  ...........]....
0010: C4 1D BD EF 81 82 FB AE   61 1E 2C 67 AD D2 02 D6  ........a.,g....
0020: E7 84 CB 1C 21 DC 42 A5   7F DE 76 00 00 56 C0 24  ....!.B...v..V.$
0030: C0 28 00 3D C0 26 C0 2A   00 6B 00 6A C0 0A C0 14  .(.=.&.*.k.j....
0040: 00 35 C0 05 C0 0F 00 39   00 38 C0 23 C0 27 00 3C  .5.....9.8.#.'.<
0050: C0 25 C0 29 00 67 00 40   C0 09 C0 13 00 2F C0 04  .%.).g.@...../..
0060: C0 0E 00 33 00 32 C0 2C   C0 2B C0 30 00 9D C0 2E  ...3.2.,.+.0....
0070: C0 32 00 9F 00 A3 C0 2F   00 9C C0 2D C0 31 00 9E  .2...../...-.1..
0080: 00 A2 00 FF 01 00 00 63   00 0A 00 16 00 14 00 17  .......c........
0090: 00 18 00 19 00 09 00 0A   00 0B 00 0C 00 0D 00 0E  ................
00A0: 00 16 00 0B 00 02 01 00   00 0D 00 1C 00 1A 06 03  ................
00B0: 06 01 05 03 05 01 04 03   04 01 04 02 03 03 03 01  ................
00C0: 03 02 02 03 02 01 02 02   00 17 00 00 00 00 00 1B  ................
00D0: 00 19 00 00 16 61 70 69   2E 6F 70 65 6E 77 65 61  .....api.openwea
00E0: 74 68 65 72 6D 61 70 2E   6F 72 67                 thermap.org
[Raw read]: length = 5
0000: 16 03 03 00 59                                     ....Y
[Raw read]: length = 89
0000: 02 00 00 55 03 03 AA 8D   CD 6C 7E 7E 08 B5 DB BC  ...U.....l......
0010: 3A 40 32 3E E9 C2 35 88   94 D1 97 85 2F 46 4D F5  :@2>..5...../FM.
0020: 00 76 11 CC 27 82 20 2D   5C B7 36 16 0C 49 C8 40  .v..'. -\.6..I.@
0030: DF 09 69 78 A1 FC 75 6E   E7 2B 35 C8 BE EE 88 26  ..ix..un.+5....&
0040: D3 7F 52 E8 99 10 86 C0   30 00 00 0D FF 01 00 01  ..R.....0.......
0050: 00 00 0B 00 04 03 00 01   02                       .........
main, READ: TLSv1.2 Handshake, length = 89
check handshake state: server_hello[2]
*** ServerHello, TLSv1.2
RandomCookie:  GMT: -1450390164 bytes = { 126, 126, 8, 181, 219, 188, 58, 64, 50, 62, 233, 194, 53, 136, 148, 209, 151, 133, 47, 70, 77, 245, 0, 118, 17, 204, 39, 130 }
Session ID:  {45, 92, 183, 54, 22, 12, 73, 200, 64, 223, 9, 105, 120, 161, 252, 117, 110, 231, 43, 53, 200, 190, 238, 136, 38, 211, 127, 82, 232, 153, 16, 134}
Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
Compression Method: 0
Extension renegotiation_info, renegotiated_connection: <empty>
Extension ec_point_formats, formats: [uncompressed, ansiX962_compressed_prime, ansiX962_compressed_char2]
***
%% Initialized:  [Session-1, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384]
** TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
update handshake state: server_hello[2]
upcoming handshake states: server certificate[11]
upcoming handshake states: server_key_exchange[12](optional)
upcoming handshake states: certificate_request[13](optional)
upcoming handshake states: server_hello_done[14]
upcoming handshake states: client certificate[11](optional)
upcoming handshake states: client_key_exchange[16]
upcoming handshake states: certificate_verify[15](optional)
upcoming handshake states: client change_cipher_spec[-1]
upcoming handshake states: client finished[20]
upcoming handshake states: server change_cipher_spec[-1]
upcoming handshake states: server finished[20]
[read] MD5 and SHA1 hashes:  len = 89
0000: 02 00 00 55 03 03 AA 8D   CD 6C 7E 7E 08 B5 DB BC  ...U.....l......
0010: 3A 40 32 3E E9 C2 35 88   94 D1 97 85 2F 46 4D F5  :@2>..5...../FM.
0020: 00 76 11 CC 27 82 20 2D   5C B7 36 16 0C 49 C8 40  .v..'. -\.6..I.@
0030: DF 09 69 78 A1 FC 75 6E   E7 2B 35 C8 BE EE 88 26  ..ix..un.+5....&
0040: D3 7F 52 E8 99 10 86 C0   30 00 00 0D FF 01 00 01  ..R.....0.......
0050: 00 00 0B 00 04 03 00 01   02                       .........
[Raw read]: length = 5
0000: 16 03 03 10 FD                                     .....
[Raw read]: length = 4349
0000: 0B 00 10 F9 00 10 F6 00   05 69 30 82 05 65 30 82  .........i0..e0.
0010: 04 4D A0 03 02 01 02 02   11 00 BC EC E6 FD EE 2E  .M..............
0020: 05 D3 46 FE 6C C6 93 30   9E EF 30 0D 06 09 2A 86  ..F.l..0..0...*.
0030: 48 86 F7 0D 01 01 0B 05   00 30 81 90 31 0B 30 09  H........0..1.0.
0040: 06 03 55 04 06 13 02 47   42 31 1B 30 19 06 03 55  ..U....GB1.0...U
0050: 04 08 13 12 47 72 65 61   74 65 72 20 4D 61 6E 63  ....Greater Manc
0060: 68 65 73 74 65 72 31 10   30 0E 06 03 55 04 07 13  hester1.0...U...
0070: 07 53 61 6C 66 6F 72 64   31 1A 30 18 06 03 55 04  .Salford1.0...U.
0080: 0A 13 11 43 4F 4D 4F 44   4F 20 43 41 20 4C 69 6D  ...COMODO CA Lim
0090: 69 74 65 64 31 36 30 34   06 03 55 04 03 13 2D 43  ited1604..U...-C
00A0: 4F 4D 4F 44 4F 20 52 53   41 20 44 6F 6D 61 69 6E  OMODO RSA Domain
00B0: 20 56 61 6C 69 64 61 74   69 6F 6E 20 53 65 63 75   Validation Secu
00C0: 72 65 20 53 65 72 76 65   72 20 43 41 30 1E 17 0D  re Server CA0...
00D0: 31 38 30 33 31 35 30 30   30 30 30 30 5A 17 0D 32  180315000000Z..2
00E0: 30 30 33 32 31 32 33 35   39 35 39 5A 30 62 31 21  00321235959Z0b1!
00F0: 30 1F 06 03 55 04 0B 13   18 44 6F 6D 61 69 6E 20  0...U....Domain
0100: 43 6F 6E 74 72 6F 6C 20   56 61 6C 69 64 61 74 65  Control Validate
0110: 64 31 1E 30 1C 06 03 55   04 0B 13 15 45 73 73 65  d1.0...U....Esse
0120: 6E 74 69 61 6C 53 53 4C   20 57 69 6C 64 63 61 72  ntialSSL Wildcar
0130: 64 31 1D 30 1B 06 03 55   04 03 0C 14 2A 2E 6F 70  d1.0...U....*.op
0140: 65 6E 77 65 61 74 68 65   72 6D 61 70 2E 6F 72 67  enweathermap.org
0150: 30 82 01 22 30 0D 06 09   2A 86 48 86 F7 0D 01 01  0.."0...*.H.....
0160: 01 05 00 03 82 01 0F 00   30 82 01 0A 02 82 01 01  ........0.......
0170: 00 ED 68 D2 F0 CE CF E4   57 F6 DF 14 53 79 01 0F  ..h.....W...Sy..
0180: A0 0B 69 C0 CB 59 92 F1   C1 B7 4C 82 24 C4 C9 FF  ..i..Y....L.$...
0190: C4 8F 71 E3 C8 32 FF F6   FB 95 5B 22 8C CB ED B9  ..q..2....["....
01A0: BB E1 36 BA A1 11 99 6E   1F 03 B4 FD D7 13 E7 CA  ..6....n........
01B0: E3 68 BE E5 A4 AC 3D 22   5B 2F 8F 1B 84 21 D8 32  .h....="[/...!.2
01C0: 91 40 3C 45 BB 2F 2A C4   F0 E8 45 0F 75 04 AA E9  .@<E./*...E.u...
01D0: 82 90 65 CA 36 AF EC 13   F3 ED 6D 9A 70 27 22 77  ..e.6.....m.p'"w
01E0: DD C8 37 C1 00 1F 91 C9   3C C6 EA D1 66 CE 10 4D  ..7.....<...f..M
01F0: E3 3E 7F 24 C3 FF C7 21   93 F4 09 D4 D7 61 5B E8  .>.$...!.....a[.
0200: 16 C4 57 45 AB A3 0B E4   53 EF 83 94 21 3A 3E 05  ..WE....S...!:>.
0210: 50 AF 8E B3 B4 27 8E 5F   EB 95 5F 63 B9 5D 89 2D  P....'._.._c.].-
00B0: 06 01 05 03 05 01 04 03   04 01 04 02 03 03 03 01  ................
00C0: 03 02 02 03 02 01 02 02   00 17 00 00 00 00 00 1B  ................
0090: 00 18 00 19 00 09 00 0A   00 0B 00 0C 00 0D 00 0E  ................
00A0: 00 16 00 0B 00 02 01 00   00 0D 00 1C 00 1A 06 03  ................
00B0: 06 01 05 03 05 01 04 03   04 01 04 02 03 03 03 01  ................
00C0: 03 02 02 03 02 01 02 02   00 17 00 00 00 00 00 1B  ................
00D0: 00 19 00 00 16 61 70 69   2E 6F 70 65 6E 77 65 61  .....api.openwea
00E0: 74 68 65 72 6D 61 70 2E   6F 72 67                 thermap.org
[Raw read]: length = 5
0000: 16 03 03 00 59                                     ....Y
[Raw read]: length = 89
0000: 02 00 00 55 03 03 AA 8D   CD 6C 7E 7E 08 B5 DB BC  ...U.....l......
0010: 3A 40 32 3E E9 C2 35 88   94 D1 97 85 2F 46 4D F5  :@2>..5...../FM.
0020: 00 76 11 CC 27 82 20 2D   5C B7 36 16 0C 49 C8 40  .v..'. -\.6..I.@
0030: DF 09 69 78 A1 FC 75 6E   E7 2B 35 C8 BE EE 88 26  ..ix..un.+5....&
0040: D3 7F 52 E8 99 10 86 C0   30 00 00 0D FF 01 00 01  ..R.....0.......
0050: 00 00 0B 00 04 03 00 01   02                       .........
main, READ: TLSv1.2 Handshake, length = 89
check handshake state: server_hello[2]
*** ServerHello, TLSv1.2
RandomCookie:  GMT: -1450390164 bytes = { 126, 126, 8, 181, 219, 188, 58, 64, 50, 62, 233, 194, 53, 136, 148, 209, 151, 133, 47, 70, 77, 245, 0, 118, 17, 204, 39, 130 }
Session ID:  {45, 92, 183, 54, 22, 12, 73, 200, 64, 223, 9, 105, 120, 161, 252, 117, 110, 231, 43, 53, 200, 190, 238, 136, 38, 211, 127, 82, 232, 153, 16, 134}
Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
Compression Method: 0
Extension renegotiation_info, renegotiated_connection: <empty>
Extension ec_point_formats, formats: [uncompressed, ansiX962_compressed_prime, ansiX962_compressed_char2]
***
%% Initialized:  [Session-1, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384]
** TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
update handshake state: server_hello[2]
upcoming handshake states: server certificate[11]
upcoming handshake states: server_key_exchange[12](optional)
upcoming handshake states: certificate_request[13](optional)
upcoming handshake states: server_hello_done[14]
upcoming handshake states: client certificate[11](optional)
upcoming handshake states: client_key_exchange[16]
upcoming handshake states: certificate_verify[15](optional)
upcoming handshake states: client change_cipher_spec[-1]
upcoming handshake states: client finished[20]
upcoming handshake states: server change_cipher_spec[-1]
upcoming handshake states: server finished[20]
[read] MD5 and SHA1 hashes:  len = 89
0000: 02 00 00 55 03 03 AA 8D   CD 6C 7E 7E 08 B5 DB BC  ...U.....l......
0010: 3A 40 32 3E E9 C2 35 88   94 D1 97 85 2F 46 4D F5  :@2>..5...../FM.
0020: 00 76 11 CC 27 82 20 2D   5C B7 36 16 0C 49 C8 40  .v..'. -\.6..I.@
0030: DF 09 69 78 A1 FC 75 6E   E7 2B 35 C8 BE EE 88 26  ..ix..un.+5....&
0040: D3 7F 52 E8 99 10 86 C0   30 00 00 0D FF 01 00 01  ..R.....0.......
0050: 00 00 0B 00 04 03 00 01   02                       .........
[Raw read]: length = 5
0000: 16 03 03 10 FD                                     .....
[Raw read]: length = 4349
```

Egress traffic resources,
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: demo-weather-app-service-entry
spec:
  hosts:
  - api.openweathermap.org
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-weather-app-gateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: TLS
    hosts:
    - api.openweathermap.org
    tls:
      mode: MUTUAL
      serverCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: demo-weather-app-dr
spec:
  host: istio-egressgateway.control.svc.cluster.local
  subsets:
  - name: demo-app
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: api.openweathermap.org
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-weather-app-vs
spec:
  hosts:
  - api.openweathermap.org
  gateways:
  - mesh
  - demo-weather-app-gateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
      - api.openweathermap.org
    route:
    - destination:
        host: istio-egressgateway.control.svc.cluster.local
        subset: demo-app
        port:
          number: 443
  tcp:
  - match:
    - gateways:
      - demo-weather-app-gateway
      port: 443
    route:
    - destination:
        host: api.openweathermap.org
        port:
          number: 443
      weight: 100
```

I cant see anything obvious in the proxy,
```
[2019-10-02 00:18:01.804][13][info][upstream] [external/envoy/source/server/lds_api.cc:60] lds: add/update listener '0.0.0.0_443'
[2019-10-02 00:18:01.807][13][info][config] [external/envoy/source/server/listener_manager_impl.cc:777] all dependencies initialized. starting workers
[2019-10-02 00:18:01.808][13][info][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:521] warming cluster outbound|15443|demo-app|istio-egressgateway.control.svc.cluster.local complete
[2019-10-02 00:18:01.808][13][info][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:521] warming cluster outbound|443|demo-app|istio-egressgateway.control.svc.cluster.local complete
[2019-10-02 00:18:01.808][13][info][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:521] warming cluster outbound|80|demo-app|istio-egressgateway.control.svc.cluster.local complete
[2019-10-02 00:18:07.385][35][warning][filter] [src/istio/mixerclient/report_batch.cc:109] Mixer Report failed with: UNAVAILABLE:Cluster not available
[2019-10-02T00:18:06.352Z] "- - -" 0 - "-" "-" 627 5737 5587 - "-" "-" "-" "-" "192.168.20.11:443" outbound|443|demo-app|istio-egressgateway.control.svc.cluster.local 192.168.90.22:49300 37.139.20.5:443 192.168.90.22:40204 api.openweathermap.org -
2019-10-02T00:18:27.027664Z	info	Envoy proxy is ready
[2019-10-02 00:18:27.176][13][info][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:509] add/update cluster outbound|8080||demo-weather-app.apps.svc.cluster.local starting warming
[2019-10-02 00:18:27.177][13][info][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:521] warming cluster outbound|8080||demo-weather-app.apps.svc.cluster.local complete
[2019-10-02T00:18:16.933Z] "- - -" 0 - "-" "-" 655 5737 5244 - "-" "-" "-" "-" "192.168.20.11:443" outbound|443|demo-app|istio-egressgateway.control.svc.cluster.local 192.168.90.22:49346 37.139.20.5:443 192.168.90.22:40250 api.openweathermap.org -
[2019-10-02T00:18:27.163Z] "- - -" 0 - "-" "-" 655 5737 5288 - "-" "-" "-" "-" "192.168.20.11:443" outbound|443|demo-app|istio-egressgateway.control.svc.cluster.local 192.168.90.22:49366 82.196.7.246:443 192.168.90.22:60632 api.openweathermap.org -
[2019-10-02T00:18:37.437Z] "- - -" 0 - "-" "-" 655 5737 5334 - "-" "-" "-" "-" "192.168.20.11:443" outbound|443|demo-app|istio-egressgateway.control.svc.cluster.local 192.168.90.22:49392 37.139.1.159:443 192.168.90.22:56324 api.openweathermap.org -
[2019-10-02 00:19:01.807][13][info][main] [external/envoy/source/server/drain_manager_impl.cc:63] shutting down parent after drain
[2019-10-02T00:18:47.747Z] "- - -" 0 - "-" "-" 655 5736 5258 - "-" "-" "-" "-" "192.168.20.11:443" outbound|443|demo-app|istio-egressgateway.control.svc.cluster.local 192.168.90.22:49418 37.139.1.159:443 192.168.90.22:56350 api.openweathermap.org -
[2019-10-02T00:18:57.981Z] "- - -" 0 - "-" "-" 580 1027 5131 - "-" "-" "-" "-" "192.168.20.11:443" outbound|443|demo-app|istio-egressgateway.control.svc.cluster.local 192.168.90.22:49444 37.139.1.159:443 192.168.90.22:56376 api.openweathermap.org -
[2019-10-02T00:19:08.097Z] "- - -" 0 - "-" "-" 655 5737 10250 - "-" "-" "-" "-" "192.168.20.11:443" outbound|443|demo-app|istio-egressgateway.control.svc.cluster.local 192.168.90.22:49470 37.139.20.5:443 192.168.90.22:40374 api.openweathermap.org -
```

**Comment by nixgadget** [comment]
This issue is not reproducible with version `1.2.7`.

**Comment by chadlwilson** [comment]
@nixgadget You could close this issue yourself if you feel it is now resolved :)

**Comment by nixgadget** [comment]
@chadlwilson As originally stated this is still an issue on `1.3.1`.

**Comment by chadlwilson** [comment]
Ahh, sorry @nixgadget - my bad - misread as `1.2.1`.

**Comment by t0il3ts0ap** [comment]
@nixgadget any luck on this ? We are facing same issue.
