### ISSUE TITLE
Cant Connect to Azure SQL using SideCar Injection

### ISSUE THREAD

**Issue by kahootali** [istio/istio#1789]
I am using Minikube 0.23, Kubernetes 1.8.0 and Istio 0.2.7 on Windows 10.
I have also used Istio 0.2.12 and it also had the same issue. 

I have deployed the bookinfo sample and its working fine but when I am deploying my own application which calls Azure SQL for data or other external services, it gives exception.

`A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)`

I then added the Egress as well 
```
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: sql
spec:
  destination:
    service: dbName.database.windows.net
  ports:
    - port: 443
      protocol: https

```
And now I am getting

 `A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - Success)`

**Comment by rshriram** [comment]
this is related to the tcp egress rule that @vadimeisenbergibm is doing.. see PR #1651 
until then use the includeIPranges or try accessing 443 over http (sidecar will do tls upgrade)

**Comment by vadimeisenbergibm** [comment]
Fixed by PR https://github.com/istio/istio/pull/1651. Please specify protocol tcp in the egress rule.

**Comment by kahootali** [comment]
I have upgrade to Istio 0.3.0 and have made the following EgressRule 

```
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: azure-sql
spec:
  destination:
    service: <server-name>.database.windows.net
  ports: 
    - port: 1433
      protocol: tcp
---
```

but it is still not working and giving the same error.

**Comment by vadimeisenbergibm** [comment]
@kahootali please note that for tcp you should specify an IP or IP range

**Comment by vadimeisenbergibm** [comment]
^ so just remove http and https, leave tcp with port 1433, and specify the service as IP or IP range, e.g. 91.198.174.128/25

**Comment by michaellandi** [comment]
For anyone else having issues:

Azure SQL v12 is using gateway redirection to non-standard ports in order to connect SQL clients to their correct database servers.  This redirection occurs by default on any modern applications connecting from within Azure.  See: [https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connectivity-architecture](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connectivity-architecture)

This does not work well with ISTIO.  

You need to follow the instructions provided to set the connection policy to proxy (through the gateway) instead of redirection.

```# Get SQL Server ID
sqlserverid=$(az sql server show -n sql-server-name -g sql-server-group --query 'id' -o tsv)

# Set URI
id="$sqlserverid/connectionPolicies/Default"

# Get current connection policy
az resource show --ids $id

# Update connection policy
az resource update --ids $id --set properties.connectionType=Proxy```
