### ISSUE TITLE
Operator beta-4 and prior install 1.4-dev control plane images instead of beta-4 control plane images

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#18554]
**Bug description**
The operator image ref here:
https://github.com/istio/operator/blob/1.4.0-beta.1/deploy/operator.yaml#L19

still has the dev tag instead of the beta tag.

**Expected behavior**
Operator image should have tag matching the release

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
Fixed in beta2

You need to install from the release archive not the github repo though

**Comment by kramvan1** [comment]
@howardjohn   I'm still seeing this the `1.4-dev` tag in the operator.yaml
https://github.com/istio/operator/blob/1.4.0-beta.2/deploy/operator.yaml#L20
same in the release archive.

**Comment by howardjohn** [comment]
```
$ cat ~/istio/istio-1.4.0-beta.2/install/kubernetes/operator/deploy/operator.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: istio-operator
  name: istio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-operator
  template:
    metadata:
      labels:
        name: istio-operator
    spec:
      serviceAccountName: istio-operator
      containers:
        - name: istio-operator
          image: docker.io/istio/operator:1.4.0-beta.2
          command:
          - istio-operator
          - server
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: LEADER_ELECTION_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "istio-operator"
...
```

**Comment by howardjohn** [comment]
That is from the release binary. We do not support install from github source

**Comment by howardjohn** [comment]
Ahh it does look like its not fixed in the `install/kubernetes/operator/profiles` though...

**Comment by kramvan1** [comment]
@howardjohn   Still seeing the control plane images with `1.4-dev` tags for operator `1.4.0-beta.3`

**Comment by linsun** [comment]
@kramvan1 it looks right for me in the binary I downloaded.  Any reason why you need it from git vs the release binary?

`apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: istio-operator
  name: istio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-operator
  template:
    metadata:
      labels:
        name: istio-operator
    spec:
      serviceAccountName: istio-operator
      containers:
        - name: istio-operator
          image: docker.io/istio/operator:1.4.0-beta.3
```

**Comment by kramvan1** [comment]
We are using the release binary istio/operator:1.4.0-beta.3

**Comment by howardjohn** [comment]
@kramvan1 as mentioned previous, we do NOT support installing from github sources

**Comment by howardjohn** [comment]
Please install from https://github.com/istio/istio/releases/tag/1.4.0-beta.3 as mentioned in the docs

**Comment by kramvan1** [comment]
@howardjohn Not sure what you mean.  For an operator install, all we need is the operator binary image (tag 1.4.0-beta.3) and the deployment yamls for it.   Once the operator is running, we just create a ICP resource and watch the control plane get created.     The default profile information is contained within the operator image itself and appears to still be setting the default to `1.4-dev`.   

Not sure how you mean to use the other files in that release operator directory.    The operator controller pod does not have access to any of that.

**Comment by howardjohn** [comment]
You should download the release which has the deployment yamls. For example:
```
$ cat ~/istio/istio-1.4.0-beta.3/install/kubernetes/operator/deploy/operator.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: istio-operator
  name: istio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-operator
  template:
    metadata:
      labels:
        name: istio-operator
    spec:
      serviceAccountName: istio-operator
      containers:
        - name: istio-operator
          image: docker.io/istio/operator:1.4.0-beta.2
          command:
          - istio-operator
          - server
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: LEADER_ELECTION_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "istio-operator"
...
```

**Comment by kramvan1** [comment]
@howardjohn Yes, we are using those to deploy the operator pod.    The 1.4.0-beta.3 operator image is coming fine for us.    It's the control plane images using the default profile that have the `1.4-dev` tags.

The bug must still be in the operator image itself.

**Comment by howardjohn** [comment]
It works for me, are you 100% sure you have `docker.io/istio/operator:1.4.0-beta.3` as the docker image for the operator?

**Comment by kramvan1** [comment]
Using that image:
```
image: docker.io/istio/operator:1.4.0-beta.3
      imageID: docker.io/istio/operator@sha256:0200e61d1bd93564eaf1c4848096f9aad2688623f4ed805d68c2053012de62c5
```

Our ICP currently does not specify a profile, just some component overrides.     We are trying it now with specifying the `profile: default`, but that should not make a difference imo.

**Comment by linsun** [comment]
works for me too.  @kramvan1 if you need to reopen this please specify the exact steps to recreate it.

**Comment by kramvan1** [comment]
@linsun @howardjohn steps to reproduce

- 1.16 cluster 
- clean cluster, no istio CRDs, istio-operator or istio-namespace
- download, expand the 1.4.0-beta.3 release tarball . https://github.com/istio/istio/releases/download/1.4.0-beta.3/istio-1.4.0-beta.3-osx.tar.gz
- `cd install/kubernetes/operator`
- `kubectl apply -k deploy/`
- Operator should be running with beta.3 image: `kubectl get pod -n istio-operator -o yaml` 
- Change the ICP to be  just the default profile
```
---
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: example-istiocontrolplane
spec:
  profile: default
...
```
- `kubectl apply -f deploy/crds/istio_v1alpha2_istiocontrolplane_cr.yaml `
- Watch for control plane to come up `kubectl get all -n istio-system`
- Check the control plane pods used:  `kubectl get pods -n istio-system  -o jsonpath="{..image}"`
```
gcr.io/istio-testing/citadel:1.4-dev gcr.io/istio-testing/citadel:1.4-dev gcr.io/istio-testing/galley:1.4-dev gcr.io/istio-testing/proxyv2:1.4-dev gcr.io/istio-testing/galley:1.4-dev gcr.io/istio-testing/proxyv2:1.4-dev gcr.io/istio-testing/proxyv2:1.4-dev gcr.io/istio-testing/proxyv2:1.4-dev gcr.io/istio-testing/pilot:1.4-dev gcr.io/istio-testing/proxyv2:1.4-dev gcr.io/istio-testing/pilot:1.4-dev gcr.io/istio-testing/proxyv2:1.4-dev gcr.io/istio-testing/mixer:1.4-dev gcr.io/istio-testing/proxyv2:1.4-dev gcr.io/istio-testing/proxyv2:1.4-dev gcr.io/istio-testing/mixer:1.4-dev gcr.io/istio-testing/sidecar_injector:1.4-dev gcr.io/istio-testing/sidecar_injector:1.4-dev gcr.io/istio-testing/proxyv2:1.4-dev gcr.io/istio-testing/mixer:1.4-dev gcr.io/istio-testing/mixer:1.4-dev gcr.io/istio-testing/proxyv2:1.4-dev docker.io/prom/prometheus:v2.12.0 icr.io/ext/istio/prom/prometheus:v2.12.0
```
- Images should be beta.3 tags, not the dev tag.

**Comment by kramvan1** [comment]
[opr.log](https://github.com/istio/istio/files/3825967/opr.log)
operator log

**Comment by linsun** [comment]
@kramvan1 thanks, recreating now.

**Comment by linsun** [comment]
@howardjohn I am able to reproduce this now.  I could not earlier because i was using istioctl manifest apply which works fine.  If I used the server side operator, this can be reproduced.  operator image is fine 1.4.0.beta-3, it is the istio control plane components that are using 1.4-dev.

```    image: gcr.io/istio-testing/pilot:1.4-dev```

**Comment by howardjohn** [comment]
@kramvan1 sorry for thinking this was fixed, I followed your steps and reproduced -- not sure how it was working for me

**Comment by kramvan1** [comment]
@howardjohn np, thx for the help

**Comment by sdake** [comment]
@howardjohn i am out of town and while the wireless coverage has improved at our campsite I don’t have a laptop to work on.  I recognize we shouldn’t block a release for an alpha feature but I’d be super appreciative if you could fix this problem prior to release by either personally taking this problem on or finding an owner.

Cheers
Steve

**Comment by howardjohn** [comment]
This is an operator issue not release-builder, reassigned to owners (because I don't know how to fix, not because I don't care :slightly_smiling_face: )

**Comment by linsun** [comment]
@kramvan1 - working with @ostromart - a workaround for you, this works for me with correct images:

```
---
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: example-istiocontrolplane
spec:
  profile: default
  hub: docker.io/istio
  tag: 1.4.0-beta.3 
```
please use this to test where you specify hub and tag in your icp cr while we continue to sort this out.

**Comment by linsun** [comment]
@ostromart @carolynhu we need to decide what to do with the issue.  Either we fix in the code or append hub and tag for every ICP profile for 1.4.

**Comment by howardjohn** [comment]
Fixed in beta 4 by https://github.com/istio/operator/pull/566, please try again

**Comment by howardjohn** [comment]
@ostromart confirmed this is NOT fixed on 1.4beta4

**Comment by howardjohn** [comment]
My ICP is just profile=demo, images used are 1.4-dev. Operator image is 1.4.0-beta.4

**Comment by kramvan1** [comment]
@howardjohn   Looking at that fix https://github.com/istio/operator/pull/566 .  I see that the hub and tag are tied together.  
`if hub != "unknown" && tag != "unknown" {`
This seems like another possible bug.    In our case, we want to just override the HUB, not the tag.   I would think that would be the same for most folks moving the images to internal/private registries.

With that logic, it seems like both HUB and TAG overrides would need to be unset for this to work, but I maybe wrong here.

**Comment by howardjohn** [comment]
Confirmed this is still broken with istio-1.4-alpha.116d124f267c1f722e727cadb56c555e5ebd2405 @linsun @ostromart

**Comment by howardjohn** [comment]
@sdake this is not just beta4 and prior, this is still breakon on HEAD of 1.4

**Comment by howardjohn** [comment]
I can confirm this is still broken on 1.4.1 @ostromart

**Comment by howardjohn** [comment]
Any info @ostromart?

**Comment by howardjohn** [comment]
Still broken at head of 1.4

**Comment by howardjohn** [comment]
Also at head of master

**Comment by howardjohn** [comment]
Any updates @ostromart?

**Comment by kramvan1** [comment]
This appears to be fixed in 1.5.0-beta.5
