### ISSUE TITLE
istioctl doesn't seem to respect disablePolicyChecks

### ISSUE THREAD

**Issue by tbarrella** [istio/istio#19139]
**Bug description**
When using `istioctl manifest`, `values.global.disablePolicyChecks` doesn't seem to have an effect

**Expected behavior**
Setting `disablePolicyChecks: false` configures the mesh data properly in the istio ConfigMap

**Steps to reproduce the bug**
- Create IstioControlPlane config `config.yaml` like
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    global:
      disablePolicyChecks: false
      policyCheckFailOpen: true  # this is still respected
```
- `istioctl manifest generate -f config.yaml | grep disablePolicyChecks:`
- disablePolicyChecks is `true`

Looking at https://github.com/istio/istio/blob/1.4.0/install/kubernetes/helm/istio/templates/configmap.yaml suggests that maybe `values.mixer.policy.enabled` needs to be set to `true`, but that didn't seem to help

**Version**
1.4.0

**How was Istio installed?**
istioctl

**Comment by richardwxn** [comment]
The issue is coming from installer, https://github.com/istio/installer/blob/master/istio-control/istio-discovery/templates/configmap.yaml#L90, the configmap value depends on values.pilot.policy.enabled instead of values.global.disablePolicyChecks although we have disablePolicyChecks defined in global. I may need to think what's the best way to reduce the confusion here.

For now you can use this config as a workaround:
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    pilot:
      policy:
        enabled: true
    global:
      policyCheckFailOpen: true
```

**Comment by tbarrella** [comment]
Ah ok, thank you for the workaround!

**Comment by NilsRenaud** [comment]
> The issue is coming from installer, https://github.com/istio/installer/blob/master/istio-control/istio-discovery/templates/configmap.yaml#L90, the configmap value depends on values.pilot.policy.enabled instead of values.global.disablePolicyChecks although we have disablePolicyChecks defined in global. I may need to think what's the best way to reduce the confusion here.
> 
> For now you can use this config as a workaround:
> 
> ```yaml
> apiVersion: install.istio.io/v1alpha2
> kind: IstioControlPlane
> spec:
>   values:
>     pilot:
>       policy:
>         enabled: true
>     global:
>       policyCheckFailOpen: true
> ```

I tried your workaround, but I get an error when applying it : 

```
$ k apply -n istio-system -f istio1-4_fix.yml
error: unable to recognize "istio1-4_fix.yml": no matches for kind "IstioControlPlane" in version "install.istio.io/v1alpha2"
```

Any ideas ? ( I tried on differents namespaces although)

```
$ ./istioctl version
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (2 proxies)
```

**Comment by tbarrella** [comment]
The IstioControlPlane CRD would need to be added to the cluster for that to work. Need to either use `istioctl manifest apply -f` as in https://istio.io/docs/setup/install/istioctl/ or install the in-cluster operator if you want to use kubectl https://istio.io/docs/setup/install/standalone-operator/

**Comment by pubudu538** [comment]
I think you can use the following command to disable policy check when using the istioctl.

istioctl manifest apply --set values.pilot.policy.enabled=true --set values.global.policyCheckFailOpen=true

**Comment by howardjohn** [comment]
@richardwxn any progress on https://github.com/istio/installer/pull/567?

**Comment by richardwxn** [comment]
@howardjohn the test is still failing for the demo which blocks the merge and I spent some time on it but no luck. I may come back to it next week.

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/installer/pull/622 which will be in 1.4.3. Thanks everyone!

**Comment by manikantabandaru** [comment]
Hi 
I see the issue still persists, though i override the disablePolicyChecks to false the config is not respecting provided value.

Istio version used  1.4.3 and the istio is installed on GKE cluster with version 1.13.11-gke.14

` istioctl manifest apply --set values.global.disablePolicyChecks=false `

**Output:**
`- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Galley...
- Applying manifest for component Policy...
- Applying manifest for component Pilot...
- Applying manifest for component Citadel...
- Applying manifest for component Prometheus...
- Applying manifest for component IngressGateway...
- Applying manifest for component Injector...
- Applying manifest for component Telemetry...
✔ Finished applying manifest for component Policy.
✔ Finished applying manifest for component Prometheus.
✔ Finished applying manifest for component Citadel.
✔ Finished applying manifest for component IngressGateway.
✔ Finished applying manifest for component Pilot.
✔ Finished applying manifest for component Galley.
✔ Finished applying manifest for component Injector.
✔ Finished applying manifest for component Telemetry.

✔ Installation complete
 `
Checking the  config:

`kubectl -n istio-system get cm istio -o jsonpath="{@.data.mesh}" | grep disablePolicyChecks`

**Output:**

`disablePolicyChecks: true `

**Comment by USA-RedDragon** [comment]
@manikantabandaru Use @pubudu538's command (https://github.com/istio/istio/issues/19139#issuecomment-558566612) to initialize it, and it'll work
