### ISSUE TITLE
removing operator manifest removes user namespaces

### ISSUE THREAD

**Issue by infa-nvarma** [istio/istio#20059]
**Bug description**
We are using KIali and we want it to pick data from Prometheus. But, We do not want to install prometheus via Istio. This is because we are already using Prometheus(deployed in a different namespace) and we want Kiali to use the same. To achieve this we added “prometheusNamespace” to values.global in Istiocontrolplane file. it looked something like below:
```
values: 
    prometheus:
      enabled: false
      replicaCount: 2
    kiali:
      enabled: true
    global:
      prometheusNamespace: testmonitoring
```
This worked fine. Kilali was picking up data. Later for some reason we removed the istio installation and installed it again. For removing we used the same istiocontrolplane file that we used in the first place to install. But while deletion istio deleted the “testmonitoring” namespace too. For the first time, since the namespace was already there, we did not realise, istion was trying to create it.

by using istio manifest generate we can see that istio is creating the namespace.
```
istioctl manifest generate -f istiocontrolplane.yaml
```
Relevant part of out put below:
```
apiVersion: v1
kind: Namespace
metadata:
  name: testmonitoring
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
```
We did not expect that. I further tested, by enabling prometheus in the istiocontrolplane file and replacing value of “prometheusNamespace” with a dummy values say “mynamespace”. So istio deployed prometheus in “istio-system” ns and created a blank names space “mynamespace”. This time I expected prometheus to to deployed in dummy namespace, but that did not happen.

In conclusion, if we use existing prometheus in a different namespace, while deletion Istio deletes that namespace with all its content. That is a disaster for us.

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Isttio just using the Prometheus from other namespace and not deleting it on removal
**Steps to reproduce the bug**
Most of my steps, I have describe in description. 
create an istiocontroplane file with a part like below:
```
values: 
    prometheus:
      enabled: false
      replicaCount: 2
    kiali:
      enabled: true
    global:
      prometheusNamespace: testmonitoring
```

then istall using istioctl

```
istioctl manifest apply -f istiocontrolplane.yaml
```

if the namespace testmonitoring has prometheus service, Kiali will use that and work fine.

now delete using the same file using below command:

istioctl manifest generate istiocontrolplane.yaml | kubectl delete -f -

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.4.2
control plane version: 1.4.2

**How was Istio installed?**
using istioctl
```
istioctl manifest apply -f istiocontrolplane.yaml
```
**Environment where bug was observed (cloud vendor, OS, etc)**
Amazon EKS

**Comment by howardjohn** [comment]
oof. @ostromart @sdake any ideas how we should fix this?

**Comment by ostromart** [comment]
There are two possible solutions:
1. detect when a namespace is already present and don't generate a resource for it. This still doesn't solve the case where user adds resources to ns created by operator later, but that seems reasonable since then it's clear the ns was created by operator.
2. never create a namespace and always require user to do it.

For manifest generate (this case used generate, not apply) we should probably never create namespace resources anyway, since we don't guarantee that this path is a fully automated install.

**Comment by infa-ddeore** [comment]
dont close :-)
