### ISSUE TITLE
Header Host into HTTP response is not accepted 

### ISSUE THREAD

**Issue by AlexandreDemailly** [istio/istio#20606]
**Bug description**

communication is failing when we have a header "host" into the HTTP response.

curl -X POST -vvv http://wiremock.xx.xxxx/api/oauth/token

Log from testing env 
Egress Gtw log
[2020-01-28T16:44:33.696Z] "POST /api/oauth/token HTTP/2" 200 - "-" "-" 0 653 109 106 "10.1.2.15" "curl/7.64.0" "8c9aec49-31c7-98e2-88fe-cb62262520a2" "wiremock.xx.xxxx" "52.51.160.56:443" outbound|443||wiremock.xx.xxxx - 10.1.2.16:80 10.1.2.15:41432 -

Sidecar log:
[2020-01-28T16:44:33.692Z] "POST /api/oauth/token HTTP/1.1" 503 UC "-" "-" 0 95 114 - "-" "curl/7.64.0" "8c9aec49-31c7-98e2-88fe-cb62262520a2" "wiremock.xx.xxxx" "10.1.2.16:80" outbound|80||istio-egressgateway.istio-system.svc.cluster.local - 52.51.160.56:80 10.1.2.15:46740 - -

invalid frame: Invalid HTTP header field was received on stream 41

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

No crash when header host is present 

**Steps to reproduce the bug**

A simple curl POST to a service that return header host into the HTTP response

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

We tried v 1.3 and v1.4 same result.

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS

We also tried to apply a rule that removes the header host  from the HTTP response but the rule cannot be apply : 
We get the following :
gRPC config for type.googleapis.com/envoy.api.v2.RouteConfiguration rejected: :-prefixed or host headers may not be removed

**Comment by howardjohn** [comment]
I can reproduce, but not the "crash". Are you seeing the proxy actually crash or just return a 503?

I am pretty sure this is in line with HTTP spec: https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name

**Comment by AlexandreDemailly** [comment]
Actually you're right, we don't get a crash but just return a 503. 
And the RFC 2616 is not so clear with the reponse header list. 
AFAIR it's not clearly written that host header is not allowed in response.

**Comment by Francois-Royer** [comment]
Hello I'm working with Alexandre Demailly. I would like to had that Host in response is not specified and so a Host header in response should be handle like a custom header. It has no link to Host in request.

For response forbidden header: https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_response_header_name, there is only Set-Cookie(2)

**Comment by howardjohn** [comment]
@PiotrSikora any ideas what is going on here/what is the expected behavior? I am not sure why going through egress gets a 503 but going just through a sidecar is fine either

**Comment by PiotrSikora** [comment]
It's a bug in Envoy, see: https://github.com/envoyproxy/envoy/issues/9873

**Comment by AlexandreDemailly** [comment]
Do we plan to onboard this fix in the next release ?

**Comment by PiotrSikora** [comment]
It's going to be included in the 1.6 release (scheduled for May).

The fix required a huge refactor in Envoy (envoyproxy/envoy#9918, envoyproxy/envoy#10001, envoyproxy/envoy#10039), and the issue is relatively minor, we we're not going to backport those changes to 1.5 release that's already in testing.

**Comment by AlexandreDemailly** [comment]
Sounds good !
Thks Piotr

**Comment by makwiatkowski** [comment]
When tried to respond to incoming message (HTTP/2) we mistakely used Host instead of Location. Host is illegal in response and our engine created garbled response header (which was impossible to decode). Envoy in reaction to getting garbage responded to invoker with 503, but in my opinion 502 shall be raised, which is clearly defined for such situation

**Comment by howardjohn** [comment]
I have verified this is fixed in 1.6. Thanks everyone!

**Comment by AlexandreDemailly** [comment]
thks a lot guys

**Comment by widdix123** [comment]
@howardjohn  - Is this fixed ? I am using 1.6.5 and i still get 503 error . Without the host header i get response 200 

**With host header in curl request**

```
curl http://argocd-server.argocd.svc.cluster.local -H 'x-real-ip:127.0.0.1' -H 'cache-control:max-age=0' -H 'user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36' -H 'accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"' -H 'sec-fetch-site:none' -H 'sec-fetch-mode:navigate' -H 'sec-fetch-user:?1' -H 'sec-fetch-dest:document' -H 'accept-language:en-US,en;q=0.9' -H 'cookie:k3dash-session-uuid=9a7ee5b0-8ffc-4a24-8ee4-2ea1663fa1d5' -H 'x-forwarded-for:10.0.11.110' -H 'x-forwarded-proto:https' -H 'x-request-id:8c4c1b74-a26f-438a-97f2-420190f9e9b1' -H 'x-envoy-expected-rq-timeout-ms:5000' -H 'x-envoy-internal:true' -H 'x-forwarded-client-cert:By=spiffe://cluster.local/ns/dex/sa/default;Hash=784b3aad1f210591a1feddbb8691a01e07a70ef9a98a3de11c804e3f96695d7f;Subject=\"\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account' -H 'x-b3-traceid:4c83156f2f36ab060c74a9b9d6a05aa6' -H 'x-b3-spanid:dc50bdbd9ea5e2c3' -H 'x-b3-parentspanid:0c74a9b9d6a05aa6' -H 'x-b3-sampled:0' -H 'host:demo.xxxxx.com'

* Rebuilt URL to: http://argocd-server.argocd.svc.cluster.local/
*   Trying 172.20.54.177...
* TCP_NODELAY set
* Connected to argocd-server.argocd.svc.cluster.local (172.20.54.177) port 80 (#0)
> GET / HTTP/1.1
> host:demo.xxxxxx.com
> x-real-ip:127.0.0.1
> cache-control:max-age=0
> user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
> accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
> sec-fetch-site:none
> sec-fetch-mode:navigate
> sec-fetch-user:?1
> sec-fetch-dest:document
> accept-language:en-US,en;q=0.9
> cookie:k3dash-session-uuid=9a7ee5b0-8ffc-4a24-8ee4-2ea1663fa1d5
> x-forwarded-for:10.0.11.110
> x-forwarded-proto:https
> x-request-id:8c4c1b74-a26f-438a-97f2-420190f9e9b1
> x-envoy-expected-rq-timeout-ms:5000
> x-envoy-internal:true
> x-forwarded-client-cert:By=spiffe://cluster.local/ns/dex/sa/default;Hash=784b3aad1f210591a1feddbb8691a01e07a70ef9a98a3de11c804e3f96695d7f;Subject=\"\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
> x-b3-traceid:4c83156f2f36ab060c74a9b9d6a05aa6
> x-b3-spanid:dc50bdbd9ea5e2c3
> x-b3-parentspanid:0c74a9b9d6a05aa6
> x-b3-sampled:0
>
< HTTP/1.1 503 Service Unavailable
< content-length: 95
< content-type: text/plain
< date: Mon, 03 Aug 2020 10:41:36 GMT
< server: envoy
<
* Connection #0 to host argocd-server.argocd.svc.cluster.local left intact
upstream connect error or disconnect/reset before headers. reset reason: connection  #termination
```

**Comment by howardjohn** [comment]
@widdix123 this issue is about servers that return a Host header in the *response*, not requests with host header.
