### ISSUE TITLE
Envoy shipped with Istio 1.4.6 appears to choke if a JWKS file returned includes an unexpected RSA key algo

### ISSUE THREAD

**Issue by mhite** [istio/istio#22597]
**Bug description**

When using a JWT Policy, the Envoy shipped with Istio 1.4.6 appears to choke if a JWKS file returned includes an unexpected RSA key algo. Specifically, I observed it failing with the PS* algos:  PS256, PS384 and PS512.

We see the following types of errors in the Istio logs:

```
 2020-03-17T21:58:28.857801Z	warn	ads	ADS:LDS: ACK ERROR 10.28.0.60:52994 router~10.28.0.60~mhite-elbgateway-68d78b69cc-zjdrg.istio-system~istio-system.svc.cluster.local-1308 (mhite-elbgateway-68d78b69cc-zjdrg.istio-system) Internal:Error adding/updating listener(s) 0.0.0.0_443: Issuer 'https://<redacted>' in jwt_authn config has invalid local jwks: [alg] is not started with [RS] for a RSA key
```

We can also see the gateway components go into STALE (Never Acknowledged) state when probing with istioctl:

```
mhite-elbgateway-68d78b69cc-g68gq.istio-system                       SYNCED     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-7c567b5cd8-c5ns9     1.4.6
mhite-elbgateway-68d78b69cc-llq8q.istio-system                       SYNCED     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-7c567b5cd8-nxfc7     1.4.6
mhite-elbgateway-68d78b69cc-zjdrg.istio-system                       SYNCED     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-7c567b5cd8-2qnkg     1.4.6
```

The outcome is that Envoy never loads an appropriate filter and JWT validation does not work properly.

**Expected behavior**

JWKS validation should issue a warning that JWKS is advertising an unsupported algorithm. It should be a warning, however, and not a total failure.

**Steps to reproduce the bug**

Add the following keys to a working JWKS:

```
    "kty" : "RSA",
    "e" : "AQAB",
    "use" : "sig",
    "crv" : "",
    "kid" : "3d038aa2-4893-4ca7-ad76-12f548f570c2_sig_ps256",
    "x5c" : [ "MIIDbDCCAiCgAwIBAgIhAJHzacg9FYsoEIkziWI203OcmvJH0NpwDOVArZXtkWR1MEEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIBBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIBBQCiAwIBIDAhMR8wHQYDVQQDDBZveEF1dGggQ0EgQ2VydGlmaWNhdGVzMB4XDTIwMDMxMTE4MTA1MFoXDTIwMDMxMzE4MTA1OFowITEfMB0GA1UEAwwWb3hBdXRoIENBIENlcnRpZmljYXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKnsafV+RDC4jdvIEo4heObd1KO7lN7BIcSOyAaRdtiMOwm+poNLNDxobId/b7jMpiIFYNm/kWxTORiFSk30Q1bbqBbxM5EtPfHCZ3c8v9zX15muzD056oEdI9XDtTXfYXGCQBbAnMwCdv9JUaaAnk2Jni+O8+YhGW1oQb0VKK9nGOHWbezLRHEoRFLL9g1x/Bor+sP/pX/9kzMrNq8QHGngQvPyk26EdCf8kV+A+SCCfFr2OGlYsRXQkv4VEmulC93Pnc9THsMTKqvKQ5caG9mr6BlrySewPBz66il3fTjvMwCs+cp2wLeKqTJt8ym34NNhILcnPTKnWNGTOSv/TnsCAwEAAaMnMCUwIwYDVR0lBBwwGgYIKwYBBQUHAwEGCCsGAQUFBwMCBgRVHSUAMEEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIBBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIBBQCiAwIBIAOCAQEAS6b9zEpSLzdyQ/ngz67MIrYRS+YUXT41JFj5ZNopBVDSzanSpZeCc381fkfaMSviKalBoSaJZzwOD/r+arTLYRGi0uSyTU5lFMVh/pYUDgfdlB2QWC/sXV/ftaKAAU59e/7WCzTbXLWJTrYXyYxzziV2jb/AGuM9COtTO/r98u9IaCR9UbNnCNPjpt9Db3Sk3upV1hcmheZP9Ayj1NGUah+5PVnYg8sU/laYf1MPNU42tKolN2gwWtkdRuCBqM3Zfs9u68MbwKo8uyuL3BFOVuWMV1jE4LsyfR+5QWACuwX8RXr+U8DfX4+bh1mg1OWa6BY8YSVE+0edIF59DgK/LA==" ],
    "exp" : 1584123058707,
    "alg" : "PS256",
    "n" : "qexp9X5EMLiN28gSjiF45t3Uo7uU3sEhxI7IBpF22Iw7Cb6mg0s0PGhsh39vuMymIgVg2b-RbFM5GIVKTfRDVtuoFvEzkS098cJndzy_3NfXma7MPTnqgR0j1cO1Nd9hcYJAFsCczAJ2_0lRpoCeTYmeL47z5iEZbWhBvRUor2cY4dZt7MtEcShEUsv2DXH8Giv6w_-lf_2TMys2rxAcaeBC8_KTboR0J_yRX4D5IIJ8WvY4aVixFdCS_hUSa6UL3c-dz1MewxMqq8pDlxob2avoGWvJJ7A8HPrqKXd9OO8zAKz5ynbAt4qpMm3zKbfg02Egtyc9MqdY0ZM5K_9Oew"
  }, {
    "kty" : "RSA",
    "e" : "AQAB",
    "use" : "sig",
    "crv" : "",
    "kid" : "f188f605-4ce9-4028-83de-cfc986f3f926_sig_ps384",
    "x5c" : [ "MIIDazCCAh+gAwIBAgIgRdE8wIVA4Ehcg/wKboudibqBiPi0vlO6eN4F+DdYzJgwQQYJKoZIhvcNAQEKMDSgDzANBglghkgBZQMEAgIFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgIFAKIDAgEwMCExHzAdBgNVBAMMFm94QXV0aCBDQSBDZXJ0aWZpY2F0ZXMwHhcNMjAwMzExMTgxMDUxWhcNMjAwMzEzMTgxMDU4WjAhMR8wHQYDVQQDDBZveEF1dGggQ0EgQ2VydGlmaWNhdGVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnW3FIfzmiWbaXYTaTA+XbX9Rq6o74WfbS8TghQGNMS8AYBlBCEPPtYzd/vIA2B7DTq+BZqwqwN45ycXP/Xl7i2QpWj9BVL3yllD/QVau/bFMUXGdLi9s8wsvRJm15AFQ0PChgllkFRHAd9TuIwa/eMoQ+JFjMeFhwxE9W3PthtMVPZplrxUYC9Ns0v3EXf9gYCX2fR2BUGWuAuc18QB2pPsdQwtH2EH6mfmxz55t7bnQyay8bWTugk2hMrW3+I4HdlRoB7iYRUmw9Yq/zs+rrGYadf6MG23gIDMk00z88xqZegYtxVzydWwV/lUTlnx8N3Us+NyfAYtVMtkPOv/CvwIDAQABoycwJTAjBgNVHSUEHDAaBggrBgEFBQcDAQYIKwYBBQUHAwIGBFUdJQAwQQYJKoZIhvcNAQEKMDSgDzANBglghkgBZQMEAgIFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgIFAKIDAgEwA4IBAQBWPrPgvmzDVMNHlWdXHQBBSeXtaF2m9UsptzqCpJmx+xLX5hzSxLqDcTDlpWHr4Vqi7sv0SOtggC5vV49AWc41ddp4co0btpPzr0UDQBpuN9GQt1gDyUCk0EElIqragSsACSdkP7U6pZiLBO5zxmSPWwvhfmQm1VVIC2NIhKv1iqCr4fqQUXEqQNYIqAVb8UIccaz6DykCbgOMDNMXtsTaKCQrJjWMz90ulZJrcdTyhesnnq5bngXws7w7amXtzWIBYS+vh9tuRCSXNGVvSbXS178KwiFKXst9lQB81qcwt3bKUtTj8hX1w6qwT6/ifwhtrv4OO+ml0jgbqLqkT5TI" ],
    "exp" : 1584123058707,
    "alg" : "PS384",
    "n" : "nW3FIfzmiWbaXYTaTA-XbX9Rq6o74WfbS8TghQGNMS8AYBlBCEPPtYzd_vIA2B7DTq-BZqwqwN45ycXP_Xl7i2QpWj9BVL3yllD_QVau_bFMUXGdLi9s8wsvRJm15AFQ0PChgllkFRHAd9TuIwa_eMoQ-JFjMeFhwxE9W3PthtMVPZplrxUYC9Ns0v3EXf9gYCX2fR2BUGWuAuc18QB2pPsdQwtH2EH6mfmxz55t7bnQyay8bWTugk2hMrW3-I4HdlRoB7iYRUmw9Yq_zs-rrGYadf6MG23gIDMk00z88xqZegYtxVzydWwV_lUTlnx8N3Us-NyfAYtVMtkPOv_Cvw"
  }, {
    "kty" : "RSA",
    "e" : "AQAB",
    "use" : "sig",
    "crv" : "",
    "kid" : "ecdf887a-f27d-4659-adc2-906fa92c67e9_sig_ps512",
    "x5c" : [ "MIIDbDCCAiCgAwIBAgIhAIiaYBZk8O0PUrwyXl/Rm/2Usw8uf1YnhrPkGJPAOzx+MEEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIDBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIDBQCiAwIBQDAhMR8wHQYDVQQDDBZveEF1dGggQ0EgQ2VydGlmaWNhdGVzMB4XDTIwMDMxMTE4MTA1MVoXDTIwMDMxMzE4MTA1OFowITEfMB0GA1UEAwwWb3hBdXRoIENBIENlcnRpZmljYXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK9rB3iPUEp89TEJ0wTqnWV+EA03YjNNLjcKFxEIux3nxyNOFU3BkVoYO64gFSvAE+ORp0o5lgYN0hpJJT3M+0xJ2onKRmc/rAKD2KhGcTpjBLZ3g+Hq/yXNMVujFgBWoAcGvoGt/G/TpuIt5xtRFFCqoyzbV/aSLRSZx02637yhdQN7K1A696NestVgIKRSAjYBekHYzA9HResQWlk9yO/ZFz/evS2lxUiCUyR1REspDaQ2PMDYeiofvLwqSU2Zma32JL3UpotgdSm3hGHRHXr+8RMJgIA4kmBR5/xuDEfXELQv0X0FFGQ4TdQ+t488TtE0H93WZCtyqFr8v7m5eqkCAwEAAaMnMCUwIwYDVR0lBBwwGgYIKwYBBQUHAwEGCCsGAQUFBwMCBgRVHSUAMEEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIDBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIDBQCiAwIBQAOCAQEAcxG0JJwN+InTq+Cb+Ijl1kJ5OGx8hYZmAstwTVRkW9gdjaR0Hqp97Rj0kv9vlkfihwHlSCDWQUh7l2oruP88QvnvypcVARwSw5gAswiC8Q5F8b+W2WvOzk+KvYY3Q6oehY+VwsEpx5gJisP7t3BW4LlJTNbRhA4ZKifnFm0ah6HsILRIpy7tqSSFyjSmGo73eLfmKyNPEH8tn0pXO7GOMUgDvovMe9iycNmpo27qbpRMlcSUbElo5PZtDknXeritt53iJnD3ucaX3Qahb0jSfN/8X25DRs6s8F2O+CzRd7hyhjCTsgPgNiNJeIS9bP9vVpUj9VWK2y0lXCsn2PnqAQ==" ],
    "exp" : 1584123058707,
    "alg" : "PS512",
    "n" : "r2sHeI9QSnz1MQnTBOqdZX4QDTdiM00uNwoXEQi7HefHI04VTcGRWhg7riAVK8AT45GnSjmWBg3SGkklPcz7TEnaicpGZz-sAoPYqEZxOmMEtneD4er_Jc0xW6MWAFagBwa-ga38b9Om4i3nG1EUUKqjLNtX9pItFJnHTbrfvKF1A3srUDr3o16y1WAgpFICNgF6QdjMD0dF6xBaWT3I79kXP969LaXFSIJTJHVESykNpDY8wNh6Kh-8vCpJTZmZrfYkvdSmi2B1KbeEYdEdev7xEwmAgDiSYFHn_G4MR9cQtC_RfQUUZDhN1D63jzxO0TQf3dZkK3KoWvy_ubl6qQ"
  },

```

Then, create a JWT policy that references the JWKS. Here is mine:

```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: mhite-elbgateway-jwt
  namespace: istio-system
spec:
  origins:
  - jwt:
      issuer: https://<redacted>
      jwksUri: https://<redacted>/oxauth/restv1/jwks
      triggerRules:
      - excludedPaths:
        - exact: /
  principalBinding: USE_ORIGIN
  targets:
  - name: mhite-elbgateway
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: unknown
accounts-mp-ilbgateway version:
accounts-mp-ilbgateway version:
commerce-elbgateway version:
commerce-elbgateway version:
etnc-prototype-ilbgateway version:
etnc-prototype-ilbgateway version:
citadel version: 1.4.6
galley version: 1.4.6
galley version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
sidecar-injector version: 1.4.6
sidecar-injector version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
mhite-elbgateway version:
mhite-elbgateway version:
mhite-elbgateway version:
mhite-ilbgateway version:
mhite-ilbgateway version:
monolith-ilbgateway version:
monolith-ilbgateway version:
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

We install Istio using helm charts.

**Environment where bug was observed (cloud vendor, OS, etc)**

We are running open source Istio 1.4.6 on Google Kubernetes Engine (GKE).

**Comment by mhite** [comment]
To "work around" this issue, we have written a proxy service that filters the JWKS and strips it of RSA algos that make Envoy unhappy.

**Comment by yangminzhu** [comment]
Thanks for the report, this should be fixed in Envoy and probably the upstream JWT library, @qiwzhang could you take a look?

**Comment by yangminzhu** [comment]
cc  @samprit another starter issue you can try.

**Comment by volkdir** [comment]
I can confirm that issue. Same with 1.4.8. We currently hardcoded a editied version of the keys via the jwks parmeter. But this is not very nice in terms of deployment to different stages.

I created a issue in the jwt_verify_lib
https://github.com/google/jwt_verify_lib/issues/49

**Comment by volkdir** [comment]
jwt_verify team implemented at least a way to ignore unkown keys:
https://github.com/google/jwt_verify_lib/issues/50
Can this be integrated in 1.4 ?

**Comment by volkdir** [comment]
Any news about this? Can we get this somehow included?

**Comment by yangminzhu** [comment]
> Can this be integrated in 1.4 ?

Support for Istio 1.4 has ended on 06/05: https://istio.io/latest/news/support/announcing-1.4-eol-final/ and the fix is merged the same day, which means it's very likely not in the last 1.4 release.

> Any news about this? Can we get this somehow included?

As this the fix is already in the jwt library, the next step is update istio to use the new version of the envoy.

@xulingqing  could you take a look?

1. Ask https://github.com/envoyproxy/envoy-wasm to update to the latest envoy that includes https://github.com/google/jwt_verify_lib/pull/51
1. Update the sha in istio/proxy: https://github.com/istio/proxy/blob/master/WORKSPACE#L41
1. Update the sha in istio/istio: https://github.com/istio/istio/blob/master/istio.deps#L7

**Comment by xulingqing** [comment]
Istio and Proxy has been updated to include the fix for include [google/jwt_verify_lib#51](https://github.com/google/jwt_verify_lib/pull/51) from Envoy

**Comment by xulingqing** [comment]
I reproduced the issue with [istio-1.7.0-alpha.0](https://github.com/istio/istio/releases/tag/1.7.0-alpha.0) using the following RequestAuthentication config. And, the issue is fixed now. Thanks.

```
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-example"
  namespace: foo
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwks: '{ 
      "keys":[ 
        {
          "e":"AQAB",
          "kid":"DHFbpoIUqrY8t2zpA2qXfCmr5VO5ZEr4RzHU_-envvQ",
          "kty":"RSA",
          "n":"xAE7eB6qugXyCAG3yhh7pkDkT65pHymX-P7KfIupjf59vsdo91bSP9C8H07pSAGQO1MV_xFj9VswgsCg4R6otmg5PV2He95lZdHtOcU5DXIg_pbhLdKXbi66GlVeK6ABZOUW3WYtnNHD-91gVuoeJT_DwtGGcp4ignkgXfkiEm4sw-4sfb4qdt5oLbyVpmW6x9cfa7vs2WTfURiCrBoUqgBo_-4WTiULmmHSGZHOjzwa8WtrtOQGsAFjIbno85jp6MnGGGZPYZbDAa_b3y5u-YpW7ypZrvD8BgtKVjgtQgZhLAGezMt0ua3DRrWnKqTZ0BJ_EyxOGuHJrLsn00fnMQ"}
          ,{
          "kty" : "RSA",
          "e" : "AQAB",
          "use" : "sig",
          "crv" : "",
          "kid" : "3d038aa2-4893-4ca7-ad76-12f548f570c2_sig_ps256",
          "x5c" : [ "MIIDbDCCAiCgAwIBAgIhAJHzacg9FYsoEIkziWI203OcmvJH0NpwDOVArZXtkWR1MEEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIBBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIBBQCiAwIBIDAhMR8wHQYDVQQDDBZveEF1dGggQ0EgQ2VydGlmaWNhdGVzMB4XDTIwMDMxMTE4MTA1MFoXDTIwMDMxMzE4MTA1OFowITEfMB0GA1UEAwwWb3hBdXRoIENBIENlcnRpZmljYXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKnsafV+RDC4jdvIEo4heObd1KO7lN7BIcSOyAaRdtiMOwm+poNLNDxobId/b7jMpiIFYNm/kWxTORiFSk30Q1bbqBbxM5EtPfHCZ3c8v9zX15muzD056oEdI9XDtTXfYXGCQBbAnMwCdv9JUaaAnk2Jni+O8+YhGW1oQb0VKK9nGOHWbezLRHEoRFLL9g1x/Bor+sP/pX/9kzMrNq8QHGngQvPyk26EdCf8kV+A+SCCfFr2OGlYsRXQkv4VEmulC93Pnc9THsMTKqvKQ5caG9mr6BlrySewPBz66il3fTjvMwCs+cp2wLeKqTJt8ym34NNhILcnPTKnWNGTOSv/TnsCAwEAAaMnMCUwIwYDVR0lBBwwGgYIKwYBBQUHAwEGCCsGAQUFBwMCBgRVHSUAMEEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIBBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIBBQCiAwIBIAOCAQEAS6b9zEpSLzdyQ/ngz67MIrYRS+YUXT41JFj5ZNopBVDSzanSpZeCc381fkfaMSviKalBoSaJZzwOD/r+arTLYRGi0uSyTU5lFMVh/pYUDgfdlB2QWC/sXV/ftaKAAU59e/7WCzTbXLWJTrYXyYxzziV2jb/AGuM9COtTO/r98u9IaCR9UbNnCNPjpt9Db3Sk3upV1hcmheZP9Ayj1NGUah+5PVnYg8sU/laYf1MPNU42tKolN2gwWtkdRuCBqM3Zfs9u68MbwKo8uyuL3BFOVuWMV1jE4LsyfR+5QWACuwX8RXr+U8DfX4+bh1mg1OWa6BY8YSVE+0edIF59DgK/LA==" ],
          "exp" : 1584123058707,
          "alg" : "PS256",
          "n" : "qexp9X5EMLiN28gSjiF45t3Uo7uU3sEhxI7IBpF22Iw7Cb6mg0s0PGhsh39vuMymIgVg2b-RbFM5GIVKTfRDVtuoFvEzkS098cJndzy_3NfXma7MPTnqgR0j1cO1Nd9hcYJAFsCczAJ2_0lRpoCeTYmeL47z5iEZbWhBvRUor2cY4dZt7MtEcShEUsv2DXH8Giv6w_-lf_2TMys2rxAcaeBC8_KTboR0J_yRX4D5IIJ8WvY4aVixFdCS_hUSa6UL3c-dz1MewxMqq8pDlxob2avoGWvJJ7A8HPrqKXd9OO8zAKz5ynbAt4qpMm3zKbfg02Egtyc9MqdY0ZM5K_9Oew"
        }, {
          "kty" : "RSA",
          "e" : "AQAB",
          "use" : "sig",
          "crv" : "",
          "kid" : "f188f605-4ce9-4028-83de-cfc986f3f926_sig_ps384",
          "x5c" : [ "MIIDazCCAh+gAwIBAgIgRdE8wIVA4Ehcg/wKboudibqBiPi0vlO6eN4F+DdYzJgwQQYJKoZIhvcNAQEKMDSgDzANBglghkgBZQMEAgIFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgIFAKIDAgEwMCExHzAdBgNVBAMMFm94QXV0aCBDQSBDZXJ0aWZpY2F0ZXMwHhcNMjAwMzExMTgxMDUxWhcNMjAwMzEzMTgxMDU4WjAhMR8wHQYDVQQDDBZveEF1dGggQ0EgQ2VydGlmaWNhdGVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnW3FIfzmiWbaXYTaTA+XbX9Rq6o74WfbS8TghQGNMS8AYBlBCEPPtYzd/vIA2B7DTq+BZqwqwN45ycXP/Xl7i2QpWj9BVL3yllD/QVau/bFMUXGdLi9s8wsvRJm15AFQ0PChgllkFRHAd9TuIwa/eMoQ+JFjMeFhwxE9W3PthtMVPZplrxUYC9Ns0v3EXf9gYCX2fR2BUGWuAuc18QB2pPsdQwtH2EH6mfmxz55t7bnQyay8bWTugk2hMrW3+I4HdlRoB7iYRUmw9Yq/zs+rrGYadf6MG23gIDMk00z88xqZegYtxVzydWwV/lUTlnx8N3Us+NyfAYtVMtkPOv/CvwIDAQABoycwJTAjBgNVHSUEHDAaBggrBgEFBQcDAQYIKwYBBQUHAwIGBFUdJQAwQQYJKoZIhvcNAQEKMDSgDzANBglghkgBZQMEAgIFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgIFAKIDAgEwA4IBAQBWPrPgvmzDVMNHlWdXHQBBSeXtaF2m9UsptzqCpJmx+xLX5hzSxLqDcTDlpWHr4Vqi7sv0SOtggC5vV49AWc41ddp4co0btpPzr0UDQBpuN9GQt1gDyUCk0EElIqragSsACSdkP7U6pZiLBO5zxmSPWwvhfmQm1VVIC2NIhKv1iqCr4fqQUXEqQNYIqAVb8UIccaz6DykCbgOMDNMXtsTaKCQrJjWMz90ulZJrcdTyhesnnq5bngXws7w7amXtzWIBYS+vh9tuRCSXNGVvSbXS178KwiFKXst9lQB81qcwt3bKUtTj8hX1w6qwT6/ifwhtrv4OO+ml0jgbqLqkT5TI" ],
          "exp" : 1584123058707,
          "alg" : "PS384",
          "n" : "nW3FIfzmiWbaXYTaTA-XbX9Rq6o74WfbS8TghQGNMS8AYBlBCEPPtYzd_vIA2B7DTq-BZqwqwN45ycXP_Xl7i2QpWj9BVL3yllD_QVau_bFMUXGdLi9s8wsvRJm15AFQ0PChgllkFRHAd9TuIwa_eMoQ-JFjMeFhwxE9W3PthtMVPZplrxUYC9Ns0v3EXf9gYCX2fR2BUGWuAuc18QB2pPsdQwtH2EH6mfmxz55t7bnQyay8bWTugk2hMrW3-I4HdlRoB7iYRUmw9Yq_zs-rrGYadf6MG23gIDMk00z88xqZegYtxVzydWwV_lUTlnx8N3Us-NyfAYtVMtkPOv_Cvw"
        }, {
          "kty" : "RSA",
          "e" : "AQAB",
          "use" : "sig",
          "crv" : "",
          "kid" : "ecdf887a-f27d-4659-adc2-906fa92c67e9_sig_ps512",
          "x5c" : [ "MIIDbDCCAiCgAwIBAgIhAIiaYBZk8O0PUrwyXl/Rm/2Usw8uf1YnhrPkGJPAOzx+MEEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIDBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIDBQCiAwIBQDAhMR8wHQYDVQQDDBZveEF1dGggQ0EgQ2VydGlmaWNhdGVzMB4XDTIwMDMxMTE4MTA1MVoXDTIwMDMxMzE4MTA1OFowITEfMB0GA1UEAwwWb3hBdXRoIENBIENlcnRpZmljYXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK9rB3iPUEp89TEJ0wTqnWV+EA03YjNNLjcKFxEIux3nxyNOFU3BkVoYO64gFSvAE+ORp0o5lgYN0hpJJT3M+0xJ2onKRmc/rAKD2KhGcTpjBLZ3g+Hq/yXNMVujFgBWoAcGvoGt/G/TpuIt5xtRFFCqoyzbV/aSLRSZx02637yhdQN7K1A696NestVgIKRSAjYBekHYzA9HResQWlk9yO/ZFz/evS2lxUiCUyR1REspDaQ2PMDYeiofvLwqSU2Zma32JL3UpotgdSm3hGHRHXr+8RMJgIA4kmBR5/xuDEfXELQv0X0FFGQ4TdQ+t488TtE0H93WZCtyqFr8v7m5eqkCAwEAAaMnMCUwIwYDVR0lBBwwGgYIKwYBBQUHAwEGCCsGAQUFBwMCBgRVHSUAMEEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIDBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIDBQCiAwIBQAOCAQEAcxG0JJwN+InTq+Cb+Ijl1kJ5OGx8hYZmAstwTVRkW9gdjaR0Hqp97Rj0kv9vlkfihwHlSCDWQUh7l2oruP88QvnvypcVARwSw5gAswiC8Q5F8b+W2WvOzk+KvYY3Q6oehY+VwsEpx5gJisP7t3BW4LlJTNbRhA4ZKifnFm0ah6HsILRIpy7tqSSFyjSmGo73eLfmKyNPEH8tn0pXO7GOMUgDvovMe9iycNmpo27qbpRMlcSUbElo5PZtDknXeritt53iJnD3ucaX3Qahb0jSfN/8X25DRs6s8F2O+CzRd7hyhjCTsgPgNiNJeIS9bP9vVpUj9VWK2y0lXCsn2PnqAQ==" ],
          "exp" : 1584123058707,
          "alg" : "PS512",
          "n" : "r2sHeI9QSnz1MQnTBOqdZX4QDTdiM00uNwoXEQi7HefHI04VTcGRWhg7riAVK8AT45GnSjmWBg3SGkklPcz7TEnaicpGZz-sAoPYqEZxOmMEtneD4er_Jc0xW6MWAFagBwa-ga38b9Om4i3nG1EUUKqjLNtX9pItFJnHTbrfvKF1A3srUDr3o16y1WAgpFICNgF6QdjMD0dF6xBaWT3I79kXP969LaXFSIJTJHVESykNpDY8wNh6Kh-8vCpJTZmZrfYkvdSmi2B1KbeEYdEdev7xEwmAgDiSYFHn_G4MR9cQtC_RfQUUZDhN1D63jzxO0TQf3dZkK3KoWvy_ubl6qQ"
        }
      ]
  }'
```

**Comment by yangminzhu** [comment]
I think @xulingqing you actually mean you verified the fix in 1.7.0-alpha other than reproducing the issue? Reproducing the issue mean it's not fixed.

**Comment by xulingqing** [comment]
Yes, I mean I verified the fix in 1.7.0-alpha. Thanks for your correction @yangminzhu !
