### ISSUE TITLE
error when applying EnvoyFilter lua example

### ISSUE THREAD

**Issue by mstrYoda** [istio/istio#22615]
**Bug description**
When I apply the example given at:
https://github.com/istio/istio/wiki/EnvoyFilter-Samples#adding-a-http-lua-filter

it gives the error:

```
"spec.configPatches.match" must validate one and only one schema (oneOf). Found none valid
spec.configPatches.match.listener in body is required
```

**Expected behavior**
Applying successfully.

**Steps to reproduce the bug**
Copy the given http lua filter example, change namespace and app label to a valid one.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio version is 1.5

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
Baremetal k8s

**Comment by johnzheng1975** [comment]
Same for me. I am try this in envoyfilter 1.4

**Comment by johnzheng1975** [comment]
https://github.com/envoyproxy/envoy/issues/11870

**Comment by howardjohn** [comment]
Hi, we have fixed the sample. Thanks!

**Comment by aatishrana** [comment]
Hi @howardjohn, 
I am still facing this issue on istio 1.7.6
Can you confirm if docs present [here](https://github.com/istio/istio/wiki/EnvoyFilter-Samples#adding-a-http-lua-filter) is the updated one?

**Comment by wangmouren609** [comment]
I am still facing this issue use this sample  [https://github.com/istio/istio/wiki/EnvoyFilter-Samples#adding-a-http-lua-filter](url)
