### ISSUE TITLE
Tracing regression in 1.5.x - nested traces are intermittently incomplete

### ISSUE THREAD

**Issue by Stono** [istio/istio#22968]
**Bug description**
We are having a problem where traces aren't coming through to Jaeger correctly, where the spans are complaining that the `parentSpanId` is missing.  

This is **only** an issue on `1.5.1`, using a `1.4.6` sidecar (with `1.5.1` control plane) this traces are always complete.  Therefore I believe this to be a 1.5 regression.

It'd be great if someone who more deeply understands istio/envoy/zipkin and the istio debug logs could help me wade through the information here to see what is up.  If you're struggling to reproduce i'm more than happy to remote share with you to debug this.

**Example failure**
As an example, we have a simple app setup of:

`nginx` -> `istio-test-app-1` -> `istio-test-app-2` ->`istio-test-app-3`

Which has been around since istio 1.0 days, to help us test these sorts of things, nothing has changed in them with regards to header forwarding logic.

As you can see in Jaeger the trace for `38e310d5619723f6` is messed up:

![Screenshot 2020-04-15 at 19 59 01](https://user-images.githubusercontent.com/1486729/79377431-92323b00-7f53-11ea-90b9-5a975878dfe3.png)

The `istio-test-app-2` span is missing.

Another example here on trace `64f13d7f39b4a5f2`:

![Screenshot 2020-04-15 at 20 01 26](https://user-images.githubusercontent.com/1486729/79377671-f1904b00-7f53-11ea-9c4e-d3f4a773ad4f.png)

In this case, the span for `istio-test-app-1` is missing.

I have captured `istio-proxy-debug` logs for each of the test apps, which contain the requests mentioned above (as well as some other noise, sorry).

[istio-test-app-1.log](https://github.com/istio/istio/files/4483208/istio-test-app-1.log)
[istio-test-app-2.log](https://github.com/istio/istio/files/4483209/istio-test-app-2.log)
[istio-test-app-3.log](https://github.com/istio/istio/files/4483210/istio-test-app-3.log)

**Expected behavior**
Traces to be complete

**Steps to reproduce the bug**
For us, it's using a `1.5.1` sidecar

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
`1.5.1` microservice model (not istiod)

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by douglas-reid** [comment]
This needs to be fixed for 1.5.x releases as well.

@fpesce is it better to make this a 1.5 milestone or leave it as 1.6 ?

**Comment by fpesce** [comment]
@douglas-reid if this is considered a regression, I think it would be better to fix it in 1.5.x.

**Comment by mandarjog** [comment]
@bianpengyuan can you investigate ?

**Comment by douglas-reid** [comment]
@objectiser if you have any insights here, that'd also be appreciated.

**Comment by bianpengyuan** [comment]
I was able to reproduce this in my test environment. Looks like the drop is random. I need to dig more.

**Comment by objectiser** [comment]
@douglas-reid Jaeger has various queues in its architecture where spans may be dropped if the component gets flooded by spans being reported - the collector being one of them. However, as @Stono pointed out, this only occurs when using a specific version of the proxy.

The other interesting point is that, rather than one span randomly going missing, which might happen occasionally - in both the example failures shown in the description, the 2 spans from the same service are missing.

So in the first failure - two spans (server and client) are missing for `istio-test-app-2`, whereas the second failure has two spans (server and client) for `istio-test-app-1` missing.

Trace context is still being propagated successfully, so doesn't appear to be a problem with whether the trace is being sampled or not.

**Comment by Stono** [comment]
Hi,
Just to clarify a couple of things.  Istio test app 1,2 and 3 are the same code base and we’ve used them to test istio for almost a year.

In terms of load, this is on a testing cluster under no load, to an in memory jaeger collector.  The same behaviour manifests on all other clusters on 1.5.1 which back onto elasticsearch.

In terms of the correlation that it was the second span, that’s just coincidental I believe, as on other tests it’s spans at various levels that disappear.  I will share some other examples just to confirm when I’m back at my desk

**Comment by Stono** [comment]
@objectiser @bianpengyuan @douglas-reid i've tried to extract from the logs everything for trace `38e310d5619723f6`, which from the information span `9fa88920d6b8778a` was reporting a parent span of `70818c6c00118cea`, which was missing.

However from the l

```
istio-test-app-1 (sidecar receiving request):
 - 'x-b3-spanid', 'ac7b27f7f9160c5e'
 - 'x-b3-parentspanid', 'e7008aa18fd4c5f6'

istio-test-app-1 (sidecar)-> istio-test-app-1 (app):
 - 'x-b3-spanid', '45749a1e06c2512d'
 - 'x-b3-parentspanid', 'ac7b27f7f9160c5e'

istio-test-app-1 (app) -> istio-test-app-1 (sidecar):
 - 'x-b3-spanid', '45749a1e06c2512d'
 - 'x-b3-parentspanid', 'ac7b27f7f9160c5e'

istio-test-app-1 (sidecar) -> istio-test-app-2 (sidecar):
 - 'x-b3-spanid', '9862709f56a411ae'
 - 'x-b3-parentspanid', '45749a1e06c2512d'

istio-test-app-2 (sidecar receiving request):
 - 'x-b3-spanid', '9862709f56a411ae'
 - 'x-b3-parentspanid', '45749a1e06c2512d'

istio-test-app-2 (sidecar) -> istio-test-app-2 (app):
 - 'x-b3-spanid', '6275ede08ea50c4a'
 - 'x-b3-parentspanid', '9862709f56a411ae'

istio-test-app-2 (app) -> istio-test-app2 (sidecar):
 - 'x-b3-spanid', '6275ede08ea50c4a'
 - 'x-b3-parentspanid', '9862709f56a411ae'

istio-test-app-2 (sidecar) -> istio-test-app-3 (sidecar):  <---- MISSING SPAN
 - 'x-b3-spanid', '70818c6c00118cea'
 - 'x-b3-parentspanid', '6275ede08ea50c4a'

istio-test-app-3 (sidecar receiving request):
 - 'x-b3-spanid', '70818c6c00118cea'
 - 'x-b3-parentspanid', '6275ede08ea50c4a'

istio-test-app-3 (sidecar) -> istio-test-app-3 (app):
 - 'x-b3-spanid', '9fa88920d6b8778a'
 - 'x-b3-parentspanid', '70818c6c00118cea'
```

So looking at the logs for `istio-test-app-2`, you can see the request from `istio-test-app-2` -> `istio-test-app-3` on line `178`, at `18:50:25.302`.   So I decided to follow down to where the Jaeger POST to report the spans happened and I saw this:

```
[Envoy (Epoch 0)] [2020-04-15 18:50:27.428][28][debug][router] [external/envoy/source/common/router/router.cc:614] [C0][S17259990231804564098] router decoding headers:
':method', 'POST'
':path', '/api/v2/spans'
':authority', 'zipkin'
':scheme', 'http'
'content-type', 'application/json'
'x-envoy-internal', 'true'
'x-forwarded-for', '10.206.8.124'
'x-envoy-expected-rq-timeout-ms', '5000'

[Envoy (Epoch 0)] [2020-04-15 18:50:27.428][28][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:104] [C15] using existing connection
[Envoy (Epoch 0)] [2020-04-15 18:50:27.428][28][debug][router] [external/envoy/source/common/router/router.cc:1711] [C0][S17259990231804564098] pool ready
[Envoy (Epoch 0)] [2020-04-15 18:50:27.429][28][debug][router] [external/envoy/source/common/router/router.cc:1115] [C0][S17259990231804564098] upstream headers complete: end_stream=false
[Envoy (Epoch 0)] [2020-04-15 18:50:27.429][28][debug][http] [external/envoy/source/common/http/async_client_impl.cc:95] async http request response headers (end_stream=false):
':status', '400'
'content-type', 'text/plain; charset=utf-8'
'vary', 'Origin'
'x-content-type-options', 'nosniff'
'date', 'Wed, 15 Apr 2020 18:50:27 GMT'
'content-length', '133'
'x-envoy-upstream-service-time', '0'

[Envoy (Epoch 0)] [2020-04-15 18:50:27.429][28][debug][client] [external/envoy/source/common/http/codec_client.cc:104] [C15] response complete
[Envoy (Epoch 0)] [2020-04-15 18:50:27.429][28][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:201] [C15] response complete
[Envoy (Epoch 0)] [2020-04-15 18:50:27.429][28][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:239] [C15] moving to ready
```

Note the 400 BAD REQUEST with a upstream-service-time of 0?  Feels like for whatever reason envoy rejected this request with a 400.

Looking through the logs further, we occasionally see these 400's after a POST to jaeger and it marries up with traces that are missing spans.

**Comment by Stono** [comment]
So i then followed this through to the jaeger collector and TCP dumped out the incoming requests and was able to see the 400s:

```
09:42:04.259148 IP 10.206.8.127.39940 > istio-tracing-5845b6fbd4-7br5j.9411: Flags [P.], seq 4163815308:4163820027, ack 504468475, win 333, options [nop,nop,TS val 2061904836 ecr 175011169], length 4719
E.....@.?.(=
...
..u..$............M9%.....
z.+.
nuaPOST /api/v2/spans HTTP/1.1
host: zipkin
content-type: application/json
x-envoy-internal: true
x-forwarded-for: 10.206.8.127
x-envoy-expected-rq-timeout-ms: 5000
transfer-encoding: chunked

119c
[{"traceId":"c71df96d08ec50ef","name":"app.istio-test-app-2.svc.cluster.local:80/*","timestamp":1.58703012360987e+15,"duration":7912,"kind":"CLIENT","localEndpoint":{"port":0,"serviceName":"istio-test-app-1","ipv4":"10.206.8.127"},"id":"aa29007755b8cbac","tags":{"upstream_cluster":"outbound|80||app.istio-test-app-2.svc.cluster.local","guid:x-request-id":"6ce4516f-0da3-48b4-8b24-17e2a54da720","http.protocol":"HTTP/1.1","component":"proxy","http.url":"http://app.istio-test-app-2/downstream?servers=app.istio-test-app-3/instant","user_agent":"-","downstream_cluster":"-","request_size":"0","response_flags":"-","response_size":"428","node_id":"sidecar~10.206.8.127~istio-test-app-1-cd9cd559d-m9hql.istio-test-app-1~istio-test-app-1.svc.cluster.local","http.status_code":"200","http.method":"GET"},"parentId":"6c2b3d8c42f24f05"},{"id":"6c2b3d8c42f24f05","tags":{"response_size":"633","node_id":"sidecar~10.206.8.127~istio-test-app-1-cd9cd559d-m9hql.istio-test-app-1~istio-test-app-1.svc.cluster.local","http.status_code":"200","http.method":"GET","upstream_cluster":"inbound|80|http-web|app.istio-test-app-1.svc.cluster.local","guid:x-request-id":"6ce4516f-0da3-48b4-8b24-17e2a54da720","http.protocol":"HTTP/2","component":"proxy","http.url":"https://app.istio-test-app-1.testing.k8.atcloud.io/downstream?servers=app.istio-test-app-2/downstream?servers=app.istio-test-app-3/instant","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36","downstream_cluster":"-","response_flags":"-","request_size":"0"},"parentId":"0b45ec791cb2b9d9","traceId":"c71df96d08ec50ef","name":"app.istio-test-app-1.svc.cluster.local:80/*","timestamp":1587030123608213,"duration":11523,"kind":"CLIENT","localEndpoint":{"port":0,"serviceName":"istio-test-app-1","ipv4":"10.206.8.127"}},{"duration":8036,"kind":"CLIENT","localEndpoint":{"port":0,"serviceName":"istio-test-app-1","ipv4":"10.206.8.127"},"id":"2271a862646ef79b","tags":{"downstream_cluster":"-","user_agent":"-","response_flags":"-","request_size":"0","response_size":"428","node_id":"sidecar~10.206.8.127~istio-test-app-1-cd9cd559d-m9hql.istio-test-app-1~istio-test-app-1.svc.cluster.local","http.status_code":"200","http.method":"GET","upstream_cluster":"outbound|80||app.istio-test-app-2.svc.cluster.local","guid:x-request-id":"9c0c4bbc-777b-4414-a36b-e2ff6a0aa30b","http.protocol":"HTTP/1.1","component":"proxy","http.url":"http://app.istio-test-app-2/downstream?servers=app.istio-test-app-3/instant"},"parentId":"514b42930dfd5f51","traceId":"b10d0bc09ddd3574","name":"app.istio-test-app-2.svc.cluster.local:80/*","timestamp":1587030124065573},{"traceId":"b10d0bc09ddd3574","name":"app.istio-test-app-1.svc.cluster.local:80/*","timestamp":1587030124063938,"duration":11654,"kind":"CLIENT","localEndpoint":{"port":0,"serviceName":"istio-test-app-1","ipv4":"10.206.8.127"},"id":"514b42930dfd5f51","tags":{"http.url":"https://app.istio-test-app-1.testing.k8.atcloud.io/downstream?servers=app.istio-test-app-2/downstream?servers=app.istio-test-app-3/instant","downstream_cluster":"-","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36","response_flags":"-","request_size":"0","response_size":"633","node_id":"sidecar~10.206.8.127~istio-test-app-1-cd9cd559d-m9hql.istio-test-app-1~istio-test-app-1.svc.cluster.local","http.status_code":"200","http.method":"GET","upstream_cluster":"inbound|80|http-web|app.istio-test-app-1.svc.cluster.local","guid:x-request-id":"9c0c4bbc-777b-4414-a36b-e2ff6a0aa30b","http.protocol":"HTTP/2","component":"proxy"},"parentId":"a663b2da260c5333"},{"localEndpoint":{"port":0,"serviceName":"istio-test-app-1","ipv4":"10.206.8.127"},"id":"ea393e07f90061e6","tags":{"http.method":"GET","upstream_cluster":"outbound|80||app.istio-test-app-2.svc.cluster.local","guid:x-request-id":"45501d11-f9cc-442f-b7b7-8e2822de8469","http.protocol":"HTTP/1.1","component":"proxy","http.url":"http://app.istio-test-app-2/downstream?servers=app.istio-test-app-3/instant","downstream_cluster":"-","user_agent":"-","request_size":"0","response_flags":"-","response_size":"428","node_id":"sidecar~10.206.8.127~istio-test-app-1-cd9cd559d-m9hql.istio-test-app-1~istio-test-app-1.svc.cluster.local","http.status_code":"200"},"parentId":"334d87d8578e0e3e","traceId":"dac5d6d050bbf254","name":"app.istio-test-app-2.svc.cluster.local:80/*","timestamp":1587030124251379,"duration":7252,"kind":"CLIENT"}]
0


09:42:04.259428 IP istio-tracing-5845b6fbd4-7br5j.9411 > 10.206.8.127.39940: Flags [P.], seq 1:308, ack 4719, win 331, options [nop,nop,TS val 175039204 ecr 2061904836], length 307
E..g..@.@.).
..u
...$..............K'......

n..z.+.HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Vary: Origin
X-Content-Type-Options: nosniff
Date: Thu, 16 Apr 2020 09:42:04 GMT
Content-Length: 133

Unable to process request body: json: cannot unmarshal number 1.58703012360987e+15 into Go struct field Span.timestamp of type int64
```

**Comment by objectiser** [comment]
I think this is the relevant [issue](https://github.com/envoyproxy/envoy/issues/9341). It relates to a couple of changes made to the zipkin v2 timestamp field, and it refers to a comment about the format: https://github.com/openzipkin/zipkin-go/pull/161#issuecomment-598558072

So potentially need to upgrade to latest envoy commit.

**Comment by mandarjog** [comment]
great sleuthing @Stono .
Does this mean *every* request should fail ? With `HTTP_JSON` endpoint,  every timestamp should be scientific notation, or does it change from number to scientific dynamically ?

**Comment by douglas-reid** [comment]
Summarizing offline conversations, etc.: In the linked issue, it looks like others were reporting the it _sometimes_ uses scientific notation. A patch was just merged and we need to verify and then cherry-pick to the impacted releases.

**Comment by bianpengyuan** [comment]
1.5 cherry-pick PR: https://github.com/istio/envoy/pull/194

**Comment by nrjpoddar** [comment]
> Summarizing offline conversations, etc.: In the linked issue, it looks like others were reporting that it _sometimes_ uses scientific notation. A patch was just merged and we need to verify and then cherry-pick to the impacted releases.

@douglas-reid I'm confused as to why this will cause intermittent failures?

**Comment by mandarjog** [comment]
@bianpengyuan the cherry-pick is only on master, not 1.5

**Comment by bianpengyuan** [comment]
@mandarjog not sure I follow. This needs to be fix on 1.5 right? the linked pr is to cherry-pick fix into istio/envoy release-1.5.

@nrjpoddar It is random behavior from protobuf struct -> json serialization with large integer.

**Comment by douglas-reid** [comment]
> > Summarizing offline conversations, etc.: In the linked issue, it looks like others were reporting that it _sometimes_ uses scientific notation. A patch was just merged and we need to verify and then cherry-pick to the impacted releases.
> 
> @douglas-reid I'm confused as to why this will cause intermittent failures?

@nrjpoddar i haven't looked closely at the patch so I don't know the underlying cause, but https://github.com/envoyproxy/envoy/issues/9341#issuecomment-577051483 shows that others have observed intermittent failures.

**Comment by Stono** [comment]
Sorry to be that naggy person but this is causing us quite a few ops issues.  When do you anticipate being able to cut a 1.5.2 with the fix?

I ask because if it’s far away I’m going to have to look at rolling back everywhere to 1.4.6

Cheers for your help!

**Comment by bianpengyuan** [comment]
This has been cherry-picked into 1.5 and will be released with 1.5.2. I've verified the fix in my test env. @Stono Please try out `gcr.io/istio-testing/proxyv2:1.5-alpha.287e52ea3c53f7a15853db550edef4dbe243b4ca` in your env when you have a chance, thanks!

**Comment by bianpengyuan** [comment]
@fpesce ^^ about 1.5.2 eta.

**Comment by fpesce** [comment]
ETA for 1.5.2 is realistically Wednesday, we are fixing https://github.com/istio/istio/issues/23038 right now, I'll probably trigger the build when https://github.com/istio/istio/pull/23037 is tested and merged

**Comment by Stono** [comment]
Thank you for the update both.  I’ll test that image shortly

**Comment by Stono** [comment]
@fpesce @bianpengyuan I've tested the above image on the deployment setup I used to replicate this issue and can confirm the issue is resolved.

This deployment has constant load at it and is also patch restarted every 5-10 minutes to generate churn so i'll leave it there for a good few days and let you know if I spot anything untoward.

Ta

**Comment by douglas-reid** [comment]
@bianpengyuan and just to be clear, that envoy patch is definitely included in 1.6 moving forward ?

**Comment by bianpengyuan** [comment]
@douglas-reid with https://github.com/istio/envoy/pull/196 it should be.

**Comment by bianpengyuan** [comment]
This should be fixed in 1.6. I will use this issue to track how to make the test more strict in order to catch a random bug like this.

**Comment by bianpengyuan** [comment]
Close in favor of https://github.com/istio/istio/issues/23260

**Comment by Stono** [comment]
Bad news, looks like this is still broken.
Please can we reopen it @bianpengyuan @douglas-reid @fpesce and i'll try and debug more tomorrow

**Comment by bianpengyuan** [comment]
Is it still broken with 1.5.2?

**Comment by Stono** [comment]
Seems so yes :-(
<img width="1680" alt="Screenshot 2020-04-30 at 20 04 29" src="https://user-images.githubusercontent.com/1486729/80749063-d3af1280-8b1d-11ea-906f-28df3c2d1003.png">

**Comment by bianpengyuan** [comment]
Ok thanks! I will also try out 1.6 installation and see if I can reproduce.

**Comment by bianpengyuan** [comment]
How often does it happen in your env? I cannot find any occurrence of this bug in my cluster installed head. If I remembered correctly it happened quite often before the fix. So not sure if it is just a transient error that you caught.

**Comment by Stono** [comment]
No unfortunately I have a lot of examples.  It's quite late here so I'll collect more information for you tomorrow.

**Comment by Stono** [comment]
```
08:11:16.180772 IP 10.194.46.22.47740 > istio-tracing-54f89c8554-ldvkv.9411: Flags [P.], seq 38021791:38026659, ack 73850609, win 4416, options [nop,nop,TS val 1276055718 ecr 244643951], length 4868
E..8..@.>...
...
.'..|$..D*..f.....@~x.....
L......oPOST /api/v2/spans HTTP/1.1
host: zipkin
content-type: application/json
x-envoy-internal: true
x-forwarded-for: 10.194.46.22
x-envoy-expected-rq-timeout-ms: 5000
transfer-encoding: chunked

1231
[{"localEndpoint":{"port":0,"serviceName":"ingress-nginx-external","ipv4":"10.194.46.22"},"id":"90baa147bf5ed88a","tags":{"http.status_code":"200","http.method":"GET","upstream_cluster":"outbound|80||app.consumer-gateway.svc.cluster.local","guid:x-request-id":"58c807e0dbabe597-MAN","http.protocol":"HTTP/1.1","component":"proxy","http.url":"https://www.autotrader.co.uk/json/finance-calculator?useDefault=true&advertId=202004309122948&selectedDid=21342&includePartEx=true&channel=cars","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36","downstream_cluster":"-","request_size":"0","response_flags":"-","response_size":"1351","node_id":"sidecar~10.194.46.22~ingress-nginx-external-controller-6758c68b6f-ccjzm.ingress-nginx~ingress-nginx.svc.cluster.local"},"parentId":"4a9ad30d09410d00","traceId":"0d645df36d72d419","name":"app.consumer-gateway.svc.cluster.local:80/*","timestamp":1.58832067599851e+15,"duration":143176,"kind":"CLIENT"},{"localEndpoint":{"port":0,"serviceName":"ingress-nginx-external","ipv4":"10.194.46.22"},"id":"91a4b9d86579e01c","tags":{"component":"proxy","http.url":"https://www.autotrader.co.uk/","downstream_cluster":"-","user_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Mobile/15E148 Safari/604.1","response_flags":"-","request_size":"0","response_size":"47157","node_id":"sidecar~10.194.46.22~ingress-nginx-external-controller-6758c68b6f-ccjzm.ingress-nginx~ingress-nginx.svc.cluster.local","http.status_code":"200","http.method":"GET","upstream_cluster":"outbound|80||app.consumer-gateway.svc.cluster.local","guid:x-request-id":"58c807e17f61ce1f-LHR","http.protocol":"HTTP/1.1"},"parentId":"cfefa6fc30ac0959","traceId":"14d19010d8cf9c61","name":"app.consumer-gateway.svc.cluster.local:80/*","timestamp":1588320676096608,"duration":45625,"kind":"CLIENT"},{"id":"462cb9066426f1c7","tags":{"http.status_code":"204","http.method":"POST","upstream_cluster":"outbound|80||app.consumer-gateway.svc.cluster.local","guid:x-request-id":"58c807e1d9e60686-LHR","http.protocol":"HTTP/1.1","component":"proxy","http.url":"https://www.autotrader.co.uk/json/js-log/error","downstream_cluster":"-","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362","response_flags":"-","request_size":"35","response_size":"0","node_id":"sidecar~10.194.46.22~ingress-nginx-external-controller-6758c68b6f-ccjzm.ingress-nginx~ingress-nginx.svc.cluster.local"},"parentId":"8d2b9c59742c31c6","traceId":"b769794e36f7a05c","name":"app.consumer-gateway.svc.cluster.local:80/*","timestamp":1588320676152718,"duration":5986,"kind":"CLIENT","localEndpoint":{"port":0,"serviceName":"ingress-nginx-external","ipv4":"10.194.46.22"}},{"tags":{"http.status_code":"204","http.method":"POST","upstream_cluster":"outbound|80||app.consumer-gateway.svc.cluster.local","guid:x-request-id":"58c807e1ed67d210-MAN","http.protocol":"HTTP/1.1","component":"proxy","http.url":"https://www.autotrader.co.uk/json/js-log/error","downstream_cluster":"-","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363","response_flags":"-","request_size":"35","response_size":"0","node_id":"sidecar~10.194.46.22~ingress-nginx-external-controller-6758c68b6f-ccjzm.ingress-nginx~ingress-nginx.svc.cluster.local"},"parentId":"20a6a93d1f52ec6c","traceId":"6d16137acf04708a","name":"app.consumer-gateway.svc.cluster.local:80/*","timestamp":1588320676165394,"duration":4196,"kind":"CLIENT","localEndpoint":{"port":0,"serviceName":"ingress-nginx-external","ipv4":"10.194.46.22"},"id":"e6a586c45cef35f7"},{"tags":{"downstream_cluster":"-","user_agent":"swcd (unknown version) CFNetwork/1125.2 Darwin/19.4.0","response_flags":"-","request_size":"0","response_size":"0","node_id":"sidecar~10.194.46.22~ingress-nginx-external-controller-6758c68b6f-ccjzm.ingress-nginx~ingress-nginx.svc.cluster.local","http.status_code":"301","http.method":"GET","upstream_cluster":"outbound|80||app.consumer-gateway.svc.cluster.local","guid:x-request-id":"58c807e1ea780070-LHR","http.protocol":"HTTP/1.1","component":"proxy","http.url":"https://autotrader.co.uk/.well-known/apple-app-site-association"},"parentId":"4caa0bdd26697db3","traceId":"d174821f86615120","name":"app.consumer-gateway.svc.cluster.local:80/*","timestamp":1588320676162625,"duration":17704,"kind":"CLIENT","localEndpoint":{"port":0,"serviceName":"ingress-nginx-external","ipv4":"10.194.46.22"},"id":"580389b9404e3ee7"}]
0


08:11:16.181063 IP istio-tracing-54f89c8554-ldvkv.9411 > 10.194.46.22.47740: Flags [P.], seq 1:308, ack 4868, win 331, options [nop,nop,TS val 244644002 ecr 1276055718], length 307
E..g..@.@...
.'.
...$..|.f...D=....Kl......
....L...HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Vary: Origin
X-Content-Type-Options: nosniff
Date: Fri, 01 May 2020 08:11:16 GMT
Content-Length: 133
```

The source pod:
```
❯ k get pods --all-namespaces -o wide| grep 10.194.46.22
ingress-nginx                              ingress-nginx-external-controller-6758c68b6f-ccjzm                                            2/2     Running             0          22d     10.194.46.22    gke-delivery-platform-core-20191114-af4e6139-61hg     <none>           1/1
```

Which is actually on 1.5.1!  Some how, it's been missed during our sidecar rollout...
```
2020-04-08T17:58:10.931836Z	info	Version 1.5.1-9d07e185b0dd50e6fb1418caa4b4d879788807e3-Clean
2020-04-08T17:58:10.931956Z	info	Obtained private IP [10.194.46.22]
2020-04-08T17:58:10.931989Z	info	Proxy role: &model.Proxy{ClusterID:"", Type:"sidecar", IPAddresses:[]string{"10.194.46.22", "10.194.46.22"}, ID:"ingress-nginx-external-controller-6758c68b6f-ccjzm.ingress-nginx", Locality:(*envoy_api_v2_core.Locality)(nil), DNSDomain:"ingress-nginx.svc.cluster.local", ConfigNamespace:"", Metadata:(*model.NodeMetadata)(nil), SidecarScope:(*model.SidecarScope)(nil), MergedGateway:(*model.MergedGateway)(nil), ServiceInstances:[]*model.ServiceInstance(nil), WorkloadLabels:labels.Collection(nil), IstioVersion:(*model.IstioVersion)(nil)}
```

Sorry for the false positive guys!

**Comment by romil-punetha** [comment]
I'm still facing this issue on istio 1.5.2, using opentelemetry library 0.7.0, and nodejs 8.9.4

<img width="1680" alt="Screenshot 2020-05-04 at 11 35 11 PM" src="https://user-images.githubusercontent.com/47735999/80998048-e8faa880-8e5f-11ea-93ae-f84b1db5eddf.png">

**Comment by bianpengyuan** [comment]
@romil-punetha Please check and make sure all of your proxies are updated to 1.5.2.

**Comment by romil-punetha** [comment]
I checked. Both the services and the gateway from the above image are using envoy:1.5.2

<img width="1369" alt="Screenshot 2020-05-04 at 11 42 56 PM" src="https://user-images.githubusercontent.com/47735999/80998697-fcf2da00-8e60-11ea-9ad7-de53d6ebc468.png">

**Comment by bianpengyuan** [comment]
I've tried to reproduce this with 1.5.2 but did not see this anymore. Could you use @Stono's TCP dump command https://github.com/istio/istio/issues/22968#issuecomment-614537948 and see if you can capture any 400s? Then it would be nice to check that the proxy sending the trace is also 1.5.2.

**Comment by brian-avery** [comment]
@bianpengyuan This is currently marked as a release blocker on the spreadsheet. If it's no longer a release blocker please either change the priority or mark it as closed.

**Comment by douglas-reid** [comment]
@brian-avery I believe this is a release blocker, and it is currently marked closed. However, I think we are trying to determine if it should in fact be considered closed, or if more work is needed.

**Comment by bianpengyuan** [comment]
I was not able to reproduce this with either 1.6.0-beta.0 or 1.5.2. I tend to treat this as fixed and not blocking, unless there are evidences show otherwise.

**Comment by romil-punetha** [comment]
@bianpengyuan I was able to fix this by configuring the Jaeger propagator in Opentelemetry library to use `jaeger-agent.istio-system:6832` as the backend.
