### ISSUE TITLE
Emby: some requests fail with "upstream connect error"

### ISSUE THREAD

**Issue by shosti** [istio/istio#23020]
**Bug description**

Since upgrading to istio 1.5.1, some requests to a pod running Emby (with an istio-proxy sidecar) are consistently returning 503 errors with the message "upstream connect error or disconnect/reset before headers. reset reason: connection termination". I've verified that emby is serving the requests correctly. The same pods were working fine with istio 1.4.3.

**Expected behavior**

Requests to emby pods running istio-proxy return the upstream response.

**Steps to reproduce the bug**

1. Apply the following manifest to install emby:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: emby
  template:
    metadata:
      labels:
        app.kubernetes.io/name: emby
    spec:
      containers:
        - name: emby
          image: "emby/embyserver:4.4.2.0"
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: UID
              value: "1000"
            - name: GID
              value: "1000"
---
apiVersion: v1
kind: Service
metadata:
  name: emby
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: emby
```

2. From another pod in the same namespace, run `curl -v emby`. 

When istio sidecar injection is not present, I get the following:

```
*   Trying 10.101.18.34:80...
* Connected to emby (10.101.18.34) port 80 (#0)
> GET / HTTP/1.1
> Host: emby
> User-Agent: curl/7.69.1-DEV
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Location: web/index.html
< Date: Fri, 17 Apr 2020 00:58:07 GMT
< Transfer-Encoding: Chunked
< 
* Connection #0 to host emby left intact
```

When the istio sidecar injection is present, I get the following:
```
*   Trying 10.98.124.223:80...
* TCP_NODELAY set
* Connected to emby (10.98.124.223) port 80 (#0)
> GET / HTTP/1.1
> Host: emby
> User-Agent: curl/7.67.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 95
< content-type: text/plain
< date: Fri, 17 Apr 2020 01:13:48 GMT
< server: envoy
< x-envoy-upstream-service-time: 89
< 
* Connection #0 to host emby left intact
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

When I examine the internal logs in the pod (at `/config/logs/embyserver.txt`), I can see the requests with a 302 response. Also, requests to some other paths succeed as expected:

```
/ # curl -v emby/web/index.html > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.98.124.223:80...
* TCP_NODELAY set
* Connected to emby (10.98.124.223) port 80 (#0)
> GET /web/index.html HTTP/1.1
> Host: emby
> User-Agent: curl/7.67.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< location: index.html?start=wizard#!/wizard/wizardstart.html
< access-control-allow-headers: Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Date, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, Slug, Transfer-Encoding, Want-Digest, X-MediaBrowser-Token, X-Emby-Token, X-Emby-Client, X-Emby-Client-Version, X-Emby-Device-Id, X-Emby-Device-Name, X-Emby-Authorization
< access-control-allow-methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
< access-control-allow-origin: *
< server: envoy
< date: Fri, 17 Apr 2020 01:15:36 GMT
< content-length: 0
< x-envoy-upstream-service-time: 35
< 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host emby left intact
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (11 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```
istioctl manifest apply -f "$DIR"/../manifests/istio.yaml
```

With the following manifest file:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      mtls:
        enabled: true
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
    gateways:
      istio-ingressgateway:
        type: LoadBalancer
    global:
      k8sIngress:
        enabled: true
        enableHttps: true
        gatewayName: ingressgateway
```

And the following `PeerAuthentication` config:

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
```

**Environment where bug was observed (cloud vendor, OS, etc)**

Running on an on-prem environment with OpenStack train (K8s installed through kubeadm).

**Comment by howardjohn** [comment]
This is an Envoy bug: https://github.com/envoyproxy/envoy/issues/10041. I can confirm this is fixed in 1.6, and sounds like it was working in 1.4 so must have been a regression that slipped in?

**Comment by howardjohn** [comment]
And thanks for the thorough report by the way! if you had left out any of the details you had in there I probably wouldn't have figured this out

**Comment by howardjohn** [comment]
Would you mind trying out 1.6? I verified it myself but would be good to get a second set of eyes on it

**Comment by andrijaperovic** [comment]
We are observing this same bug with istio 1.6 OSS. Can you validate on your end if this has been fixed in 1.6 ASM?

**Comment by howardjohn** [comment]
I have verified this is fixed on 1.6 from reproducing the config above. Its possible you are experiencing a different issue?

**Comment by andrijaperovic** [comment]
@howardjohn the exact same services which failed for us on 1.5.4 ASM failed on 1.6 OSS, and were fixed with a rollback to 1.4.9 ASM/OSS in the respective scenarios. So it is most likely due to the Transfer-Encoding: Chunked issue which has been documented on envoy repository which you shared in the above comments.

**Comment by howardjohn** [comment]
@andrijaperovic do you have any info suggesting it is this issue aside from it breaking on 1.5? Do you see the same `dispatch error: http/1.1 protocol error: unsupported transfer encoding` error?

**Comment by andrijaperovic** [comment]
From what I can tell by this pull request, the changes were on a **release-1.5** branch in envoyproxy/envoy: 
https://github.com/envoyproxy/envoy/pull/10055

Not sure how this repository is being shipped with OSS/ASM istio or what the release/branching strategy is.

**Comment by howardjohn** [comment]
It was added to 1.5 branch a few days ago, it has not yet shipped in any 1.5.x release

**Comment by andrijaperovic** [comment]
We did originally observe the dispatch error on the 1.5.4 ASM install, I haven't found a similar snippet on 1.6, will have to re-install on a test cluster to validate: 
`[external/envoy/source/common/network/io_socket_error_impl.cc:29] Unknown error code 104 details Connection reset by peer
[Envoy (Epoch 0)] [2020-06-02 20:13:34.626][30][trace][connection] [external/envoy/source/common/network/raw_buffer_socket.cc:38] [C176] read error: Resource temporarily unavailable
[Envoy (Epoch 0)] [2020-06-02 20:13:34.626][30][debug][client] [external/envoy/source/common/http/codec_client.cc:127] [C176] protocol error: http/1.1 protocol error: unsupported transfer encoding`

**Comment by howardjohn** [comment]
This will be shipped out in 1.5.6 which should be out pretty soon - within a week or so, I am not sure the exact schedule though

**Comment by howardjohn** [comment]
Closing as I think this is fixed in all versions now. If not please reopen/open a new issue. Thanks!

**Comment by andrijaperovic** [comment]
@howardjohn this appears to be still broken in 1.6.5, please see my comment on istio/envoy:
https://github.com/envoyproxy/envoy/pull/10055#issuecomment-666867460
