### ISSUE TITLE
Istio 1.6.2 compatibility with AWS EKS in a multicluster shared control plane configuration

### ISSUE THREAD

**Issue by ghost** [istio/istio#24730]
**Bug description**
Out of the box, Istio 1.6.2 does not deploy successfully on AWS EKS. (I was able to get it working with a few small changes, but I'm not confident I fully understand all the implications, so I don't want to just submit a PR... I've included a diff below)

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Istio 1.6.2 would install according to the guide (https://istio.io/latest/docs/setup/install/multicluster/shared/) with no customisations to the charts.

**Steps to reproduce the bug**

Main cluster config: [main-config.yaml.txt](https://github.com/istio/istio/files/4790796/main-config.yaml.txt)

Remote cluster config: [remote-config.yaml.txt](https://github.com/istio/istio/files/4790798/remote-config.yaml.txt)

1. Create two EKS private clusters (i.e. cluster API and worker nodes are in private subnets, worker nodes can pull images from ECR via VPC endpoints).
2. Ensure that ECR has all the required Istio container images pushed to it.
3. Attempt to configure one cluster as the "main" and one as the "remote" cluster as per the guide.
4. You'll get an error when installing the main cluster:
```
✘ Istiod encountered an error: Service "istiod" is invalid: spec.ports: Invalid value: []core.ServicePort{core.ServicePort{Name:"grpc-xds", Protocol:"TCP", Port:15010, TargetPort:intstr.IntOrString{Type:0, IntVal:15010, StrVal:""}, NodePort:0}, core.Serv
icePort{Name:"https-dns", Protocol:"TCP", Port:15012, TargetPort:intstr.IntOrString{Type:0, IntVal:15012, StrVal:""}, NodePort:0}, core.ServicePort{Name:"https-webhook", Protocol:"TCP", Port:443, TargetPort:intstr.IntOrString{Type:0, IntVal:15017, StrVal
:""}, NodePort:0}, core.ServicePort{Name:"http-monitoring", Protocol:"TCP", Port:15014, TargetPort:intstr.IntOrString{Type:0, IntVal:15014, StrVal:""}, NodePort:0}, core.ServicePort{Name:"dns", Protocol:"UDP", Port:53, TargetPort:intstr.IntOrString{Type:
0, IntVal:15053, StrVal:""}, NodePort:0}, core.ServicePort{Name:"dns-tls", Protocol:"TCP", Port:853, TargetPort:intstr.IntOrString{Type:0, IntVal:15053, StrVal:""}, NodePort:0}}: cannot create an external load balancer with mix protocols
```
5. If you fix that (see diff below) you then get another error when installing the remote cluster:
```
✘ Istio core encountered an error: failed to create "Endpoints/istio-system/istiod-remote": Endpoints "istiod-remote" is invalid: [subsets[0].addresses[0].ip: Invalid value: "<nlb_name>.elb.<aws_region>.amazonaws.
com": must be a valid IP address, (e.g. 10.9.8.7), subsets[0].addresses[0].ip: Invalid value: "<nlb_name>.elb.<aws_region>.amazonaws.
com": must be a valid IP address]
```
6. If you fix that (again see diff below) then the remote cluster install hangs on the Addons step, because the istiod-remote service doesn't have the ExternalName set as it should.
```
$ kubectl describe service -n istio-system istiod-remote
Name:              istiod-remote
Namespace:         istio-system
Labels:            install.operator.istio.io/owning-resource=installed-state
                   operator.istio.io/component=Base
                   operator.istio.io/managed=Reconcile
                   operator.istio.io/version=1.6.2
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"install.operator.istio.io/owning-resource":"installed-state","...
Selector:          <none>
Type:              ClusterIP
IP:                None
Port:              tcp-istiod  15012/TCP
TargetPort:        15012/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```
7. If you fix that, everything works as expected.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
client version: 1.6.2
control plane version: 1.6.2
data plane version: 1.6.2 (16 proxies)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:40:13Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64
"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64
"}

```

**How was Istio installed?**
```
istioctl install -f main-config.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS 1.16

**My suggested fix**
I was able to get everything working by tweaking a few of the Istio manifests. And "EndPoint" should not be created if the remotePilotAddress is a DNS name (this seems to be a bug?) and an ExternalName should be added to the istiod-remote service (again this seems to be a bug).

Finally, because EKS doesn't support multi-protocol load balancers, I had to remove udp/53 from the list of ports for istiod - this isn't a bug so much as an EKS limitation, so perhaps a flag to disable this port could be added to the templates.

**git diff against branch release-1.6.2-patch showing what I had to change to get it working**
[istio-1.6.2-diff.txt](https://github.com/istio/istio/files/4790776/istio-1.6.2-diff.txt)

**Comment by erousseau-deloitte** [comment]
Potentially related issues:
https://github.com/istio/istio/issues/24596
https://github.com/istio/istio/issues/24081 (@costinm I assume your change didn't make it into the 1.6 release? Or is this actually a different issue)

**Comment by rverma-jm** [comment]
@erousseau-deloitte as per this https://istio.io/latest/docs/setup/install/multicluster/shared/#prerequisites, i am assuming that nonoverlapping service cidr is required. All eks clusters same service cidr. Can you tell your setup still worked with shared control pane??

**Comment by erousseau-deloitte** [comment]
Hi @rverma-jm  - I also noticed that requirement, but the mesh appears to function well even though the service CIDR ranges are the same. Note that in our configuration, each cluster is in a separate "network" (in the Istio mesh configuration sense) and communication with services in other clusters is done via an Istio ingress gateway.

**Comment by rcreasey** [comment]
This is also happening with private GKE clusters with a similar configuration as above with 1.6.3:

```
✘ Istiod encountered an error: failed to create "Service/istio-system/istiod": Service "istiod" is invalid: spec.ports: Invalid value: []core.ServicePort{core.ServicePort{Name:"grpc-xds", Protocol:"TCP", Port:15010, TargetPort:intstr.IntOrString{Type:0, IntVal:15010, StrVal:""}, NodePort:0}, core.ServicePort{Name:"https-dns", Protocol:"TCP", Port:15012, TargetPort:intstr.IntOrString{Type:0, IntVal:15012, StrVal:""}, NodePort:0}, core.ServicePort{Name:"https-webhook", Protocol:"TCP", Port:443, TargetPort:intstr.IntOrString{Type:0, IntVal:15017, StrVal:""}, NodePort:0}, core.ServicePort{Name:"http-monitoring", Protocol:"TCP", Port:15014, TargetPort:intstr.IntOrString{Type:0, IntVal:15014, StrVal:""}, NodePort:0}, core.ServicePort{Name:"dns", Protocol:"UDP", Port:53, TargetPort:intstr.IntOrString{Type:0, IntVal:15053, StrVal:""}, NodePort:0}, core.ServicePort{Name:"dns-tls", Protocol:"TCP", Port:853, TargetPort:intstr.IntOrString{Type:0, IntVal:15053, StrVal:""}, NodePort:0}}: cannot create an external load balancer with mix protocols
```

```
  components:
    pilot:
      k8s:
        service:
          type: LoadBalancer
        service_annotations:
          cloud.google.com/load-balancer-type: Internal
```

**Comment by rcreasey** [comment]
This is likely fixed by #25008

**Comment by dicksontung** [comment]
Still happening in 1.6.5, I generated the manifest, I think the issue with this:
```
export ISTIOD_REMOTE_EP=$(kubectl get svc -n istio-system --context=${MAIN_CLUSTER_CTX} istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
echo "ISTIOD_REMOTE_EP is ${ISTIOD_REMOTE_EP}"
```
This step wont get an IP of the AWS ELB. If we substitute it with the DNS name of AWS ELB, it breaks the Endpoint definition.
```
apiVersion: v1
kind: Endpoints
metadata:
  name: istiod-remote
  namespace: istio-system
subsets:
- addresses:
  - ip: <elb-name>.us-east-1.elb.amazonaws.com
  ports:
  - port: 15012
    name: tcp-istiod
```
This is invalid because it is an invalid ip address.
