### ISSUE TITLE
Envoy Proxy disconnects with applicaiton container for some conditions

### ISSUE THREAD

**Issue by kyaparla** [istio/istio#24753]
Envoy sidecar proxy is dropping connection with application container and causing this error with 503 status and UC response flag.  upstream connect error or disconnect/reset before headers. reset reason: connection termination, 

[X ] Networking
[X] Performance and Scalability

**Expected behavior**
Get 200 response for all requests.

**Steps to reproduce the bug**
Not sure,  it happens when request gets large data set from backend.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version --remote
client version: 1.6.2
control plane version: 1.6.2
data plane version: 1.6.2 (4 proxies)

**How was Istio installed?**
Istio Operator (default profile)

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS, 1.15

 We are seeing an issue with 1.5 istio version, where sidecar proxy is dropping connection with application container and causing this error with 503 status and UC response flag.  upstream connect error or disconnect/reset before headers. reset reason: connection termination,   Debug logs shows following error messages.  It's only happen when we try to get large data set from backend which is outside k8s cluster.  Response from backend is always 200, but the connection btw sidecar and application container drops with multiple retries.  We tried 1.6.2 version today, seeing same issue.  This is not happening in 1.2.2 version.   We also tried making the same request from with in pod from side proxy using localhost and it works fine,  issue is only when routed through envoy proxy.  Appreciate any pointers or help to resolve this issue.
[/http/codec_client.cc:127] [C61] protocol error: http/1.1 protocol error: unsupported transfer encoding
[/network/connection_impl.cc:101] [C61] closing data_to_write=0 type=1
[/network/connection_impl.cc:192] [C61] closing socket: 1
[/http/codec_client.cc:91] [C61] disconnect. resetting 1 pending requests
[/http/codec_client.cc:114] [C61] request reset
[/router/router.cc:990] [C59][S8598556017247194609] upstream reset: reset reason connection termination

More debug logs in envoy proxy:
2020-06-17T16:54:53.025416Z	debug	envoy client	[external/envoy/source/common/http/codec_client.cc:104] [C297] response complete
2020-06-17T16:54:53.026436Z	debug	envoy pool	[external/envoy/source/common/http/http1/conn_pool.cc:48] [C297] response complete
2020-06-17T16:54:53.026454Z	debug	envoy pool	[external/envoy/source/common/http/conn_pool_base.cc:93] [C297] destroying stream: 0 remaining
2020-06-17T16:54:53.026592Z	debug	envoy wasm	[external/envoy/source/extensions/common/wasm/context.cc:1100] wasm log stats_outbound: [extensions/stats/plugin.cc:629]::report() metricKey cache miss _istio_requests_total , stat=12
2020-06-17T16:54:53.026610Z	debug	envoy wasm	[external/envoy/source/extensions/common/wasm/context.cc:1100] wasm log stats_outbound: [extensions/stats/plugin.cc:629]::report() metricKey cache miss _istio_response_bytes , stat=6
2020-06-17T16:54:53.026770Z	debug	envoy client	[external/envoy/source/common/http/codec_client.cc:127] [C295] protocol error: http/1.1 protocol error: unsupported transfer encoding
2020-06-17T16:54:53.026783Z	debug	envoy connection	[external/envoy/source/common/network/connection_impl.cc:109] [C295] closing data_to_write=0 type=1
2020-06-17T16:54:53.026786Z	debug	envoy connection	[external/envoy/source/common/network/connection_impl.cc:200] [C295] closing socket: 1
2020-06-17T16:54:53.026834Z	debug	envoy client	[external/envoy/source/common/http/codec_client.cc:91] [C295] disconnect. resetting 1 pending requests
2020-06-17T16:54:53.026845Z	debug	envoy client	[external/envoy/source/common/http/codec_client.cc:114] [C295] request reset
2020-06-17T16:54:53.026856Z	debug	envoy router	[external/envoy/source/common/router/router.cc:1018] [C294][S17503853286743059635] upstream reset: reset reason connection termination
2020-06-17T16:54:53.026887Z	debug	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1475] [C294][S17503853286743059635] Sending local reply with details upstream_reset_before_response_started{connection termination}
2020-06-17T16:54:53.026927Z	debug	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1706] [C294][S17503853286743059635] encoding headers via codec (end_stream=false):

':status', '503'

'content-length', '95'

'content-type', 'text/plain'

'x-envoy-peer-metadata', 'ChoKCkNMVVNURVJfSUQSDBoKS3ViZXJuZXRlcwofCgxJTlNUQU5DRV9JUFMSDxoNMTAwLjY0LjEwLjIyMwqJBAoGTEFCRUxTEv4DKvsDChMKCmFkcC5jb20vZGMSBRoDYXdzChQKC2FkcC5jb20vZW52EgUaA2RpdAoZChBhZHAuY29tL2Vudi10eXBlEgUaA2RpdAohCg9hZHAuY29tL3Byb2plY3QSDhoMcmVsZWFzZS1uYW1lCiwKGmFwcC5rdWJlcm5ldGVzLmlvL2luc3RhbmNlEg4aDHJlbGVhc2UtbmFtZQooChxhcHAua3ViZXJuZXRlcy5pby9tYW5hZ2VkLWJ5EggaBlRpbGxlcgo2ChZhcHAua3ViZXJuZXRlcy5pby9uYW1lEhwaGm1pY3JvYXBpLXdvcmtlci1vcGVyYXRpb25zCioKDWhlbG0uc2gvY2hhcnQSGRoXd2ViLXNlcnZpY2UtaXN0aW8tMS4xLjAKGQoMaXN0aW8uaW8vcmV2EgkaB2RlZmF1bHQKIQoRcG9kLXRlbXBsYXRlLWhhc2gSDBoKNTZmODY0NGM1YwokChlzZWN1cml0eS5pc3Rpby5pby90bHNNb2RlEgcaBWlzdGlvCj8KH3NlcnZpY2UuaXN0aW8uaW8vY2Fub25pY2FsLW5hbWUSHBoabWljcm9hcGktd29ya2VyLW9wZXJhdGlvbnMKLwojc2VydmljZS5pc3Rpby5pby9jYW5vbmljYWwtcmV2aXNpb24SCBoGbGF0ZXN0ChoKB01FU0hfSUQSDxoNY2x1c3Rlci5sb2NhbAo1CgROQU1FEi0aK21pY3JvYXBpLXdvcmtlci1vcGVyYXRpb25zLTU2Zjg2NDRjNWMtczZwaHYKFgoJTkFNRVNQQUNFEgkaB3Zhbi1kaXQKXgoFT1dORVISVRpTa3ViZXJuZXRlczovL2FwaXMvYXBwcy92MS9uYW1lc3BhY2VzL3Zhbi1kaXQvZGVwbG95bWVudHMvbWljcm9hcGktd29ya2VyLW9wZXJhdGlvbnMKHAoPU0VSVklDRV9BQ0NPVU5UEgkaB2RlZmF1bHQKLQoNV09SS0xPQURfTkFNRRIcGhptaWNyb2FwaS13b3JrZXItb3BlcmF0aW9ucw=='

'x-envoy-peer-metadata-id', 'sidecar~100.64.10.223~microapi-worker-operations-56f8644c5c-s6phv.van-dit~van-dit.svc.cluster.local'

'date', 'Wed, 17 Jun 2020 16:54:52 GMT'

'server', 'istio-envoy'

2020-06-17T16:54:53.026948Z	debug	envoy filter	[src/envoy/http/authn/http_filter.cc:49] Called AuthenticationFilter : onDestroy
2020-06-17T16:54:53.026965Z	debug	envoy pool	[external/envoy/source/common/http/conn_pool_base.cc:265] [C295] client disconnected, failure reason: 
2020-06-17T16:54:53.027048Z	debug	envoy wasm	[external/envoy/source/extensions/common/wasm/context.cc:1100] wasm log stats_inbound: [extensions/stats/plugin.cc:612]::report() metricKey cache hit , stat=12
2020-06-17T16:54:53.027058Z	debug	envoy wasm	[external/envoy/source/extensions/common/wasm/context.cc:1100] wasm log stats_inbound: [extensions/stats/plugin.cc:612]::report() metricKey cache hit , stat=6
2020-06-17T16:54:53.027062Z	debug	envoy wasm	[external/envoy/source/extensions/common/wasm/context.cc:1100] wasm log stats_inbound: [extensions/stats/plugin.cc:612]::report() metricKey cache hit , stat=10
2020-06-17T16:54:53.027065Z	debug	envoy wasm	[external/envoy/source/extensions/common/wasm/context.cc:1100] wasm log stats_inbound: [extensions/stats/plugin.cc:612]::report() metricKey cache hit , stat=14
2020-06-17T16:54:53.027103Z	debug	envoy pool	[external/envoy/source/common/http/conn_pool_base.cc:93] [C295] destroying stream: 0 remaining
2020-06-17T16:54:53.027322Z	debug	envoy connection	[external/envoy/source/common/network/connection_impl.cc:558] [C294] remote close
2020-06-17T16:54:53.027333Z	debug	envoy connection	[external/envoy/source/common/network/connection_impl.cc:200] [C294] closing socket: 0
2020-06-17T16:54:53.027370Z	debug	envoy connection	[external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:298] [C294] SSL shutdown: rc=1
2020-06-17T16:54:53.027375Z	debug	envoy connection	[external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:226] [C294] 
2020-06-17T16:54:53.027389Z	debug	envoy conn_handler	[external/envoy/source/server/connection_handler_impl.cc:111] [C294] adding to cleanup list
2020-06-17T16:54:53.029577Z	debug	envoy wasm	[external/envoy/source/extensions/common/wasm/context.cc:1100] wasm log stats_outbound: [extensions/stats/plugin.cc:629]::report() metricKey cache miss _istio_request_duration_milliseconds , stat=10
2020-06-17T16:54:53.031995Z	debug	envoy filter	[external/envoy/source/extensions/filters/listener/original_dst/original_dst.cc:18] original_dst: New connection accepted
2020-06-17T16:54:53.032017Z	debug	envoy filter	[external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:78] tls inspector: new connection accepted
2020-06-17T16:54:53.032072Z	debug	envoy filter	[external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:148] tls:onServerName(), requestedServerName: outbound_.8080_._.microapi-worker-operations.van-dit.svc.cluster.local
2020-06-17T16:54:53.032085Z	debug	envoy filter	[external/envoy/source/extensions/filters/listener/http_inspector/http_inspector.cc:37] http inspector: new connection accepted
2020-06-17T16:54:53.032133Z	debug	envoy conn_handler	[external/envoy/source/server/connection_handler_impl.cc:403] [C298] new connection
2020-06-17T16:54:53.032286Z	debug	envoy connection	[external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:191] [C298] handshake expecting read
2020-06-17T16:54:53.032297Z	debug	envoy connection	[external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:191] [C298] handshake expecting read
2020-06-17T16:54:53.032410Z	debug	envoy connection	[external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:176] [C298] handshake complete
2020-06-17T16:54:53.032499Z	debug	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:268] [C298] new stream
2020-06-17T16:54:53.032564Z	debug	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:781] [C298][S5686435881520010723] request headers complete (end_stream=true):

':authority', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx'

':path', '/hr/v2/workers?$top=47'

':method', 'GET'

'user-agent', 'curl/7.50.3'

'accept', 'application/json'

'acsgroups', '%LDAP%'

'sm_transactionid', '1234567'

'x-forwarded-for', '10.204.127.106'

'x-forwarded-proto', 'http'

'x-envoy-internal', 'true'

'x-request-id', '53189ebd-b390-96bb-9bbb-96c8d7dcbd0e'

'x-envoy-decorator-operation', 'microapi-worker-operations.van-dit.svc.cluster.local:8080/microapi-worker-operations/1/xyz/*'

'x-envoy-peer-metadata', 'ChoKCkNMVVNURVJfSUQSDBoKS3ViZXJuZXRlcwoeCgxJTlNUQU5DRV9JUFMSDhoMMTAwLjY0LjEyLjI1CpYCCgZMQUJFTFMSiwIqiAIKHQoDYXBwEhYaFGlzdGlvLWluZ3Jlc3NnYXRld2F5ChMKBWNoYXJ0EgoaCGdhdGV3YXlzChQKCGhlcml0YWdlEggaBlRpbGxlcgoZCgVpc3RpbxIQGg5pbmdyZXNzZ2F0ZXdheQohChFwb2QtdGVtcGxhdGUtaGFzaBIMGgo2YzliY2RmYjlkChIKB3JlbGVhc2USBxoFaXN0aW8KOQofc2VydmljZS5pc3Rpby5pby9jYW5vbmljYWwtbmFtZRIWGhRpc3Rpby1pbmdyZXNzZ2F0ZXdheQovCiNzZXJ2aWNlLmlzdGlvLmlvL2Nhbm9uaWNhbC1yZXZpc2lvbhIIGgZsYXRlc3QKGgoHTUVTSF9JRBIPGg1jbHVzdGVyLmxvY2FsCi8KBE5BTUUSJxolaXN0aW8taW5ncmVzc2dhdGV3YXktNmM5YmNkZmI5ZC1yNmw2agobCglOQU1FU1BBQ0USDhoMaXN0aW8tc3lzdGVtCl0KBU9XTkVSElQaUmt1YmVybmV0ZXM6Ly9hcGlzL2FwcHMvdjEvbmFtZXNwYWNlcy9pc3Rpby1zeXN0ZW0vZGVwbG95bWVudHMvaXN0aW8taW5ncmVzc2dhdGV3YXkKpwEKEVBMQVRGT1JNX01FVEFEQVRBEpEBKo4BCiAKDmF3c19hY2NvdW50X2lkEg4aDDgzODAxMDkwNDQ5MwolChVhd3NfYXZhaWxhYmlsaXR5X3pvbmUSDBoKdXMtZWFzdC0xYQooCg9hd3NfaW5zdGFuY2VfaWQSFRoTaS0wNzhmYTYwYzBjNjc3ODBlNQoZCgphd3NfcmVnaW9uEgsaCXVzLWVhc3QtMQo5Cg9TRVJWSUNFX0FDQ09VTlQSJhokaXN0aW8taW5ncmVzc2dhdGV3YXktc2VydmljZS1hY2NvdW50CicKDVdPUktMT0FEX05BTUUSFhoUaXN0aW8taW5ncmVzc2dhdGV3YXk='

'x-envoy-peer-metadata-id', 'router~100.64.12.25~istio-ingressgateway-6c9bcdfb9d-r6l6j.istio-system~istio-system.svc.cluster.local'

'x-envoy-expected-rq-timeout-ms', '50000'

'x-b3-traceid', 'e8d7653e211045ebf7cad02b32970102'

'x-b3-spanid', 'f7cad02b32970102'

'x-b3-sampled', '1'

'x-envoy-original-path', '/microapi-worker-operations/1/abcd/hr/v2/workers?$top=47'

'content-length', '0'

**Comment by howardjohn** [comment]
Similar to https://github.com/istio/istio/issues/23020 but should be fixed in this version...

**Comment by kyaparla** [comment]
@howardjohn I tested our service with 1.5.6 and also 1.6.2 version,  and still seeing this issue.  I can confirm that its not happening with 1.4.6 version.

**Comment by lambdai** [comment]
@kyaparla Could you enable the trace log on http topic?
`kubectl exec -it pod/<POD> -- curl -X POST localhost:15000/logging?http=trace`
I have something below. the `completed header: key=transfer-encoding` should be a little bit above the http1.1 protocol error.

Looks like envoy support only "chunked". No other values are allowed. It shouldn't be a issue with default istio config.

Let's figure out the transfer-encoding value and see.

```
2020-06-22T23:29:32.265768Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:470] [C22] parsing 91926 bytes
2020-06-22T23:29:32.265775Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:672] [C22] message begin
2020-06-22T23:29:32.265785Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C22] completed header: key=content-type value=text/plain; charset=UTF-8
2020-06-22T23:29:32.265793Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C22] completed header: key=cache-control value=no-cache, max-age=0
2020-06-22T23:29:32.265799Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C22] completed header: key=x-content-type-options value=nosniff
2020-06-22T23:29:32.265805Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C22] completed header: key=date value=Mon, 22 Jun 2020 23:29:32 GMT
2020-06-22T23:29:32.265809Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C22] completed header: key=server value=envoy
2020-06-22T23:29:32.265815Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:573] [C22] onHeadersCompleteBase
2020-06-22T23:29:32.265819Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C22] completed header: key=transfer-encoding value=chunked
2020-06-22T23:29:32.265826Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:986] [C22] Client: onHeadersComplete size=6
```

**Comment by kyaparla** [comment]
@lambdai  Here is the trace log.

2020-06-23T21:40:36.630160Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1827] [C529][S13945774491571653993] encode data called: filter=0x55ff03dc9e00 status=0
2020-06-23T21:40:36.630165Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1827] [C529][S13945774491571653993] encode data called: filter=0x55ff03b0eb40 status=0
2020-06-23T21:40:36.630168Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1827] [C529][S13945774491571653993] encode data called: filter=0x55ff03dfba90 status=0
2020-06-23T21:40:36.630170Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1827] [C529][S13945774491571653993] encode data called: filter=0x55ff033b1720 status=0
2020-06-23T21:40:36.630173Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1853] [C529][S13945774491571653993] encoding data via codec (size=8370 end_stream=false)
2020-06-23T21:40:36.630177Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:497] [C482] parsed 8702 bytes
2020-06-23T21:40:36.631142Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:470] [C528] parsing 8192 bytes
2020-06-23T21:40:36.631152Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:672] [C528] message begin
2020-06-23T21:40:36.631157Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=Vary value=Origin
2020-06-23T21:40:36.631162Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=Vary value=Access-Control-Request-Method
2020-06-23T21:40:36.631165Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=Vary value=Access-Control-Request-Headers
2020-06-23T21:40:36.631168Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=server value=envoy
2020-06-23T21:40:36.631171Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=expires value=Tues, 01 Jan 1980 00:00:00 GMT
2020-06-23T21:40:36.631174Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=last-modified value=Tue, 23 Jun 2020 21:40:36 GMT
2020-06-23T21:40:36.631177Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=content-language value=en_US
2020-06-23T21:40:36.631181Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=cache-control value=no-cache
2020-06-23T21:40:36.631185Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=date value=Tue, 23 Jun 2020 21:40:36 GMT
2020-06-23T21:40:36.631189Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=x-envoy-upstream-service-time value=1353
2020-06-23T21:40:36.631195Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=transfer-encoding value=chunked
2020-06-23T21:40:36.631200Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=Content-Type value=application/json
2020-06-23T21:40:36.631204Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:573] [C528] onHeadersCompleteBase
2020-06-23T21:40:36.631207Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=Transfer-Encoding value=chunked
2020-06-23T21:40:36.631231Z	debug	envoy client	[external/envoy/source/common/http/codec_client.cc:127] [C528] protocol error: http/1.1 protocol error: unsupported transfer encoding
2020-06-23T21:40:36.631237Z	debug	envoy connection	[external/envoy/source/common/network/connection_impl.cc:109] [C528] closing data_to_write=0 type=1
2020-06-23T21:40:36.631239Z	debug	envoy connection	[external/envoy/source/common/network/connection_impl.cc:200] [C528] closing socket: 1
2020-06-23T21:40:36.631260Z	debug	envoy client	[external/envoy/source/common/http/codec_client.cc:91] [C528] disconnect. resetting 1 pending requests
2020-06-23T21:40:36.631267Z	debug	envoy client	[external/envoy/source/common/http/codec_client.cc:114] [C528] request reset
2020-06-23T21:40:36.631297Z	debug	envoy router	[external/envoy/source/common/router/router.cc:1018] [C527][S18312929050256593281] upstream reset: reset reason connection termination
2020-06-23T21:40:36.631318Z	debug	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1475] [C527][S18312929050256593281] Sending local reply with details upstream_reset_before_response_started{connection termination}
2020-06-23T21:40:36.631329Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1565] [C527][S18312929050256593281] encode headers called: filter=0x55ff03412b40 status=0
2020-06-23T21:40:36.631333Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1565] [C527][S18312929050256593281] encode headers called: filter=0x55ff03c2c320 status=0
2020-06-23T21:40:36.631336Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1565] [C527][S18312929050256593281] encode headers called: filter=0x55ff03dfaa50 status=0
2020-06-23T21:40:36.631345Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1565] [C527][S18312929050256593281] encode headers called: filter=0x55ff0436dc70 status=0
2020-06-23T21:40:36.631361Z	debug	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1706] [C527][S18312929050256593281] encoding headers via codec (end_stream=false):

':status', '503'

'content-length', '95'

'content-type', 'text/plain'

'x-envoy-peer-metadata', 'ChoKCkNMVVNURVJfSUQSDBoKS3ViZXJuZXRlcwofCgxJTlNUQU5DRV9JUFMSDxoNMTAwLjY0LjQwLjE4NwqJBAoGTEFCRUxTEv4DKvsDChMKCmFkcC5jb20vZGMSBRoDYXdzChQKC2FkcC5jb20vZW52EgUaA2RpdAoZChBhZHAuY29tL2Vudi10eXBlEgUaA2RpdAohCg9hZHAuY29tL3Byb2plY3QSDhoMcmVsZWFzZS1uYW1lCiwKGmFwcC5rdWJlcm5ldGVzLmlvL2luc3RhbmNlEg4aDHJlbGVhc2UtbmFtZQooChxhcHAua3ViZXJuZXRlcy5pby9tYW5hZ2VkLWJ5EggaBlRpbGxlcgo2ChZhcHAua3ViZXJuZXRlcy5pby9uYW1lEhwaGm1pY3JvYXBpLXdvcmtlci1vcGVyYXRpb25zCioKDWhlbG0uc2gvY2hhcnQSGRoXd2ViLXNlcnZpY2UtaXN0aW8tMS4xLjAKGQoMaXN0aW8uaW8vcmV2EgkaB2RlZmF1bHQKIQoRcG9kLXRlbXBsYXRlLWhhc2gSDBoKN2Q2YmNkZmY0NAokChlzZWN1cml0eS5pc3Rpby5pby90bHNNb2RlEgcaBWlzdGlvCj8KH3NlcnZpY2UuaXN0aW8uaW8vY2Fub25pY2FsLW5hbWUSHBoabWljcm9hcGktd29ya2VyLW9wZXJhdGlvbnMKLwojc2VydmljZS5pc3Rpby5pby9jYW5vbmljYWwtcmV2aXNpb24SCBoGbGF0ZXN0ChoKB01FU0hfSUQSDxoNY2x1c3Rlci5sb2NhbAo1CgROQU1FEi0aK21pY3JvYXBpLXdvcmtlci1vcGVyYXRpb25zLTdkNmJjZGZmNDQtdHJnamcKFgoJTkFNRVNQQUNFEgkaB3Zhbi1kaXQKXgoFT1dORVISVRpTa3ViZXJuZXRlczovL2FwaXMvYXBwcy92MS9uYW1lc3BhY2VzL3Zhbi1kaXQvZGVwbG95bWVudHMvbWljcm9hcGktd29ya2VyLW9wZXJhdGlvbnMKHAoPU0VSVklDRV9BQ0NPVU5UEgkaB2RlZmF1bHQKLQoNV09SS0xPQURfTkFNRRIcGhptaWNyb2FwaS13b3JrZXItb3BlcmF0aW9ucw=='

'x-envoy-peer-metadata-id', 'sidecar~100.64.40.187~microapi-worker-operations-7d6bcdff44-trgjg.van-dit~van-dit.svc.cluster.local'

'date', 'Tue, 23 Jun 2020 21:40:36 GMT'

'server', 'istio-envoy'


2020-06-23T21:40:36.631375Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1827] [C527][S18312929050256593281] encode data called: filter=0x55ff03412b40 status=0
2020-06-23T21:40:36.631380Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1827] [C527][S18312929050256593281] encode data called: filter=0x55ff03c2c320 status=0
2020-06-23T21:40:36.631382Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1827] [C527][S18312929050256593281] encode data called: filter=0x55ff03dfaa50 status=0
2020-06-23T21:40:36.631385Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1827] [C527][S18312929050256593281] encode data called: filter=0x55ff0436dc70 status=0
2020-06-23T21:40:36.631387Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1853] [C527][S18312929050256593281] encoding data via codec (size=95 end_stream=true)
2020-06-23T21:40:36.631394Z	debug	envoy filter	[src/envoy/http/authn/http_filter.cc:49] Called AuthenticationFilter : onDestroy
2020-06-23T21:40:36.631409Z	debug	envoy pool	[external/envoy/source/common/http/conn_pool_base.cc:265] [C528] client disconnected, failure reason: 
2020-06-23T21:40:36.631477Z	debug	envoy wasm	[external/envoy/source/extensions/common/wasm/context.cc:1100] wasm log stats_inbound: [extensions/stats/plugin.cc:612]::report() metricKey cache hit , stat=12
2020-06-23T21:40:36.631486Z	debug	envoy wasm	[external/envoy/source/extensions/common/wasm/context.cc:1100] wasm log stats_inbound: [extensions/stats/plugin.cc:612]::report() metricKey cache hit , stat=6
2020-06-23T21:40:36.631490Z	debug	envoy wasm	[external/envoy/source/extensions/common/wasm/context.cc:1100] wasm log stats_inbound: [extensions/stats/plugin.cc:612]::report() metricKey cache hit , stat=10
2020-06-23T21:40:36.631494Z	debug	envoy wasm	[external/envoy/source/extensions/common/wasm/context.cc:1100] wasm log stats_inbound: [extensions/stats/plugin.cc:612]::report() metricKey cache hit , stat=14
2020-06-23T21:40:36.631526Z	debug	envoy pool	[external/envoy/source/common/http/conn_pool_base.cc:93] [C528] destroying stream: 0 remaining
2020-06-23T21:40:36.632297Z	debug	envoy connection	[external/envoy/source/common/network/connection_impl.cc:558] [C527] remote close
2020-06-23T21:40:36.632303Z	debug	envoy connection	[external/envoy/source/common/network/connection_impl.cc:200] [C527] closing socket: 0
2020-06-23T21:40:36.632323Z	debug	envoy connection	[external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:298] [C527] SSL shutdown: rc=1
2020-06-23T21:40:36.632326Z	debug	envoy connection	[external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:226] [C527] 
2020-06-23T21:40:36.632345Z	debug	envoy conn_handler	[external/envoy/source/server/connection_handler_impl.cc:111] [C527] adding to cleanup list
2020-06-23T21:40:36.640113Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:470] [C482] parsing 5915 bytes
2020-06-23T21:40:36.640131Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1827] [C529][S13945774491571653993] encode data called: filter=0x55ff03dc9e00 status=0
2020-06-23T21:40:36.640134Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1827] [C529][S13945774491571653993] encode data called: filter=0x55ff03b0eb40 status=0
2020-06-23T21:40:36.640136Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1827] [C529][S13945774491571653993] encode data called: filter=0x55ff03dfba90 status=0
2020-06-23T21:40:36.640139Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1827] [C529][S13945774491571653993] encode data called: filter=0x55ff033b1720 status=0
2020-06-23T21:40:36.640142Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1853] [C529][S13945774491571653993] encoding data via codec (size=5900 end_stream=false)
2020-06-23T21:40:36.640148Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:497] [C482] parsed 5915 bytes
2020-06-23T21:40:36.640295Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:470] [C482] parsing 4470 bytes

**Comment by lambdai** [comment]
Thanks for the update! It's petty clear that there are duplicated transfer-encoding since http headers are case-insensitive.
```
2020-06-23T21:40:36.631195Z trace envoy http [external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=transfer-encoding value=chunked
...
2020-06-23T21:40:36.631207Z trace envoy http [external/envoy/source/common/http/http1/codec_impl.cc:433] [C528] completed header: key=Transfer-Encoding value=chunked
```
IIRC envoy would do concatenation on duplicate headers: so the value is "chunked, chunked".

Confirmed on 1.6.2

**Comment by lambdai** [comment]
Can you confirm the next hop which directly respond duplicated Transfer-Encoding? Is it another envoy? If it's envoy, is it 1.6.2 or 1.5.6?

I could not reproduce: If the upstream of envoy responds either "Transfer-Encoding" or "transfer-encoding", envoy doesn't generate duplicated these headers as in above logs.

**Comment by kyaparla** [comment]
@lambdai 

This was collected from 1.6.2 version.  Are there any changes to envoy proxy around headers between 1.4 and 1.5 that could impact this?  We are thinking of using 1.4.6 version, as it supports service entries, and with out this particular issue.

Request flow is as follows.

inbound request through envoy proxy to the application,  application make outbound request to outside k8s cluster ( tried through service entry & direct ).  When payload size is big inbound request fails with 503 response,  but outbound request is always 200.

Here is the flow.

Route53->elb->ingress gateway->envoy proxy-> application -> egress->outbound->external service

Please let me know, for additional information.

**Comment by kyaparla** [comment]
@lambdai 

Tested enabling http trace on Istio 1.4.6, with same service and I dont see Transfer encoding: chunked text.  Is this something new with Istio 1.5?  

Is this an issue with Istio or the application doing some thing not supported by Istio?

**Comment by lambdai** [comment]
There is no intended behavior change regarding to handle `Transfer-Encoding: chunked`.

As we can see in http trace, it means envoy received duplicated `Transfer-Encoding`. Can you figure out the first hop *producing* the duplicated `Transfer-Encoding`?

**Comment by kyaparla** [comment]
@lambdai 

I see ingressgateway http trace shows only 1 header,  with small case.  Next hop from here is side car proxy right?  Does side car introduces another header?

Do we have to find out where below header is coming from?

http/http1/codec_impl.cc:433] [C905872] completed header: key=server value=istio-envoy
http/http1/codec_impl.cc:573] [C905872] onHeadersCompleteBase
http/http1/codec_impl.cc:433] [C905872] completed header: key=transfer-encoding value=chunked
http/http1/codec_impl.cc:986] [C905872] Client: onHeadersComplete size=11

**Comment by lambdai** [comment]
"server: istio-envoy" says so. Unless you have a manipulated process pretending to be envoy.


However, when I setup an istio-envoy inside istio 1.6.2 and 1.5.6, that envoy doesn't produce 2 "transfer-encoding"
```
curl <-> envoy(1.5.6 or 1.6.2) <-> "nc -l"
```
nc is introduced so that I can feed http 200 with my own "transfer-encoding", lower case or upper case. That envoy could either abort when I produce double transfer-encoding from nc(which is what saw in your istio-ingressgateway), or that envoy produces single `Transfer-Encoding" header.

**Comment by kyaparla** [comment]
@lambdai 

We enabled further debugging,  and found that the backend,  our service is interacting with is returning this header and our application is setting these headers and returning the response.  We modified our code to delete transfer-encoding header, and see the issue is not happening.

Wanted to understand more,  on why this is working in versions < 1.5, but breaks from versions > 1.5.  And also if the headers are case insensitive, shouldnt it do dedup and consider only 1 header instead of 2?

**Comment by lambdai** [comment]
@kyaparla Great to see you resolve it! Thank you for the update.

Back to topic of istio's behavior. Istio dataplane is all in envoyproxy. Envoy was improving the performance of http header operations and I believe some regressions are accidentally introduced. #23020 is one of them. I believe you are reporting anther one.

I agree with you that duplicate `chunked` is not ideal but should not fail the http request. I see curl doesn't report error. Earlier version envoy didn't report either.

The follow up: I will fix the upstream envoy.

**Comment by lambdai** [comment]
@kyaparla Discussed in https://github.com/envoyproxy/envoy/pull/11916
And envoy won't add the tolerance back. Because
1. two `transfer-encoding: chunked` is equivalent to `transfer-encoding: chunked, chunked` as per RFC
2.  `transfer-encoding: chunked, chunked` doesn't have the same semantic as `transfer-encoding: chunked`
3. Before your fix, the body in your http response is actually should be decoded by `transfer-encoding: chunked` but you are sending  `transfer-encoding: chunked, chunked`

We know

**Comment by lambdai** [comment]
tl;dr 
`chunked, chunked` should not be considered "chunked" although it happens to resolve the failure. 
Close if for now.
We can raise another discussion if there overwhelming cases

**Comment by kyaparla** [comment]
> tl;dr
> `chunked, chunked` should not be considered "chunked" although it happens to resolve the failure.
> Close if for now.
> We can raise another discussion if there overwhelming cases

@lambdai 

Just looking for more details on what changed between 1.4 and 1.5 versions,  that introduced this?  Was transfer-encoding being interpreted differently before 1.5?

**Comment by atcjunior** [comment]
Hi guys,

I've tested istio from versions 1.6.0 to 1.6.8 and happens the same issue when header has **Transfer-Encoding:chunked**.
I've set **reject_unsupported_transfer_encodings = false** on proxy as workaround and the issue is temporarily solved.
```
## Set envoy feature ##
kubectl exec istio-ingressgateway-XXXXXXX-- \
curl -X POST http://localhost:15000/runtime_modify?envoy.reloadable_features.reject_unsupported_transfer_encodings=false
```

Is that behaviour expected when connection is HTTP 1.1 ?
Is that a envoy bug ?
Is there any solution I could apply on istio to have this solved ?

**## Proxy trace ##**

2020-08-14T11:35:02.046161Z     debug   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:268] [C809] new stream
2020-08-14T11:35:02.046177Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C809] completed header: key=host value=istio-app-test.mydomain.com.br
2020-08-14T11:35:02.046182Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C809] completed header: key=Accept value=*/*
2020-08-14T11:35:02.046186Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C809] completed header: key=Authorization value=Bearer oprt314h8ufosus2q89849024927uj
2020-08-14T11:35:02.046190Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C809] completed header: key=Content-Type value=application/json
2020-08-14T11:35:02.046194Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C809] completed header: key=User-Agent value=curl/7.69.1
2020-08-14T11:35:02.046199Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C809] completed header: key=X-Forwarded-For value=X.X.X.X
2020-08-14T11:35:02.046204Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C809] completed header: key=X-Forwarded-Port value=80
2020-08-14T11:35:02.046207Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C809] completed header: key=X-Forwarded-Proto value=http
2020-08-14T11:35:02.046210Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C809] completed header: key=Content-Length value=87
2020-08-14T11:35:02.046214Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:573] [C809] onHeadersCompleteBase
2020-08-14T11:35:02.046220Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C809] completed header: key=Connection value=keep-alive
2020-08-14T11:35:02.046226Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:771] [C809] Server: onHeadersComplete size=10
2020-08-14T11:35:02.046252Z     debug   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:781] [C809][S11663957191911470421] request headers complete (end_stream=false):
':authority', 'istio-app-test.mydomain.com.br'
':path', '/api/core/v1/my-app/search'
':method', 'POST'
'accept', '*/*'
'authorization', 'Bearer oprt314h8ufosus2q89849024927uj'
'content-type', 'application/json'
'user-agent', 'curl/7.69.1'
'x-forwarded-for', 'X.X.X.X'
'x-forwarded-port', '80'
'x-forwarded-proto', 'http'
'content-length', '87'
'connection', 'keep-alive'

2020-08-14T11:35:02.046337Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1042] [C809][S11663957191911470421] decode headers called: filter=0x55c0ab4695c0 status=0
2020-08-14T11:35:02.046350Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1042] [C809][S11663957191911470421] decode headers called: filter=0x55c0ab070540 status=0
2020-08-14T11:35:02.046356Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1042] [C809][S11663957191911470421] decode headers called: filter=0x55c0ab0707e0 status=0
2020-08-14T11:35:02.046361Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1042] [C809][S11663957191911470421] decode headers called: filter=0x55c0ab48ad80 status=0
2020-08-14T11:35:02.046488Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1042] [C809][S11663957191911470421] decode headers called: filter=0x55c0ab07eae0 status=1
2020-08-14T11:35:02.046501Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:649] [C809] message complete
2020-08-14T11:35:02.046504Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:851] [C809] body size=87
2020-08-14T11:35:02.046508Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1181] [C809][S11663957191911470421] decode data called: filter=0x55c0ab4695c0 status=0
2020-08-14T11:35:02.046511Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1181] [C809][S11663957191911470421] decode data called: filter=0x55c0ab070540 status=0
2020-08-14T11:35:02.046513Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1181] [C809][S11663957191911470421] decode data called: filter=0x55c0ab0707e0 status=0
2020-08-14T11:35:02.046516Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1181] [C809][S11663957191911470421] decode data called: filter=0x55c0ab48ad80 status=0
2020-08-14T11:35:02.046522Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1181] [C809][S11663957191911470421] decode data called: filter=0x55c0ab07eae0 status=3
2020-08-14T11:35:02.046530Z     debug   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1333] [C809][S11663957191911470421] request end stream
2020-08-14T11:35:02.046532Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1181] [C809][S11663957191911470421] decode data called: filter=0x55c0ab4695c0 status=0
2020-08-14T11:35:02.046535Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1181] [C809][S11663957191911470421] decode data called: filter=0x55c0ab070540 status=0
2020-08-14T11:35:02.046537Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1181] [C809][S11663957191911470421] decode data called: filter=0x55c0ab0707e0 status=0
2020-08-14T11:35:02.046539Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1181] [C809][S11663957191911470421] decode data called: filter=0x55c0ab48ad80 status=0
2020-08-14T11:35:02.046542Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1181] [C809][S11663957191911470421] decode data called: filter=0x55c0ab07eae0 status=3
2020-08-14T11:35:02.046545Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:497] [C809] parsed 442 bytes
2020-08-14T11:35:02.404644Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:470] [C862] parsing 6378 bytes
2020-08-14T11:35:02.404669Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:672] [C862] message begin
2020-08-14T11:35:02.404681Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Vary value=Origin
2020-08-14T11:35:02.404688Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Vary value=Access-Control-Request-Method
2020-08-14T11:35:02.404691Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Vary value=Access-Control-Request-Headers
2020-08-14T11:35:02.404693Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Date value=Fri, 14 Aug 2020 11:35:02 GMT
2020-08-14T11:35:02.404697Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Transfer-Encoding value=chunked
2020-08-14T11:35:02.404703Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Connection value=keep-alive
2020-08-14T11:35:02.404708Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Expires value=Thu, 19 Nov 1981 08:52:00 GMT
2020-08-14T11:35:02.404712Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Cache-Control value=no-store, no-cache, must-revalidate
2020-08-14T11:35:02.404717Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Pragma value=no-cache
2020-08-14T11:35:02.404721Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Set-Cookie value=PHPSESSID=oj7s29ot4f4ckhduu5e2vgv090; expires=Fri, 14-Aug-2020 12:35:01 GMT; Max-Age=3600; path=/; domain=api-app.mydomain.com.br; HttpOnly
2020-08-14T11:35:02.404726Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=X-Frame-Options value=SAMEORIGIN
2020-08-14T11:35:02.404729Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Vary value=Accept-Encoding
2020-08-14T11:35:02.404732Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=X-Store value=desktop
2020-08-14T11:35:02.404736Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=X-Device value=desktop
2020-08-14T11:35:02.404739Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=X-Result value=desktopdesktop
2020-08-14T11:35:02.404760Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Content-Type value=application/json;charset=utf-8
2020-08-14T11:35:02.404765Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:573] [C862] onHeadersCompleteBase
2020-08-14T11:35:02.404767Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Transfer-Encoding value=chunked
2020-08-14T11:35:02.404882Z     debug   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1475] [C809][S11663957191911470421] Sending local reply with details upstream_reset_before_response_started{connection termination}
2020-08-14T11:35:02.404899Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1565] [C809][S11663957191911470421] encode headers called: filter=0x55c0ab39a4b0 status=0
2020-08-14T11:35:02.404903Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1565] [C809][S11663957191911470421] encode headers called: filter=0x55c0ab2153b0 status=0
2020-08-14T11:35:02.404907Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1565] [C809][S11663957191911470421] encode headers called: filter=0x55c0aae84730 status=0
2020-08-14T11:35:02.404915Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1565] [C809][S11663957191911470421] encode headers called: filter=0x55c0ab41b900 status=0
2020-08-14T11:35:02.404939Z     debug   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1706] [C809][S11663957191911470421] encoding headers via codec (end_stream=false):
':status', '503'
'content-length', '95'
'content-type', 'text/plain'
'date', 'Fri, 14 Aug 2020 11:35:02 GMT'
'server', 'istio-envoy'

2020-08-14T11:35:02.404953Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1827] [C809][S11663957191911470421] encode data called: filter=0x55c0ab39a4b0 status=0
2020-08-14T11:35:02.404956Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1827] [C809][S11663957191911470421] encode data called: filter=0x55c0ab2153b0 status=0
2020-08-14T11:35:02.404958Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1827] [C809][S11663957191911470421] encode data called: filter=0x55c0aae84730 status=0
2020-08-14T11:35:02.404961Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1827] [C809][S11663957191911470421] encode data called: filter=0x55c0ab41b900 status=0
2020-08-14T11:35:02.404964Z     trace   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1853] [C809][S11663957191911470421] encoding data via codec (size=95 end_stream=true)
2020-08-14T11:35:02.482192Z     trace   envoy http      [external/envoy/source/common/http/http1/codec_impl.cc:470] [C863] parsing 128 bytes

**Comment by lambdai** [comment]
@atcjunior 

> I've set reject_unsupported_transfer_encodings = false on proxy as workaround and the issue is temporarily solved.

Thank you for the workaround! Please fix the upstream http app which populate double chucked at high priority. Envoy is removing the reject_unsupported_transfer_encodings [soon](https://www.envoyproxy.io/docs/envoy/latest/version_history/current)
AFAIK some user report Tomcat cors plugin is a potential culprit but I didn't verify.

Your pasted log shows this is **double** "chunked". See the below explanation. It's the **double** which is illegal. 
A single "Transfer-Encoding:chunked" is fine.
 
```
2020-08-14T11:35:02.404669Z trace envoy http [external/envoy/source/common/http/http1/codec_impl.cc:672] [C862] message begin
...
2020-08-14T11:35:02.404697Z trace envoy http [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Transfer-Encoding value=chunked
...
2020-08-14T11:35:02.404765Z trace envoy http [external/envoy/source/common/http/http1/codec_impl.cc:573] [C862] onHeadersCompleteBase
## The log line right below onHeadersCompleteBase is the last header
2020-08-14T11:35:02.404767Z trace envoy http [external/envoy/source/common/http/http1/codec_impl.cc:433] [C862] completed header: key=Transfer-Encoding value=chunked
```
So this is `Transfer-Encoding: chunked` twice in same http response.
According to the RFC this line appeared twice has the exact same semantic of "Transfer-Encoding: chunked, chunked`.

To avoid future confusing let's refer it as multiple-chunked regardless it's literal "chunked, chunked" or duplicated "Transfer-Encoding: chunked" :)

**Comment by niuqg** [comment]
The same response, curl reports no error. curl has better fault tolerance？

**Comment by jbilliau-rcd** [comment]
We just spent 4 hours troubleshooting a very similiar problem like this, but there were no duplicate values at all. Just the presence of `transfer-encoding: chunked` alone broke Istio. We have an API that, when hit, calls out to another API to get some information. The response headers from that upstream API include `transfer-encoding: chunked`, just once, no duplicates. 

If I port-forwarded to the pod and hit it on localhost, it works fine. If i hit it externally so traffic flows through sidecar, app gets the request, seemingly processes it just fine, but envoy shows a 502 UPE for every request. Only solution was to remove the header in code.

It seems crazy that something so trivial could blow up Envoy/Istio. Is there no solution to this?

**Comment by tommyforlini** [comment]
What if we don't have access to the source code ? What then?
Doesn't seem that VirtualService remove header helps either.

**Comment by howardjohn** [comment]
declare the protocol as "TCP" and it won't try to parse it as http
