### ISSUE TITLE
Istio 1.5.6, istiod not creating istio-ca-root-cert configmap for namespaces where istio injection is enabled

### ISSUE THREAD

**Issue by rajivml** [istio/istio#26259]
HI Guys,

with reference to the below comment, the config map creation issue where istio injection is enabled on the namespace should have fixed in istio 1.5.6 , but that's not the case as this has hit us badly again in production today.

Based on the confirmation. we have migrated all our environments from Istio 1.5.4 to Istio 1.5.6 just to fix this burning issue, but the issue still exists 

Whenever a tenant onboard we create a namespace for the tenant and all the deployments of that tenant happens in his own namespace and whenever istiod stops creating istio-ca-certs for new namespaces, the deployments for all these new tenants will fail

the stop gap solution is to restart the istiod pod and it will resolve the issue, but it's a bad hack and it's not a good customer experience

Cloud Provider: GCP
Managed Kubernetes: Yes, we are using GKE
Kubernetes Cluster Version:  1.16.10-gke.8
No of Nodes: 120
Istio Version: 1.5.6
No of Namespaces: 350 currently & growing

Can you guys please suggest, how can this problem be fixed asap as it's happening on our production environments 

![image](https://user-images.githubusercontent.com/46923567/89661483-6109bc00-d8f0-11ea-84d4-62c8e40fc2cf.png)

"@rajivml @Mdirfan6 Actually this is fixed in 1.5.6, please see the release announcement
 https://istio.io/latest/news/releases/1.5.x/announcing-1.5.6/.

_Originally posted by @knight42 in https://github.com/istio/istio/issues/22463#issuecomment-648777698_
"

![image](https://user-images.githubusercontent.com/46923567/89629724-f0e14300-d8bb-11ea-8752-63d3b6a69e31.png)

**Comment by rajivml** [comment]
I have verified the istio-leader configmap, it's pointing to the right istiod pod which is of istio 1.5.6 version itself

**Comment by rajivml** [comment]
Please let us know if any additional logs are needed, after we restarted istiod problem went away and in couple of hours again the problem started, will changing the istiod pod replicas to 1 will temporarily solve the issue if it's an leader election issue among istiod pods ?

**Comment by rajivml** [comment]
any update on this ? this issue is happening consistently on our prod environment at-least once a day , any suggestion on how to fix this for good would be helpful

**Comment by rajivml** [comment]
cc @howardjohn @tariq1890 @knight42

**Comment by howardjohn** [comment]
Can you post the istiod logs? does this issue happen always/permanently or only after some period of time? I mean if you restart istiod, then create a new namespace, will it update the configmap?

**Comment by rajivml** [comment]
it's happening many times a day and when we are restarting istiod, it's creating missing configmaps in the namespaces where istio injection is enabled and we have temporarily scheduled a cron like this to restart istiod when ever configmap creation is not happening .

I will share the logs shortly , I have just now asked our IT admin to create an sink (GCP bucket) to upload the istiod logs as gcp console is giving an option to download only 300 lines of logs


```
#!/bin/bash

echo "Validating istio setup"
temp_namespace="validate-istio"
#create temp namespace
kubectl create namespace $temp_namespace
echo "$temp_namespace namespace created. Labelling namespace ... "
sleep 10
kubectl label namespace $temp_namespace istio-injection=enabled
sleep 30
#validating istiod
counter=1
while [ $counter -le 3 ];
do
  # check configmap
  response=$(kubectl -n ${temp_namespace} get configmap | grep istio-ca-root-cert | awk '{print $1}')
  echo "$response"
  if [ \( ! -z "${response}" \) -a \( "${response}" = "istio-ca-root-cert" \) ]; then
    echo "Istio Setup successfully completed and working fine."
    kubectl delete namespace $temp_namespace
    echo "$temp_namespace namespace deleted"
    exit 0
  else
    kubectl -n istio-system rollout restart deployment istiod
    echo "${counter} iteration restarting istio ..."
    sleep 30
  fi
  counter=$((counter+1))
done

echo "Istio setup validation failed"
kubectl delete namespace $temp_namespace
echo "$temp_namespace namespace deleted"

```

**Comment by rajivml** [comment]
@howardjohn plz find the logs downloadable at below link, attached logs worth of couple of hours

https://uipath-my.sharepoint.com/:u:/p/rajiv_chodisetti/EQUC5shCdeZPvg2Kt9PpKw8BPJd5N9p1zv49VkeZaFt0sA?e=3smp8J
https://uipath-my.sharepoint.com/:u:/p/rajiv_chodisetti/ERa8gKX6yFBDtdCw6bc1XuIB_IS8tlYg893h0zdqO6sYpQ?e=nwoD9l

**Comment by rajivml** [comment]
Hi, is anyone looking into it

**Comment by JimmyCYJ** [comment]
@myidpt @howardjohn since you worked on https://github.com/istio/istio/issues/22463, could you help to take a look at this issue? It is not clear to me what is the root cause, and whether the root cause to this issue is the same as the one fixed at #22463.

**Comment by rajivml** [comment]
This issue is still consistently happening on all our environments i.e alpha, staging and prod where istio 1.5.6 is being used and we put a cronjob to restart istiod pod whenever we run into such issue which is not an elegant solution. So, appreciate any support here, if more logs are required please let me know

**Comment by myidpt** [comment]
@howardjohn Hi John, do we observe similar issues on Istio 1.6 or later versions?

**Comment by howardjohn** [comment]
Not that I know of, probably fixed by #22598. We can re-open if we see it in 1.7+

**Comment by rajivml** [comment]
@howardjohn Nope, this fix was live in 1.5.6 and use 1.5.6 in production and this issue happens on our production on a day to day basis and we have a cron setup to restart istiod when this happens https://github.com/istio/istio/pull/22598
