### ISSUE TITLE
Virtual Service with host containing IP address doesn’t work

### ISSUE THREAD

**Issue by ashleythomasv28** [istio/istio#26686]
**Bug description**
My use case is to access external http endpoint through egress gateway. For that, I create a service entry and a virtual service to have host set as IP of the external endpoint. After application of the virtual service, all the proxies go to _STALE_ state. And I see following logs for istio-proxy: 
`warning	envoy config	[external/envoy/source/common/config/grpc_subscription_impl.cc:101] gRPC config for type.googleapis.com/envoy.api.v2.RouteConfiguration rejected: Only unique values for domains are permitted. Duplicate entry of domain <IP>
`

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
All the proxies should have correct route to the external IP and proxy states should be _OK_ not _STALE_. But I see in the sidecar of source pod does not point to egress gateway cluster for this endpoint's route

**Steps to reproduce the bug**
1. Create service entry for the external IP with http protocol with address and endpoint set as the IP address
2. Apply the service entry created above 
3. Create a virtual service with the IP as the host (so that it is used whenever user hits the IP from within the cluster)
4. Apply the virtual service created above
5. See output of command ` istioctl proxy-status`, it will give all proxy status as stale
6. Check logs for istio-proxy for any pod, it will give gRPC error mentioned in bug description

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version --remote
client version: 1.6.8
control plane version: 1.6.8

kubectl version
Major:"1", Minor:"18"
Major:"1", Minor:"18"

**How was Istio installed?**
Using istioctl install 

Please let me know if we can use IP address as host in virtual service as mentioned [here](https://istio.io/latest/docs/reference/config/networking/virtual-service/?_ga=2.180256738.739216154.1597739117-662355876.1588066267#VirtualService) because this seem to trigger when I use IP in host in virtual service.

**Comment by howardjohn** [comment]
can you add the config you used so we can reproduce?

cc @ramaraochavali

**Comment by SchedulerSimulator** [comment]
Sure, please find configurations for gateway, service entry and virtual service below: 

Egress gateway: 

`apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"`

Service Entry: 

`
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ip-external
spec:
  hosts:
  - "ip-external.com"
  addresses:
  - 10.20.30.40
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 10.20.30.40
`

Virtual Service:

`
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-ip-virtual-service
spec:
  hosts:
  - 10.20.30.40
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route: # route requests from mesh to egress gateway 
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 80
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    route: # route requests from egress gateway to external service
    - destination:
        host: ip-external.com
        port:
          number: 80
`

Then try `istioctl proxy-status` you'll see STALE state for RDS for all sidecars where this is applied. 
Additionally, check logs of istio-proxy container in any of the pods with sidecar

Let me know if any other information is required.

**Comment by howardjohn** [comment]
I have confirmed this is fixed by #24455 in 1.7+ Thanks for the info!

**Comment by itsLucario** [comment]
@howardjohn The issue still exists it seems in 1.9. With IP has host I'm unable to route traffic via egress gateway. Could you please help with an example if possible?

**Comment by itsLucario** [comment]
Below is the configuration I'm using :
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: "bulksms-ext"
spec:
  hosts:
  - bulksms.ext
  addresses: 
  - IP_ADDRESS/32
  ports:
  - number: 8080
    name: http-8080
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: IP_ADDRESS
  location: MESH_EXTERNAL
```
---
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-sms-email-via-egress-gw-{{ .Values.env }}
spec:
  hosts:
  - IP_ADDRESS
  gateways:
  - my-egress-gateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 8080
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 80
  - match:
    - gateways:
      - my-egress-gateway
      port: 80
    route:
    - destination:
        host: bulksms.ext
        port:
          number: 8080
```

The response I'm getting on sending a request: 
```
Trying IP_ADDRESS:8080...
* Connected to IP_ADDRESS (IP_ADDRESS) port 8080 (#0)
> GET / HTTP/1.1
> Host: IP_ADDRESS:8080
> User-Agent: curl/7.75.0-DEV
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 84
< content-type: text/plain
< date: Thu, 11 Mar 2021 13:58:09 GMT
< server: envoy
<
* Connection #0 to host IP_ADDRESS left intact
upstream connect error or disconnect/reset before headers. reset reason: local reset
```

**Comment by linouxis9** [comment]
Were you able to make it work? @itsLucario
