### ISSUE TITLE
Bad config randomly pushed to proxies - conflicts, external service has no endpoints

### ISSUE THREAD

**Issue by vngzs** [istio/istio#27083]
**Bug description**

Without any changes on our side (that I can detect), `istiod` will take a working app in this configuration and (seemingly) randomly propagate incorrect configs to Envoy.

It starts with this, which happens a few times from `istiod`:
```
2020-09-01T20:12:28.325847Z	info	ads	Incremental push, service external-service-m has no endpoints
2020-09-01T20:12:28.325855Z	info	ads	Incremental push, service external-service-n has no endpoints
2020-09-01T20:12:28.327323Z	info	ads	Incremental push, service external-service-x has no endpoints
2020-09-01T20:12:28.327324Z	info	ads	Cluster init time 866.739µs 2020-09-01T20:12:28Z/9
```
Followed by:
```
2020-09-01T20:12:28.327792Z	info	ads	Pushing sidecar~10.34.209.199~our-pod-name-57cb4dbc5b-tzp55.our-namespace-name~our-namespace-name.svc.cluster.local-5053
2020-09-01T20:12:28.336122Z	info	ads	EDS: PUSH for node:our-pod-name-57cb4dbc5b-tzp55.our-namespace-name clusters:67 endpoints:137 empty:0
2020-09-01T20:12:28.342320Z	info	ads	RDS: PUSH for  node:our-pod-name-57cb4dbc5b-tzp55.our-namespace-name routes:28
2020-09-01T20:12:28.426037Z	info	ads	XDS:EDSInc Pushing:2020-09-01T20:12:28Z/9 Services:map[external-service-m:{} external-service-n:{} external-service-x:{}] ConnectedEndpoints:8
2020-09-01T20:12:28.426597Z	info	ads	XDS:EDSInc Pushing:2020-09-01T20:12:28Z/9 Services:map[external-service-m:{} external-service-n:{} external-service-x:{}] ConnectedEndpoints:7
2020-09-01T20:12:28.427493Z	info	ads	Push debounce stable[720] 4: 100.065683ms since last change, 100.084975ms since last push, full=false
2020-09-01T20:12:28.427563Z	info	ads	XDS:EDSInc Pushing:2020-09-01T20:12:28Z/9 Services:map[external-service-m:{} external-service-n:{} external-service-x:{}] ConnectedEndpoints:3
```
After all those push notifications, we get get this:

```
2020-09-01T20:12:35.944174Z     info    ads     Push Status: {
    "pilot_conflict_inbound_listener": {
        "our-pod-name-57cb4dbc5b-tzp55.our-namespace-name": {
            "proxy": "our-pod-name-57cb4dbc5b-tzp55.our-namespace-name",
            "message": "Conflicting inbound listener:10.55.209.199:3000. existing: our-pod-name-load-balancer.our-name
space-name.svc.cluster.local, incoming: our-pod-name.our-namespace-name.svc.cluster.local"
        },
        "another-pod-name-6bdfc856f8-wr27j.our-namespace-name": {
            "proxy": "another-pod-name-6bdfc856f8-wr27j.our-namespace-name",
            "message": "Conflicting inbound listener:10.55.191.222:3000. existing: another-pod-name-load-balancer.our-
namespace-name.svc.cluster.local, incoming: another-pod-name.our-namespace-name.svc.cluster.local"
        },
        "yet-another-pod-name-866b497868-gvx46.another-namespace-name": {
            "proxy": "yet-another-pod-name-866b497868-gvx46.another-namespace-name",
            "message": "Conflicting inbound listener:10.55.215.244:10000. existing: yet-another-pod-name.another-names
pace-name.svc.cluster.local, incoming: a-fourth-pod-name.another-namespace-name.svc.cluster.local"
        }
    },
    "pilot_conflict_outbound_listener_tcp_over_current_tcp": {
        "0.0.0.0:443": {
            "proxy": "our-pod-name-57cb4dbc5b-tzp55.our-namespace-name",
            "message": "Listener=0.0.0.0:443 AcceptedTCP=external-service-n,kms.us-east-2.amazonaws.com,kms-fips.us-ea
st-2.amazonaws.com,kms.us-east-1.amazonaws.com,kms-fips.us-east-1.amazonaws.com,kms.us-west-1.amazonaws.com,kms-fips.u
s-west-1.amazonaws.com,kms.us-west-2.amazonaws.com RejectedTCP=kms-fips.us-west-2.amazonaws.com TCPServices=8"
        },
        "0.0.0.0:5432": {
            "proxy": "arbitrary-external-pod-78c45bf945-2dqmh.another-namespace-name",
            "message": "Listener=0.0.0.0:5432 AcceptedTCP=one-postgres-db RejectedTCP=another-postgres-db TCPServices=1"

        }
    },
    "pilot_eds_no_instances": {
        "outbound|80||aws.magic": {}
    }
}
```

Then, in the app, 1s later it has errors hitting `external-service-x`:

```
Put "https://external-service-x:8200/v1/auth/envname/eks/login": read tcp 10.55.195.241:54688->10.55.2.4:8200: read: connection reset by peer	
```
It is automatically resolved once we kill `istiod`, but from the start of the problem until `istiod` is restarted, the proxy blocks app traffic.

We have a `ServiceEntry` for `external-service-x`, among others:

```yaml
- apiVersion: networking.istio.io/v1beta1
  kind: ServiceEntry
  metadata:
    name: external-service-x
    namespace: our-namespace-name
  spec:
    exportTo:
    - .
    hosts:
    - external-service-x
    location: MESH_EXTERNAL
    ports:
    - name: HTTPS-x
      number: 8200
      protocol: HTTPS
    resolution: DNS
```
```yaml
- apiVersion: networking.istio.io/v1beta1
  kind: ServiceEntry
  metadata:
    name: external-service-n
    namespace: our-namespace-name
  spec:
    exportTo:
    - .
    hosts:
    - external-service-n
    location: MESH_EXTERNAL
    ports:
    - name: HTTPS-external-service-n
      number: 443
      protocol: HTTPS
    resolution: DNS
```
```yaml
- apiVersion: networking.istio.io/v1beta1
  kind: ServiceEntry
  metadata:
    name: external-service-m
    namespace: our-namespace-name
  spec:
    exportTo:
    - .
    hosts:
    - external-service-m
    location: MESH_EXTERNAL
    ports:
    - name: TCP-external-service-m
      number: 1433
      protocol: TCP
    resolution: DNS
```
There are many more, but those appear to be the ones in question. They rarely change; they are tested and working modulo this issue.

Endpoints/services all have been around for months.

```
$ k get ep -n our-namespace-name
NAME                                           ENDPOINTS                                                             AGE
pod-k                                          10.55.164.81:8080                                                     76d
pod-k-load-balancer                            10.55.164.81:8080                                                     76d
pod-u                                          10.55.195.241:10000,10.55.195.241:3000                                76d
our-pod-name                                   10.55.219.186:10000,10.55.219.186:3000                                76d
our-pod-name-load-balancer                     10.55.219.186:10000,10.55.219.186:3000                                76d
pod-u-load-balancer                            10.55.195.241:10000,10.55.195.241:3000                                76d
pod-t                                          10.55.154.60:7200,10.55.164.117:7200,10.55.195.250:7200               76d
pod-t-load-balancer                            10.55.154.60:7200,10.55.164.117:7200,10.55.195.250:7200 + 3 more...   76d
another-pod-name                               10.55.203.241:3000                                                    76d
another-pod-name-load-balancer                 10.55.203.241:3000,10.55.203.241:3000                                 76d
```

```
$ k get svc -n our-namespace-name
NAME                                           TYPE           CLUSTER-IP       EXTERNAL-IP                                                                        PORT(S)                          AGE
pod-k                                          ClusterIP      172.20.71.145    <none>                                                                             80/TCP                           76d
pod-k-load-balancer                            LoadBalancer   172.20.64.155    aws-internal-elb.us-east-1.elb.amazonaws.com                                       80:31205/TCP                     76d
pod-u                                          ClusterIP      172.20.198.134   <none>                                                                             10000/TCP,3000/TCP               76d
our-pod-name                                   ClusterIP      172.20.58.18     <none>                                                                             10000/TCP,3000/TCP               76d
our-pod-name-load-balancer                     LoadBalancer   172.20.47.10     another-aws-internal-elb.us-east-1.elb.amazonaws.com                               10000:30020/TCP,3000:30388/TCP   76d
pod-u-load-balancer                            LoadBalancer   172.20.220.52    pod-u-aws-internal-elb.us-east-1.elb.amazonaws.com                                 10000:31573/TCP,3000:32223/TCP   76d
pod-t                                          ClusterIP      172.20.191.189   <none>                                                                             80/TCP                           76d
pod-t-load-balancer                            LoadBalancer   172.20.126.232   pod-t-aws-internal-elb.us-east-1.elb.amazonaws.com                                 443:32526/TCP,80:30190/TCP       76d
another-pod-name                               ClusterIP      172.20.170.142   <none>                                                                             80/TCP                           76d
another-pod-name-load-balancer                 LoadBalancer   172.20.107.191   another-pod-name-elb.us-east-1.elb.amazonaws.com                                   443:30070/TCP,80:31583/TCP       76d
```

Port 10000 is grpc (and the service ports are named as such), and port 3000 is http.

There's one exception: `another-pod-name`'s service definition does its ports like this:

```
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      service: another-pod-name

```

While `another-pod-name-load-balancer` has:

```
    ports:
    - name: https
      nodePort: 30070
      port: 443
      protocol: TCP
      targetPort: 3000
    - name: http
      nodePort: 31583
      port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      app: another-pod-name
      service: another-pod-name
```

I could see that maybe causing this message:

```
Conflicting inbound listener:10.55.191.222:3000. existing: another-pod-name-load-balancer.our-
namespace-name.svc.cluster.local, incoming: another-pod-name.our-namespace-name.svc.cluster.local
```

but even if that's the case, why does this affect `external-service-x`, which uses port 8200? And why does it work 99% of the time, and then break `istiod` irrecoverably 1% of the time?

Output of `istioctl analyze`:

```
$ istioctl analyze -n our-namespace-name
Warn [IST0107] (Service another-pod-name.our-namespace-name) Misplaced annotation: sidecar.istio.io/inject can only be applied to Pod
Info [IST0118] (Service pod-k-load-balancer.our-namespace-name) Port name  (port: 80, targetPort: 8080) doesn't follow the naming convention of Istio port.
Error: Analyzers found issues when analyzing namespace: our-namespace-name.
See https://istio.io/docs/reference/config/analysis for more information about causes and resolutions.
```

The warning there about a misplaced istio label on a service (which we should clean up) and a port naming issue with `pod-k-load-balancer`. That pod looks like this:

```
  - nodePort: 31205
    port: 80
    protocol: TCP
    targetPort: 8080
```

Potentially related issues:

- [pilot_conflict_inbound_listener despite annotations to tell envoy to ignore the port](https://github.com/istio/istio/issues/17465)
- [pilot/debug/push_status shows outdated information ](https://github.com/istio/istio/issues/17464)
- [Pilot generates invalid inbound listeners some times](https://github.com/istio/istio/issues/20260)

I'm calling this a networking issue, since the networking behavior should at least be stable (it would be OK for this to break after a deployment, for example, but not for it to take down a running service). And it's a user experience issue at least inasmuch as Istio should not be surprising - if there's something desperately wrong with our config, I'd rather have Istio fail loudly than randomly fall over.

I'm not sure how the conflicts are exactly related to our external service "having no endpoints", but they seem to come hand-in-hand.

To get a sense of the rareness of this issue, we replicate our setup across 5 deployments, and thus far we tend to see it in production, where it's both less likely we can spend time investigating and debugging and costs more to be wrong.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

The app should stay up. Istio shouldn't kill (by terminating access to external services) running applications. I'd even prefer `istiod` to detect this and fail its healthcheck versus continuing running in a broken state.

**Steps to reproduce the bug**

Unfortunately, despite this happening multiple times in our production clusters, I've failed thus far to get a repro. It doesn't appear to have a specific cause.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.5.8
control plane version: 1.5.8
data plane version: 1.5.8 (19 proxies)
```

1.5.0 through 1.5.8 are definitely affected. I never saw this in 1.0 -> 1.3, but it started when we went to 1.5. We plan to test with 1.6/1.7 as soon as we can, but it's hard to prove a negative so it will take a while of stable runs to show that this is avoided.

**How was Istio installed?**

Operator

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS

> Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching the dump file to this issue.

I'd really love to get a cluster dump when this happens, but (1) we don't really want to map our internal infra and put it on the Internet and (2) the dumps take a _very long_ time to run (they could benefit from some parallelism), so it's hard to buy time for a dump when we know we can resolve the issue by bouncing `istiod`.

**Comment by vngzs** [comment]
Time has done us the favor of reproducing this bug in a lower environment. And I can see the config issue:

Here's the Envoy config snippet in question for a working setup:

```yaml
    - cluster:
        '@type': type.googleapis.com/envoy.api.v2.Cluster
        circuit_breakers:
          thresholds:
          - max_connections: 4294967295
            max_pending_requests: 4294967295
            max_requests: 4294967295
            max_retries: 4294967295
        connect_timeout: 1s
        dns_lookup_family: V4_ONLY
        dns_refresh_rate: 5s
        filters:
        - name: envoy.filters.network.upstream.metadata_exchange
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange
            value:
              protocol: istio-peer-exchange
        load_assignment:
          cluster_name: outbound|8200||external-service-name.com
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: external-service-name.com
                    port_value: 8200
              load_balancing_weight: 1
            load_balancing_weight: 1
            locality: {}
        name: outbound|8200||external-service-name.com
        respect_dns_ttl: true
        type: STRICT_DNS
      last_updated: "2020-09-08T16:38:59.386Z"
      version_info: 2020-09-02T19:26:11Z/22
```

And, on the broken environment:

```yaml
    - cluster:
        '@type': type.googleapis.com/envoy.api.v2.Cluster
        circuit_breakers:
          thresholds:
          - max_connections: 4294967295
            max_pending_requests: 4294967295
            max_requests: 4294967295
            max_retries: 4294967295
        connect_timeout: 1s
        dns_lookup_family: V4_ONLY
        dns_refresh_rate: 5s
        filters:
        - name: envoy.filters.network.upstream.metadata_exchange
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange
            value:
              protocol: istio-peer-exchange
        load_assignment:
          cluster_name: outbound|8200||external-service-name.com
        name: outbound|8200||external-service-name.com
        respect_dns_ttl: true
        type: STRICT_DNS
      last_updated: "2020-09-01T21:03:35.244Z"
      version_info: 2020-08-28T18:25:58Z/45
```
```

**Comment by vngzs** [comment]
Confirmed I'm still seeing this with Istio 1.6.8.

**Comment by vngzs** [comment]
After much investigation, I believe this is a consequence of poor namespace isolation and swapping ServiceEntry objects when timestamps change. It would therefore be solved in [*ServiceEntry Resolution Design*](https://docs.google.com/document/d/15-PU9O22Pb0qTzCfwK2hjwNTcb-CqFuw8JnIgwK3EIM/edit#), and we must adopt the `Sidecar` resource to solve it. I'm working on applying this throughout our infra.

That doesn't completely explain the bad pushes:

```
2020-09-01T20:12:28.325847Z	info	ads	Incremental push, service external-service-m has no endpoints
2020-09-01T20:12:28.325855Z	info	ads	Incremental push, service external-service-n has no endpoints
2020-09-01T20:12:28.327323Z	info	ads	Incremental push, service external-service-x has no endpoints
```

Those `ServiceEntry` objects are static and rarely change. But the timing in the logs (collisions consistently line up with those messages in logs) seems to indicate the problems are related. Will follow up with results.

**Comment by nirvanagit** [comment]
@vngzs - I experienced the same issue where two service entries in different namespaces had the same host name.

This can be fixed (WIP PR) with updating this statement - https://github.com/istio/istio/blob/1.5.8/pilot/pkg/serviceregistry/external/servicediscovery.go#L268

Explanation
- Whenever istiod gets an update from kube-api (sequential based on create/update time of the resource) it updates its cache. This cache is used for its reconciliation loop.
- While updating its cache, it deletes the entry by executing:
    ```
    delete(d.instances[instance.Service.Hostname], instance.Service.Attributes.Namespace)
    delete(d.instances, instance.Service.Hostname)
    ```
   + The second statement, removes the entry from the object if the hostname was defined by a service entry defined in another namespace. This results in only the last service entry being stored in its cache, while deleting the rest.

    + Although on bouncing istiod pods it recovers the correct state, where it refreshes its cache by listing all serviceentries across all namespaces

cc: @howardjohn

**Comment by nirvanagit** [comment]
This is already fixed in master - https://github.com/istio/istio/pull/22712

Thanks @howardjohn !

**Comment by vngzs** [comment]
Yeah, I think this is safe to close. It is still broken in 1.5.x as far as I know, but we are on 1.6.x now and things are golden.

When I thought I had a 1.6.8 repro, what _actually_ happened was an artifact of TCP service discovery weirdness. We had an app relying on PassthroughCluster to hit a RabbitMQ instance outside the cluster. When someone launched RabbitMQ within the cluster, we found traffic to the external service was broken. This was not quite the same as the random breakages that are the subject of this report.
