### ISSUE TITLE
Unable to delete spec.template.spec.volumes[name:ingressgateway-ca-certs].secret using profile

### ISSUE THREAD

**Issue by infa-sanaik** [istio/istio#28734]
**Bug description**
Unable to delete spec.template.spec.volumes[name:ingressgateway-ca-certs].secret using profile.
We are trying to set spec.template.spec.volumes[name:ingressgateway-ca-certs].emptyDir to {} since vault sidecar is going to inject the certs.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
Use following code in istio operator profile
```
- apiVersion: apps/v1
          kind: Deployment
          name: iicsgateway
          patches:
          - path: spec.template.spec.volumes[name:ingressgateway-ca-certs].emptyDir
            value: {}
          - path: spec.template.spec.volumes[name:ingressgateway-certs].emptyDir
            value: {}
            
          ## Delete secret attribute by not setting the value
          - path: spec.template.spec.volumes[name:ingressgateway-ca-certs].secret
          - path: spec.template.spec.volumes[name:ingressgateway-certs].secret
```
and run istioctl manifest genereate -f <file>
It adds emptyDir attribute but does not remove secret attribute.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
client version: 1.5.4
control plane version: 1.5.8
data plane version: 1.4.6 (2 proxies), 1.5.8 (398 proxies), 1.5.4 (42 proxies), 1.4.5 (2 proxies), 1.4.2 (3 proxies)

$ kubectl version --short
Client Version: v1.17.3
Server Version: v1.15.11-eks-065dce
```

**How was Istio installed?**
Upgraded from 1.4 via operator.

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS7, k8s

**Comment by morvencao** [comment]
@infa-sanaik Please try with istio-1.7.x and above:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      k8s:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.spec.volumes[name:ingressgateway-ca-certs].emptyDir
            value: {}
          - path: spec.template.spec.volumes[name:ingressgateway-certs]..emptyDir
            value: {}
          - path: spec.template.spec.volumes[name:ingressgateway-ca-certs].secret
          - path: spec.template.spec.volumes[name:ingressgateway-certs].secret
```

**Comment by williamaronli** [comment]
@infa-sanaik have you tried the method morvencan provide to mitigate this issue?

**Comment by howardjohn** [comment]
Presuming this is fixed since we haven't gotten any additional feedback. Thanks

**Comment by infa-sanaik** [comment]
We changed the path where certificates were installed since we are still not on 1.7 yet.
