### ISSUE TITLE
Underlying NLB of istio-ingressgateway fails its healthchecks after istioctl upgrade

### ISSUE THREAD

**Issue by Kyslik** [istio/istio#28856]
**Bug description**

`istioctl upgrade` _bricks_ NLB. After we install Istio using `istioctl` everything works fine - as expected; once we use the same config and issue `istioctl upgrade -f config.yaml`, service manifest `istio-ingressgateway` changes (`nodePorts` are _different_), service-controller issues update but it fails:

```
Events:
  Type     Reason                  Age                From                Message
  ----     ------                  ----               ----                -------
  Warning  SyncLoadBalancerFailed  79s                service-controller  Error syncing load balancer: failed to ensure load balancer: Error creating load balancer target group: "DuplicateTargetGroupName: A target group with the same name 'k8s-istiosys-istioing-e5ab3b8d49' exists, but with different settings\n\tstatus code: 400..."
```

Target groups start to fail their healthchecks and ingress stops working.

> **Note**: we are using NLB:
> ```yaml
>         gateways:
>           istio-ingressgateway:
>             serviceAnnotations:
>               "service.beta.kubernetes.io/aws-load-balancer-internal": "true"
>               "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
> ```

We looked for the similar symptoms on the Istio issue tracker and could not find any except: https://discuss.istio.io/t/istio-operator-1-6-8-install-issues-nlb-target-groups-being-recreated/8034 we confirmed that its the same or at least very similar issue.

We are forced to delete the service (`kubectl delete svc istio-ingressgateway`) and let `istio upgrade` do its job from _scratch_ so to speak.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[x] Upgrade

**Expected behavior**

Upgrade using `istioctl upgrade` should result in working ingress.

**Steps to reproduce the bug**

- install Istio using `istioctl install` & use NLB annotation
- "upgrade" Istio using `istioctl upgrade` (it can be same config as installation one)

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```sh
$ ./istio-1.6.13/bin/istioctl version --remote
client version: 1.6.13
control plane version: 1.6.13
data plane version: 1.6.13
$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.15.11
```

**How was Istio installed?**

Via `istioctl install`.

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS.

**Comment by Kyslik** [comment]
Current workaround is _hardcoding_ `nodePorts` - the same way how it was on Istio 1.5 when helm was used for templating it https://github.com/istio/istio/blob/release-1.5.9-patch/install/kubernetes/helm/istio/charts/gateways/values.yaml#L55-L73

**Comment by sel-vcc** [comment]
Is this fixed by https://github.com/istio/istio/pull/28072?

**Comment by Kyslik** [comment]
I can't find which version of `istioctl` the fix is in; we tested with version `1.16.13` and it wasn't fixed.

**Comment by kirankumar15** [comment]
Seeing the same issue while using NLB with istio. NLB healthchecks does not seem to pass.

**Comment by esnible** [comment]
@istio/wg-environments-maintainers Can you triage this or assign it to someone from area/upgrade?

**Comment by a8j8i8t8** [comment]
I'm facing this issue with Istio 1.9. I'm using below config.
```yaml
      istio-ingressgateway:
        autoscaleEnabled: true
        env: {}
        name: istio-ingressgateway
        secretVolumes:
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          secretName: istio-ingressgateway-certs
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          secretName: istio-ingressgateway-ca-certs
        nodeSelector:
          kops.k8s.io/instancegroup: istio-nodes
        tolerations:
        - key: team
          value: istio
          effect: NoSchedule
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:123456789000:certificate/123abc45-6def-4753-8731-56d045ba01c6
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
        type: LoadBalancer
        ports:
        - name: http2
          port: 80
          protocol: TCP
          targetPort: 8080
          nodePort: 31597
        - name: https
          port: 443
          protocol: TCP
          targetPort: 8443
          nodePort: 30516
        loadBalancerSourceRanges:
          - 192.168.0.1/18
          - 192.167.5.6/32
```
With above, AWS NLB target-groups are unhealthy.
Am I missing something?
Appreciate your help.
Thanks.
- ajit

**Comment by ChrisKstalik** [comment]
We are facing the same issue.

**Comment by howardjohn** [comment]
This should be fixed in 1.8+ by https://github.com/istio/istio/pull/28072. if you see this issue on 1.8+ please reopen/open a new issue. Thanks everyone!

**Comment by wiegandf** [comment]
This happened to us after istioctl upgrade from 1.8.3 to 1.9.4:
```
  Type     Reason                  Age                From                Message
  ----     ------                  ----               ----                -------
  Warning  SyncLoadBalancerFailed  34m                service-controller  Error syncing load balancer: failed to ensure load balancer: error adding tags for targetGroup arn:aws:elasticloadbalancing:us-east-1:<account_id>:targetgroup/k8s-istiosys-istioing-b5972487c6/28fc269140083f9f due to "TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:us-east-1:<account_id>:targetgroup/k8s-istiosys-istioing-b5972487c6/28fc269140083f9f' not found\n\tstatus code: 400, request id: 5e767014-90c6-407a-9c48-d3f7485f5e2d"
  Normal   EnsuringLoadBalancer    23m (x4 over 14h)  service-controller  Ensuring load balancer
  Normal   EnsuredLoadBalancer     23m (x3 over 14h)  service-controller  Ensured load balancer
```

**Comment by vasrem** [comment]
It happens when updating from 1.9.7 to 1.10.4. 

The issue also occurs whenever one restarts the Istio Operator. The service gets reapplied and a new nodePort is allocated triggering the issue mentioned in the description.
