### ISSUE TITLE
Can not connect external https server in container

### ISSUE THREAD

**Issue by zhengqisong** [istio/istio#30708]
**Bug description**
Can not connect external https server in container

[*] Networking

**How was Istio installed?**
istioctl install -f istio.yml

**Environment where the bug was observed (cloud vendor, OS, etc)**
istio version: 1.7.6
kubernetes version: 1.8.10
os version: centos 7.6
kernel version: 4.4.214-1.el7.elrepo.x86_64
istio config:
```
meshConfig:
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    policyCheckFailOpen: false
    disablePolicyChecks: true
    enableTracing: true
    accessLogFile: "/dev/stdout"
    accessLogEncoding: JSON
    accessLogFormat: ''
    enableAutoMtls: true
  values:
    global:
      logging:
        level: "default:warn"
      trustDomain: "cluster.local"
      logAsJson: true
      proxy:
        clusterDomain: "cluster.local"
        tracer: "zipkin"
      istiod:
        enableAnalysis: true
      sds:
        token:
          aud: istio-ca
```
Can not connect https server, curl https://www.baidu.com -v
```
/ # curl https://www.baidu.cm -v                                                                                                                  
* Could not resolve host: www.baidu.cm                                                                                                            
* Closing connection 0                                                                                                                            
curl: (6) Could not resolve host: www.baidu.cm                                                                                                    
/ # curl https://www.baidu.com -v                                                                                                                 
*   Trying 110.242.68.4:443...                                                                                                                    
* TCP_NODELAY set                                                                                                                                 
* Connected to www.baidu.com (110.242.68.4) port 443 (#0)                                                                                         
* ALPN, offering h2                                                                                                                               
* ALPN, offering http/1.1                                                                                                                         
* successfully set certificate verify locations:                                                                                                  
*   CAfile: /etc/ssl/certs/ca-certificates.crt                                                                                                    
  CApath: none                                                                                                                                    
* TLSv1.3 (OUT), TLS handshake, Client hello (1):                                                                                                 
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number                                                                                
* Closing connection 0                                                                                                                            
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```
but can connect http server, curl http://www.baidu.com -v
```
# curl http://www.baidu.com -v
*   Trying 103.235.46.39:80...
* TCP_NODELAY set
* Connected to www.baidu.com (103.235.46.39) port 80 (#0)
> GET / HTTP/1.1
> Host: www.baidu.com
> User-Agent: curl/7.66.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< accept-ranges: bytes
< cache-control: private, no-cache, no-store, proxy-revalidate, no-transform
< content-length: 2381
< content-type: text/html
< date: Sat, 06 Feb 2021 09:16:16 GMT
< etag: "588604ec-94d"
< last-modified: Mon, 23 Jan 2017 13:28:12 GMT
< pragma: no-cache
< server: envoy
* Added cookie BDORZ="27315" for domain baidu.com, path /, expire 1612689376
< set-cookie: BDORZ=27315; max-age=86400; domain=.baidu.com; path=/
< x-envoy-upstream-service-time: 614
```
if set includeOutboundIPRanges annotation in pod, connect https server, such as, raffic.sidecar.istio.io/includeOutboundIPRanges: 172.16.0.1/16,172.17.0.0/16

**Comment by howardjohn** [comment]
please add a config dump, see https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by zhengqisong** [comment]
config dump, see https://raw.githubusercontent.com/zhengqisong/camel/master/istio-config-dump.json

**Comment by howardjohn** [comment]
The confi dump shows you are using Istio 1.6. Please upgrade to istio 1.8.3, this bug is fixed (most likely, assuming its the same issue I am thinking). 1.6 is not supported. thanks. https://istio.io/latest/news/support/announcing-1.6-eol-final/

**Comment by zhengqisong** [comment]
Thanks @howardjohn ,

I test it  in 1.7.6, this bug still exists, I think istio-proxy set TLSv1.3 to client curl,  but curl can not support tlsv1.3(I test wget can connect https server with istio-proxy). How to set istio-proxy use TLSv1.2?

the flow: curl --TLSv1.3->istio-proxy---TLSv1.2--->external https server.

OK, I will test istio 1.8.3.

config dump see: https://raw.githubusercontent.com/zhengqisong/camel/master/istio-proxy-1.7.6-config_dump.json

**Comment by howardjohn** [comment]
Its not fixed in 1.7

**Comment by zhengqisong** [comment]
upgrade istio version 1.8.3,  Segmentation fault
./bin/istioctl upgrade -f conf/istio.yaml --set values.gateways.istio-ingressgateway.runAsRoot=true
2021-02-20T04:08:45.200665Z     info    proto: tag has too few fields: "-"
! values.global.tracer.zipkin.address is deprecated; use meshConfig.defaultConfig.tracing.zipkin.address instead
! values.global.trustDomain is deprecated; use meshConfig.trustDomain instead
Control Plane - pilot pod - istiod-7bd6f8696b-2v42c - version: 1.7.6
Control Plane - pilot pod - istiod-7bd6f8696b-qdm4g - version: 1.7.6

Upgrade version check passed: 1.7.6 -> 1.8.3.

Segmentation fault

**Comment by zhengqisong** [comment]
I test it in 1.8.3, this bug was fixed.

**Comment by howardjohn** [comment]
Great!
