### ISSUE TITLE
e2e-pilot test failure in checking logs of mixer

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3125]
Seen in multiple tests. It appears mixer crashed.

https://storage.googleapis.com/istio-prow/pull/istio_istio/2465/istio-pilot-e2e/2256/build-log.txt

I0202 17:40:16.195] =================== Failed infrastructure tests! =====================
I0202 17:40:16.196] 1 error occurred:
I0202 17:40:16.196] 
I0202 17:40:16.196] * (auth infra) http-reachability run 0 failed all 90 attempts for Checking log of mixer

**Comment by ldemailly** [comment]
happens quite a lot
https://circleci.com/gh/istio/istio/25264

did someone do re run with ssh to check what's up on the pods / what the errors might be ?

**Comment by kyessenov** [comment]
I thought we should be fetching logs on failure. Is the log fetching not working?

**Comment by ldemailly** [comment]
the short cut added to skip cleanup is tied to dev mode and skips log collection, costin has a change in a bigger unrelated pr to always fetch the logs (but I asked that it there should still be some way to not do it as it's very very slow on a real cluster in dev mode)

**Comment by kyessenov** [comment]
I don't mind doing log preservation async, or saving a link to stackdriver
or wherever these logs end up at. it's a bummer not to have logs and wastes
lots of hours trying to reproduce the same failure.

**Comment by ldemailly** [comment]
just one of the many hidden cost of switching build/test platform and scripts

**Comment by andraxylia** [comment]
I reproduced this here and ssh-ed into the VM:
https://circleci.com/gh/istio/istio/25446

There is no crash, mixer logs are there, but the request ID is not present in the mixer log.
$ kubectl  logs istio-mixer-2045601324-tnsv0  -n istio-test-t35zs -c mixer | grep 53702c50-ae0d-9731-8499-3a8845e33462

There is no wrapping of the logs, they are there from the begining.

It may be related to the caching of requests in the mixer filter, which would explain the random behavior, or it may be some other bug. @jmuk please follow up on the explanation.

Meanwhile, I will submit a PR to disable this check from e2e pilot.

**Comment by costinm** [comment]
The test is fetching mixer logs about a dozen times - just to find grep for
a request ID.

I think we spend far more time wasting because we fail to collect the
actual logs - there are many other things to optimize.
I don't mind an extra flag to not collect the logs if anyone wants to add
it - but not cleaning up the cluster (since
the VM goes away anyways or you want to do additional testing) is different
than not fetching the logs.

I agree we should only fetch on failure, if someone has time to implement
this.

Costin

**Comment by andraxylia** [comment]
@douglas-reid confirmed the logging in mixer has changed.

We should not rely on logs to verify failure, so I will disable this in the e2e pilot tests.

Also opened an issue for logs missing for pilot, mixer, ca: #3140

**Comment by yusuoh** [comment]
I think this has been fixed by #3089. It is because mixer did not have the permission to read CRD data in some tests where RBAC rules are enforced.

**Comment by ldemailly** [comment]
it still happened in https://circleci.com/gh/istio/istio/26680?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link is it a rebase issue?

**Comment by jmuk** [comment]
It seems `pilot/test/integration/testdata/mixer.yaml.tmpl` does not have CRDs and mixer rules / configs, maybe that's why. I'll set up another PR tomorrow.

**Comment by ldemailly** [comment]
thanks jun !

**Comment by andraxylia** [comment]
@jmuk This has been disabled and it is no longer affecting automated tests, please feel free to open another issue for the full fix.
