### ISSUE TITLE
Injection params.Verbosity is ignored and Envoy log level defaults to 'none'

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio#3168]
The injection verbosity parameter is ignored. Verbosity can be set via command line arguments, and then it is sent in here:

https://github.com/istio/istio/blob/master/pilot/cmd/istioctl/inject.go#L197

But the config file string literal does not use verbosity anywhere:

https://github.com/istio/istio/blob/master/pilot/pkg/kube/inject/mesh.go

This problem is compounded because the default log level for Envoy is 'off', not even 'error'. Envoy log level cannot be set and all logging output is suppressed.

**Comment by ijsnellf** [comment]
^^ @cmluciano @ayj: thoughts?

**Comment by ayj** [comment]
Default log level "off" for Envoy should probably be changed unless there is a perf cost for error/warnings? @ldemailly 

Should `verbosity` map to envoy log level ([`proxyLogLevel`](https://github.com/istio/istio/blob/cbaa2a65b805a4be23c3e9ae19d363f29b85a46b/pilot/cmd/pilot-agent/main.go#L269)), the pilot-agent log level ([istio.io/pkg/log](https://github.com/istio/istio/tree/master/pkg/log)), or both? They both seem to have a notion of warning/error/info/debug so maybe we can map the integer verbosity to the same value in both components? 

Full customization is exposed through the [template](https://github.com/istio/istio/blob/master/install/kubernetes/templates/istio-sidecar-injector-configmap-debug.yaml.tmpl) and the `kube-inject` flags should generally be considered as a convenience for common cases and backwards compat.

**Comment by ldemailly** [comment]
I thought the off was already fixed in some other PR already

**Comment by ijsnellf** [comment]
Looks like the default log level part is fixed in master.

**Comment by ayj** [comment]
@ijsnellf, is this issue fixed now in master?

**Comment by ijsnellf** [comment]
The problem is still present. `verbosity` is still ignored in the injection template.

**Comment by ijsnellf** [comment]
`verbosity` has been deprecated. The pilot-agent `--proxyLogLevel` arg serves a similar purpose. Closing.
