### ISSUE TITLE
vm support: `envoy` process stays alive after running `sudo systemctl stop istio`

### ISSUE THREAD

**Issue by yskopets** [istio/istio#34385]
**Bug description**

`envoy` process stays alive after running `sudo systemctl stop istio`.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

When a user runs `sudo systemctl stop istio`, all processes representing an `Istio Sidecar` should be stopped.

**Steps to reproduce the bug**

1. Follow [Virtual Machine Installation](https://preliminary.istio.io/latest/docs/setup/install/virtual-machine/) Guide
2. Run `sudo systemctl stop istio`
3. Run `sudo netstat -tlpn` to confirm that `envoy` process is still running

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
client version: 1.11.0-beta.2
control plane version: 1.11.0-beta.2
data plane version: 1.11.0-beta.2 (8 proxies)
```

**How was Istio installed?**

```
istioctl install
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

* Cloud: `GCP`
* OS: `Debian 10`

**Comment by hzxuzhonghu** [comment]
There was a similar issue reported but was fixed. Is this a new one?

**Comment by yskopets** [comment]
I see 2 related PRs:
1. [#33043](https://github.com/istio/istio/pull/33043) - it was merged, it's a part of `1.11.0-beta.2`, but the issue is still reproducible
2. [#33040](https://github.com/istio/istio/pull/33040) - it wasn't merged

This issue reports the the same problem as [#33040](https://github.com/istio/istio/pull/33040) was trying to fix.

**Comment by hzxuzhonghu** [comment]
@yskopets  Could you help test that patch?

**Comment by yskopets** [comment]
@hzxuzhonghu I replied in https://github.com/istio/istio/pull/33040

**Comment by TamasNeumer** [comment]
I believe I still have this issue on Istio 1.10.4

**Comment by TamasNeumer** [comment]
@yskopets can you please remove the stale lifecycle?

**Comment by zirain** [comment]
not stale

**Comment by TamasNeumer** [comment]
@yskopets can you please remove the stale lifecycle?

**Comment by TamasNeumer** [comment]
@yskopets Can we reopen this?
