### ISSUE TITLE
Move sample Grafana dashboards URLs back to old names like dashboard/db/istio-*-dashboard

### ISSUE THREAD

**Issue by ericvn** [istio/istio#35226]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

https://github.com/istio/istio/pull/35196 caused the Grafana dashboards to be moved from `dashboard/db/istio-*-dashboard` to names like `d/G8wLrJIZk/istio-mesh-dashboard`. This broke the documentation and tests, and that was corrected with https://github.com/istio/istio.io/pull/10349.

Is it possible to move back to the prior names, as they do make more sense in the documentation: see the Urls in https://preliminary.istio.io/latest/docs/tasks/observability/metrics/using-istio-dashboard/#viewing-the-istio-dashboard for example.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by douglas-reid** [comment]
@ericvn have you had any luck in investigating the fix here?

**Comment by zirain** [comment]
Is this fixed by https://github.com/istio/istio.io/pull/10349 ? @ericvn

**Comment by ericvn** [comment]
@zirain I just tried the instructions the pageant if I click on the various dashboards in the UI, they still have the new names. The old names show as not found. Thus the issue still exists.

**Comment by zirain** [comment]
@ericvn I can only make the url to `http://localhost:3000/d/istio-control-plane-dashboard`, I think something changed from the grafana side.

**Comment by zirain** [comment]
cc @ericvn , anything left with this ticket?
