### ISSUE TITLE
Istio Operator Error Loops 

### ISSUE THREAD

**Issue by danninov** [istio/istio#39599]
### Bug Description

We're upgrading our Istio cluster from v1.12.7 to v1.14.1 using Istio Operator. Istio cluster itself is fine, ingressgateway and Istio proxy are updated, but Istio Operator keep looping error and usage memory keep increased.

### Version

```prose
$ istioctl version
client version: 1.14.1
control plane version: 1.14.1
$ kubectl version --short
Client Version: v1.23.3
Server Version: v1.21.11-gke.900
```

### Additional Information

```
error analysis error setting up error handling for kube crdclient: 2 errors occurred:
	* informer has already started
	* informer has already started
```

**Comment by tobymilne-haven** [comment]
I'm also seeing this after a 1.13.2 -> 1.14.1 upgrade on EKS 1.20

$kubectl version --short

Client Version: v1.24.0
Server Version: v1.20.15-eks-a64ea69

**Comment by zirain** [comment]
@tobymilne-haven @danninov do your guys changed the iop configuration more than once?

**Comment by tobymilne-haven** [comment]
@zirain Yes our EKS clusters have had istio on for 2 years, so had several different operator configs. 
However, i can also repro the error on a clean KIND cluster, using the default operator profile.

**Comment by zirain** [comment]
> @zirain Yes our EKS clusters have had istio on for 2 years, so had several different operator configs. However, i can also repro the error on a clean KIND cluster, using the default operator profile.

the root cause of that is multi call of the following function, but I do not have any good idea about how to fix it now.
https://github.com/istio/istio/blob/1aca7a67afd7b3e1d24fafb2fbfbeaf1e41534c0/operator/pkg/helmreconciler/reconciler.go#L154

**Comment by AndreaM12345** [comment]
looks like the issue is also in istio v1.15 and error seems to come from here:

https://github.com/istio/istio/blob/master/pkg/config/analysis/local/istiod_analyze.go#L285

however unclear what is causing the informer to be called again

**Comment by diranged** [comment]
We've been running Istio 1.14.0 for a while, and had Istio on our EKS clusters for the last ~2y as well.. we just started running into this. We're seeing this on both 1.22 and 1.23 EKS clusters and we are hitting exactly the same behavior and logs. Tried upgrading to 1.14.3 with no change in the behavior.

**Comment by NexiStein** [comment]
This is also an error we are facing in AKS version >= 1.22 in multiple Istio versions, but with different behavior:

- Istio version 1.13.2: the operator logs include the error, but the operator is able to reconcile the CR and the status is Healthy.
- Istio version 1.14.1+2: same error, but the operator is not able to reconcile the CR and the status of it is Reconciling.
  - The operator is OOM killed every 5-9 days here, which does not happen in 1.13.2

**Comment by jurgen-weber-deltatre** [comment]
I am experiencing this in 1.14.*. As per @NexiStein 256MB resource limit that eventually gets OOMKilled.

**Comment by lajchon** [comment]
Testing for this with a new KIND cluster with Istio v1.14.3-distroless and was able to reproduce the error log entry, along with constant reconciliation loop. After removing the following entry from the IstioOperator custom resource, the Operator no longer logged the error and reconciliation completed.

```
spec:
  values:
    global:
      meshNetworks: {}
```

**Comment by jurgen-weber-deltatre** [comment]
> Testing for this with a new KIND cluster with Istio v1.14.3-distroless and was able to reproduce the error log entry, along with constant reconciliation loop. After removing the following entry from the IstioOperator custom resource, the Operator no longer logged the error and reconciliation completed.
> 
> ```
> spec:
>   values:
>     global:
>       meshNetworks: {}
> ```

I tried this, but I still have the error and reconciliation loop.

**Comment by zirain** [comment]
should be fixed by https://github.com/istio/istio/pull/40727, feel free to reopen.

**Comment by William-Newshutz** [comment]
Istio 1.15.1 has the change zirain added. I still get a continuous reconcile loop in my istio/operator pod but the logs are different now.

> \- Pruning removed resources
> 2022-09-29T12:57:48.412711Z	info	installer	Reconciling IstioOperator
> -snip for length-
> 2022-09-29T12:57:49.690730Z	info	installer	Generated manifest objects are the same as cached for component EgressGateways.
> 2022-09-29T12:57:49.706047Z	info	installer	Generated manifest objects are the same as cached for component IngressGateways.
> \- Pruning removed resources
> 2022-09-29T12:57:51.754029Z	info	installer	Reconciling IstioOperator

**Comment by NexiStein** [comment]
> Istio 1.15.1 has the change zirain added. I still get a continuous reconcile loop in my istio/operator pod but the logs are different now.
> 
> >

We have observed the same behavior but have also managed to resolve it. We have installed Istio components by using the operator approach, i.e. we run `istioctl operator init` and the apply the desired IstioOperator CR after which the operator deploys the necessary components.

After revisiting our IstioOperator CR, we found that using a specific profile (in our case "demo") and at the same time specifying all generated fields in the CR we saw the above behavior. For this reason we have now chosen to only specify the fields which we overwrite, e.g. adding nodeports to the ingressGateway, HPA, resource request+limit, and podaffinity.

Hope it helps.

**Comment by jurgen-weber-deltatre** [comment]
Yeah, pruning your configuration and removing any and all deprecated/default configuration and my reconciliation loop is now resolved also. Thanks!

**Comment by Rahul1804** [comment]
Hi @zirain , I am trying to install istio 1.15.1, and I see errors
**error	analysis	error setting up error handling for kube arbitraryclient: 2 errors occurred:
	* informer has already started
	* informer has already started**
I'm not getting IstioOperator Reconciling loop(As I've patched istiooperator(1.15.1) with the changes in 1.16...), but this error. Do you've some suggestion to fix **"* informer has already started"**
