### ISSUE TITLE
Kind installation with `example/setupkind.sh` fails due to deprecated "PodSecurityPolicy" crd

### ISSUE THREAD

**Issue by davesee** [istio/istio#41888]
### Bug Description

When running the `example/setupkind.sh`  script, the current `metallb` deployment fails at the end with:

```bash
Creating cluster "cluster1" 
...
resource mapping not found for name: "controller" namespace: "" from "https://raw.githubusercontent.com/metallb/metallb/v0.12/manifests/metallb.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "speaker" namespace: "" from "https://raw.githubusercontent.com/metallb/metallb/v0.12/manifests/metallb.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

This happens since the PodSecurityPolicy has been deprecated in K8s / Kind.

### Version

```prose
istioctl version
1.15.3
---
kubectl version --short
Client Version: v1.25.3
Kustomize Version: v4.5.7
```

### Additional Information

Update the script to use the [current referenced](https://kind.sigs.k8s.io/docs/user/loadbalancer/) version of the `metallb` deployment which uses: 

```bash
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
```

**Comment by howardjohn** [comment]
I think this is fixed on master?

**Comment by davesee** [comment]
You are absolutely right, my sincere apologies. Thought I had latest. 

Change was here: https://github.com/istio/istio/commit/11a590c9fd2655cc5a27b7ecd254e677f867f26d 

Closing issue.

**Comment by keithmattix** [comment]
I'm running into this same error message running integration tests. The PodSecurityPolicy is still present in [metallb.yaml](https://github.com/istio/istio/blob/master/common/scripts/metallb.yaml). Should I re-open the issue?

**Comment by howardjohn** [comment]
fwiw it still works, just had error messages

**Comment by keithmattix** [comment]
Ah, I see the real error message now. My bad; please disregard
