### ISSUE TITLE
DestinationPolicy circuitBreaker rules not applied to sidecar "in.<port>" cluster

### ISSUE THREAD

**Issue by prune998** [istio/istio#4751]
# Description
I'm using a DestinationPolicy rule to increase the number of connexions from my client to my server, behind an `istio-ingress`.

client -- grpc + tls --> istio-ingress (port 443) -- grpc --> useredge pod (port 1081)
```
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: useredged-circuit-breaker
  namespace: dev
spec:
  circuitBreaker:
    simpleCb:
      httpConsecutiveErrors: 10
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100
      httpMaxPendingRequests: 1000
      httpMaxRequests: 100000
      httpMaxRequestsPerConnection: 10000
      maxConnections: 100000
      sleepWindow: 30s
  destination:
    name: useredged
```

Looking at the `istio-ingress` `cluster` metrics, I see it is configured as : 
```
out.useredged.dev.svc.cluster.local|grpc::default_priority::max_connections::100000
out.useredged.dev.svc.cluster.local|grpc::default_priority::max_pending_requests::1000
out.useredged.dev.svc.cluster.local|grpc::default_priority::max_requests::100000
out.useredged.dev.svc.cluster.local|grpc::default_priority::max_retries::3
```

This is working fine and I can go up to 10k+ client connexions, which result to around 8 TCP connexions to the `useredge`, multiplexing my 10k+ streams.

## adding Istio Sidecar
When adding the sidecar to the `useredge` pod (using auto-inject annotation), the local Istio config does not take care of the `DestinationPolicy`, leading to a configuration of : 
```
in.1081::default_priority::max_connections::1024
in.1081::default_priority::max_pending_requests::1024
in.1081::default_priority::max_requests::1024
in.1081::default_priority::max_retries::3
```

In this situation, is seems the local Istio Sidecar is limitting the number of requests the pod can handle.

# Version
Istio 0.7.0 + auto_inject on GKE 1.9.6

**Comment by linsun** [comment]
I think it is possible to do that, you'd have to write a pilot webhook to do that customization.  Or wait till the istio control plane fix this.  cc @GregHanson @ijsnellf @costinm @rshriram

**Comment by prune998** [comment]
Well, for testing purpose, I did a simple code change to pilot in `istio/pilot/pkg/proxy/envoy/v1/route.go` line 139 : 

```
// BuildInboundCluster builds an inbound cluster.
func BuildInboundCluster(port int, protocol model.Protocol, timeout *duration.Duration) *Cluster {
	CB := &CircuitBreaker{
		Default: DefaultCBPriority{
			MaxConnections:     100000,
			MaxPendingRequests: 1000,
			MaxRequests:        100000,
			MaxRetries:         5,
		},
	}
	cluster := &Cluster{
		Name:             fmt.Sprintf("%s%d", InboundClusterPrefix, port),
		Type:             ClusterTypeStatic,
		ConnectTimeoutMs: protoDurationToMS(timeout),
		LbType:           DefaultLbType,
		Hosts:            []Host{{URL: fmt.Sprintf("tcp://%s:%d", "127.0.0.1", port)}},
		CircuitBreaker:   CB,
	}
	if protocol == model.ProtocolGRPC || protocol == model.ProtocolHTTP2 {
		cluster.Features = ClusterFeatureHTTP2
	}
	return cluster
}
```

This is pure testing, sounds to be working, but I still have limitations... I'm currently still trying to understand what the issue is...

**Comment by rshriram** [comment]
Solved in the new v1alpha3 implementation that will be available in 0.8. Please try with istio master and configure connection pool size using v1alpha3 rules (examples in the test suite in tests/e2e/tests/pilot/testdata/

**Comment by prune998** [comment]
@rshriram It was either closed too early or I'm missing some config parameters when using the v2 API.
I've deployed Istios 0.8.0 + latest master images for pilot and sidecar, and I still have the limitation of 100 streams per TCP socket when a client+sidecar is talking to a server+sidecar

I'm going to re-TCP dump to understand where the issue is, but my guess is that the `egress sidecar` (on the client) does not honor the max_streams limitation and / or still does not negociate with the `ingress sidecar` (on the server), defaulting to some nghttp default

**Comment by mbanikazemi** [comment]
@prune998 did you the tests you have mentioned above? Does the problem still exist?

**Comment by prune998** [comment]
@mbanikazemi I think 1.0.3 was OK. 
I'm in KubeCon for the coming days (you there ? meetup ? ) and I'll check for sure when I'm back to work.

**Comment by mbanikazemi** [comment]
thank @prune998 
How about the other issue you have open: https://github.com/istio/istio/issues/4777
Is that problem still there? I would like to resolve this problem if it is still there. If not, we can close the issue. Please advise. Thanks.
