### ISSUE TITLE
Unable to read istio configmap on Canonical Kubernetes cluster, "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by ayj** [istio/istio#4938]
@conorcurlett commented on [Tue Feb 13 2018](https://github.com/istio/issues/issues/202)

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**: Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
Istio 0.5.0, procured through https://git.io/getLatestIstio
Canonical Kubernetes in AWS, installed using juju charms, Flannel overlay, Kubernetes v1.9.2

```
istioctl version
Version: 0.5.0
GitRevision: c9debceacb63a14a9ae24df433e2ec3ce1f16fc7
User: root@211b132eb7f1
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Attempted both installation types, no changes in behaviour detected

**What happened**:
Attempted to run the bookinfo sample app following instructions in the documentation, and received the error
```
kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/kube/bookinfo.yaml -c ~/.kube/config.d/juju-context)
Error: could not read valid configmap "istio" from namespace  "istio-system": Get https://xx.xxx.xxxx.xxx:443/api/v1/namespaces/istio-system/configmaps/istio: x509: certificate signed by unknown authority - Use --meshConfigFile or re-run kube-inject with `-i <istioSystemNamespace> and ensure valid MeshConfig exists
error: no objects passed to apply

kubectl get configmap istio -n istio-system -o yaml
apiVersion: v1
data:
  mesh: |-
    # Uncomment the following line to enable mutual TLS between proxies
    authPolicy: MUTUAL_TLS
...
```

**What you expected to happen:**
The sample application would be deployed successfully. Alternatively, fetching the configmap using kubectl should fail for the same reason as istioctl is failing.

**How to reproduce it:**
In a vanilla Canonical Kubernetes installation in AWS, install Istio 0.5.0 and run the bookinfo app following the instructions in the documentation.

---

@terinjokes commented on [Fri Mar 23 2018](https://github.com/istio/issues/issues/202#issuecomment-375820369)

At least in my cause, it seems `istioctl` isn't using the "certificate-authority-data" information from my ~/.kube/config.

---

@Rigdon commented on [Fri Apr 13 2018](https://github.com/istio/issues/issues/202#issuecomment-381182944)

@terinjokes or @conorcurlett  Were you able to find a workaround for this?

---

@Rigdon commented on [Fri Apr 13 2018](https://github.com/istio/issues/issues/202#issuecomment-381187814)

Turns out I was able to work around this with `kubectl config set-cluster ${KUBE_CONTEXT} --insecure-skip-tls-verify=true`.

**Comment by sakshigoel12** [comment]
@ayj are you working on this one?

**Comment by sakshigoel12** [comment]
@Rigdon @conorcurlett @terinjokes can you test if you see this issue with the 0.8 release . We would like to close this if it is fixed for you.

**Comment by ozevren** [comment]
Closing this due to age. Please reopen a new issue if this is still a problem.

**Comment by bazaglia** [comment]
@ozevren Sometimes I get this error:

```
Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "k8s.cluster.local")
```

Usually it happens when I deploy a new pod. Stopping and starting minikube solves it.

**Comment by Rigdon** [comment]
@sakshigoel12 I just confirmed that this is still an issue with 0.8.

**Comment by sakshigoel12** [comment]
@ayj please could you take a look

**Comment by ayj** [comment]
This could possibility be related to the version of github.com/imdario/mergo we've vendored for k8s's go-client. kubectl uses an older version of mergo where `Merge()` overwrites existing values. istioctl uses a newer version which doesn't. This might be manifesting in the k8s client loading code with multiple config sources not being merged properly. See https://github.com/kubernetes/kubernetes/pull/23789, https://github.com/kubernetes/kubernetes/issues/27543, and https://github.com/imdario/mergo/issues/33#issuecomment-357105051.

Experimental patch is available [here](https://github.com/ayj/istio/commit/e0e2b3e142b8ed55844ee459ed9ffe199b495e0a.patch). I haven't been able to reproduce to verify.

**Comment by ayj** [comment]
This should be fixed by https://github.com/istio/istio/pull/6987

**Comment by majorinche** [comment]
hello, 
if is fixed, what is the right method
i tried with kubectl config set-cluster ${KUBE_CONTEXT} --insecure-skip-tls-verify=true
but still not fix

error shows below, which i follow the steps in https://istio.io/docs/tasks/traffic-management/ingress/
[root@k8s01 httpbin-gateway]# kubectl apply -f httpbin-gateway.yaml -n t-istio-ingress
Error from server (InternalError): error when creating "httpbin-gateway.yaml": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: x509: certificate has expired or is not yet valid

**Comment by kahramanakyil** [comment]
Still getting this error when installed istio on local on-promise kubernetes cluster. Error from server (InternalError): error when creating "microservices.yaml": Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: x509: certificate signed by unknown authority
