### ISSUE TITLE
Deprecation warnings for downstream_connections

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#49490]
```
2024-02-22T15:04:15.263650Z     warning envoy main external/envoy/source/server/server.cc:923   There is no configured limit to the number of allowed active downstream connections. Configure a limit in `envoy.resource_monitors.downstream_connections` resource monitor.  thread=20
2024-02-22T15:04:15.264806Z     warning envoy main external/envoy/source/server/server.cc:833   Usage of the deprecated runtime key overload.global_downstream_max_connections, consider switching to `envoy.resource_monitors.downstream_connections` instead.This runtime key will be removed in future.    thread=20
```

Previously attempted in https://github.com/istio/istio/pull/47474, but it was alpha at the time.

Now its stable though. Time to move?

One question I have -- we are actually setting this to set the limit to ~max_int. Do we really need it at all?

cc @briansonnenberg

**Comment by howardjohn** [comment]
IIRC when the feature was added originally it would give a bunch of spam if you did _not_ set it. Like not just a log, but 100s of logs or something. We couldn't set it to anything low because its dangerous for us to arbitrarily deny connections when we are dealing with arbitrary workloads, so we set it to the max to silence the logs really

**Comment by ramaraochavali** [comment]
My vote would be to remove this and see what happens now instead of moving those to resource monitors OOB.

**Comment by hammadzz** [comment]
I am seeing this error since upgrading to istio v1.22.2, is there a config fix/workaround or will it be addressed in a new version of istio?

**Comment by jbilliau-rcd** [comment]
I as well, did this ever get implemented into a released version of Istio? Seeing it in my sidecars on Istio 1.22.5.

@howardjohn @ramaraochavali

**Comment by ramaraochavali** [comment]
Are you seeing a sinlge log line or multiple log lines?

**Comment by hzxuzhonghu** [comment]
https://github.com/envoyproxy/envoy/pull/30620  This warning will no occur in new release

**Comment by akshaysgithub** [comment]
> [envoyproxy/envoy#30620](https://github.com/envoyproxy/envoy/pull/30620) This warning will no occur in new release

Thank you, when is the new release expected?

**Comment by adamdavis40208** [comment]
1.25, for anyone who stumbles here https://istio.io/latest/news/releases/1.25.x/announcing-1.25/change-notes/

**Comment by adamdavis40208** [comment]
still seeing these log messages on 1.25:

```
image: docker.io/istio/proxyv2:1.25.0
imageID: docker.io/istio/proxyv2@sha256:8489a7
```

Pod logs:
```
2025-03-05T04:58:17.861527Z     warning envoy main external/envoy/source/server/server.cc:863   Usage of the deprecated runtime key overload.global_downstream_max_connections, consider switching to `envoy.resource_monitors.global_downstream_max_connections` instead.This runtime key will be removed in future. thread=23
2025-03-05T04:58:17.862362Z     warning envoy main external/envoy/source/server/server.cc:959   There is no configured limit to the number of allowed active downstream connections. Configure a limit in `envoy.resource_monitors.global_downstream_max_connections` resource monitor.       thread=23
```

**Comment by shaoye** [comment]
seeing these in 1.24.3

```
2025-03-20T22:00:46.509816Z	warning	envoy main external/envoy/source/server/server.cc:843	Usage of the deprecated runtime key overload.global_downstream_max_connections, consider switching to `envoy.resource_monitors.downstream_connections` instead.This runtime key will be removed in future.	thread=13
```

**Comment by isaac88** [comment]
Hello,

I wanted to bring to your attention that we are currently using proxyv2:1.25.1. However, we are still experiencing a persistent WARN message that seems to be quite noisy.

Any insights or suggestions on how to address this issue would be greatly appreciated. Thank you!

```
There is no configured limit to the number of allowed active downstream connections. Configure a limit in `envoy.resource_monitors.global_downstream_max_connections` resource monitor.

Usage of the deprecated runtime key overload.global_downstream_max_connections, consider switching to `envoy.resource_monitors.global_downstream_max_connections` instead.This runtime key will be removed in future.

```

**Comment by ramaraochavali** [comment]
Can you please share the proxy log and env vars set?

**Comment by frittentheke** [comment]
FWIW, we've been observing the same noise in the logs:
`
Usage of the deprecated runtime key overload.global_downstream_max_connections, consider switching to envoy.resource_monitors.global_downstream_max_connections instead. This runtime key will be removed in future.
`

We run 1.24.4 via Helm chart - the relevant values are:
```
meshConfig:
  # Config for the default ProxyConfig.
  defaultConfig:
    runtimeValues:
      "overload.global_downstream_max_connections": "100000"
```

resulting in the `istio` configmap containing:

```
kind: ConfigMap
apiVersion: v1                                                                                                                                                                                                                                                                           
data:
  mesh: |-

[...]
                                                   
    defaultConfig:

[...]                                                                
      runtimeValues:
        overload.global_downstream_max_connections: "100000"

[...]
```

**Comment by ramaraochavali** [comment]
https://github.com/istio/istio/pull/54738 - This is the fix. I do not think it is available in 1.24.x?

**Comment by shaoye** [comment]
we upgraded to 1.25.2 and still seeing the deprecation warnings

**Comment by jt-shippit** [comment]
I just upgraded to 1.25.3 and still seeing these deprecation warnings too. Is there any extra configuration required to have them disabled?

**Comment by ramaraochavali** [comment]
We found at one place this is still happening. We are working the fix @vamshi177

**Comment by frittentheke** [comment]
@ramaraochavali would you kindly have a pointer to the issue / PR for the upcoming change?
1.27.1 still throws this warning ...

**Comment by ramaraochavali** [comment]
https://github.com/envoyproxy/envoy/pull/40919 - This is merged last week

**Comment by frittentheke** [comment]
> [envoyproxy/envoy#40919](https://github.com/envoyproxy/envoy/pull/40919) - This is merged last week

Thanks @ramaraochavali  As I understand this "just" skips the logged warning about the deprecation, but it does NOT fix the deprecation itself, right?

**Comment by ramaraochavali** [comment]
correct

**Comment by frittentheke** [comment]
Consider me confused.
1) What about the "undeprecation" of this config key by Envoy (https://github.com/envoyproxy/envoy/pull/30620/ // https://github.com/istio/istio/issues/49490#issuecomment-2421278474)? Or was it deprecated again in favor of the downstream connections monitor? 

2) Should this issue then not remain open until the ISSUE reported by @howardjohn was fixed. Fixed likely by moving to the 
downstream connection monitor as previously attempted / proposed by https://github.com/istio/istio/pull/47474
Any you @ramaraochavali  said in https://github.com/istio/istio/issues/49490#issuecomment-1966865392 yourself that you favor the replacement. The monitor seems ready: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/resource_monitors/downstream_connections/v3/downstream_connections.proto

**Comment by ramaraochavali** [comment]
1. Yes. It was deprecated again
> Any you @ramaraochavali said in https://github.com/istio/istio/issues/49490#issuecomment-1966865392 yourself that you favor the replacement.

I was suggesting to remove this key completely because the value we set is not useful

**Comment by adem-durakovic-equifax** [comment]
> [envoyproxy/envoy#40919](https://github.com/envoyproxy/envoy/pull/40919) - This is merged last week

Which version of istio will this change come with? @ramaraochavali

**Comment by ramaraochavali** [comment]
That is not needed. I fixed in Master with this https://github.com/istio/istio/pull/57823

**Comment by adem-durakovic-equifax** [comment]
> That is not needed. I fixed in Master with this [#57823](https://github.com/istio/istio/pull/57823)

I am on Istio version 1.25.2 and I am still seeing those logs, any changes you reccomend?

**Comment by ramaraochavali** [comment]
1.25.2 does not have that fix. Please wait till 1.28 is released

**Comment by frittentheke** [comment]
@ramaraochavali @howardjohn sorry to get back to you on this one after the fact (merge of https://github.com/istio/istio/pull/57823).
But I believe the fix does have side effects / is not a proper one ...

Your PR removed the runtime flag `overload.global_downstream_max_connections` in favor of the `envoy.resource_monitors.global_downstream_max_connections` overload resource_monitor:

https://github.com/istio/istio/pull/57823/changes#diff-8f3cc6e4d0a41f3371120cb3c1fcf80af3bc37eb7e0b0f4c696578b75352f0aeL376 -> https://github.com/istio/istio/pull/57823/changes#diff-dc74fae565827d99d96be83fe1c95391dfa4c0005b88917e22ca71234e8e97edR754

this while maintaining the same value of `2147483647`.

So in theory this was just a change in how the same value was applied.


But the static runtime value could be overridden via `runtimeValues` like, e.g. via annotations

```
[...]
    proxy.istio.io/config: |
      runtimeValues:
        "overload.global_downstream_max_connections": "100000"
[...]
```

while the new approach leaves the resource_monitor at the same MAXINT static value (one that is certainly too large, thus the warning / recommendation to properly configure this at https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager#limiting-active-connections.

So in essence with Istio 1.28.1 looking at the resulting proxy config it now looks like this:

```
{
 "configs": [
  {
   "@type": "type.googleapis.com/envoy.admin.v3.BootstrapConfigDump",
   "bootstrap": {

[...]

       "runtimeValues": {
        "overload.global_downstream_max_connections": "100000"
       },

[..]

    "overload_manager": {
     "resource_monitors": [
      {
       "name": "envoy.resource_monitors.global_downstream_max_connections",
       "typed_config": {
        "@type": "type.googleapis.com/envoy.extensions.resource_monitors.downstream_connections.v3.DownstreamConnectionsConfig",
        "max_active_downstream_connections": "2147483647"
       }
      }
     ]
    },
    "layered_runtime": {
     "layers": [
      {
       "name": "global config",
       "static_layer": {
        "envoy.reloadable_features.http_reject_path_with_fragment": false,
        "re2.max_program_size.error_level": "32768",
        "envoy.deprecated_features:envoy.config.listener.v3.Listener.hidden_envoy_deprecated_use_original_dst": true,
        "overload.global_downstream_max_connections": "100000"
       }
      },
      {
       "name": "admin",
       "admin_layer": {}
      }
     ]
    }
```

1. I did not check weather the co-existence of runtime value and overload manager causes the limit to still be in place. However this weird mix of the two approaches to achieve a connection limit should not remain this way.

2. The previously documented way of configuring a connection limit via `overload.global_downstream_max_connections` parameter in runtime value (https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig-runtime_values) would need to be mentioned to be obsolete in the release notes.

3. A new value for "global connection limit" that is "just Istio config" should be introduced and then be used to set `max_active_downstream_connections` in the resource_monitor to the user-intended value. Leaving MAXINT makes no sense, as it 
  a) renders the overload monitor pressure value useless
  b) is conflicting with the runtime value

4. Last but not least I ended up noticing these issues, because I worked on an overload manager config (like enabled with this PR https://github.com/istio/istio/issues/14366) which included


```
overload_manager:
  refresh_interval: 5s
  resource_monitors:
    - name: "envoy.resource_monitors.global_downstream_max_connections"
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.resource_monitors.downstream_connections.v3.DownstreamConnectionsConfig
        max_active_downstream_connections: 100000
```


but since your PR already added such a monitor, this causes Envoy to reject the config due to the duplicate.



@ramaraochavali I gladly open a new issue if you feel this makes more sense than re-opening this one.

**Comment by ramaraochavali** [comment]
Yes. Please open another issue and I will take a look

**Comment by frittentheke** [comment]
> Yes. Please open another issue and I will take a look

Thanks @ramaraochavali - I just opened https://github.com/istio/istio/issues/58594
