### ISSUE TITLE
Add tests for readiness and liveness probes on statefulsets with multiple replicas.

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#5037]
istio sidecar injection causes readliness and liveness probe failure with `statefulsets` on the second pod

  Warning  Unhealthy              5m    kubelet, gke-joy-test-default-pool-cf9a73c3-0pcq  Readiness probe failed: Get http://10.44.10.13:9001/healthz: read tcp 10.44.10.1:33344->10.44.10.13:9001: read: co

```
kind: StatefulSet
spec:
  replicas: 2
....
    spec:
      containers:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9001
        name: esp
        ports:
        - containerPort: 9001
          name: health
          protocol: UDP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9001
```

**Comment by xiaolanz** [comment]
Same problem observed on replicasets too

**Comment by xiaolanz** [comment]
Filed an issue: https://github.com/kubernetes/kubernetes/issues/62798

**Comment by xiaolanz** [comment]
added

  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 10

1) Increase the number of pilot pods
2) Change the discoveryRefreshDelay from 1s to 5s.

**Comment by morvencao** [comment]
Please refer to: https://github.com/istio/istio/issues/2628

**Comment by liamawhite** [comment]
@xiaolanz is this still an issue in 0.8?

**Comment by wattli** [comment]
I believe this should be solved in 0.8, will give a try and update this issue soon.

**Comment by aneslozo** [comment]
I can confirm that issue is still present in 0.8. 
As soon as I remove readiness and liveness everything is working fine.

**Comment by csabakollar** [comment]
having the same issue with istio-0.8.0 and postgres (timescaledb).

I set liveness and readiness probes to:
```
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - su - postgres -c "pg_isready --host=$POD_IP"
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: timescaledb
        ports:
        - containerPort: 5432
          name: psql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - su - postgres -c "pg_isready --host=$POD_IP"
```
(POD_IP env var is a fieldRef from fieldPath: status.podIP)

Replaced the $POD_IP with 127.0.0.1, the pod stays alive.
Maybe this "workaround" will help for some.

**Comment by alastairs** [comment]
I'm seeing this issue in Istio 1.1.0, deployed to Kubernetes 1.11.2 with the Helm chart (default settings, etc.). RBAC is enabled on this cluster.

**Comment by wattli** [comment]
@alastairs , do you have mTLS enabled or not? To clarify: are you saying using absolute URL with command line (instead of httpGet) does not work?

@incfly FYI

**Comment by wattli** [comment]
@alastairs , thanks for your info.

@mandarjog has is currently working on it and it should be out by 1.1 release.

**Comment by incfly** [comment]
@alastairs The failure in mTLS enabled is kinda expected, but it's unclear to me why after turning off the mTLS http probing still failing...

**Comment by alastairs** [comment]
Thanks @incfly. I'm in the process of redeploying the k8s cluster now, I want to try again with a clean cluster with Istio 1.0.1 this time.

I tried uninstalling and reinstalling on the existing cluster, but there's all sorts of weirdness happening: telemetry and policy pods not starting properly, again apparently due to liveness issues.

Honestly, the documentation on getting started could use some work. I've tried the following installation methods:
 - `helm install` on the original cluster on AKS (failures described here)
 - Google Deployment Manager deployment following [the quick start](https://istio.io/docs/setup/kubernetes/quick-start-gke-dm/), which failed because the deployment template's specified version of Kubernetes (1.10.5 IIRC) wasn't available to me

Nothing has worked for me out of the box. I'd really like to use Istio in our production k8s cluster, but right now I don't see how we'd be able to install it successfully. I'm really hoping the fresh AKS cluster I'm now creating will work better...

**Comment by alastairs** [comment]
> Nothing has worked for me out of the box. I'd really like to use Istio in our production k8s cluster, but right now I don't see how we'd be able to install it successfully. I'm really hoping the fresh AKS cluster I'm now creating will work better...

I think I've finally managed to get Istio 1.0.1 running on a new AKS cluster. I used the `helm template` approach for installing istio this time, and everything in `istio-system` seems much happier now. I'm going to continue deploying application services to the cluster in spare time over the next few days, and will update this thread with further information.

**Comment by duderino** [comment]
Any update?

**Comment by avik-so** [comment]
@alastairs Any update here? Does silence mean it was a success?

**Comment by alastairs** [comment]
No, no luck unfortunately. We ended up abandoning our investigations as we couldn’t get RabbitMQ running on the test cluster.

**Comment by howardjohn** [comment]
I think readiness probes work now, for other stateful set issues see https://github.com/istio/istio/issues/10659
