### ISSUE TITLE
Create two gateways will lead the second gateway does not work

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#6046]
I deployed two applications including bookinfo and httpbin.

1) Create gateway and virutalservice for httpbin first, and httpbin works fine.
```
[root@gyliu-icp-1 istio-0.8.0]# cat <<EOF | istioctl create -f -
> apiVersion: networking.istio.io/v1alpha3
> kind: Gateway
> metadata:
>   name: httpbin-gateway
> spec:
>   selector:
>     istio: ingressgateway # use Istio default gateway implementation
>   servers:
>   - port:
>       number: 80
>       name: http
>       protocol: HTTP
>     hosts:
>     - "*"
> EOF
Created config gateway/default/httpbin-gateway at revision 1709253
```
```
[root@gyliu-icp-1 istio-0.8.0]#
[root@gyliu-icp-1 istio-0.8.0]# cat <<EOF | istioctl create -f -
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: httpbin
> spec:
>   hosts:
>   - "*"
>   gateways:
>   - httpbin-gateway
>   http:
>   - match:
>     - uri:
>         prefix: /status
>     - uri:
>         prefix: /delay
>     route:
>     - destination:
>         port:
>           number: 8000
>         host: httpbin
> EOF
Created config virtual-service/default/httpbin at revision 1709254
```
```
[root@gyliu-icp-1 istio-0.8.0]# curl --resolve httpbin.example.com:$INGRESS_PORT:$INGRESS_HOST -I http://httpbin.example.com:$INGRESS_PORT/status/200
HTTP/1.1 200 OK
server: envoy
date: Wed, 06 Jun 2018 03:15:45 GMT
content-type: text/html; charset=utf-8
access-control-allow-origin: *
access-control-allow-credentials: true
content-length: 0
x-envoy-upstream-service-time: 8
```

2) Deploy gateway and virtualservice for bookinfo and bookinfo will not work.
```
[root@gyliu-icp-1 istio-0.8.0]# istioctl create -f samples/bookinfo/routing/bookinfo-gateway.yaml
Created config gateway/default/bookinfo-gateway at revision 1709319
Created config virtual-service/default/bookinfo at revision 1709320
```
The curl command return nothing and no log in `istio-proxy` of bookinfo.
```
[root@gyliu-icp-1 istio-0.8.0]# curl $INGRESS_HOST:$INGRESS_PORT/productpage
```

3) All of the gateway and virtualservices in my cluster.
```
[root@gyliu-icp-1 istio-0.8.0]# istioctl get virtualservices -oyaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: bookinfo
  namespace: default
  resourceVersion: "1709320"
spec:
  gateways:
  - bookinfo-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: httpbin
  namespace: default
  resourceVersion: "1709254"
spec:
  gateways:
  - httpbin-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
---
```
```
[root@gyliu-icp-1 istio-0.8.0]# istioctl get gateway -oyaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  creationTimestamp: null
  name: bookinfo-gateway
  namespace: default
  resourceVersion: "1709319"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  creationTimestamp: null
  name: httpbin-gateway
  namespace: default
  resourceVersion: "1709253"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
---
```

But if I delete gateway of httpbin, then productpage works fine.
```
[root@gyliu-icp-1 istio-0.8.0]# istioctl delete virtualservices httpbin
Deleted config: virtualservices httpbin
```
```
[root@gyliu-icp-1 istio-0.8.0]# istioctl delete gateway httpbin-gateway
Deleted config: gateway httpbin-gateway
```
```
[root@gyliu-icp-1 istio-0.8.0]# curl $INGRESS_HOST:$INGRESS_PORT/productpage
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Bookstore App</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  </head>
  <body>



<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">BookInfo Sample</a>
        </div>

        <button type="button" class="btn btn-default navbar-btn navbar-
....
```

@rshriram @vadimeisenbergibm @cmluciano comments for this?

**Comment by gyliu513** [comment]
Duplicate with https://github.com/istio/istio/issues/6045

Pilot log report the follows:
```
2018-06-06T02:55:28.761534Z     warn    ads     ADS:LDS: ACK ERROR 10.1.158.215:50602 istio-ingressgateway-7d89dbf85f-mpllq.istio-system version_info:"2018-06-06 02:55:03.601637912 +0000 UTC m=+333.043700598" node:<id:"router~10.1.158.215~istio-ingressgateway-7d89dbf85f-mpllq.istio-system~istio-system.svc.cluster.local" cluster:"istio-ingressgateway" metadata:<fields:<key:"POD_NAME" value:<string_value:"istio-ingressgateway-7d89dbf85f-mpllq" > > fields:<key:"istio" value:<string_value:"sidecar" > > > build_version:"0/1.7.0-dev//RELEASE" > type_url:"type.googleapis.com/envoy.api.v2.Listener" response_nonce:"2018-06-06 02:55:28.670130244 +0000 UTC m=+358.112192937" error_detail:<code:13 message:"Error adding/updating listener 0.0.0.0_80: Only a single wildcard domain is permitted" >
```

**Comment by thedebugger** [comment]
I think we should reopen this issue for a couple of reasons 

1) it causes ingress config to go stale. So no changes are reflected to ingress controller if someone adds a gateway with same rules. Ideally, Istio should validate the create gateway request and reject for this use case. 

2) How does a virtual service refer to the gateway if the default gateway is not present in the same namespace? So let's suppose if the default gateway exists in namespaceA, how does a virtual service in namespaceB can refer to default gateway? AFAIT from virtual service doc, it takes a list of gateway name. The other option is to create the gateway in the namespaceB and refer it in the virtual service but that causes above problem.

Thoughts?

**Comment by gyliu513** [comment]
+1 to @thedebugger 

For 1), Yes, I think we should fail fast as long as there are duplicate gateways with same rules.

For 2), I think the gateway in one namespace can only be accessed by virutalservice in same namespace.

@rshriram @cmluciano  comments for this?

**Comment by gyliu513** [comment]
Let's get some comments from @rshriram

**Comment by fevin86** [comment]
I walked into this problem as well. I really want to have the flexibility to keep virtual services defined in their own namespace; I think this is a nicer way to organise things.

I am happy having just one global gateway in `default` namespace.

**Comment by rshriram** [comment]
I fixed a bug today with respect to gateway references. When referring to a gateway in another namespace use the fqdn (name.ns.svc.cluster.local).

**Comment by gyliu513** [comment]
@rshriram great, can you please link your PR here so that I can close this?

**Comment by andraxylia** [comment]
Fixed in #6483

**Comment by saratkoganti** [comment]
Hi,

I'm using 1.0.2 and I'm still facing the same issue mentioned in this ticket. Here is the scenario - 

#HTTPS with mTLS -- webapi
cat <<EOF | kubectl apply -n istio-system -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: webapi-gw-mtls
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: MUTUAL
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      caCertificates: /etc/istio/ingressgateway-ca-certs/webapi.pem
    hosts:
    - "webapi.example.com"
EOF

cat <<EOF | kubectl apply -n istio-system -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapi-gw
spec:
  hosts:
  - "webapi.example.com"
  gateways:
  - corewebapi-gw-mtls
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: webapi.example.svc.cluster.local
EOF

#HTTPS with mTLS -- beautapp
cat <<EOF | kubectl apply -n istio-system -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: beautapp-gw-mtls
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: MUTUAL
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      caCertificates: /etc/istio/ingressgateway-ca-certs/beautapp.pem
    hosts:
    - "beautapp.example.com"
EOF

cat <<EOF | kubectl apply -n istio-system -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: beautapp-gw
spec:
  hosts:
  - "beautapp-istio.techshed-dev.com"
  gateways:
  - beautapp-gw-mtls
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8000
        host: beautapp.example.svc.cluster.local
EOF

After that, when I access webapi, I get 200 and when I access beautapp I get `curl: (35) gnutls_handshake() failed: Error in the pull function.`

**Comment by vadimeisenbergibm** [comment]
@kubaj Note this is documented here https://preliminary.istio.io/docs/tasks/traffic-management/secure-ingress/#configure-a-tls-ingress-gateway-for-multiple-hosts. You should add a new certificate for your second host.

**Comment by vadimeisenbergibm** [comment]
@saratkoganti do you use mTLS to communicate with your cluster? I see the same server certificate in both hosts, don't you have to use different certificates per each host?

Take a look at  https://preliminary.istio.io/docs/tasks/traffic-management/secure-ingress/#configure-a-tls-ingress-gateway-for-multiple-hosts.

**Comment by kubaj** [comment]
@vadimeisenbergibm I'm using a wildcard certificate, so I have only one shared certificates for subdomains.

**Comment by vadimeisenbergibm** [comment]
@kubaj I see. Can you try to use a single gateway with two servers, as in this example https://preliminary.istio.io/docs/tasks/traffic-management/secure-ingress/#configure-a-tls-ingress-gateway-for-multiple-hosts ?

**Comment by kubaj** [comment]
I have tried to redeploy ingress-gateway with wildcard certificate mounted two times:

original ceritificate path:
```
/etc/istio/ingressgateway-certs/
```
and to the another path:
```
/etc/istio/ingressgateway-certs-b/
```

and I have changed the second gateway's TLS serverCertificate and privateKey to following:
```
tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs-b/tls.crt
      privateKey: /etc/istio/ingressgateway-certs-b/tls.key
```

and it makes no difference, problem with ssl persists:
```
curl -v https://b.example.com/
*   Trying 1.2.3.4...
* TCP_NODELAY set
* Connected to b.example.com (1.2.3.4) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to b.example.com:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to b.example.com:443
```

**Comment by gramic** [comment]
The problem is in the wildcard certificate.
After I created different certs for every sub domain and the root domain, everything works find again.
Even if one domain or sub domain uses a wildcard certificate, some will not work.
The workaround is to not use wildcard for now.
Using istio-1.0.0 on the cluster.

**Comment by tmc** [comment]
@gramic is there an issue open for that?
