### ISSUE TITLE
No Pod Registration with Non-default Cluster Domain

### ISSUE THREAD

**Issue by Rigdon** [istio/istio#6313]
**Describe the bug**

Pilot discovery is unable to properly register pods and services when running a kubernetes where the `--cluster-domain` argument to kubelet has more than two sections (for example `weimaraner.cluster.local`) and the `--domain` argument passed to the sidecar injector is set to `"$(POD_NAMESPACE).svc.weimaraner.cluster.local"` as described in the [pilot-agent docs](https://istio.io/docs/reference/commands/pilot-agent/#pilot-agent%20proxy).

Log line from the application pod's proxy container
```
[2018-06-15 05:26:21.597][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:235] gRPC config stream closed: 2, 1 error occurred:%0A%0A* invalid node domain format "datadog.svc.weimaraner.cluster.local". Should be <namespace>.svc.cluster.local
```

The error appears to be coming from [here](https://github.com/istio/istio/blob/5c20da865125980921d2652e31fee47f19d2af73/pilot/pkg/serviceregistry/kube/conversion.go#L178-L190).

Log line from the discovery container of the Pilot pod
```
2018-06-15T05:29:27.554544Z	error	invalid service node 172.30.25.122 httpbin2-7949878d89-drsw2.datadog invalid node domain format "datadog.svc.weimaraner.cluster.local". Should be <namespace>.svc.cluster.local
```

**Expected behavior**
Pod registration should work exactly as it does on clusters with the default cluster domain.

**Steps to reproduce the bug**
1. set up a kubernetes cluster with a `--cluster-domain` divided by more than 1 period (.). 
1. Pass the `--domain` argument to a proxy sidecar according to the pilot agent docs linked above.

**Version**
Istio 0.8 Release
Kubectl 1.10.4

**Is Istio Auth enabled or not?**
Installed using Helm. Mostly default values, only citadel, pilot, and sidecar-injector enabled. added the following two lines to the [sidecar injector configmap](https://github.com/istio/istio/blob/0.8.0/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml#L106)

```
        - --domain
        - "$(POD_NAMESPACE).svc.weimaraner.cluster.local"
```

**Environment**
AWS, self-managed Kubernetes clusters on Ubuntu 18.04 LTS

**Comment by kyessenov** [comment]
Thanks for filing this issue. It's been difficult to enforce the use of "cluster domain" parameter consistently through the system, so there are bits here and there that hardcode "svc.cluster.local".

/cc @rshriram @costinm @louiscryan

**Comment by Rigdon** [comment]
A side note that may end up being an issue: We'll be running multiple Kubernetes clusters and each of these will have a different cluster domain but using a centralized control plane as described in #6092.

**Comment by andraxylia** [comment]
This does not look like a critical issue to be backported to 0.8.1, does it?

**Comment by Rigdon** [comment]
@andraxylia It should be, because this is the setup we're using for our Kubernetes clusters as described in the [kubelet docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/#options) as `--cluster-domain`. It's also in the [Istio docs](https://istio.io/docs/reference/commands/pilot-agent/#pilot-agent%20proxy) as an argument to Pilot itself. If this isn't back-ported to 0.8.1 that configuration option should be removed from the docs and a caveat added to indicate that custom cluster domains aren't supported.

**Comment by andraxylia** [comment]
@Rigdon if we fix the documentation, can you workaround the lack of the complete fix in 0.8.1, until 1.0 is released?

**Comment by Rigdon** [comment]
We're doing some exploratory testing to see if we can work around it. It's currently a total blocker. For a sense of the intrusiveness of this issue, if we do find a workaround it'll almost certainly involve rebuilding our Kubernetes clusters.

**Comment by Rigdon** [comment]
Someone more familiar with this particular feature would be better suited
to tackle it. Kuat's comment above makes it seem like this is a bit of an
ongoing issue.

**Comment by andraxylia** [comment]
@GregHanson If your commit in #6432 fixes this issue, please close it. We discussed this issue in the nw community meeting, and that more work is required to test this, so please open a separate issues for adding testing and mark is Nebulous Future.

**Comment by hklai** [comment]
Ping. This is included in the [0.8.1 tracker](https://github.com/istio/istio/issues/5982) but this is still open.

Please provide an update as we are finalizing 0.8.1.

**Comment by rshriram** [comment]
This was fixed recently. Don’t have the sha though.

**Comment by andraxylia** [comment]
@Rigdon could you please check with the latest master? #6432 should have fixed this , but there is no automated test.

**Comment by Rigdon** [comment]
@andraxylia #6432 did indeed stop the Pilot errors. Pilot still doesn't register services with the correct cluster domain but at least routing works correctly now using the short service names (i.e., `service.namespace`). IMO #6432 should definitely be backported.

**Comment by AWKIF** [comment]
@andraxylia @Rigdon I will test it right now, but if you can tell me what need to be changed, from what i see:
add --domain to pilot discovery, istio-proxy(sidecar), 
is it needed to add this to every proxy ? (ie ingress gateway, pilot)
Thanks :)

**Comment by AWKIF** [comment]
Finally got it working fine, no errors, all looks good! thanks !!

**Comment by andraxylia** [comment]
great, thanks @AWKIF for the confirmation.

**Comment by deniskril** [comment]
> Finally got it working fine, no errors, all looks good! thanks !!

Can You show example with different domain please?

**Comment by AWKIF** [comment]
@deniskril  a bit late but this is my istio.yaml file from 1.0 version
you can grep for dev.kubernetes
[istio.yaml.tar.gz](https://github.com/istio/istio/files/2441413/istio.yaml.tar.gz)
