### ISSUE TITLE
LoadBalancers present when ingress is disabled for Jaeger.

### ISSUE THREAD

**Issue by ekarlso** [istio/istio#6352]
**Describe the bug**
Jaeger is assigned double LoadBalancers even though I have set to have ingress for Jaeger disabled.

**Expected behavior**
No LoadBalancers should be assigned when you disable the ingress, it's not wanted to expose the Query / UI endpoints publicly?

https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/tracing/templates/service.yaml#L23

**Steps to reproduce the bug**
Steps to reproduce the behavior.

**Version**
0.8 / 1.9.x on AKS

**Is Istio Auth enabled or not?**
I am using the helm chart included in the 0.8.0 release

**Environment**
Azure AKS

**Comment by ymesika** [comment]
@ekarlso I do see the problem (even in master) but I don't see the "double LoadBalancers" that you mentioned.

Can you please share the output where you see double jaeger LB?

**Comment by gyliu513** [comment]
@ekarlso @ymesika  this should have been fixed in https://github.com/istio/istio/pull/6002

**Comment by ymesika** [comment]
With current master, if I enable `tracing` and `jaeger` but disable `ingress` I still have the `jaeger-query` LoadBalancer installed.

**Comment by gyliu513** [comment]
@ymesika I think we need to disable lb for `jaeger-query` as well.
