### ISSUE TITLE
Sidecars crashing with build build master-20180615-09-15

### ISSUE THREAD

**Issue by jnativio** [istio/istio#6363]
**Describe the bug**
Regression Patrol could not run the tests with build master-20180615-09-15, as the injected pods go to a CrashLoopBackOff mode as they are deployed. The log on the istio-proxy container says:

[2018-06-17 21:58:01.262][17][critical][main] external/envoy/source/server/server.cc:77] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': malformed IP address: istio-statsd-prom-bridge

By comparing the injected yaml file from the previous build with the current, I found out that the previous has this for -- statsdUdpAddress argument:
`istio-statsd-prom-bridge.istio-system:9125`

while this build has this:
`istio-statsd-prom-bridge:9125`

So, I edited the yaml file to include the istio-system namespace to the argument and it works.

**Expected behavior**
It should work like it was working in the previous builds.

**Steps to reproduce the bug**
Have an app with injected sidecars using build master-20180615-09-15.

**Version**
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-2+231cc32d0a1119", GitCommit:"231cc32d0a111940d45936b3206548c610869df2", GitTreeState:"clean", BuildDate:"2018-04-25T08:09:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

./istioctl version
Version: master-20180615-09-15
GitRevision: ddc5f752d407ef66b00187292094e3300a282a42
User: root@9e39b1ede738
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

**Is Istio Auth enabled or not?**
Not enabled

**Environment**
IKS

cc @ldemailly

**Comment by ldemailly** [comment]
this sort of networking or helm related @andraxylia can you assign ? (or maybe @linsun ?)

**Comment by ymesika** [comment]
This should be fixed by #6349 
Sorry for that. I guess all our tests are running in the same namespace and that's why tests passed.

**Comment by jnativio** [comment]
This issue still persists on daily build master-20180618-09-15.

**Comment by ymesika** [comment]
The fix still didn't make it into that daily. Should be in the following. 18 is the latest?

**Comment by ldemailly** [comment]
I was asking on slack yesterday how come there are no newer daily - @hklai ?

**Comment by hklai** [comment]
@ldemailly tests had been failing
we are trying to restore it but the June release currently takes higher priority.
