### ISSUE TITLE
[Istio Prelim 1.0]Control plane upgrade ERROR out on upgrade istio.yaml from stio 0.8 to istio-1.0.0-snapshot.0

### ISSUE THREAD

**Issue by janevalleye2e** [istio/istio#7090]
**Describe the bug**
[Istio Prelim 1.0]Control plane upgrade ERROR out on upgrade istio.yaml from stio 0.8 to istio-1.0.0-snapshot.0
Error from server (Invalid): error when applying patch
**Expected behavior**
after control plane upgrade, all services Status should be Running

**Steps to reproduce the bug**
1. Installation on istio-0.8.0:https: //istio.io/docs/guides/bookinfo/
cd  ~/istio-0.8.0
kubectl apply -f install/kubernetes/istio-demo.yaml
kubectl apply -f samples/bookinfo/kube/bookinfo.yaml
bin/istioctl create -f samples/bookinfo/routing/bookinfo-gateway.yaml
kubectl get services
```
NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
details       ClusterIP   10.51.253.57    <none>        9080/TCP   2m
kubernetes    ClusterIP   10.51.240.1     <none>        443/TCP    17h
productpage   ClusterIP   10.51.250.18    <none>        9080/TCP   2m
ratings       ClusterIP   10.51.242.155   <none>        9080/TCP   2m
reviews       ClusterIP   10.51.244.44    <none>        9080/TCP   2m
```
   kubectl get pods
```
NAME                              READY     STATUS    RESTARTS   AGE
details-v1-64b86cd49-xl4dg        1/1       Running   0          2m
productpage-v1-84f77f8747-5npwj   1/1       Running   0          2m
ratings-v1-5f46655b57-g8lsl       1/1       Running   0          2m
reviews-v1-ff6bdb95b-ssjx9        1/1       Running   0          2m
reviews-v2-5799558d68-72smp       1/1       Running   0          2m
reviews-v3-58ff7d665b-dns9b       1/1       Running   0          2m
```
kubectl get pods -n istio-system
```
NAME                                        READY     STATUS    RESTARTS   AGE
grafana-cd99bf478-npmk8                     1/1       Running   0          1m
istio-citadel-ff5696f6f-tlzqg               1/1       Running   0          1m
istio-egressgateway-58d98d898c-6h75v        1/1       Running   0          1m
istio-ingressgateway-6bc7c7c4bc-p4j67       1/1       Running   0          1m
istio-pilot-6c5c6b586c-9kwnt                2/2       Running   0          1m
istio-policy-5c7fbb4b9f-267xw               2/2       Running   0          1m
istio-sidecar-injector-dbd67c88d-ndcdv      1/1       Running   0          1m
istio-statsd-prom-bridge-6dbb7dcc7f-9grkg   1/1       Running   0          1m
istio-telemetry-54b5bf4847-pml5g            2/2       Running   0          1m
istio-tracing-67dbb5b89f-rqz58              1/1       Running   0          1m
prometheus-586d95b8d9-4r6g6                 1/1       Running   0          1m
servicegraph-6d86dfc6cb-bbvp7               1/1       Running   0          1m
```
kubectl get service -n istio-system

```
NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                                                               AGE
grafana                    ClusterIP      10.51.240.112   <none>           3000/TCP                                                              2m
istio-citadel              ClusterIP      10.51.243.87    <none>           8060/TCP,9093/TCP                                                     2m
istio-egressgateway        ClusterIP      10.51.242.121   <none>           80/TCP,443/TCP                                                        2m
istio-ingressgateway       LoadBalancer   10.51.244.32    35.226.208.55    80:31380/TCP,443:31390/TCP,31400:31400/TCP                            2m
istio-pilot                ClusterIP      10.51.240.108   <none>           15003/TCP,15005/TCP,15007/TCP,15010/TCP,15011/TCP,8080/TCP,9093/TCP   2m
istio-policy               ClusterIP      10.51.247.226   <none>           9091/TCP,15004/TCP,9093/TCP                                           2m
istio-sidecar-injector     ClusterIP      10.51.242.33    <none>           443/TCP                                                               2m
istio-statsd-prom-bridge   ClusterIP      10.51.251.54    <none>           9102/TCP,9125/UDP                                                     2m
istio-telemetry            ClusterIP      10.51.255.145   <none>           9091/TCP,15004/TCP,9093/TCP,42422/TCP                                 2m
prometheus                 ClusterIP      10.51.249.187   <none>           9090/TCP                                                              2m
servicegraph               ClusterIP      10.51.250.105   <none>           8088/TCP                                                              2m
tracing                    LoadBalancer   10.51.240.255   35.226.146.146   80:32577/TCP                                                          1m
zipkin                     ClusterIP      10.51.244.245   <none>           9411/TCP                                                              1m
```
2. upgrade on istio-1.0.0-snapshot.0: https://preliminary.istio.io/docs/setup/kubernetes/upgrading-istio/, **got ERRORS**
cd ~/istio-1.0.0-snapshot.0
helm template --namespace istio-system --set global.proxy.image=proxy \
  --values install/kubernetes/helm/istio/values-istio.yaml \
  install/kubernetes/helm/istio >> install/kubernetes/istio.yaml
kubectl apply -f install/kubernetes/istio.yaml

```
ERRORS:
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"batch/v1\",\"kind\":\"Job\",\"metadata\":{\"annotations\":{\"helm.sh/hook\":\"post-install\",\"helm.sh/hook-delete-policy\":\"before-hook-creation\"},\"labels\":{\"app\":\"mixer\",\"chart\":\"mixer-0.8.0\",\"heritage\":\"Tiller\",\"release\":\"RELEASE-NAME\"},\"name\":\"istio-mixer-post-install\",\"namespace\":\"istio-system\"},\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"app\":\"mixer\",\"release\":\"RELEASE-NAME\"},\"name\":\"istio-mixer-post-install\"},\"spec\":{\"containers\":[{\"command\":[\"/bin/bash\",\"/tmp/mixer/run.sh\",\"/tmp/mixer/custom-resources.yaml\"],\"image\":\"quay.io/coreos/hyperkube:v1.7.6_coreos.0\",\"name\":\"hyperkube\",\"volumeMounts\":[{\"mountPath\":\"/tmp/mixer\",\"name\":\"tmp-configmap-mixer\"}]}],\"restartPolicy\":\"OnFailure\",\"serviceAccountName\":\"istio-mixer-post-install-account\",\"volumes\":[{\"configMap\":{\"name\":\"istio-mixer-custom-resources\"},\"name\":\"tmp-configmap-mixer\"}]}}}}\n"}},"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"hyperkube"}],"containers":[{"command":["/bin/bash","/tmp/mixer/run.sh","/tmp/mixer/custom-resources.yaml"],"name":"hyperkube"}],"restartPolicy":"OnFailure"}}}}
to:
&{0xc42100a3c0 0xc42085f500 istio-system istio-mixer-post-install install/kubernetes/istio.yaml 0xc42009cf40 0xc42009d240 90051 false}
for: "install/kubernetes/istio.yaml": Job.batch "istio-mixer-post-install" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"istio-mixer-post-install", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"release":"RELEASE-NAME", "app":"mixer", "controller-uid":"18afae1b-86b9-11e8-adee-42010a8000f0", "job-name":"istio-mixer-post-install"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:"tmp-configmap-mixer", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(0xc42a0b97c0), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"hyperkube", Image:"quay.io/coreos/hyperkube:v1.7.6_coreos.0", Command:[]string{"/bin/bash", "/tmp/mixer/run.sh", "/tmp/mixer/custom-resources.yaml"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"tmp-configmap-mixer", ReadOnly:false, MountPath:"/tmp/mixer", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil)}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc426dcce50), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"istio-mixer-post-install-account", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc42a0b9940), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil)}}: field is immutable
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"batch/v1\",\"kind\":\"Job\",\"metadata\":{\"annotations\":{\"helm.sh/hook\":\"post-install\",\"helm.sh/hook-delete-policy\":\"hook-succeeded\"},\"labels\":{\"app\":\"security\",\"chart\":\"security-0.8.0\",\"heritage\":\"Tiller\",\"release\":\"RELEASE-NAME\"},\"name\":\"istio-cleanup-old-ca\",\"namespace\":\"istio-system\"},\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"app\":\"security\",\"release\":\"RELEASE-NAME\"},\"name\":\"istio-cleanup-old-ca\"},\"spec\":{\"containers\":[{\"command\":[\"/bin/bash\",\"-c\",\"NS=\\\"-n istio-system\\\"; ./kubectl get deploy istio-ca $NS; if [[ $? = 0 ]]; then ./kubectl delete deploy istio-ca $NS; fi; ./kubectl get serviceaccount istio-ca-service-account $NS; if [[ $? = 0 ]]; then ./kubectl delete serviceaccount istio-ca-service-account $NS; fi; ./kubectl get service istio-ca-ilb $NS; if [[ $? = 0 ]]; then ./kubectl delete service istio-ca-ilb $NS; fi\\n\"],\"image\":\"quay.io/coreos/hyperkube:v1.7.6_coreos.0\",\"name\":\"hyperkube\"}],\"restartPolicy\":\"OnFailure\",\"serviceAccountName\":\"istio-cleanup-old-ca-service-account\"}}}}\n"}},"spec":{"template":{"spec":{"restartPolicy":"OnFailure"}}}}
to:
&{0xc420116840 0xc42046e380 istio-system istio-cleanup-old-ca install/kubernetes/istio.yaml 0xc420890e30 0xc4208910a0 90408 false}
for: "install/kubernetes/istio.yaml": Job.batch "istio-cleanup-old-ca" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"istio-cleanup-old-ca", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app":"security", "controller-uid":"3e982d9d-86b9-11e8-adee-42010a8000f0", "job-name":"istio-cleanup-old-ca", "release":"RELEASE-NAME"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"hyperkube", Image:"quay.io/coreos/hyperkube:v1.7.6_coreos.0", Command:[]string{"/bin/bash", "-c", "NS=\"-n istio-system\"; ./kubectl get deploy istio-ca $NS; if [[ $? = 0 ]]; then ./kubectl delete deploy istio-ca $NS; fi; ./kubectl get serviceaccount istio-ca-service-account $NS; if [[ $? = 0 ]]; then ./kubectl delete serviceaccount istio-ca-service-account $NS; fi; ./kubectl get service istio-ca-ilb $NS; if [[ $? = 0 ]]; then ./kubectl delete service istio-ca-ilb $NS; fi\n"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc42ffffab0), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"istio-cleanup-old-ca-service-account", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc42e23ab40), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil)}}: field is immutable
```
3. Workaroud istio.yaml on upgrade
a. remove block Job.batch "istio-mixer-post-install" and block Job.batch "istio-cleanup-old-ca"  from  install/kubernetes/istio.yaml"
b. kubectl apply -f install/kubernetes/istio.yaml
command ran successfully

4. pods -n istio-system status **not Running**
kubectl get pods -n istio-system
```
NAME                                        READY     STATUS             RESTARTS   AGE
grafana-cd99bf478-npmk8                     1/1       Running            0          10m
istio-citadel-74dd8f4d48-jf45l              0/1       ImagePullBackOff   0          5m
istio-egressgateway-7b8b7b99f5-4b578        0/1       ImagePullBackOff   0          5m
istio-galley-566d5d978d-wcpmt               0/1       ImagePullBackOff   0          5m
istio-ingress-7bf95b79f-9jrqg               0/1       ImagePullBackOff   0          5m
istio-ingressgateway-7f4659bdc9-zsxs4       0/1       ImagePullBackOff   0          5m
istio-pilot-66cf4f8dd5-nj5gz                0/2       ImagePullBackOff   0          5m
istio-policy-77f456ccb4-prr67               0/2       ImagePullBackOff   0          5m
istio-sidecar-injector-7bc94664f7-zpgrx     0/1       ImagePullBackOff   0          5m
istio-statsd-prom-bridge-6dbb7dcc7f-9grkg   1/1       Running            0          10m
istio-telemetry-6f89c4bb56-xk266            0/2       ImagePullBackOff   0          5m
istio-tracing-67dbb5b89f-rqz58              1/1       Running            0          10m
prometheus-586d95b8d9-4r6g6                 1/1       Running            0          10m
servicegraph-6d86dfc6cb-bbvp7               1/1       Running            0          10m
```
kubectl get service -n istio-system
```
NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP       PORT(S)                                                               AGE
grafana                    ClusterIP      10.51.240.112   <none>            3000/TCP                                                              11m
istio-citadel              ClusterIP      10.51.243.87    <none>            8060/TCP,9093/TCP                                                     11m
istio-egressgateway        ClusterIP      10.51.242.121   <none>            80/TCP,443/TCP                                                        11m
istio-galley               ClusterIP      10.51.244.73    <none>            443/TCP                                                               5m
istio-ingress              LoadBalancer   10.51.242.54    104.154.235.102   80:32000/TCP,443:30971/TCP                                            5m
istio-ingressgateway       LoadBalancer   10.51.244.32    35.226.208.55     80:31380/TCP,443:31390/TCP,31400:31400/TCP                            11m
istio-pilot                ClusterIP      10.51.240.108   <none>            15003/TCP,15005/TCP,15007/TCP,15010/TCP,15011/TCP,8080/TCP,9093/TCP   11m
istio-policy               ClusterIP      10.51.247.226   <none>            9091/TCP,15004/TCP,9093/TCP                                           11m
istio-sidecar-injector     ClusterIP      10.51.242.33    <none>            443/TCP                                                               11m
istio-statsd-prom-bridge   ClusterIP      10.51.251.54    <none>            9102/TCP,9125/UDP                                                     11m
istio-telemetry            ClusterIP      10.51.255.145   <none>            9091/TCP,15004/TCP,9093/TCP,42422/TCP                                 11m
prometheus                 ClusterIP      10.51.249.187   <none>            9090/TCP                                                              11m
servicegraph               ClusterIP      10.51.250.105   <none>            8088/TCP                                                              11m
tracing                    LoadBalancer   10.51.240.255   35.226.146.146    80:32577/TCP                                                          11m
zipkin                     ClusterIP      10.51.244.245   <none>            9411/TCP                                                              11m
```
5. docker pull got **Error response**
```
docker pull docker.io/istio/pilot:0.8.latest
Error response from daemon: manifest for istio/pilot:0.8.latest not found
janevalley-macbookpro:istio-1.0.0-snapshot.0 janevalley$ docker pull docker.io/istio/galley:0.8.latest
Error response from daemon: manifest for istio/galley:0.8.latest not found
```
**Version**
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.3", GitCommit:"9b5b719c5f295c99de68ffb5b63101b0e0175376", GitTreeState:"clean", BuildDate:"2018-05-31T18:32:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
**Is Istio Auth enabled or not?**
install istio.yaml

**Environment**
tested on MAC

**Comment by janevalleye2e** [comment]
@kidiyoor @mandarjog @vilobhmm@costinm@sdake

**Comment by janevalleye2e** [comment]
this also happened on Istio Prelim 1.0 helm install istio.yaml: ttps://preliminary.istio.io/docs/setup/kubernetes/helm-install/
the steps:
Install with Helm via helm template:
cd ~/istio-1.0.0-snapshot.0
helm template install/kubernetes/helm/istio --name istio --namespace istio-system > $HOME/istio.yaml
kubectl create -f $HOME/istio.yaml
kubectl get pods -n istio-system
```
NAME                                        READY     STATUS              RESTARTS   AGE
istio-citadel-74dd8f4d48-fm8dn              0/1       ImagePullBackOff    0          3m
istio-egressgateway-7b8b7b99f5-v4tpz        0/1       ImagePullBackOff    0          4m
istio-galley-566d5d978d-j8bw5               0/1       ContainerCreating   0          4m
istio-ingress-7bf95b79f-9b4nm               0/1       ImagePullBackOff    0          4m
istio-ingressgateway-7f4659bdc9-9gtqw       0/1       ImagePullBackOff    0          4m
istio-mixer-post-install-rg8km              1/1       Running             0          4m
istio-pilot-66cf4f8dd5-l59cd                0/2       ContainerCreating   0          4m
istio-policy-77f456ccb4-dn78x               0/2       ImagePullBackOff    0          4m
istio-sidecar-injector-7bc94664f7-nn7lb     0/1       ContainerCreating   0          3m
istio-statsd-prom-bridge-6dbb7dcc7f-84jgl   1/1       Running             0          4m
istio-telemetry-7f9589c77b-ccnd8            0/2       ImagePullBackOff    0          4m
prometheus-586d95b8d9-rx6j2                 1/1       Running             0          4m
```
kubectl describe pods -n istio-system istio-citadel-74dd8f4d48-fm8dn
```
Events:
  Type     Reason                 Age               From                                                          Message
  ----     ------                 ----              ----                                                          -------
  Normal   Scheduled              9m                default-scheduler                                             Successfully assigned istio-citadel-74dd8f4d48-fm8dn to gke-kokoro-adapter-publi-default-pool-73392550-7h88
  Normal   SuccessfulMountVolume  9m                kubelet, gke-kokoro-adapter-publi-default-pool-73392550-7h88  MountVolume.SetUp succeeded for volume "istio-citadel-service-account-token-gcvcx"
  Normal   SandboxChanged         8m (x2 over 8m)   kubelet, gke-kokoro-adapter-publi-default-pool-73392550-7h88  Pod sandbox changed, it will be killed and re-created.
  Warning  Failed                 8m (x3 over 8m)   kubelet, gke-kokoro-adapter-publi-default-pool-73392550-7h88  Failed to pull image "docker.io/istio/citadel:0.8.latest": rpc error: code = Unknown desc = Error response from daemon: manifest for istio/citadel:0.8.latest not found
  Warning  Failed                 8m (x3 over 8m)   kubelet, gke-kokoro-adapter-publi-default-pool-73392550-7h88  Error: ErrImagePull
  Normal   BackOff                7m (x6 over 8m)   kubelet, gke-kokoro-adapter-publi-default-pool-73392550-7h88  Back-off pulling image "docker.io/istio/citadel:0.8.latest"
  Normal   Pulling                7m (x4 over 9m)   kubelet, gke-kokoro-adapter-publi-default-pool-73392550-7h88  pulling image "docker.io/istio/citadel:0.8.latest"
  Warning  Failed                 4m (x20 over 8m)  kubelet, gke-kokoro-adapter-publi-default-pool-73392550-7h88  Error: ImagePullBackOff```

**Comment by quanjielin** [comment]
https://github.com/istio/istio/pull/7106 should be fix ```ImagePullBackOff``` error
the upgrade failure in step 2 above repro for me, @ayj

**Comment by sdake** [comment]
This is a dup of https://github.com/istio/istio/issues/7072 - however the wrong images are used in this test case.  snapshot.0 is ~15 days old.

Cheers
-steve

**Comment by janevalleye2e** [comment]
upgrade from istio-0.8.0 to istio-release-1.0-20180713-09-15, I still got errors
kubectl apply -f install/kubernetes/istio.yaml
```
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"helm.sh/hook-delete-policy":"hook-succeeded","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"batch/v1\",\"kind\":\"Job\",\"metadata\":{\"annotations\":{\"helm.sh/hook\":\"post-install\",\"helm.sh/hook-delete-policy\":\"hook-succeeded\"},\"labels\":{\"app\":\"mixer\",\"chart\":\"mixer-1.0.0\",\"heritage\":\"Tiller\",\"release\":\"RELEASE-NAME\"},\"name\":\"istio-mixer-post-install\",\"namespace\":\"istio-system\"},\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"app\":\"mixer\",\"release\":\"RELEASE-NAME\"},\"name\":\"istio-mixer-post-install\"},\"spec\":{\"containers\":[{\"command\":[\"/bin/bash\",\"/tmp/mixer/run.sh\",\"/tmp/mixer/custom-resources.yaml\"],\"image\":\"quay.io/coreos/hyperkube:v1.7.6_coreos.0\",\"name\":\"hyperkube\",\"volumeMounts\":[{\"mountPath\":\"/tmp/mixer\",\"name\":\"tmp-configmap-mixer\"}]}],\"restartPolicy\":\"OnFailure\",\"serviceAccountName\":\"istio-mixer-post-install-account\",\"volumes\":[{\"configMap\":{\"name\":\"istio-mixer-custom-resources\"},\"name\":\"tmp-configmap-mixer\"}]}}}}\n"},"labels":{"chart":"mixer-1.0.0"}},"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"hyperkube"}],"containers":[{"command":["/bin/bash","/tmp/mixer/run.sh","/tmp/mixer/custom-resources.yaml"],"name":"hyperkube"}],"restartPolicy":"OnFailure"}}}}
to:
&{0xc420a5e600 0xc420964380 istio-system istio-mixer-post-install install/kubernetes/istio.yaml 0xc42000d438 0xc42000d738 2256 false}
for: "install/kubernetes/istio.yaml": Job.batch "istio-mixer-post-install" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"istio-mixer-post-install", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"release":"RELEASE-NAME", "app":"mixer", "controller-uid":"205cef1d-878f-11e8-9d28-42010a80007f", "job-name":"istio-mixer-post-install"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:"tmp-configmap-mixer", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(0xc4294a0900), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"hyperkube", Image:"quay.io/coreos/hyperkube:v1.7.6_coreos.0", Command:[]string{"/bin/bash", "/tmp/mixer/run.sh", "/tmp/mixer/custom-resources.yaml"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"tmp-configmap-mixer", ReadOnly:false, MountPath:"/tmp/mixer", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil)}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc4232a1330), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"istio-mixer-post-install-account", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc4294a0c80), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil)}}: field is immutable
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"helm.sh/hook-delete-policy":"hook-succeeded","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"batch/v1\",\"kind\":\"Job\",\"metadata\":{\"annotations\":{\"helm.sh/hook\":\"post-install\",\"helm.sh/hook-delete-policy\":\"hook-succeeded\"},\"labels\":{\"app\":\"mixer\",\"chart\":\"mixer-1.0.0\",\"heritage\":\"Tiller\",\"release\":\"RELEASE-NAME\"},\"name\":\"istio-mixer-post-install\",\"namespace\":\"istio-system\"},\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"app\":\"mixer\",\"release\":\"RELEASE-NAME\"},\"name\":\"istio-mixer-post-install\"},\"spec\":{\"containers\":[{\"command\":[\"/bin/bash\",\"/tmp/mixer/run.sh\",\"/tmp/mixer/custom-resources.yaml\"],\"image\":\"quay.io/coreos/hyperkube:v1.7.6_coreos.0\",\"name\":\"hyperkube\",\"volumeMounts\":[{\"mountPath\":\"/tmp/mixer\",\"name\":\"tmp-configmap-mixer\"}]}],\"restartPolicy\":\"OnFailure\",\"serviceAccountName\":\"istio-mixer-post-install-account\",\"volumes\":[{\"configMap\":{\"name\":\"istio-mixer-custom-resources\"},\"name\":\"tmp-configmap-mixer\"}]}}}}\n"},"labels":{"chart":"mixer-1.0.0"}},"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"hyperkube"}],"containers":[{"command":["/bin/bash","/tmp/mixer/run.sh","/tmp/mixer/custom-resources.yaml"],"name":"hyperkube"}],"restartPolicy":"OnFailure"}}}}
to:
&{0xc420ea1680 0xc4211fd110 istio-system istio-mixer-post-install install/kubernetes/istio.yaml 0xc42037a2a0 0xc420e9c000 2256 false}
for: "install/kubernetes/istio.yaml": Job.batch "istio-mixer-post-install" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"istio-mixer-post-install", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app":"mixer", "controller-uid":"205cef1d-878f-11e8-9d28-42010a80007f", "job-name":"istio-mixer-post-install", "release":"RELEASE-NAME"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:"tmp-configmap-mixer", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(0xc422bcd540), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"hyperkube", Image:"quay.io/coreos/hyperkube:v1.7.6_coreos.0", Command:[]string{"/bin/bash", "/tmp/mixer/run.sh", "/tmp/mixer/custom-resources.yaml"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"tmp-configmap-mixer", ReadOnly:false, MountPath:"/tmp/mixer", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil)}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc429424dd8), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"istio-mixer-post-install-account", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc422bcd6c0), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil)}}: field is immutable
```

**Comment by janevalleye2e** [comment]
I got the build from https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20180713-09-15/

**Comment by janevalleye2e** [comment]
Workaroud istio.yaml on upgrade
a. remove block Job.batch "istio-mixer-post-install"  from install/kubernetes/istio.yaml"
b. kubectl apply -f install/kubernetes/istio.yaml
command ran successfully

get pods -n istio-system
```
NAME                                        READY     STATUS             RESTARTS   AGE
grafana-cd99bf478-p9vpm                     1/1       Running            0          17m
istio-citadel-8c8684ddb-wxg5g               1/1       Running            0          9m
istio-egressgateway-db67db858-5phzs         1/1       Running            0          9m
istio-galley-6f6d864dff-wbb89               1/1       Running            0          9m
istio-ingressgateway-77f4dfc87b-wqpjv       1/1       Running            0          9m
istio-pilot-6c969ff954-p2x7j                2/2       Running            0          9m
istio-policy-758fdccc9f-sh68q               2/2       Running            0          9m
istio-sidecar-injector-59cb9fb975-whcq9     1/1       Running            0          9m
istio-statsd-prom-bridge-66684ccf7b-j7rrq   1/1       Running            0          9m
istio-telemetry-6665669b88-mcl7k            1/2       ImagePullBackOff   0          9m
istio-tracing-67dbb5b89f-q87zx              1/1       Running            0          16m
prometheus-7b6f8b9996-wls5d                 1/1       Running            0          9m
servicegraph-6d86dfc6cb-9pfqs               1/1       Running            1          16m
```
kubectl describe pod  istio-telemetry-6665669b88-mcl7k -n istio-system
```
Events:
  Type     Reason                 Age                From                                                          Message
  ----     ------                 ----               ----                                                          -------
  Normal   Scheduled              12m                default-scheduler                                             Successfully assigned istio-telemetry-6665669b88-mcl7k to gke-kokoro-adapter-publi-default-pool-08415344-z40m
  Normal   SuccessfulMountVolume  12m                kubelet, gke-kokoro-adapter-publi-default-pool-08415344-z40m  MountVolume.SetUp succeeded for volume "uds-socket"
  Normal   SuccessfulMountVolume  12m                kubelet, gke-kokoro-adapter-publi-default-pool-08415344-z40m  MountVolume.SetUp succeeded for volume "istio-certs"
  Normal   SuccessfulMountVolume  12m                kubelet, gke-kokoro-adapter-publi-default-pool-08415344-z40m  MountVolume.SetUp succeeded for volume "istio-mixer-service-account-token-6vs67"
  Normal   Pulling                12m                kubelet, gke-kokoro-adapter-publi-default-pool-08415344-z40m  pulling image "docker.io/istionightly/mixer:nightly-release-1.0"
  Normal   Pulled                 12m                kubelet, gke-kokoro-adapter-publi-default-pool-08415344-z40m  Successfully pulled image "docker.io/istionightly/mixer:nightly-release-1.0"
  Normal   Created                12m                kubelet, gke-kokoro-adapter-publi-default-pool-08415344-z40m  Created container
  Normal   Started                12m                kubelet, gke-kokoro-adapter-publi-default-pool-08415344-z40m  Started container
  Normal   Pulling                11m (x3 over 12m)  kubelet, gke-kokoro-adapter-publi-default-pool-08415344-z40m  pulling image "docker.io/istionightly/proxy:nightly-release-1.0"
  Warning  Failed                 11m (x3 over 12m)  kubelet, gke-kokoro-adapter-publi-default-pool-08415344-z40m  Failed to pull image "docker.io/istionightly/proxy:nightly-release-1.0": rpc error: code = Unknown desc = Error response from daemon: manifest for istionightly/proxy:nightly-release-1.0 not found
  Warning  Failed                 11m (x3 over 12m)  kubelet, gke-kokoro-adapter-publi-default-pool-08415344-z40m  Error: ErrImagePull
  Warning  Failed                 7m (x18 over 12m)  kubelet, gke-kokoro-adapter-publi-default-pool-08415344-z40m  Error: ImagePullBackOff
  Normal   BackOff                2m (x40 over 12m)  kubelet, gke-kokoro-adapter-publi-default-pool-08415344-z40m  Back-off pulling image "docker.io/istionightly/proxy:nightly-release-1.0"
```

**Comment by vilobhmm** [comment]
@sdake @costinm : ^^

**Comment by sdake** [comment]
@janevalleye2e there have been several fixes in this area in the last few days.  We are aware there are problems with upgrade.  Would appreciate if you could try with the latest daily.  I believe there is still one issue left as described here:
https://github.com/istio/istio/issues/7072#issuecomment-404699629

**Comment by janevalleye2e** [comment]
it is fixed and verified on daily build: istio-release-1.0-20180719-09-15

**Comment by vilobhmm** [comment]
Control plane upgrade works fine but Data plane is still broken.
