### ISSUE TITLE
Proposal: Publish Helm chart to a chart repository

### ISSUE THREAD

**Issue by krancour** [istio/istio#7505]
It's a little awkward / bad UX to to have to download Istio from `https://git.io/getLatestIstio` in order to proceed with installing it onto the cluster via Helm. An improved `helm install` UX might look more like this:

```
$ helm repo add istio <url>
$ helm install istio/istio --name istio --namespace istio-system
```

**Comment by monotek** [comment]
Why not to stable/istio?
Imho it's likely most users would search for the chart there first anyway...

**Comment by krancour** [comment]
I think that is reasonable, but the counter-argument is that many projects prefer to keep the charts closer to the source and 100% under their own control.

**Comment by gyliu513** [comment]
I think we can contribute the helm char to https://github.com/helm/charts , and then people can get it from google storage.

FYI @sdake @linsun @costinm

**Comment by grantbachman** [comment]
As a newcomer to Istio, but a longtime user of Helm, I agree the helm chart should be published _somewhere_. Our org wants to keep all of our Kubernetes config under source control, but it's a pain to not be able to just reference a chart repository. Like the other comments mentioned, many people have come to search for charts at https://github.com/helm/charts

**Comment by krancour** [comment]
> I think we can contribute the helm chart to https://github.com/helm/charts , and then people can get it from google storage.

Respectfully, after having written many Helm charts-- some in helm/charts and others, elsewhere, I don't feel helm/charts is the right place for this.

helm/charts is a _great_ place for "off the shelf" software wherein the authors of that software didn't write it with Kubernetes in mind and thus didn't bother to package it as a chart themselves. For instance, take WordPress or Postgres. You can run those _anywhere_. They're open source. But I can take an educated guess that if I offered them the charts to keep in their own source control closer to the source of the products those charts install, they'd say no. helm/charts becomes a good place for the Kubernetes community to add value to that "off the shelf" software by packaging it for installation on Kubernetes.

Now compare this to one of your _own_ projects-- especially one wherein you have an expectation of deploying it (maybe even exclusively) to Kubernetes. You are far, far better off keeping the source for such a chart closer to the source for the software itself. Why?...

Inevitably, you will encounter circumstances where changes to the software necessitate a change to the chart. Consider the case of a simple, non-breaking change like a new feature that is activated by a flag or environment variable. If your chart is kept separate from the software it installs, adding support for that feature requires coordinating two PRs across not only two different projects, but two different _organizations_, each with their own reviewers, processes, and sense of priority.

If your chart is kept in the same repo as the rest of your source, you can implement a new feature with a single PR.

There are other benefits as well...

helm/charts is continuously deployed. On _every_ merge to master, every chart is packaged up and pushed to the cloud storage from where it is hosted. There are some undesirable implications to this. For one, _every single little change you make to the chart results in a new version of the chart_. You very likely do _not_ want that. Compare to the software that the chart installs and it would be like tagging every single commit to master with a semver tag and releasing it to the world.

Keeping your chart's source with the rest of your source fixes this problem. Pending changes can accumulate in the master branch (or dev branch or whatever) and can be versioned and released when _you_ choose-- i.e. in cadence with the release of the software itself.

I strongly urge whoever is the decider on this to _not_ use helm/charts for this.

**Comment by krancour** [comment]
And I know that I probably appear, in the above, to have conflated discussion of where the chart source is kept and where the chart is _hosted_. Sure there's a difference, but not a meaningful one. If your chart's source is in helm/charts, your charts _will_ be published to / hosted by their Helm repository. You'd have no other choice.

It is only by _not_ hosting the chart source in helm/charts that you even allow yourself the option to publish / host the charts elsewhere.

**Comment by aslafy-z** [comment]
see https://github.com/istio/istio.io/pull/2842

**Comment by thomschke** [comment]
Is there a helm repo somewhere that contains the helm charts from all istio releases (not daily-build)?

**Comment by xeor** [comment]
Not yet it seams.. https://github.com/istio/istio/blob/master/Makefile#L87

**Comment by aslafy-z** [comment]
There was kind-of one but it has been sadly removed. It had to be triggered manually but still.

**Comment by xeor** [comment]
Is istio helmchart in a repository happening soon, or is it still going to take a while? There are many pr's and issues on this, all pointing in different directions.. Whats going on?

**Comment by aslafy-z** [comment]
I built a small helm add-on to address this kind of issue, see https://github.com/aslafy-z/helm-git

**Comment by berstend** [comment]
In case anyone else is having issues with the istio helm chart repo flow, I've posted a working setup here: https://github.com/istio/istio/issues/10402#issuecomment-465131590

**Comment by krancour** [comment]
It's a little disheartening that 7 months later this is unresolved. The UX for initial install should be a an important concern for any project and as long as Istio's install story starts with "go download something," it's really not optimal.

Can someone please make a decision about _where_ charts will be published? Maybe even go ahead and provision a chart repository? Once those minor hurdles are cleared, I'm sure there are plenty of people (myself included) who would be happy to assist in incorporating the publishing of charts into the CI/CD process.

**Comment by Miouge1** [comment]
I found this chart repo: https://gcsweb.istio.io/gcs/istio-prerelease/prerelease/1.1.0-rc.5/ unfortunately it's available only on 1.1.x versions at the moment.

**Comment by howardjohn** [comment]
Helm repo can be found on the Github release page (https://github.com/istio/istio/releases) under Helm Chart Index. For example https://storage.googleapis.com/istio-release/releases/1.1.2/charts/index.yaml

We are working on making this more idiomatic and having a single Helm repo rather than one per release. Follow https://github.com/istio/istio/issues/12974 for updates on that.

**Comment by wstrange** [comment]
Lateral thought: Given that kustomize is now built in to `kubectl` and an upstream base can be hosted on github, is there really a need for a helm chart?

**Comment by howardjohn** [comment]
This has been resolved. As mentioned above

> Helm repo can be found on the Github release page (https://github.com/istio/istio/releases) under Helm Chart Index. For example https://storage.googleapis.com/istio-release/releases/1.1.2/charts/index.yaml

> We are working on making this more idiomatic and having a single Helm repo rather than one per release. Follow #12974 for updates on that.

We acknowledge they are not the idiomatic Helm repos that most projects are using, and are tracking the progress in https://github.com/istio/istio/issues/12974. Since there is no work to be done here, I am going to close the issue

@wstrange we are moving to a kustomize approach in https://github.com/istio/installer (will be alpha in 1.2). Helm will still be supported though.

**Comment by rocketspacer** [comment]
Can we consider reopen this? I followed all the linked issues, all of them are closed, but I still can't find a  Helm chart repository for Istio (which is the problem this issue address).
