### ISSUE TITLE
DestionationRule with external mTLS preventing services from reaching running state when certs not present

### ISSUE THREAD

**Issue by castlemilk** [istio/istio#8541]
**Describe the bug**
## Description
When a `DestinationRule` is created which refers to certs that aren't available on a sidecar but will be available on say an egress gateway, all sidecars will stop taking updates from pilot and cause liveness/readiness probes to fail which then causes the microservice to go down.

We would like/expect the ability to do mTLS with external endpoints with mTLS origination from the egressgateway, where the egressgateway has the required certs mounted etc.

A potential solution is to modify the sidecar pod template to ensure certs referenced in the `DestinationRule` are available, however given we would like to originate the mTLS connect on the egressgateway this seems superfluous. Alternatively if the `DestinationRule` had a selector to say where the configuration should reside within the mesh (for example ONLY on the egressgateway), similar to how `VirtualService` configuration can be more explicitly applied.

We are following the pattern shown in the Istio docs:

- [forcing egress traffic through egressgateway](https://istio.io/docs/examples/advanced-egress/egress-gateway/)
- [mTLS for external endpoint with custom certs (mongoDB example with `ServiceEntry` + `DestinationRule`)](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry)

## expectations
When configuration is synced (deployed from a `DestinationRule`) to sidecars which don't have the given certs available, the configuration can be ignore/gracefully handled and allow the sidecar to continue synchronising configuration from pilot.

This should also be fixed to guard against a scenario where a user introduces malformed/incorrect configuration which can be seen to take down all services, like we're seeing in this issue. I believe this also will impact service mesh hosted services across namespaces, potentially allowing a malicious actor to takedown the services in another namespace, simply because `DestinationRule` resources are deployed to ALL mesh components, independent of namespace or function/context (like ingress/egress/mesh).

Would be great to get some guidance on the best approach to enable mTLS to external endpoints outside the mesh, and how to manage the mounting of secrets to the required components within the mesh.
## Steps to reproduce
1. deploy some services with sidecars
2. apply a `DestinationRule` which refers to a custom cert location such as:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: external-example-mtls-config
spec:
  host: external.example.com
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /etc/istio/external.example.com/tls.crt
      privateKey: /etc/istio/external.example.com/tls.key
      caCertificates: /etc/istio/external.example.com.ca-certs/root-cert.pem
```
3. delete your services deployments pod and wait for it to be redeployed, this will then get the sidecar to attempt to synchronise with the newly added `DestinationRule` above.
4. the sidecar will have the below logs, and the pod should enter a `CrashLoopBackoff` until the `DestinationRule` is deleted, once deleted the service is able to reach a complete 2/2 running state. This can be done across different namespaces as well.

```text
[2018-09-06 20:51:55.395][23][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:223] gRPC config for type.googleapis.com/envoy.api.v2.Cluster update rejected: unable to read file: /etc/istio/external.example.com.ca-certs/root-cert.pem
[2018-09-06 20:51:55.395][23][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy
.api.v2.Cluster rejected: unable to read file: /etc/istio/external.example.com.ca-certs/root-cert.pem
```

## Versions
Tested on the following:

Istio: 1.0.0 (nightlybuild)
kubernetes: 1.9.10
`---`
Istio: 1.0.1
kubernetes: 1.10.7

# Auth Enabled
mTLS/global auth is enabled.
## Environment
AWS

There's nothing particularly special about the state of our environment, other than the reference to custom certs. These certs are being mounted via `Secrets`, but only to the egress/ingress gateways where required, as this is where our external mTLS is being originated.

**Comment by castlemilk** [comment]
@rshriram do you have any suggestions on a solution for this? Is it correct to expect a `DestinationRule` defined in one namespace should effect sidecars in a different namespace? Would it be possible to add a gateway selector on the `DestinationRule`, and have filtering on pilot to NOT configure `DestinationRule` in a cluster scope and instead per-namespace?

**Comment by vadimeisenbergibm** [comment]
@castlemilk Good point, thank you for discovering this.

@rshriram It seems there is no other choice but to add specifying the source a `DestinationRule` is applied to. The issue is not related to gateways, the same issue can happen when you want to specify custom mTLS, or `caCertificates` between one service to another service inside the mesh, and when you want the sidecar/gateway to perform (m)TLS origination for you.

**Comment by castlemilk** [comment]
@vadimeisenbergibm @rshriram could the `DestinationRule` also be filtered based off namespace, to prevent superfluous/undesired rules being deployed to all namespaces.

Also were you able to observe the impact to `Pod` deployments? Where they are pevented from reaching a "running" state while the above `DestinationRule` is in place? Really interested to see if this is consistent in other users environments, as the ramifications on security/namespace isolation would be quite concerning.

**Comment by ZackButcher** [comment]
cc @louiscryan too, this is relevant to some of the discussions we're having re Gateways. https://github.com/istio/api/pull/656 also has some relevant concepts.

We (Tetrate) are hitting this specific problem as well, but it gets at a more general problem in Istio which is: Istio does not handle egress gateways well. Name resolution is one problem (though https://github.com/istio/istio/pull/9346, split ServiceEntries per network, helps address this problem), the next problem is that we really want to split DestinationRules per network too (which would address this secret mounting problem). I wonder if we wouldn't side-step this whole problem is we allowed ServiceEntries and DestinationRules to be bound to Gateways in the same way we allow VirtualServices to bind to Gateways?

**Comment by louiscryan** [comment]
@PiotrSikora 

It seems hard to guarantee consistency between two parallel configuration systems (files, ADS) and so I think the runtime needs to be more tolerant here. I.e Envoy should not fail the entire config in this case but rather put just the affected cluster into an auto-erroring state for things which connect to it.

**Comment by PiotrSikora** [comment]
@louiscryan wrt files vs ADS, this should be solved by SDS already, which puts listeners and clusters with missing SDS resources in a warming state. cc @qiwzhang @JimmyCYJ @lizan

**Comment by JimmyCYJ** [comment]
Yes, if a listener A does not have certificates, and is trying to get certificates via SDS, listener A is in warming list. Other listeners that have certs already can serve traffic, and they are not affected by listener A. When listener A gets certs from SDS, it will be marked as ready and will start serving traffic. Clusters are the same.

**Comment by castlemilk** [comment]
Please try reproduce locally, as per the instructions. I’m still facing
this issue.

**Comment by wattli** [comment]
This should be a dup of https://github.com/istio/istio/issues/9659, @castlemilk ,  https://github.com/istio/istio/pull/9786/ should fix this.

**Comment by wattli** [comment]
Close this for now since it is a dup of #9659

**Comment by castlemilk** [comment]
@wattli I don't fully agree with this issue being resolved. Maybe another issue should be raised that more specifically addresses the current limitations of both namespace isolation and `ServiceEntry` and `DestinationRule` selectors. As it stands, because of this missing capability, there's still plenty of room for miss-configuration and/or malicious actors to severely impact the functionality of the service mesh. Some scenarios that I can see include:
* defining overlapping domain names in different namespaces, causing mesh instability via config rejections
* flooding the mesh with policies that aren't relevant to all namespaces
* providing access to egress downstream services that are not required in all namespaces
* potentially hijacking/routing traffic with virtualservices to undesired destinations

**Comment by castlemilk** [comment]
@costinm is this how it operates today? We're currently running the egress gateway in the istio-system namespace, but defining `DestinationRule` resources in other namespaces, these resources still seem to get deployed to the given egress gateway.

**Comment by vadimeisenbergibm** [comment]
Should be fixed by https://github.com/istio/istio/issues/13319.

**Comment by vadimeisenbergibm** [comment]
@castlemilk The issue should be resolved now by using [the Sidecar resource](https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/).
