### ISSUE TITLE
NodePort port incorrectly used in Host header for request routing

### ISSUE THREAD

**Issue by krancour** [istio/istio#8807]
Kuberntes: __1.11.1__ on minikube __v0.28.2__
Istio: __1.0.2__

I've been using Istio on minikube with the ingress gateway using a service of type `NodePort`.

Most examples in the docs use host `*` in both their gateways and outward facing virtual services. This works fine, but the moment you want to start trying more complex things and need to actually start routing requests on host name, things fall apart.

Consider the following gateway:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: example
  namespace: example
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - '*'
    port:
      number: 80
      name: http
      protocol: HTTP
```

And the following virtual service:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: www
  namespace: example
spec:
  hosts:
  - www.example.com
  gateways:
  - example
  http:
  - route:
    - destination:
        host: www
```

Now suppose that in my local `/etc/hosts` file, I added the following entry (192.168.99.100 is the IP of my minikube vm):

```
192.168.99.100 www.example.com
```

I now get the node port for the ingress gateway:

```
$ kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}'
31380
```

Now I try and open http://www.example.com:31380 in my browser.

This does not work. The reason why is clear. Ingress gateway access logs show entries like the following:

```
[2018-09-18T04:06:14.693Z] "GET / HTTP/1.1" 404 NR 0 0 0 - "172.17.0.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" "44659f89-1292-9c6e-8c74-3217db2fd088" "www.example.com:31380" "-"
```

The host is being, incorrectly, imo, determined to be `www.example.com:31380`.

I'll explain why I believe this is incorrect.

By [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23), the `Host` header sent by a user agent (e.g. browser) _may_ contain trailing port information. In the absence of this, port 80 is assumed for URLs using HTTP as the protocol and 443 is assumed for URLs using HTTPS as the protocol. All browsers that I have checked, omit 80 and 443, respectively for those circumstances, but otherwise _do_ include the port number.

In this case, I can confirm that my browser sends the `Host` header with the value `www.example.com:31380`.

This being the case, it seems unsurprising that the gateway sees the `Host` header as `www.example.com:31380`-- that is, after all, what it was sent... _however_...

imo, it's wrong for the gateway to make routing decisions on the basis of this value. Why? Because the request was _received_ on the gateway's port 80. i.e. The fact that the user agent requested `www.example.com:31380` is of no consequence once the gateway has received the request on port 80. imo, it should interpret the `Host` header as <host:_receiving port_>-- `www.example.com:80` in this case-- and then, by established convention, drop the `:80` or `:443` if applicable. Here, this would result in `www.example.com`. This request would be routed correctly.

If there's any doubt that the behavior I am advocating for here is sensible, please consider that this is how Nginx works.

In Nginx, I have modified the log format as follows:

```
log_format  main  '$remote_addr !!! $host !!! $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
```

I'm running this in Kubernetes, with a service of type `NodePort`-- port `30399`

With the following entry in my local `/etc/hosts`:

```
192.168.99.100 www.foo.com
```

And a request from my browser to `http://www.foo.com:30399`

I see access logs such as this:

```
172.17.0.1 !!! www.foo.com !!! [18/Sep/2018:16:35:28 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" "-"
```

Note that Nginx sensibly disregarded the `:30399`.

Last, I should acknowledge that there are various spots in the Istio documentation that point out the difficulties of using Istio on minkube and driving traffic through a browser-- where headers aren't as easily manipulated as they are with `curl`. The suggested workaround is to only use `*` as the host in both gateways and virtual services. The problem with this workaround, of course, is that its far too constraining for anyone to attempt anything non-trivial with Istio on minikube...

That difficulty and the need for the very constraining workaround could be remediated by correcting this bug.

**Comment by krancour** [comment]
/assign rshriram

@rshriram... just assigning to someone to get this triaged. Sorry if you're the wrong person.

**Comment by rshriram** [comment]
This is a known issue. The problem is not on istio side. It’s Envoy that needs to be changed to strip the port from the host header before doing the virtual host matching.

**Comment by krancour** [comment]
@rshriram 

> It’s Envoy that needs to be changed to strip the port from the host header before doing the virtual host matching.

That may be true, but I am proposing that it's equally incorrect (in many cases) for the ingress gateway to not have stripped the port from the host header.

The ingress gateway should effectively consider the port a request is was _received on_ instead of whatever port is at the end of the host header. The port at the end of the host header is only reflective of the shenanigans that an end user had to engage in to get their request _to_ the ingress gateway (because of some node level port mapping). Once the request hist the gateway, that information should be treated as extraneous since it is.

**Comment by rshriram** [comment]
Ingress gateway is also an envoy :)

**Comment by krancour** [comment]
@rshriram... well then...

Did not know that and good to know!

Thanks!

**Comment by markeijsermans** [comment]
Can confirm this effects both Ingress and Gateways. The Envoy bug in question is this: https://github.com/envoyproxy/envoy/issues/886

I have dedicated node-pool for my ingress/gateway deployments which I run as a `DaemonSet`. I `hostPort` my gateways to listen on a static port on those hosts (could as well be `NodePort`s). So the Envoy pod listens on port 80, and is then mapped to port 8080 on the host. I then have an ELB which listens on port 80, and forwards to port 8080. This cenario works fine. The client make a request to port 80, and the Envoy process is also listening on port 80.
```
             +------------------------+
+-------+    |             +---------+|
|80 ELB +--->|8080 Node -->|80 Envoy ||
+-------+    |             +---------+|
             +------------------------+
```

The problem is that I wish to attach multiple `Gateway`s to the same gateway pod, yet have them listen on different ports so I can attach separate security groups etc. This breaks. Eg:
```
             +--------------------------+
+-------+    |             +-----------+|
|80 ELB +--->|8080 ------->|8080       ||
+-------+    |             |           ||
             |     Node    |     Envoy ||
+-------+    |             |           ||
|80 ELB +--->|9080 ------->|9080       ||
+-------+    |             +-----------+|
             +--------------------------+
```

The way I solved this is to create multiple Envoy gateway processes which is not ideal. Eg:
```
             +--------------------------+
+-------+    |             +-----------+|
|80 ELB +--->|8080 ------->|80 Envoy   ||
+-------+    |             +-----------+|
             |     Node                 |
+-------+    |             +-----------+|
|80 ELB +--->|9080 ------->|80 Envoy   ||
+-------+    |             +-----------+|
             +--------------------------+
```

**Comment by krancour** [comment]
@rshriram can this issue stay open, please?

**Comment by rshriram** [comment]
sorry its stale bot..

**Comment by bitsofinfo** [comment]
Experiencing same issue, is there an open envoy issue around this?

**Comment by An0nymous0** [comment]
More concerned about this issue, whether there are plans

**Comment by weibaohui** [comment]
More concerned about this issue, whether there are plans

**Comment by silverReaperMaster** [comment]
I Manage to work around this issue using match -> authority:
 

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-http-rabbitmq
  namespace: xxxx
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-80
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rabbitmq-http
  namespace: xxxxx
spec:
  hosts:
  - "*"
  gateways:
  - gateway-http-rabbitmq
  http:
  - match:
    - uri:
        prefix: /rabbitmq/
      authority: 
        prefix: xxxx.yyyyy.cl
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 15672
        host: xxxxx.svc.cluster.local




Hope this Helps Some one.

**Comment by laobao** [comment]
Experiencing same issue, is there an open envoy issue around this?

**Comment by Siddharthk** [comment]
@rshriram  @howardjohn Same issue here. This is a real blocker. This issue does not happen when using heptio contour ingress controller. Contour also uses Envoy proxy and there also it does not strip the port. Can we know any official workarounds for now?

**Comment by howardjohn** [comment]
@laobao envoy issue is https://github.com/envoyproxy/envoy/issues/886

> This issue does not happen when using heptio contour ingress controller. Contour also uses Envoy proxy and there also it does not strip the port.

I am curious about this. If it does not strip the port it sounds the same as our usage of Envoy. How are they handling this?

**Comment by hdimitriou** [comment]
Noting down here that in case this blocks you from using istio ingress on a non 80/443 port (maybe internally in your company network), you can do the following:
* set ingress gateway to have an extra port like [31400](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/gateways/values.yaml#L70)
* set your nodeport to match the above port, for example 31400.

As a result, your requests will have <host>:31400 on the host header and this will match the ingress configuration.
Moreover, the ingress configuration will also include <host> without the port, so you can also set your external Load Balancer to use this port as a backend if you like.

**Comment by barrowkwan** [comment]
I have same issue here.  @hdimitriou how exactly you implement the extra port (31400)? any help will be appreciated .  thanks

**Comment by hdimitriou** [comment]
@barrowkwan by default this already exists from the helm chart on the [gateways' values](https://github.com/istio/istio/blob/4170e2e2bd27e4d5b6e585fde8bfe9cce9d45ce5/install/kubernetes/helm/istio/charts/gateways/values.yaml#L70)

The same way the port 31400 is defined you can add more ports if you want or different ports. You simply need 'port' and 'nodePort' to match

**Comment by howardjohn** [comment]
I am pretty sure this is fixed, but I am not sure when. If you install bookinfo, you will see routes like

```
   "dynamic_route_configs": [
    {
     "version_info": "2020-01-02T19:06:46Z/13",
     "route_config": {
      "name": "http.80",
      "virtual_hosts": [
       {
        "name": "*:80",
        "domains": [
         "*",
         "*:80"
        ],
        "routes": [
         {
          "match": {
           "path": "/productpage",
           "case_sensitive": true
          },
```

Note the one without the port, which will match even when nodeport is set?

**Comment by strideynet** [comment]
@howardjohn I'm still seeing this issue with the latest Istio. I think the issue comes when specifying a host.

* may generate * and *:80, but specifying a host of test.istio.com would only generate test.istio.com and test.istio.com:80, when in reality it also needs to generate one for the node-port i.e test.istio.com:32700

**Comment by bitsofinfo** [comment]
not stale

**Comment by skolenkin** [comment]
I have checked this issue on the  istio version (1.4.6, 1.4.7, 1.5.2) and it's still there. So if you are using a custom ports to connect to service - envoy will receive header as domain:port and  it will cause a problem that envoy can not match expected domain name and received domain:port. As a temporary workaround - you can create a nginx proxy with config like:

```
## tcp LB  and SSL passthrough for backend ##
stream {
    upstream apigee {
        server K8S-NODE-IP:NODEPORT;
    }

    log_format basic '$remote_addr [$time_local] '
                 '$protocol $status $bytes_sent $bytes_received '
                 '$session_time "$upstream_addr" '
                 '"$upstream_bytes_sent" "$upstream_bytes_received" "$upstream_connect_time"';

    access_log /var/log/nginx/apigee_access.log basic;
    error_log  /var/log/nginx/apigee_error.log;

    server {
        listen 443;
        proxy_pass apigee;
        proxy_next_upstream on;
    }
}
```
http://nginx.org/en/docs/stream/ngx_stream_core_module.html

```
curl -v http://35.242.141.132:32287/hello
*   Trying 35.242.141.132...
* TCP_NODELAY set
* Connected to 35.242.141.132 (35.242.141.132) port 32287 (#0)
> GET /hello HTTP/1.1
> Host: 35.242.141.132:32287
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< content-length: 60
< server: istio-envoy
< date: Tue, 28 Apr 2020 10:41:36 GMT
< x-envoy-upstream-service-time: 176
<
Hello version: v1, instance: helloworld-v1-578dd69f69-6srxc
* Connection #0 to host 35.242.141.132 left intact
* Closing connection 0
```
```
curl -v -H "Host:helloworld.test.com" http://helloworld.test.com:32287/hello
*   Trying 35.242.141.132...
* TCP_NODELAY set
* Connected to helloworld.test.com (35.242.141.132) port 32287 (#0)
> GET /hello HTTP/1.1
> Host:helloworld.test.com
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< content-length: 60
< server: istio-envoy
< date: Tue, 28 Apr 2020 10:45:10 GMT
< x-envoy-upstream-service-time: 165
<
Hello version: v2, instance: helloworld-v2-776f74c475-q7p7q
* Connection #0 to host helloworld.test.com left intact
* Closing connection 0
```
```
istioctl version
client version: 1.5.0
control plane version: 1.5.2
data plane version: 1.5.2 (5 proxies)
```
```
Istio 1.4.7: envoy --version envoy  version: f777dd13e28edc4ff394e98cd82c82ca4a2bcc71/1.12.0/Clean/RELEASE/BoringSSL
 Istio 1.5.2: envoy --version
envoy  version: 54fd05bc1e3e59a155651e5c84e4138d849e8d58/1.13.1-dev/Clean/RELEASE/BoringSSL
```

**Comment by krancour** [comment]
This is not stale. Can it please be re-opened.... _again_?

**Comment by howardjohn** [comment]
not stale, sorry

**Comment by howardjohn** [comment]
I am pretty sure this is fixed in master.

VS:
```
  spec:
    gateways:
    - bookinfo-gateway
    hosts:
    - productpage.com
    http:
    - match:
      - uri:
          exact: /productpage
      - uri:
          prefix: /static
      - uri:
          exact: /login
      - uri:
          exact: /logout
      - uri:
          prefix: /api/v1/products
      route:
      - destination:
          host: productpage
          port:
            number: 9080
```

GW:
```
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - productpage.com
      port:
        name: http
        number: 80
        protocol: HTTP
```

requests:
* `curl 192.168.9.3:31682/productpage -H "Host: productpage.com:31682"` works,
* `curl 192.168.9.3:31682/productpage -H "Host: productpage.com:80"` works,
* `curl 192.168.9.3:31682/productpage -H "Host: productpage.com"` works,

Envoy config:
```
     "route_config": {
      "@type": "type.googleapis.com/envoy.api.v2.RouteConfiguration",
      "name": "http.80",
      "virtual_hosts": [
       {
        "name": "productpage.com:80",
        "domains": [
         "productpage.com",
         "productpage.com:*"
        ],
        "routes": [
         {
          "match": {
           "path": "/productpage",
           "case_sensitive": true
```

Please let me know if I am reproducing this wrong

**Comment by skolenkin** [comment]
Hi @howardjohn 

Could you please run the following command:
curl http://productpage.com:31682/productpage 

curl -v -H "Host:helloworld.test.com" http://helloworld.test.com:32287/hello - works 
curl -v http://helloworld.test.com:32287/hello - doesn't work

**Comment by howardjohn** [comment]
@skolenkin `curl 192.168.9.3:31682/productpage -H "Host: productpage.com:31682"` is the same as  `curl -v http://helloworld.test.com:32287/hello` right? I don't have a real domain to test it on. This is on 1.6 alpha builds, not older versions this was reported on

**Comment by skolenkin** [comment]
@howardjohn I tested on real DNS name and fake domain name (added in my /etc/hosts 35.242.141.132 helloworld.test.com). 
I was deployed cluster on GKE. 
curl -v http://35.242.141.132:32287/hello
*   Trying 35.242.141.132...
* TCP_NODELAY set
* Connected to 35.242.141.132 (35.242.141.132) port 32287 (#0)
> GET /hello HTTP/1.1
> Host: 35.242.141.132:32287
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< content-length: 60
< server: istio-envoy
< date: Tue, 28 Apr 2020 10:41:36 GMT
< x-envoy-upstream-service-time: 176
<
Hello version: v1, instance: helloworld-v1-578dd69f69-6srxc
* Connection #0 to host 35.242.141.132 left intact
* Closing connection 0

curl -v -H "Host:helloworld.test.com" http://helloworld.test.com:32287/hello
*   Trying 35.242.141.132...
* TCP_NODELAY set
* Connected to helloworld.test.com (35.242.141.132) port 32287 (#0)
> GET /hello HTTP/1.1
> Host:helloworld.test.com
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< content-length: 60
< server: istio-envoy
< date: Tue, 28 Apr 2020 10:45:10 GMT
< x-envoy-upstream-service-time: 165
<
Hello version: v2, instance: helloworld-v2-776f74c475-q7p7q
* Connection #0 to host helloworld.test.com left intact
* Closing connection 0

**Comment by skolenkin** [comment]
@howardjohn 
I deployed now a new GKE cluster with Istio 1.5.2
```
gcloud beta container clusters create istio-test \
> --machine-type=n1-standard-4 \
> --num-nodes=3 \
> --enable-stackdriver-kubernetes \
> --subnetwork=default \
> --zone=europe-west1-b \
> --enable-ip-alias \
> --addons=HttpLoadBalancing
```

```
cd istio-1.5.2/bin
./istioctl manifest apply --set profile=demo \
> --set values.gateways.istio-ingressgateway.type=NodePort
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Pilot...
✔ Finished applying manifest for component Pilot.
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
- Applying manifest for component EgressGateways...
- Applying manifest for component IngressGateways...
- Applying manifest for component AddonComponents...
✔ Finished applying manifest for component EgressGateways.
✔ Finished applying manifest for component IngressGateways.
✔ Finished applying manifest for component AddonComponents.


✔ Installation complete
```

```
kubectl label namespace default istio-injection=enabled
kubectl create -f helloworld.yaml
service/helloworld created
deployment.apps/helloworld-v1 created
deployment.apps/helloworld-v2 created

kubectl create -f helloworld-gateway.yaml
gateway.networking.istio.io/helloworld-gateway created
virtualservice.networking.istio.io/helloworld created
```

```
kubectl -n istio-system get svc istio-ingressgateway
NAME                   TYPE       CLUSTER-IP   EXTERNAL-IP   PORT(S)                                                                                                                                      AGE
istio-ingressgateway   NodePort   10.4.13.88   <none>        15020:30811/TCP,80:31831/TCP,443:31577/TCP,15029:30535/TCP,15030:30642/TCP,15031:31450/TCP,15032:30324/TCP,31400:31526/TCP,15443:31386/TCP   10m
```

```
istioctl version
client version: 1.5.0
control plane version: 1.5.2
data plane version: 1.5.2 (5 proxies)
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
cat helloworld-gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helloworld-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    #- "*"
    - "helloworld.test.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
  - "helloworld.test.com"
  #- "*"
  gateways:
  - helloworld-gateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
```

```
kubectl get nodes -o wide |grep 104.199.76.75
gke-istio-test-default-pool-7a9a7bfb-g0jg   Ready    <none>   15m   v1.14.10-gke.27   10.132.15.207   104.199.76.75    Container-Optimized OS from Google   4.14.138+        docker://18.9.7
```

```
curl -k -v http://104.199.76.75:31831/hello
*   Trying 104.199.76.75...
* TCP_NODELAY set
* Connected to 104.199.76.75 (104.199.76.75) port 31831 (#0)
> GET /hello HTTP/1.1
> Host: 104.199.76.75:31831
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< date: Tue, 28 Apr 2020 16:01:20 GMT
< server: istio-envoy
< content-length: 0
<
* Connection #0 to host 104.199.76.75 left intact
* Closing connection 0
```

```
curl -k -v http://helloworld.test.com:31831/hello
*   Trying 104.199.76.75...
* TCP_NODELAY set
* Connected to helloworld.test.com (104.199.76.75) port 31831 (#0)
> GET /hello HTTP/1.1
> Host: helloworld.test.com:31831
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< date: Tue, 28 Apr 2020 16:01:51 GMT
< server: istio-envoy
< content-length: 0
<
* Connection #0 to host helloworld.test.com left intact
* Closing connection 0
```

```
curl -k -v -H "Host:helloworld.test.com"  http://104.199.76.75:31831/hello
*   Trying 104.199.76.75...
* TCP_NODELAY set
* Connected to 104.199.76.75 (104.199.76.75) port 31831 (#0)
> GET /hello HTTP/1.1
> Host:helloworld.test.com
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< content-length: 60
< server: istio-envoy
< date: Tue, 28 Apr 2020 16:01:58 GMT
< x-envoy-upstream-service-time: 168
<
Hello version: v2, instance: helloworld-v2-6cd449dff4-rls2w
* Connection #0 to host 104.199.76.75 left intact
* Closing connection 0
```
cat  /etc/hosts |grep helloworld.test.com
104.199.76.75 helloworld.test.com

```
istioctl  proxy-status
NAME                                                  CDS        LDS        EDS        RDS          PILOT                      VERSION
helloworld-v1-7bb88866c4-h7xrn.default                SYNCED     SYNCED     SYNCED     SYNCED       istiod-8cc9bfd95-p5b6q     1.5.2
helloworld-v2-6cd449dff4-rls2w.default                SYNCED     SYNCED     SYNCED     SYNCED       istiod-8cc9bfd95-p5b6q     1.5.2
istio-ingressgateway-7df659d78-7pvjx.istio-system     SYNCED     SYNCED     SYNCED     SYNCED       istiod-8cc9bfd95-p5b6q     1.5.2
prometheus-75f89f4df8-nsgn6.istio-system              SYNCED     SYNCED     SYNCED     SYNCED       istiod-8cc9bfd95-p5b6q     1.5.2
```

```
istioctl  proxy-config listener istio-ingressgateway-7df659d78-7pvjx.istio-system
ADDRESS     PORT      TYPE
0.0.0.0     80        HTTP
0.0.0.0     15090     HTTP
```

```
   "dynamic_route_configs": [
    {
     "version_info": "2020-04-28T15:55:02Z/24",
     "route_config": {
      "@type": "type.googleapis.com/envoy.api.v2.RouteConfiguration",
      "name": "http.80",
      "virtual_hosts": [
       {
        "name": "helloworld.test.com:80",
        "domains": [
         "helloworld.test.com",
         "helloworld.test.com:80"
        ],
        "routes": [
         {
          "match": {
           "path": "/hello",
           "case_sensitive": true
          },
          "route": {
           "cluster": "outbound|5000||helloworld.default.svc.cluster.local",
           "timeout": "0s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
            "num_retries": 2,
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts"
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             503
            ]
           },
           "max_grpc_timeout": "0s"
          },
          "metadata": {
           "filter_metadata": {
            "istio": {
             "config": "/apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/helloworld"
            }
           }
          },
          "decorator": {
           "operation": "helloworld.default.svc.cluster.local:5000/hello"
          }
         }
        ]
       }
      ],
      "validate_clusters": false
     },
     "last_updated": "2020-04-28T15:55:02.596Z"
    }
   ]
  },
```

curl -k -v -H "Host:helloworld.test.com"  http://104.199.76.75:31831/hello - works 
curl -k -v http://helloworld.test.com:31831/hello - doesn't work
curl -k -v http://104.199.76.75:31831/hello - doesn't work

**Comment by howardjohn** [comment]
Yes this is changed in 1.6, you can see in my envoy config its `:*` now instead of `:80`

**Comment by skolenkin** [comment]
@howardjohn 
Do you have any plans to make backports for 1.4 and 1.5 releases?
Thank you very much for the information

**Comment by howardjohn** [comment]
@skolenkin I don't think there are plans to cherrypick to 1.5. While its likely safe, changing behavior in a late patch release is discouraged. Since https://github.com/istio/istio/pull/20870 has fixed this I think this can be closed

**Comment by nataraj24** [comment]
when will version 1.6 will be released

**Comment by aavileli** [comment]
This is awful as this is not ported to the 1.5 branch as so many users are on 1.5

**Comment by krancour** [comment]
OP here. Respectfully, #20870 _didn't_ fix this. It just complicated things further. Instead of adhering to some kind of principle of least surprise, it asks developers to understand the nuances of how Istio routes requests and compensate with additional configuration.

**Comment by howardjohn** [comment]
@krancour can you help me understand how this requires additional configuration?

**Comment by krancour** [comment]
@howardjohn my apologies. I believe now that I may have misunderstood elements of the conversation in #26354 

The conversation left with the impression that adding a match for `hostname:*` was the user's responsibility, but looking at the code that was committed in that PR, I see now that it's automatically generated.

I withdraw my complaint. 😄

**Comment by howardjohn** [comment]
@krancour thanks for clearing that up. I will note that this is still not 100% fixed, we recently realized with wildcard hostnames its not quite right. Support in envoy is needed, see https://github.com/envoyproxy/envoy/issues/12647

**Comment by yann-soubeyrand** [comment]
Hi,

I'd like to add that this problem not only occurs with ingress gateway: in our setup we use haproxy as our ingress gateway with an istio-proxy sidecar to forward requests to the mesh. We're also hit by this issue when requests are done on non standard ports (nor 80, nor 443) which leads to browsers adding the port to authority. We've tried to strip the port in authority but then the redirections done by the applications are bad (missing port).

It seems to me that the right solution would be for envoy listeners to match only on the domain (ignoring the port) but as I understand envoy is missing this feature as of now, right?

In the meantime, adding the non standard ports to the application services fixes our problem (istio then adds new authorities for theses ports to the listeners) but it's a hackish workaround.

**Comment by howardjohn** [comment]
@yann-soubeyrand yes, that is correct. We actually ignore the port in some cases, by `domain:*`, but if you have a wildcard in the domain like `*.example.com:*` will not work since envoy only supports a single wildcard.
