### ISSUE TITLE
pods not coming up when istio is enabled on namespace with resourcequotas and limit range

### ISSUE THREAD

**Issue by vikranttkamble** [istio/istio#9332]
Istio was installed using helm template. Option1: https://istio.io/docs/setup/kubernetes/helm-install/#option-1-install-with-helm-via-helm-template

Following an old issue: https://github.com/istio/old_issues_repo/issues/339

I added resources block with cpu and memory to init container and added memory block in resources of proxy container, deleted the istio and created it again.

With setting only resourcequota and not limit range set it throws following error

```
Error creating: pods "<app>-56b778f9b7-bhs4v" is forbidden: failed quota: quota: must specify cpu,memory
``` 
and with setting both resourcequota and limit range, pods are stuck in init.

```
 Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "880830dad728da7e70c2b86026b8da7ce9f17a77710a6801916555bb8c174579" network for pod "<microservice>-56b778f9b7-j47cv": NetworkPlugin cni failed to set up pod "<microservice>-56b778f9b7-j47cv_<app>pt" network: Pod "<microservice>-56b778f9b7-j47cv" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations) {"Volumes":[{"Name":"default-token-ktxwf","HostPath":null,"EmptyDir":null,"GCEPersistentDisk":null,"AWSElasticBlockStore":null,"GitRepo":null,"Secret":{"SecretName":"default-token-ktxwf","Items":null,"DefaultMode":420,"Optional":null},"NFS":null,"ISCSI":null,"Glusterfs":null,"PersistentVolumeClaim":null,"RBD":null,"Quobyte":null,"FlexVolume":null,"Cinder":null,"CephFS":null,"Flocker":null,"DownwardAPI":null,"FC":null,"AzureFile":null,"ConfigMap":null,"VsphereVolume":null,"AzureDisk":null,"PhotonPersistentDisk":null,"Projected":null,"PortworxVolume":null,"ScaleIO":null,"StorageOS":null},{"Name":"istio-envoy","HostPath":null,"EmptyDir":{"Medium":"Memory","SizeLimit":null},"GCEPersistentDisk":null,"AWSElasticBlockStore":null,"GitRepo":null,"Secret":null,"NFS":null,"ISCSI":null,"Glusterfs":null,"PersistentVolumeClaim":null,"RBD":null,"Quobyte":null,"FlexVolume":null,"Cinder":null,"CephFS":null,"Flocker":null,"DownwardAPI":null,"FC":null,"AzureFile":null,"ConfigMap":null,"VsphereVolume":null,"AzureDisk":null,"PhotonPersistentDisk":null,"Projected":null,"PortworxVolume":null,"ScaleIO":null,"StorageOS":null},{"Name":"istio-certs","HostPath":null,"EmptyDir":null,"GCEPersistentDisk":null,"AWSElasticBlockStore":null,"GitRepo":null,"Secret":{"SecretName":"istio.default","Items":null,"DefaultMode":420,"Optional":true},"NFS":null,"ISCSI":null,"Glusterfs":null,"PersistentVolumeClaim":null,"RBD":null,"Quobyte":null,"FlexVolume":null,"Cinder":null,"CephFS":null,"Flocker":null,"DownwardAPI":null,"FC":null,"AzureFile":null,"ConfigMap":null,"VsphereVolume":null,"AzureDisk":null,"PhotonPersistentDisk":null,"Projected":null,"PortworxVolume":null,"ScaleIO":null,"StorageOS":null}],"InitContainers":[{"Name":"istio-init","Image":"docker.io/istio/proxy_init:1.0.2","Command":null,"Args":["-p","15001","-u","1337","-m","REDIRECT","-i","*","-x","","-b","8080,","-d",""],"WorkingDir":"","Ports":null,"EnvFrom":null,"Env":null,"Resources":{"Limits": A: {"cpu":"200m","memory":"488Mi"},"Requests":{"cpu":"10m","memory":"144Mi"}},"VolumeMounts":null,"VolumeDevices":null,"LivenessProbe":null,"ReadinessProbe":null,"Lifecycle":null,"TerminationMessagePath":"/dev/termination-log","TerminationMessagePolicy":"File","ImagePullPolicy":"IfNotPresent","SecurityContext":{"Capabilities":{"Add":["NET_ADMIN"],"Drop":null},"Privileged":null,"SELinuxOptions":null,"RunAsUser":null,"RunAsGroup":null,"RunAsNonRoot":null,"ReadOnlyRootFilesystem":null,"AllowPrivilegeEscalation":null},"Stdin":false,"StdinOnce":false,"TTY":false}],"Containers":[{"Name":"<microservice>","Image":"<registry_url>/<app>/<microservice>","Command":null,"Args":null,"WorkingDir":"","Ports":[{"Name":"","HostPort":0,"ContainerPort":8080,"Protocol":"TCP","HostIP":""}],"EnvFrom":null,"Env":null,"Resources":{"Limits":{"cpu":"200m","memory":"488Mi"},"Requests":{"cpu":"100m","memory":"244Mi"}},"VolumeMounts":[{"Name":"default-token-ktxwf","ReadOnly":true,"MountPath":"/var/run/secrets/kubernetes.io/serviceaccount","SubPath":"","MountPropagation":null}],"VolumeDevices":null,"LivenessProbe":null,"ReadinessProbe":null,"Lifecycle":null,"TerminationMessagePath":"/dev/termination-log","TerminationMessagePolicy":"File","ImagePullPolicy":"Always","SecurityContext":null,"Stdin":false,"StdinOnce":false,"TTY":false},{"Name":"istio-proxy","Image":"docker.io/istio/proxyv2:1.0.2","Command":null,"Args":["proxy","sidecar","--configPath","/etc/istio/proxy","--binaryPath","/usr/local/bin/envoy","--serviceCluster","istio-proxy","--drainDuration","45s","--parentShutdownDuration","1m0s","--discoveryAddress","istio-pilot.istio-system:15007","--discoveryRefreshDelay","1s","--zipkinAddress","zipkin.istio-system:9411","--connectTimeout","10s","--statsdUdpAddress","istio-statsd-prom-bridge.istio-system:9125","--proxyAdminPort","15000","--controlPlaneAuthPolicy","NONE"],"WorkingDir":"","Ports":null,"EnvFrom":null,"Env":[{"Name":"POD_NAME","Value":"","ValueFrom":{"FieldRef":{"APIVersion":"v1","FieldPath":"metadata.name"},"ResourceFieldRef":null,"ConfigMapKeyRef":null,"SecretKeyRef":null}},{"Name":"POD_NAMESPACE","Value":"","ValueFrom":{"FieldRef":{"APIVersion":"v1","FieldPath":"metadata.namespace"},"ResourceFieldRef":null,"ConfigMapKeyRef":null,"SecretKeyRef":null}},{"Name":"INSTANCE_IP","Value":"","ValueFrom":{"FieldRef":{"APIVersion":"v1","FieldPath":"status.podIP"},"ResourceFieldRef":null,"ConfigMapKeyRef":null,"SecretKeyRef":null}},{"Name":"ISTIO_META_POD_NAME","Value":"","ValueFrom":{"FieldRef":{"APIVersion":"v1","FieldPath":"metadata.name"},"ResourceFieldRef":null,"ConfigMapKeyRef":null,"SecretKeyRef":null}},{"Name":"ISTIO_META_INTERCEPTION_MODE","Value":"REDIRECT","ValueFrom":null}],"Resources":{"Limits":{"cpu":"200m","memory":"488Mi"},"Requests":{"cpu":"10m","memory":"144Mi"}},"VolumeMounts":[{"Name":"istio-envoy","ReadOnly":false,"MountPath":"/etc/istio/proxy","SubPath":"","MountPropagation":null},{"Name":"istio-certs","ReadOnly":true,"MountPath":"/etc/certs/","SubPath":"","MountPropagation":null}],"VolumeDevices":null,"LivenessProbe":null,"ReadinessProbe":null,"Lifecycle":null,"TerminationMessagePath":"/dev/termination-log","TerminationMessagePolicy":"File","ImagePullPolicy":"IfNotPresent","SecurityContext":{"Capabilities":null,"Privileged":null,"SELinuxOptions":null,"RunAsUser":1337,"RunAsGroup":null,"RunAsNonRoot":null,"ReadOnlyRootFilesystem":true,"AllowPrivilegeEscalation":null},"Stdin":false,"StdinOnce":false,"TTY":false}],"RestartPolicy":"Always","TerminationGracePeriodSeconds":30,"ActiveDeadlineSeconds":null,"DNSPolicy":"ClusterFirst","NodeSelector":null,"ServiceAccountName":"default","AutomountServiceAccountToken":null,"NodeName":"nvmbd1aow230d00","SecurityContext":{"HostNetwork":false,"HostPID":false,"HostIPC":false,"ShareProcessNamespace":null,"SELinuxOptions":null,"RunAsUser":null,"RunAsGroup":null,"RunAsNonRoot":null,"SupplementalGroups":null,"FSGroup":null,"Sysctls":null},"ImagePullSecrets":[{"Name":"kuberegcred"}],"Hostname":"","Subdomain":"","Affinity":null,"SchedulerName":"default-scheduler","Tolerations":[{"Key":"node.kubernetes.io/not-ready","Operator":"Exists","Value":"","Effect":"NoExecute","TolerationSeconds":300},{"Key":"node.kubernetes.io/unreachable","Operator":"Exists","Value":"","Effect":"NoExecute","TolerationSeconds":300}],"HostAliases":null,"PriorityClassName":"","Priority":0,"DNSConfig":null,"ReadinessGates":null} B: null,"Requests":{"cpu":"10m","memory":"144Mi"}},"VolumeMounts":null,"VolumeDevices":null,"LivenessProbe":null,"ReadinessProbe":null,"Lifecycle":null,"TerminationMessagePath":"/dev/termination-log","TerminationMessagePolicy":"File","ImagePullPolicy":"IfNotPresent","SecurityContext":{"Capabilities":{"Add":["NET_ADMIN"],"Drop":null},"Privileged":null,"SELinuxOptions":null,"RunAsUser":null,"RunAsGroup":null,"RunAsNonRoot":null,"ReadOnlyRootFilesystem":null,"AllowPrivilegeEscalation":null},"Stdin":false,"StdinOnce":false,"TTY":false}],"Containers":[{"Name":"<microservice>","Image":"<registry_url>/<app>/<microservice>","Command":null,"Args":null,"WorkingDir":"","Ports":[{"Name":"","HostPort":0,"ContainerPort":8080,"Protocol":"TCP","HostIP":""}],"EnvFrom":null,"Env":null,"Resources":{"Limits":{"cpu":"200m","memory":"488Mi"},"Requests":{"cpu":"100m","memory":"244Mi"}},"VolumeMounts":[{"Name":"default-token-ktxwf","ReadOnly":true,"MountPath":"/var/run/secrets/kubernetes.io/serviceaccount","SubPath":"","MountPropagation":null}],"VolumeDevices":null,"LivenessProbe":null,"ReadinessProbe":null,"Lifecycle":null,"TerminationMessagePath":"/dev/termination-log","TerminationMessagePolicy":"File","ImagePullPolicy":"Always","SecurityContext":null,"Stdin":false,"StdinOnce":false,"TTY":false},{"Name":"istio-proxy","Image":"docker.io/istio/proxyv2:1.0.2","Command":null,"Args":["proxy","sidecar","--configPath","/etc/istio/proxy","--binaryPath","/usr/local/bin/envoy","--serviceCluster","istio-proxy","--drainDuration","45s","--parentShutdownDuration","1m0s","--discoveryAddress","istio-pilot.istio-system:15007","--discoveryRefreshDelay","1s","--zipkinAddress","zipkin.istio-system:9411","--connectTimeout","10s","--statsdUdpAddress","istio-statsd-prom-bridge.istio-system:9125","--proxyAdminPort","15000","--controlPlaneAuthPolicy","NONE"],"WorkingDir":"","Ports":null,"EnvFrom":null,"Env":[{"Name":"POD_NAME","Value":"","ValueFrom":{"FieldRef":{"APIVersion":"v1","FieldPath":"metadata.name"},"ResourceFieldRef":null,"ConfigMapKeyRef":null,"SecretKeyRef":null}},{"Name":"POD_NAMESPACE","Value":"","ValueFrom":{"FieldRef":{"APIVersion":"v1","FieldPath":"metadata.namespace"},"ResourceFieldRef":null,"ConfigMapKeyRef":null,"SecretKeyRef":null}},{"Name":"INSTANCE_IP","Value":"","ValueFrom":{"FieldRef":{"APIVersion":"v1","FieldPath":"status.podIP"},"ResourceFieldRef":null,"ConfigMapKeyRef":null,"SecretKeyRef":null}},{"Name":"ISTIO_META_POD_NAME","Value":"","ValueFrom":{"FieldRef":{"APIVersion":"v1","FieldPath":"metadata.name"},"ResourceFieldRef":null,"ConfigMapKeyRef":null,"SecretKeyRef":null}},{"Name":"ISTIO_META_INTERCEPTION_MODE","Value":"REDIRECT","ValueFrom":null}],"Resources":{"Limits":null,"Requests":{"cpu":"10m","memory":"144Mi"}},"VolumeMounts":[{"Name":"istio-envoy","ReadOnly":false,"MountPath":"/etc/istio/proxy","SubPath":"","MountPropagation":null},{"Name":"istio-certs","ReadOnly":true,"MountPath":"/etc/certs/","SubPath":"","MountPropagation":null}],"VolumeDevices":null,"LivenessProbe":null,"ReadinessProbe":null,"Lifecycle":null,"TerminationMessagePath":"/dev/termination-log","TerminationMessagePolicy":"File","ImagePullPolicy":"IfNotPresent","SecurityContext":{"Capabilities":null,"Privileged":null,"SELinuxOptions":null,"RunAsUser":1337,"RunAsGroup":null,"RunAsNonRoot":null,"ReadOnlyRootFilesystem":true,"AllowPrivilegeEscalation":null},"Stdin":false,"StdinOnce":false,"TTY":false}],"RestartPolicy":"Always","TerminationGracePeriodSeconds":30,"ActiveDeadlineSeconds":null,"DNSPolicy":"ClusterFirst","NodeSelector":null,"ServiceAccountName":"default","AutomountServiceAccountToken":null,"NodeName":"nvmbd1aow230d00","SecurityContext":{"HostNetwork":false,"HostPID":false,"HostIPC":false,"ShareProcessNamespace":null,"SELinuxOptions":null,"RunAsUser":null,"RunAsGroup":null,"RunAsNonRoot":null,"SupplementalGroups":null,"FSGroup":null,"Sysctls":null},"ImagePullSecrets":[{"Name":"kuberegcred"}],"Hostname":"","Subdomain":"","Affinity":null,"SchedulerName":"default-scheduler","Tolerations":[{"Key":"node.kubernetes.io/not-ready","Operator":"Exists","Value":"","Effect":"NoExecute","TolerationSeconds":300},{"Key":"node.kubernetes.io/unreachable","Operator":"Exists","Value":"","Effect":"NoExecute","TolerationSeconds":300}],"HostAliases":null,"PriorityClassName":"","Priority":0,"DNSConfig":null,"ReadinessGates":null} 
```
It seems it only allows to edit following fields ```containers[*].image, initContainers[*].image, activeDeadlineSeconds or tolerations```

Pods runs with either istio injection enabled or with resource quota set. Unable to run pods with both enabled.

Whats the correct way to achieve this?

**Comment by vikranttkamble** [comment]
Update: I reinstalled istio using helm chart: https://github.com/helm/charts/tree/master/incubator/istio

now, its giving following error: no matches for kind Gateway and VirtualService.

```
unable to recognize "appgateway.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "appgateway.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
```

**Comment by Hosweay** [comment]
To add on to this. From the sidecar-injector config map there seems to be a way to set CPU and memory requests but no way to set a limit. So if you have a resource quota where memory limits are defined, sidecar auto-injection fails.

Can additional options be allowed for CPU and memory limits to be applied to the sidecar proxy?

**Comment by ostromart** [comment]
https://github.com/istio/istio/issues/8553 should give you a way to handle this.

**Comment by jimmiebtlr** [comment]
Also I believe the incubator istio is massively out of date.

master branch is 1.1.0 on helm chart, incubator is I think 0.2.7

Granted I just started working with istio today, so may be missing something.

**Comment by joubertredrat** [comment]
Same issue here.
```
status:
  conditions:
  - lastTransitionTime: "2019-02-04T13:24:14Z"
    lastUpdateTime: "2019-02-04T13:24:14Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2019-02-04T13:24:14Z"
    lastUpdateTime: "2019-02-04T13:24:14Z"
    message: 'pods "app-example-65d9b6d5c5-4z72p" is forbidden: failed quota: namespace-resource-limits:
      must specify limits.cpu,limits.memory,requests.cpu,requests.memory'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
```

If I remove istio, disable sidecar injeciton or remove `ResourceQuota` from namespace, deployment works.

**Comment by cainelli** [comment]
I can also reproduce the issue running kubernetes 1.10.5, istio 1.0.5 and having `limitrange` on the namespace with sidecar injection enabled. Testing on kubernetes 1.13.4 seems to work.

**Comment by dcberg** [comment]
@cainelli when you say you tested on kube 1.13.4 is this with ResourceQuota and LimitRange? If so my guess is that kube 1.13 removed the restriction from LimitRange to change the resources on an init container.

Ultimately the correct fix is for Istio to set proper resource requests and limits for the proxy and init container. Having the config map to allow customers to adjust the resource settings on the proxy is still a good idea but the same settings should not adjust the init container. Istio needs to set logical defaults for both and not rely on a LimitRange.

Also note that in the kube documentation, the recommended ordering of the admission controllers has the LimitRanger prior to the MutatingAdmissionWebhook which is used by Istio to inject the Istio containers. This means that many of kube configurations in the market problem have LimitRangers that will not work with Istio anyway and pods will fail to start with Istio injection enabled and ResourceQuotas.

**Comment by rvennam** [comment]
Resource limits and requests was fixed in 1.1. https://github.com/istio/istio/pull/8409

Could you try this on 1.1?

**Comment by cainelli** [comment]
> @cainelli when you say you tested on kube 1.13.4 is this with ResourceQuota and LimitRange? 

Yes, worked on 1.13 with LimitRange enabled. I didn't checked ResourceQuota tho.

**Comment by r0fls** [comment]
This still fails if ephemeral-storage limits are in place :cry:

**Comment by r0fls** [comment]
Is it configurable in the istio values.yaml?
