### ISSUE TITLE
Sidecar doesn't start since certificates are missing on the sidecar pod.

### ISSUE THREAD

**Issue by axel7born** [istio/istio#9659]
**Describe the bug**
We have a scenario, where the egress gateway originates TLS with certificates that are mounted to the path `/etc/istio/egressgateway-certs/`. 
This path is automatically mounted, if a secret with the name istio-egressgateway-certs exists.

We configure the the TLS origination by a destination rule:
```
piVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-pinger
spec:
  host: pinger.services.acme.com
  subsets:
  - name: pinger
    trafficPolicy:
      portLevelSettings:
      - port:
          number: 9000
        tls:
          caCertificates: /etc/istio/egressgateway-certs/ca.crt
          clientCertificate: /etc/istio/egressgateway-certs/client.crt
          mode: MUTUAL
          privateKey: /etc/istio/egressgateway-certs/client.key
          sni: pinger.services.acme.com
```

Our pods have sidecars, that do not start since the sidecar expects to find certificates in
`/etc/istio/egressgateway-certs/`  

I extracted parts of the sidecar envoy log:

```
2018-10-30T15:33:14.237072Z	info	Monitored certs: []envoy.CertSource{envoy.CertSource{Directory:"/etc/certs/", Files:[]string{"cert-chain.pem", "key.pem", "root-cert.pem"}}}
2018-10-30T15:33:14.237222Z	info	Opening status port 15020

2018-10-30T15:33:14.237236Z	info	Starting proxy agent
2018-10-30T15:33:14.237487Z	info	Received new config, resetting budget
2018-10-30T15:33:14.237497Z	info	Reconciling retry (budget 10)
2018-10-30T15:33:14.237525Z	info	Epoch 0 starting
2018-10-30T15:33:14.238236Z	info	Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster client.default --service-node sidecar~100.96.1.17~client-845b478b6d-lkwgd.default~default.svc.cluster.local --max-obj-name-len 189 --allow-unknown-fields -l warning --v2-config-only]
[2018-10-30 15:33:14.270][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:243] gRPC config stream closed: 14, no healthy upstream
[2018-10-30 15:33:14.271][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:43] Unable to establish new stream
[2018-10-30 15:33:14.284][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:243] gRPC config stream closed: 14, no healthy upstream
[2018-10-30 15:33:14.284][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:43] Unable to establish new stream
2018-10-30T15:33:15.929821Z	info	Envoy proxy is NOT ready: 2 errors occurred:

* envoy stat missing: cluster_manager.cds.update_success
* envoy stat missing: listener_manager.lds.update_success
2018-10-30T15:33:17.929777Z	info	Envoy proxy is NOT ready: 2 errors occurred:

* envoy stat missing: cluster_manager.cds.update_success
* envoy stat missing: listener_manager.lds.update_success
[2018-10-30 15:33:19.366][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:226] gRPC config for type.googleapis.com/envoy.api.v2.Cluster update rejected: unable to read file: /etc/istio/egressgateway-certs/client.crt
[2018-10-30 15:33:19.366][16][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Cluster rejected: unable to read file: /etc/istio/egressgateway-certs/client.crt
[2018-10-30 15:33:19.459][16][warning][config] src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
[2018-10-30 15:33:19.461][16][warning][config] src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
...
2018-10-30 15:33:19.529][25][warning][config] src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
[2018-10-30 15:33:19.529][25][warning][config] src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
[2018-10-30 15:33:19.532][25][warning][config] src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
[2018-10-30 15:33:19.532][25][warning][config] src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
[2018-10-30 15:33:19.532][25][warning][config] src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
[2018-10-30 15:33:19.532][25][warning][config] src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
...
2018-10-30T15:33:19.935145Z	info	Envoy proxy is NOT ready: 1 error occurred:

* envoy stat missing: cluster_manager.cds.update_success
2018-10-30T15:33:21.935445Z	info	Envoy proxy is NOT ready: 1 error occurred:

* envoy stat missing: cluster_manager.cds.update_success
2018-10-30T15:33:23.935120Z	info	Envoy proxy is NOT ready: 1 error occurred:

* envoy stat missing: cluster_manager.cds.update_success
2018-10-30T15:33:25.934052Z	info	Envoy proxy is NOT ready: 1 error occurred:
...
```

**Expected behavior**
We would expect, that the sidecar ignores the missing certificates, as it doesn't need them.
This seems to be the behaviour in 1.0.
Or some method to specify the gateway, where the destination rule should be active.

**Steps to reproduce the bug**
* Create a secret with the required name for egress certificates.
* Deploy a Destination rule like in the example above.
* Start a pod with a sidecar. 

**Version**
Istio 1.1.0-snapshot.2 - October 2018 Release
and the current master.

**Comment by castlemilk** [comment]
This is related to the issue I've raised here: https://github.com/istio/istio/issues/8541.

**Comment by c0d1ngm0nk3y** [comment]
With git bisecting, we found out that the commit
(00abab79d96eb74b1b021be6f81c91f25a262768)[https://github.com/istio/istio/commit/00abab79d96eb74b1b021be6f81c91f25a262768] introduced this issue.

>  - Adding an HttpGet readiness probe to the pilot-agent
>     on the new status port. The agent (not Envoy) will
>     open this port. When receiving an HTTP GET on the readiness path,
>     the agent will probe Envoy, checking that it has received dynamic
>     listeners and clusters. If so, it's "ready".

That sounds suspicious. The configuration was rejected before, but the envoy worked fine and just ignored the missing cert. Now it does not get ready anymore.

**Comment by PiotrSikora** [comment]
If I understand this correctly, the sidecars are not starting because of missing certificates needed for connections to external services, which should be only configured on the egress gateway(s) and not all sidecars.

Is that correct? If so, that sounds like Pilot is pushing too much configuration to sidecars.

cc @costinm @rshriram @duderino

**Comment by c0d1ngm0nk3y** [comment]
Right. That would be the *real* fix. I would consider this more as a mitigation, since introducing this health probe hinders the sidecars of starting. Before, the configuration was `rejected`, but the sidecars started anyway.

**Comment by duderino** [comment]
@costinm assigning to you for at least an answer, but if you don't have the bandwidth to fix please assign to me

**Comment by linsun** [comment]
@vadimeisenbergibm could you help look at this issue?

**Comment by vadimeisenbergibm** [comment]
@linsun The issue is with the design of DestinationRules in general:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-pinger
spec:
  host: pinger.services.acme.com
  subsets:
  - name: pinger
    trafficPolicy:
      portLevelSettings:
      - port:
          number: 9000
        tls:
          caCertificates: /etc/istio/egressgateway-certs/ca.crt
          clientCertificate: /etc/istio/egressgateway-certs/client.crt
          mode: MUTUAL
          privateKey: /etc/istio/egressgateway-certs/client.key
          sni: pinger.services.acme.com
```

The DestinationRule references certificates, but cannot specify the pods the certificates must be loaded in. As a result, either the certificates must be loaded in all the pods, or there will be warning/errors in the pods where the certificates are not loaded. A possible workaround currently is to mount "fake" certificates in all the pods other than the egress gateway. Only the egress gateway will use the certificates, that will be real in its pod(s).

cc @rshriram @costinm

**Comment by linsun** [comment]
@vadimeisenbergibm thank you for digging into it.  Ok, so this is related to the network scoping issue that has been discussed.  I got a little confused earlier because @axel7born  mentioned it worked in 1.0 but not in 1.1.   It is possible our tls mode is 1.1 has a different default that is non strict..

**Comment by vadimeisenbergibm** [comment]
@linsun Right, the scoping should resolve this issue. See @costinm's reply on https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/istio-security/a8yl8YfMCNE/QkK71haXAgAJ 

> We are working on an extension of the Gateway spec that will allow customizing the sidecar.

**Comment by rshriram** [comment]
We have an implementation of scoping in progress for 1.1.

**Comment by loewenstein** [comment]
@linsun there was no probe in place for 1.0, hence the rejected config that anyway didn't get used on sidecars didn't stop the pod from being ready.

**Comment by linsun** [comment]
@loewenstein thank you - that makes sense now.

**Comment by louiscryan** [comment]
With namespace isolation for Sidecars implemented in 1.1 it is possible to avoid this situation. It would be nice to have a softer failure mode but there is a viable workaround. 

Marking as P1 and targeting for the next release.

**Comment by costinm** [comment]
The 'viable workaround' will be to use Sidecar and export API so the DestinationRule using certs is contained to a namespace, and that namespace will have the certs..

**Comment by loewenstein** [comment]
@costinm @louiscryan 

How would the 'viable workaround' config look like? 
I found [ConfigScope](https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3/#ConfigScope) on `ServiceEntry`s. I suppose that would have to be set to PRIVATE for a `ServiceEntry` in the egress gateway namespace for the service that needs a client certificate applied at the egress gateway. Correct?

What has to be configured with `Sidecar`?

I suppose any workload in the mesh can still point to the egress gateway without any config?

**Comment by rshriram** [comment]
Update, with release 1.1 these problems can be solved. You can create a destination rule in the egress gateway namespace with the exportTo field set to '.' . This will cause the destination rule to be bound only to the egress gateway namespace's pods

**Comment by loewenstein** [comment]
@rshriram well, in a default installation that's both going to be `istio-system`.

In particular in the new integration test framework, I am not sure about the level of control about namespaces. 
@nmittler could we spread istio installation on multiple namespaces?

**Comment by holgero** [comment]
This is not only a problem in the test framework, but also in a 'normal' Istio installation (where ingressgateway and egressgateway are both installed in the namespace istio-system). As soon as you start using both the secrets istio-egressgateway-certs AND istio-ingressgateway-certs to supply certificates to the ingress- and egress-gateways, they will start to fail, because their configuration contains invalid clusters.

@wenchenglu, @duderino: Should we look into a real solution for this problem? That would be e.g. to change the DestinationRule in a way that one can specify the pods (here istio-egressgateways) where it should be applied. Would a change like this have a chance to make it into 1.1 release?

We also made a pull request to envoy itself, to improve the behaviour there (don't abort at the first error in a cluster, but continue with the remaining clusters and fail at the end): https://github.com/envoyproxy/envoy/pull/5806 .

**Comment by axel7born** [comment]
/reopen 
#12129 doesn't solve this issue. The certificates missing on the sidecar are custom certs and will never be there.

**Comment by rshriram** [comment]
this has been solved with exportTo. 

```
piVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-pinger
  namespace: Istio-system or wherever the egress gateway is
spec:
  exportTo:
  - '.' # implies that this dest rule is not visible outside this namespace
  host: pinger.services.acme.com
  subsets:
  - name: pinger
    trafficPolicy:
      portLevelSettings:
      - port:
          number: 9000
        tls:
          caCertificates: /etc/istio/egressgateway-certs/ca.crt
          clientCertificate: /etc/istio/egressgateway-certs/client.crt
          mode: MUTUAL
          privateKey: /etc/istio/egressgateway-certs/client.key
          sni: pinger.services.acme.com
```

**Comment by loewenstein** [comment]
@rshriram the problem still exists with egress- and ingress-gateway in the same namespace (as is the case by default when installing with the Helm chart).

Further, the namespace isolation was mentioned as mitigation, not a solution in this issue's discussion.

Not sure what a real solution would be. Maybe add a `gateways` field to DestinationRule, similar to VirtualService?

**Comment by danila-trushin** [comment]
Comment to remain this issue opened. Investigations still needed as we have egress gateway in our custom namespace and exportTo doesn't resolve the problem.

**Comment by vadimeisenbergibm** [comment]
It seems the solution is as follows, starting from 1.1. There is `exportTo` field in DestinationRule https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/#DestinationRule which allows to export the destination rule to the current namespace. So you can deploy the egress gateway into a separate namespace, and define the destination rule to specify mTLS in that namespace with `exportTo: "."` directive.

**Comment by howardjohn** [comment]
Closing as duplicate of https://github.com/istio/istio/issues/15517

**Comment by nrjpoddar** [comment]
I tried adding a DR in a new namespace with `exportTo: "."` with egressgateways installed in that namespace (this namespace is not istio-system). I still see that Pilot is trying to push certificates for the cluster to all sidecars instead of just to egressgateway. This is with 1.3.6

**Comment by spanspan** [comment]
I've experienced the same in 1.5.5. is it a regression bug?
